### ISSUE TITLE
Als beheerder van de content ontvang ik notificatie van feedback

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#100]
### Toelichting
Als beheerder van de content ontvang ik notificatie van feedback, zodat ik snel de feedback kan
verwerken.

RvL: defacto gaat dit om het versturen van een email als er vanuit de frontend een feedback object wordt gemaakt. 

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...
- [ ] ...

### Taken Conduction
- [ ] Review api toevoegen (Huwelijksplanner)
- [ ] Message api toevoegen (huwelijksplanner)
- [ ] Subscriber toevoegen die bij het maken van een review op een werk instructie of nieuwsbericht een email verstuurd. 

### Taken ICATT
- [ ] ...
- [ ] ...

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als beheerder van de content ontvang ik notificatie van feedback, zodat ik snel de feedback kan
verwerken.

**Comment by rubenvdlinde** [comment]
Inmiddels is  review als api  toegevoegd aan #134 met die opmerking dat we ook een comment object in het ORC zouden kunnen plaatsen.

Voortschrijdend inzicht is dat we de subscriber ook rechtstreek emails kunnen laten sturen zonder de berichten service, dan zouden we alleen wel de tracibility van berichten verliezen (waarvan we kunnen afvragen of dat bij kiss hoort)

**Comment by rubenvdlinde** [comment]
Overigens betkend dit wel dat we per object uit een bron (bijvoorbeeld kennis artikel) de beheerder of  auteur moeten kunnen opzoeken en daar een email van hebben.

**Comment by sytskevanhasselt** [comment]
Status = Done
