### ISSUE TITLE
Als contentbeheerder kan ik in de notificatie zien over welk deel van de content deze feedback gaat

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#101]
### Toelichting
Als beheerder van de content kan ik in de notificatie zien over welk deel van de content deze feedback gaat, zodat ik snel de feedback kan verwerken.

Dit is afhankelijk van meer gestructureerde bronnen. Pas als we dat hebben, kunnen we bepalen hoe we de informatie over substructuur kunnen meesturen. 

Voorwaarde: [E-01, #23](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/23) is afgerond. daarna bepalen hoe we de referentie naar de content in de notificatie opnemen

### Acceptatiecriteria
- [x] Bij kennisartikelen staat er bij de verschillende onderdelen van een kennisartikel (óók?) een elementen om feedback te koppelen aan dat specifieke element.
- [x] In het review bericht wordt óók een uniek id van het artikel opgenomen. Dit is de URL uit het SDG-plus-object. Dit zal op op zichzelfstaand weinig zinvolle info zijn voor de Ontvanger van de Feedback
- [x] In de mail die gestuurd wordt (zie [G-01, #121](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/121) is niet alleen de titel van het artikel zichtbaar, maar ook het 'property' waarover de feedback gaat. Zowel de naam die in het scherm staat, als de naam uit het Object. 
    - in het geval van SDG/PDC is dat één van de volgende onderdelen: specifiekeTekst, procedureBeschrijving, kostenEnBetaalmethoden, condition, bezwaarEnBeroep, notice, vereisten, bewijs, contact, deskmemo
    - we nemen hierbij ook op de Titel vand e tab in KISS

- [x] Er staat óók een knop bij Medewerkers
- [x] De functionaliteit voor feedback versturen is voorlopig één functionaliteit. Dit betekent dat het feedbackformulier bij Medewerkers er een beetje gek uitziet. Eerst overleggen met Ontwerpgroep

### Te beslissen
- sturen we alleen den aam van het onderdeel mee, en als ja: doen we dan de schermnaam of de propertynaam? we sturen schermnaam en propirtu mee
- Of sturen we de hele inhoud van het property mee? In dat laatste geval moeten we waarschijnlijk nog een keer kijken naar de opbouw van de mail? zie hierboven, mail is OK

### Taken Conduction
- [x] afhankelijk van beslissing: eventueel notificatiemail aanpassen

### Taken ICATT
- [ ] ...
- [ ] ...

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Is dit niet gewoon onderdeel van het bij #100 gemaakt email template?

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als beheerder van de content kan ik in de notificatie zien over welk deel van de content deze
feedback gaat, zodat ik snel de feedback kan verwerken.

**Comment by rubenvdlinde** [comment]
Oplossing blijft dan om de content mee te nemen in de email?

**Comment by sytskevanhasselt** [comment]
Ik heb de On Hold eraf gehaald: met het realiseren van E-01, #23 hebben we gestructureerde content. 
We kunnen nu een opzet maken van het opnemen van een Onderdeel uit het PDC artikel in de Feedbackmail

**Comment by sytskevanhasselt** [comment]
Status = Done
