### ISSUE TITLE
Als beheerder wil ik in de notificatie de naam en het e-mailadres van de indiener zien

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#102]
### Toelichting
Als beheerder wil ik in de notificatie de naam en het e-mailadres van de indiener zien. Ik kan deze
beantwoorden, zodat de indiener weet dat de aanpassing gedaan is

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...
- [ ] ...

### Taken Conduction
- Geen

### Taken ICATT
- [ ] ...
- [ ] ...

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Tijdinschatting 
- *Conduction* 
- *ICATT* 

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Is dit niet gewoon onderdeel van het onder #100 gemaakt email template?

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als beheerder wil ik in de notificatie de naam en het e-mailadres van de indiener zien. Ik kan deze
beantwoorden, zodat de indiener weet dat de aanpassing gedaan is

**Comment by PascalIcatt** [comment]
Opgeleverd in https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/121

**Comment by sytskevanhasselt** [comment]
Status = Done
