### ISSUE TITLE
Als KCM heb ik een klantbeeld nodig

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#103]
Gekoppeld aan https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/133 (klant zoeken)

**Besluit 19/7:**
handmatig aanmaken nieuwe klant valt buiten de scope. Dat wordt een aparte story

### Toelichting
Als klantcontactmedewerker heb ik een klantbeeld nodig dat voorziet in informatie over
klantgegevens, zaken, meldingen, contactmomenten via verschillende kanalen, zodat ik de klant
snel verder kan helpen.

nb. als de persoon gevonden wordt in het brp dan slaan we alleen het bsn op bij de klant. bij het tonen van het klantbeeld kunnen de overige gegevens dan weer uit het brp gehaald worden.
in theorie zou het niet altijd nodig zijn om een klantobject aan te maken, je zou bv een contaactmoment ook aan het bsn kunnen koppelen, maar we kiezen ervoor om altijd de klant als koppelobject aan te maken.

**Vraag voorontwerpgroep **
volgens de documentatie is klantnummer verplicht (https://klanten-api.vng.cloud/api/v1/schema/#operation/klant_create)
maar hoe bepaalt/vindt de KCM dat nummer bij het aanmaken van een nieuwe klant?
- update 18/7: vraag uitgezet bij PO v Dimpact (tot we feedback hebben gebruiken we een dummynummer)
- update 25/7: in deze story gaan we GEEN nieuwe klanten aanmaken: uitstellen naar nieuwe story, #193

### Acceptatiecriteria
- [ ] zie design en taken

### Taken Conduction
- [x] koppelobjecten onsluiten voor klantzaak en klantcontact
- [x] klanten api endpoint voor klantbeeld
- [x] ~~klant aanmaken in klantregister bij nieuw klantcontact als deze nieuw is / nog niet bestaat~~ out of scope: kcm maakt niet zelf nieuwe klanten aan
- [x] ~~als het klantobject een bsn bevat dan het klantobject aanvullen vanuit het brp~~ out of scope: kcm maakt niet zelf nieuwe klanten aan
- [x] ~~bij het opslaan van een klant mag deze of een bsn bevatten of andere gegevens, maar nooit beiden.~~ out of scope: kcm maakt niet zelf nieuwe klanten aan
- [x] toevoegen testdata: een aantal personen in het brp en een aantal klantobjecten met een emailadres en/of telefoonnummer. Dit is inmiddels deels gedaan, maar moet nog wat uitgebreid worden: medewerker bij contactmoment en zaak bij klant toevoegen. NB: voor medewerker kunnen we gebruik maken van de (verwijzingen naar de) vier testusers. 
- [x] Redoc bijwerken op de invoeging van properties 'telefoonnummers' en 'emails', als arrays van objecten.
- [x] Zorgen dat contactmomenten gesorteerd kunnen worden op Datum (SH05)
- [x] Zorgen dat de lijst gevonden klanten gesorteerd kan worden op Achternaam (A-Z) (SH06)
- [x] Zorgen dat je kunt zoeken op een deel van: telefoonnummer, e-mailadres, tzt ook: achternaam (SH07)

### Taken ICATT
- [x] design
implementatie icatt blocked: wachten op design uitwerking
- [x] klant zoeken in klanten api obv email of tel nr. dit wordt gerealiseerd in https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/133
- [x] gevonden klanten tonen  (zie design)
- [x] per klant deze gegevens tonen: Zie ook [comment HH](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/103#issuecomment-1155230470): 
   - zie figma design https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1
- [x] **Als een klant een bsn heeft in de registratie, dan ook de zaken van die klant tonen.**
    - [x] **In overzicht: zaaknummer, zaaktype, status, behandelaar,  datum ingediend, datum einde behandeltermijn**

- [x] Per klant de contactmomenten: Medewerker.datum, kanaal gespreksresultaat; nb op korte termijn hebben we alleen de datum, het gespreskresultaat en het kanaal om te tonen. Zodra we de medewerker weten en opslaan, kunnen we die ook tonen in de lijst
- [x] bij het opslaan van een contactmoment dit koppelen aan de klant. (kan als het goed is in 1 call, waarbij je ipv een object voor een nieuwe klant ook alleen een klant id kan opgeven (zie opmerking barry): https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/KlantContactMoment-contactmomenten-collection/operation/klantcontactmomenten%20KlantContactMoment_post
- [x] feedback van de pr voor zaak aan contactmoment verwerken: https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/pull/182
- [x] gegevens van contactmoment, zaken en dergelijke die we nu nog niet hebben/verwerken kunnen we nog niet tonen bij het klantbeeld. waar we merken da we daarmee niet aan het ontwerp voldoen maken we taken aan bij de desbetreffende stories waar die gegevens toegevoegd worden om ze ook in het klantbeeld te tonen. 
- [x] review comments die misschien nog niet resolved waren: medewerker naam ophalen en tonen ipv de url van de medewerker. nb. kan nog niet omdat er geen medewerker bij een contactmoment wordt opgelsagen. dat wordt een aparte story
- [x] test gegevens waren als placeholder of title atribuut toegevoegd. even weghalen als dat al niet gedaan is
- [x] Query parameters url encoden tbv partial zoeken

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken...

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker heb ik een klantbeeld nodig dat voorziet in informatie over
klantgegevens, zaken, meldingen, contactmomenten via verschillende kanalen, zodat ik de klant
snel verder kan helpen.

**Comment by rubenvdlinde** [comment]
Ik vind dit  een scopings vraagstuk, gemeenten moeten PDS apis aanbieden. Hoe ze dat doen doen ze het.

Overigens gebruikt Tilburg hiervoor SalesFource waar ze een PDS adapter boven op hebben gezet (we zaten met Tilburg in de PDS hackathon, nog iets specifieker dat was @rjzondervan )

**Comment by sytskevanhasselt** [comment]
Misschien begrijp ik PDS verkeerd, maar dat lijkt mij meer gaan over informatie over status van een proces naar buiten. Terwijl zoals ik klantbeeld begrijp, is dit vooral gegevens over een klant preseteren aan een KCM. Evt. uit verschillende bronnen waar PDS er één is? En BRP. Daarnaast moet er ergens ruimte zijn om contactgegevens op te slaan die niet in de BRP staan. Maar dat zit meer in R-02, https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/112

**Comment by rubenvdlinde** [comment]
PDS is geen bron maar een design patern waarbij bijna alle ZGW en klant API's onder vallen

**Comment by rjzondervan** [comment]
Frontend gaat binnen sprint 4 waarschijnlijk niet afkomen omdat hier nog wat afstemming over nodig is.

**Comment by bbrands02** [comment]
Er kan een klantcontactmoment gemaakt waar ook een nieuw of bestaande klant en een contactmoment aangemaakt kunnen worden. Het endpoint is `/api/klantcontactmomenten&extend[]=all`. Een voorbeeld:
`{
    "contactmoment": {
        "bronorganisatie": "340311484",
        "initiatiefnemer": "klant",
        "kanaal": "email",
        "medewerker": "https://example.com",
        "medewerkerIdentificatie": {
            "achternaam": "Brands",
            "voorletters": "B"
        },
        "onderwerpLinks": [
            "https://www.example.com",
            "https://www.conduction.nl"
        ],
        "registratiedatum": "2022-04-06 13:53:00",
        "tekst": "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec ullamcorper nulla non metus auctor fringilla. Nullam quis risus eget urna mollis ornare vel eu leo.",
        "voorkeurskanaal": "email",
        "voorkeurstaal": "nld"
    },
    "klant": {
        "bronorganisatie": "string",
        "klantnummer": "string",
        "bedrijfsnaam": "string",
        "functie": "string",
        "websiteUrl": "http://example.com",
        "voornaam": "string",
        "voorvoegselAchternaam": "string",
        "achternaam": "string",
        "telefoonnummer": "string",
        "emailadres": "user@example.com",
        "adres": {
            "straatnaam": "string",
            "huisnummer": 99999,
            "huisletter": "s",
            "huisnummertoevoeging": "stri",
            "postcode": "string",
            "woonplaatsnaam": "string",
            "landcode": "stri"
        },
        "subject": "http://example.com",
        "subjectType": "natuurlijk_persoon",
        "subjectIdentificatie": {
            "inpBsn": "string",
            "anpIdentificatie": "string",
            "inpANummer": "string",
            "geslachtsnaam": "string",
            "voorvoegselGeslachtsnaam": "string",
            "voorletters": "string",
            "voornamen": "string",
            "geslachtsaanduiding": "m",
            "geboortedatum": "string"
        }
    },
    "rol": "gesprekspartner"
}`

Als er al een bestaande klant is hoef je alleen een id mee te geven als `"klant": "id"`. 

Er is nog iemand van icatt nodig om dit te testen.

**Comment by bbrands02** [comment]
[Klantbeeld.postman_collection.txt](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/9064461/Klantbeeld.postman_collection.txt)

Dit is de postman collectie om de requests te testen voor het klantbeeld. Het bestand moet nog wel van .txt naar .json hernoemd worden voordat het in postman geimporteerd kan worden.

**Comment by sytskevanhasselt** [comment]
@mstokericatt , ik zie in de story een aantal vragen staan over de gegevens die we tonen van een klant, of van een contactmoment. Mijn beeld: 

1. Klantgegevens die we iig zien per klant: 
    - Basale persoonsgegevens: naam, en daarnaast iig  die gegevens waarmee je een klant kan zoeken: tel.nr e-mail, adres, geboortedatum
    - Contacthistorie, mogelijk niet alles maar in ieder geval meest recent beperkt
    - Aantal lopende zaken en meldingen van deze klant.

**Comment by mstokericatt** [comment]
volgens de documentatie is klantnummer verplicht (https://klanten-api.vng.cloud/api/v1/schema/#operation/klant_create)
maar hoe bepaalt/vindt de KCM dat nummer bij het aanmaken van een nieuwe klant?

**Comment by sytskevanhasselt** [comment]
@mstokericatt , @rubenvdlinde , ik zie nog één question staan: over klantnummer. 
Insteek PO: voorlopig géén nieuwe klanten opslaan. In ieder geval niet in deze story. 

Maar: dan moeten we misschien wel overleggen over testdata. 
Maar ik haal question label weg.

**Comment by rubenvdlinde** [comment]
Technisch grootste uitdaging is Geevens aanvullen vanuit BPR, hierbij even een voorstel

- Er moet een validatie regel worden toegevoegd dat  als er een BSN is opgegeven en geen NAW waardes mogen worden ingevuld (ex email en tel)
- Er moet (via de action -> functie route) een actie worden aangemaakt die afgaat bij GET klant.
- Deze actie moet een custom functie aanroepen (die dus overmag naar de een plugin)
- Deze actie moet vanut JSON logic alleen afgaan als de klant een BSN nummer bevat
- De functie moet aan de hand van het BSN nummer de klant gegeven uit het BRP halen en aanvullen (dat gebeurd dus alleen voor het terug te geven object, de gevens worden niet weggeschreven naar het klantenregister)
- De locatie van het BRP moet configureerbaar zijn (of als intern object BRP Persoon of als Externe Source)
- Er mag vanuit worden gegaan dat BRP bevragingen geschieden aan de hand van haal centraal.

**Comment by lencodes** [comment]
@sytskevanhasselt om dit te testen kan je zoeken naar een klant per e-mailadres: icatttest+roza@gmail.com.

Je kan uiteraard ook op andere klanten zoeken, maar let op:

Als een klant geen BSN bevat, dan tonen er ook geen zaken (we kunnen immers niet zoeken op BSN) en
Als een klant wél een BSN bevat én zaken bevat maar geen gekoppelde medewerker aan de zaak, dan wordt het label "Onbekend" bij behandelaar.

**Comment by WilcoLouwerse** [comment]
Voor: "Zorgen dat je kunt zoeken op een deel van: telefoonnummer, e-mailadres, tzt ook: achternaam (SH07)" is nu het volgende geregeld:
Bij filteren op een get collectie op de gateway is het mogelijk om in query parameters (voorbeeld:) ?email=%value% mee te geven. Er word op de value die je meegeeft letterlijk [sql LIKE](https://www.w3schools.com/sql/sql_like.asp) toegepast. Op deze manier kan er partial gezocht worden op de genoemde velden.
Het enige probleem voor nu is dat %nummer (ofwel %0123) niet werkt, waarschijnlijk door iets vaags in hoe sql werkt. Conduction is aan het kijken of we hier een oplossing voor kunnen vinden, maar anders is het idee om voor nu alleen zoeken op 'begint met' (dus 01234%) toe te staan via de front-end.

Voor het sorteren op datum en achternaam ben ik vandaag bezig een uitbreiding te doen op de gateway. Ik laat weten als dit af is.
Voor nu kan ik al wel laten weten hoe dit gaat werken.
Bij een get collectie kan je de query param 'order' meegeven met de value asc/desc. voorbeeld:
?order[naamVanEenAttribuut]=desc

**Comment by rjzondervan** [comment]
Gezien de Gateway de binnenkomende query parameters nog een URL decode geeft, wordt %12 nog omgeslagen tot een bijzonder karakter. De truc om de values normaal in te schieten is dus eigenlijk heel simpel: het url_encoden van de query parameter voor deze in te schieten naar de gateway.

**Comment by WilcoLouwerse** [comment]
Redoc zou up to date moeten zijn:
https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json?nocache
Ik zie hier in onder klant de 'telefoonnummers' en 'emails' als arrays van objecten terug

**Comment by WilcoLouwerse** [comment]
Sorteren op de achternaam van een klant werkt nu:
![Image](https://user-images.githubusercontent.com/3785488/186677472-d9bd9b2d-c9a5-4a32-9556-af72b2386723.png)

**Comment by WilcoLouwerse** [comment]
Sorteren op datum van een contactmoment ook:
![Image](https://user-images.githubusercontent.com/3785488/186678835-afb0a522-998c-437b-b7c2-2d39a1e35b0f.png)

**Comment by WilcoLouwerse** [comment]
Ik pak vandaag "Redoc bijwerken op de invoeging van properties 'telefoonnummers' en 'emails', als arrays van objecten." op

**Comment by WilcoLouwerse** [comment]
De redoc is bijgewerkt en onder klanten staan nu arrays voor emails, addressen en telefoonnummers:
https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json?nocache#tag/KlantKlanten-collection/operation/klanten_Klant_post

**Comment by sytskevanhasselt** [comment]
Status = done
