### ISSUE TITLE
Als KCM wil ik de documenten bij een zaak kunnen inzien

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#104]
*oude titel: Als KCM wil ik inzicht in welke documenten de klant via de mijn omgeving aanlevert*

### Toelichting
Omdat er nog veel onduidelijk is rondom MijnOmgevingen, en welk documenten daar in zouden komen, interpreteren we deze story anders : 

We gaan er vanuit dat documenten alleen aan zaken kunnen hangen. Bij het opvragen van zaken, kunnen we de bijbehorende documenten opvragen. We tonen dus geen los lijstje documenten, maar alleen de documenten in de context van hun zaak.

> *Antwoord 21/07/2022, besproken met PL en PO*
> Ja, is goed voorstel. 
> Aan de documenten uit een eventuele Mijn-omgeving kleven nog teveel onzekerheden. Niet alle  gemeenten hebben ook een Mijn-omgeving.

NB: het opbouwen van een zaakdetailscherm had vermoedelijk bij E-06 moeten gebeuren. Daar is het niet gebeurd, dus doen we het hier. 

### Acceptatiecriteria
- [x] Als je doorklikt op een Zaak in een zoekresultaat, open je de Detailview van de zaak. 
- [x] Hier zie je alle elementen van een zaak, verdeeld over verschillende tabs zoals geschetst in het Design. 
https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1
- [x] Onder de tab Documenten kan je de documenten zien, die er bij die zaak horen. 
- [x] Je kan de bestandsnaam zien zoals die ook in het zaaksysteem te zien is 
- [x] Je kan de documenten ook openen en inzien
- [ ] _Je kan het type document zien, zoals die ook in het zaaksysteem te zien is (bv. Aanvraag, Beschikking)?_
- [x] In de tab Contactmomenten zie je de contactmomenten die aan deze zaak zijn  gekoppeld, en je kan ze openklappen om de inhoud te lezen

### Taken Conduction
- [ ] Testdata aanvullen, iig met Documenten
- [ ] Ondersteuning bij het inregelen van de ZGW-API-calls vanuit de frontend.

### Taken ICATT
- [ ] Zorgen dat het schermontwerp in het [design-figma](https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1) staat.
- [ ] Detailview zaak verder opbouwen: ook hiervoor contact opnemen met Backend; bij vragen over design: met Gina.
- [ ] DOcumenten op te vragen door te extenden op de ZAAK, nl: zaakinformatieobject & zaakinformatieobject.zaakinformatieobject && zaakinformatieobject.zaakinformatieopbjecttype: neem hiervoor contact op met Backender via Ruben
- [ ] Zorgen dat de documenten te openen zijn.

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
In mijn beleving is de documenten API als onderdeel van de ZGW api's reeds in een eerder stadium uitgerold

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik inzicht in welke documenten de klant via de mijn omgeving
aanlevert.

**Comment by sytskevanhasselt** [comment]
@mstokericatt @rubenvdlinde vraag beantwoord, label verwijderd

**Comment by sytskevanhasselt** [comment]
Vier bevindingen, waarvan er twee nu niet opgepakt hoeve te worden. 
Zie ook het document [Bevindingen_J-02_#104_DocsBijZaak.docx, in Testen + testdata > Bevindingen Sprint-07, Sprint-08](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20Sprint-07,%20Sprint-08/Bevindingen_J-02_%23104_DocsBijZaak.docx?d=wb2f8f5ff5bce4487b69a14dd137e259f&csf=1&web=1&e=XAqHR5)

De twee die openstaan: 
1. SH01: Zaaktype en Zaakomschrijving ontbreken in de tab Algemeen. 
DIt staat ook niet goed in het design. Zie ook screenshot in bevindingen doc, met info over welke informatie dat is
2. SH02: in de tab Contactmomenten kan ik de Contactmomenten niet Openklikken. Dat zou wel moeten (net als in Klantbeeld).
