### ISSUE TITLE
Als KCM wil ik samenhangende contactmomenten kunnen groeperen naar gesprekken

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#105]
HH 30-9: gebruikersgroep 29-9 zegt dit is niet meer nodig. 

### Toelichting
Als klantcontactmedewerker wil ik samenhangende contactmomenten kunnen groeperen naar gesprekken, om zo een compleet overzicht te creëren van het met de klant gevoerde gesprek, ook als dat over meerdere contactmomenten heen loopt.  

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] Contactmomenten API uitbreiden met gesprekken

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik samenhangende contactmomenten kunnen groeperen naar
gesprekken, om zo een compleet overzicht te creëren van het met de klant gevoerde gesprek,
ook als dat over meerdere contactmomenten heen loopt.

**Comment by sytskevanhasselt** [comment]
gelabled en gesloten
