### ISSUE TITLE
Als klant wil ik de contactmomenten die ik met de gemeente heb gehad kunnen laten verwijderen

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#106]
HH 30-9 
Gebruikersgroep beslist dit is out of scope. KCM mag geen contactmomenten verwijderen

### Toelichting
Als klant wil ik de contactmomenten die ik met de gemeente heb gehad kunnen laten verwijderen, uiteraard met inachtneming van de juridische kaders. 

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] Plugin voor het verwijderen van contact momenten

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klant wil ik de contactmomenten die ik met de gemeente heb gehad kunnen laten
verwijderen, uiteraard met inachtneming van de juridische kaders.

**Comment by sytskevanhasselt** [comment]
gelabled en gesloten
