### ISSUE TITLE
Als KCM wil ik een anoniem contactmoment kunnen registreren

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#107]
### Toelichting
Als klantcontactmedewerker wil ik een anoniem contactmoment kunnen registreren, zodat een klant regie heeft over de eigen gegevens terwijl de gemeente een compleet inzicht heeft in de gestelde vragen

Het gaat hier bijv. om: 
- contactmomenten waarop de klant zelf anoniem wil blijven
- of om bv algemene vragen die gesteld worden: dan wil je wel registreren dát de vraag is gesteld, maar wie de vraag stelde is irrelevant Bv: vragen naar openingstijden, wat kost paspoort, wanneer wordt het afval opgehaald. 

Je kan al een anoniem contactmoment opslaan (een contactmoment is by default anoniem). Alle info die bij het contactmoment wordt verzameld (zaken, klanten, ..) kan bij het opslaan van het contactmoment uitgevinkt worden. Deze info wordt dan niet bij het contactmoment opgeslagen. KISS voldoet dus al aan deze story. Er hoeft geen werk meer gedaan te worden.

**vraag voor gebruikersgroep**: 
mag je bij een anoniem contactmoment zaken opslaan? daarmee zou het contactmoment niet meer anoniem zijn. 
> *Antwoord 14/07/2022*
> Ja, je mag een zaak opslaan, die verder niet aan een klant gekoppeld is. 
> *voorbeeld: ik bel over een kapotte lantaarnpaal, en het blijkt dat hier al een bestaande Melding Openbare Ruimte voor is gedaan. Het contactmoment met mij kan dan anoniem worden gekoppeld aan die melding, zonder dat ik er als klant aan gekoppeld ben. 
> Aanvullend: het kan ook voorkomen dat ik als KCM een klant al heb opgezocht bij het contactmoment. Maar het gaat bijv. om een melding overlast of burenruzie. en dan geeft de beller aan dat zijn niet wil dat haar gegevens bij deze melding wordt opgeslagen. Dus dan moet het mogelijk zijn om de klant te ontkoppelen. 

### Acceptatiecriteria
- [x] checkbox om contactmoment anoniem opslaan, er wordt dan geen klant gekoppeld aan het contactmoment
- [x] klantgevens die misschien zijn opgezocht tijdens het contactmoment moeten als je voor een anonieme melding kiest niet opgeslagen worden

### Functionele teststappen
- [ ] ...

### Taken Conduction
- Geen

### Taken ICATT
- Geen

### Taken DIMPACT
- [ ] ...

### Tijdinschatting 
- *Conduction* 
- *ICATT* 

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik een anoniem contactmoment kunnen registreren, zodat een
klant regie heeft over de eigen gegevens terwijl de gemeente een compleet inzicht heeft in de
gestelde vragen

**Comment by sytskevanhasselt** [comment]
Status = done
