### ISSUE TITLE
Als KCM wil ik meerdere vragen bij één contactmoment kunnen registreren

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#108]
### Toelichting
Als klantcontactmedewerker wil ik meerdere vragen bij één contactmoment kunnen registreren, zodat ik een overzicht heb van alle vragen die ik voor de klant afgehandeld heb. (Een contactmoment kan uit meerdere vragen bestaan)

nb. als je wisselt tussen vragen, dan kan het zijn dat er informatie blijft staan op het scherm die je bij de vorige vraag had opgezocht. die gegevens worden dan niet aan het volgende contactmoment gekoppeld, termwijl ze daar misschien wel gebruikt worden. dit is een afweging tussen zuiverheid/compleetheid van de data en gebruiksgemak. voor nu: het werkt zoals het werkt. @sytskevanhasselt: bovenstaande nog even bespreken 

het is wenselijk dat het klantbeeld wel blijft staan (dat gebeurt waarschijnlijk automatisch) als je een nieuwe vraag start ,maar dat die klant dan ook automatisch aan de nieuwe vraag gekoppeld wordt. @sytskevanhasselt mee eens?

### Acceptatiecriteria

- [x] Tijdens een contactmoment kan je aangeven dat de klant een tweede vraag stelt, m.b.v. een druk op de knop. Hiermee start je een tweede Klantvraag. Vanaf dat moment: 
    - [x] hoort alle logging bij het tweede contactmoment
    - [x] horen alle nieuw gezochte resources bij het tweede contactmoment. (de al gevonden recources wel in beeld laten staan als je een volgende vraag begint, je wil bv niet de klant opnieuw op zoeken. de reeds gezocht resources niet kopelen aan de volgende vraag, met uitzondering van de klant. het gaat immers nog steeds over dezelfde klant)
    - [x] start je een lege, nieuwe notitie, bij de tweede vraag. 
- [x] Nadat de klant heeft opgehangen, kan je nog door je verschillende Klantvragen bladeren, om te zorgen dat alle informatie netjes staat, bij elke Klantvraag
- [x] Als je op Einde Contactmoment klikt zie je een overview van de verschillende Klantvragen. je kunt hier nog wijzgen notitie en  afhandeling
- [x] Op het moment dat je op Opslaan klikt, wordt elke Klantvraag in een eigen Contactmoment opgeslagen / verstuurd naar de onderliggende Registratie. 
- [x] De evt. verschillende opgeslagen Contactmomenten, zijn welk aan elkaar te lieren, met het veld 'gesprek' in het contactmoment. Alle Klantvragen die tijdens één telefooncontact door een Klant zijn gesteld, krijgen hier allemaal hetzelfde GespreksID. (dit genererern we zelf) 
- [x] Alle dialogen zijn in de Je-vorm

### Functionele teststappen
- [ ] zie [dit comment](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/108#issuecomment-1194343131).

### Taken Conduction
- [ ] ~~Vragen/ VAC-api ontwikkelen aan de hand van internationale vragen norm~~
- [x] ~~uitzoeken hoe meerdere vragen aan een contactmoment gekoppeld kunnen worden en voorstel doen~~
- [x] ~~toevoegen aan contactmoment: afwijkendOnderwerp (string) Max 2555~~
- [ ] Redoc bijwerken: 1Contactmoment = 1Vraag 
- [ ] Bij ontvangst van Contactmoment zonder Gespreksid, genereert Gateway een ID (uuuid). Die geeft Gateway terug in de response (feedback), die gebruikt kan worden als GespreksID in de volgende Contactmomenten. 

### Taken ICATT
nb. kan zowel als losse calls (aanmaken contactmoment, opslaan koppeling), of een call met faq al extend in de contactmonent opslaan call
- [x] design, zie [Figma-bestand, kolom Sprint 4, bij 'N-09: Als KCM wil ik meerder vragen bij één contactmoment kunnen registreren'](https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1)
- [x] openstaande bevinding: dialoog bij annuleren opslaan contactmoment van "u" naar "je", zie [**comment** hieronder](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/108#issuecomment-1204928317)
- [ ] Zorgen dat bij de tweede vraag het gespreksid van de eerste wordt ingevuld bij de tweede (en derde)

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Tijdinschatting 
- *Conduction* 
- *ICATT* 

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik meerdere vragen bij één contactmoment kunnen registreren,
zodat ik een overzicht heb van alle vragen die ik voor de klant afgehandeld heb. (Een
contactmoment kan uit meerdere vragen bestaan)

**Comment by rubenvdlinde** [comment]
Zie ook #111 vanuit het datamodel is het zinnig om te zeggen dat een gebruiker één gesprek voert bestaande uit meerdere contact momenten en dat ieder contact moment over één vraag gaat. Daarmee valt de metadata van vragen en contactmomenten samen.

**Comment by sytskevanhasselt** [comment]
Zou je dan uit ons scherm 'Contactmoment', in de backend feitelijk meerdere losse contactmomenten kunnen vastleggen?

**Comment by rubenvdlinde** [comment]
@sytskevanhasselt yes, that would be the point

**Comment by rubenvdlinde** [comment]
Vragen koppelen de VAC API aan de hand van [koppelobjecten](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ObjectContactMoment/operation/ObjectContactMoment_postId), deze laatste staat al live dus feitenlijk kan dit al

**Comment by sytskevanhasselt** [comment]
Aanvullend besproken met PO / PL van Dimpact:

Het gaat erom dat je tijdens je gesprek, meerdere vragen behandeld van een klant. De informatie van deze verschillende vragen wil je goed opslaan bij die klant. Deze vragen zullen eigenlijk allemaal na elkaar komen: éérst handelen we de ene vraag af, en daarna de tweede. ZIE OOK HET SCENARIO ONDERIN DE MAIL

Wat ze het liefst zouden willen zien, is dat je, binnen je Contactmoment, één of meer ‘subjes’ hebt, waarin je de verschillende vragen in verschillende blokje opneemt. Eigenlijk: meerdere ‘contactmomenten’ binnen 1 contactmoment. 

Twee overwegingen: 
-	Voor de KCM is een gesprek met twee of meer vragen één klantinteractie. Dus willen we dit in KISS in één sessie afhandelen. 
-	Voor de managementinformatie is het prettig om te zien dat het aantal telefonische contactmomenten overeenkomt met het aantal telefoontjes dat geregistreerd is in de Telefooncentrale. 

NB: dat eerste is belangrijker dan het tweede. 

Op dit moment zit de Contactmomenten-api volgens mij zo in elkaar: 
1.	Één contactmoment heeft maar één Gespreksresultaat
2.	Er kunnen wel meerdere ‘vragen’ in de vorm van meerdere links aan gekoppeld worden, maar steeds maar één gespreksresultaat. **Dus op het moment dat er uit één telefoongesprekken twee verschillende gespreksresultaten komen, MOETEN we op dit moment twee contactmomenten meesturen.**

Idealiter breiden we de Contactmomenten-api uit: 
1.	Het liefst ziet men dat de vraag wordt opgenomen als subobjecten
    a.	Waarbij elk subobject z’n eigen Gespreksresultaat, alternatieve vraag, gekoppelde links heeft, en mogelijk ook z’n eigen notities

2. Als dat niet mogelijk is, zou een alternatieve manier zijn om bij een Contactmoment een soort ‘gespreksID’ mee te geven. En Contactmomenten met hetzelfde GespreksID zijn door de KCM in één Klantinteractie afgehandeld. 
    a.	Op korte termijn zou KISS een gespreksID kunnen meegeven
    b.	Op termijn, na koppeling met de Telefonie, zou de Telefonie het gespreksID kunnen meegeven; In die situatie, namelijk, zou ook het starten en beëindigen van een contactmoment door telefonie gerealiseerd worden. 


### Scenario en uitwerking in KISS
1.	Joske belt naar het 14-nummer van haar gemeente. 
2.	KCM neemt telefoon op en Start contactmoment. 
3.	Eerst wordt de eerste vraag behandeld: wat is de status van mijn omgevingsvergunning. 
4.	KCM zoekt de zaak erbij,  koppelt de status terug. 
5.	Klant vraagt maar wat is nou de behandeltermijn?
6.	KCM zoekt op Kennisbank naar de termijnen en werkwijzen van Omgevingsvergunning. Contstateert dat er inderdaad vertraging is. 
7.	KCM maakt een terugbelnotitie voor de behandelaar, Karin Jansen. 
8.	Bij afronden van deze vraag, vraagt KCM: “heeft u nog meer vragen?”
9.	Joske zegt ja: mijn afvalkliko is eigenlijk te klein.
10.	KCM klikt op een knop, ‘Nog een vraag’ (oid). 
11.	Hiermee wordt het contactmoment ahw in tweeen geknipt: 
a.	Alle handelingen in de actie-log horen vanaf dat moent bij de tweede vvraag
b.	Alle bezochten pagina’s, zake, collega’s, horen vanaf dat moment bij de tweede vraag.
c.	Uitdaging maken we één kladblokje, of krijgt kcm nu ook een tweede, nieuw kladblokje? 
12.	KCM zoekt op Kliko, en vindt een productpagina over Afval. Daar ziet KCM dat het mogelijk is om een grotere Kliko aan te vragen. 
13.	KCM vult de vraag om grotere Kliko in namens de klant. 
14.	Hiermee is het telefoongesprek afgerond, KCM hangt op en klikt Einde Contactmomet. 
15.	In het afhandelscherm kan de KCM nu voor de twee vragen de afhandeling inrichten: 
a.	Twee stukjes actie log, en prducten/ zaken / medewerkers om te koppelen
b.	Twee omschrijving velden 
c.	Twee keer de mogelijkheid om de eigenlijke vraag van de kant in te vullen (in afwijkendOnderwerp )
16.	Bij Opslaan stuurt KISS 2 contactmoment-objecten naar de gateway. Beide gekoppeld aan dezelfde klant. 
a.	Het moment waarop KCM op Nog een Vraag klikte bepaalt de eindtijd van het eerste contactmoment, en de starttijd van het tweede contactmoment.
b.	Alle resources die geraadpleegd zijn vóór het klikken op Nog een vraag, horen bij het eerste contactmoment.
c.	En alles wat daarna is geraadpleegd, hoort bij het tweede contactmoment.

**Comment by sytskevanhasselt** [comment]
Openstaande testbevinding uit eerdere stories hierbij geplaatst: 
Zoals ook eerder opgemerkt bij  G-01 - Als KCM wil ik vanuit het kennisartikel in KISS feedback kunnen geven op geraadpleegde content #121: 
Ik zie dat in de dialoog de aanspreekvorm ‘u’ is: voorstel: wijzigen in JE.’
Dus:

&nbsp;&nbsp;&nbsp;&nbsp;Weet je zeker dat je het contactmoment wilt annuleren? Alle gegevens worden verwijderd.

**Comment by sytskevanhasselt** [comment]
Ik heb de inhoudelijke vragen / discussie met Gebruikersgroep verplaatst naar de éérste comment, om de story zelf wat overzichtelijker te houden.

**Comment by hannekevanderhorst** [comment]
Getest 1 kleine bevinding voor nu: als je een terugbelverzoek aanmaakt, kun je in hetbehandelscherm geen afhandeloptie meer kiezen zie https://icattnl.sharepoint.com/:x:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/_testData/Overzicht-Testdata.xlsx?d=w8106ea81e3a048c5baa8417c7af87bdd&csf=1&web=1&e=QBLI4d 

aantal andere die we niet bij deze story oppakken
