### ISSUE TITLE
Als KCM wil ik een terugbelnotitie kunnen maken voor een collega

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#109]
### Toelichting
Als klantcontactmedewerker wil ik een terugbelnotitie kunnen maken voor een collega. Hierin wil ik:
- de gegevens van de klant overnemen (nu nog handmatig, het efficient samenstellen is een aparte story)
- een notitie toevoegen voor mijn collega, met daarin de vraag van de klant 
- Dit zijn de overige velden die in de terugbelnotitie moeten: e-mailadres, telefoonnummer 1, telefoonnummer 2, ~~afdeling~~, en medewerker waarvoor het terugbelverzoek is.
- de medewerker kan gevonden worden in het smoelenboek via elastic search
- een terugbelverzoek wordt opgeslagen as contactmoment (zie onderstaande discussie)
- Een terugbelverzoek is voor 1 medewerker. voor terugbelverzoeken voor afdelingen of groepen is er een aparte story
- in Klantbeeld wil ik zien welke en hoeveel terugbelnotities er nog open staan voor de betreffende klant (zie ook #103 ). In dat overzicht moet de betreffende behandelaar / collega óók bij die terugbelnotitie staan. NB. aangezien er nu voor gekozen is de terugbelnotites als contactmoment op te slaan, worde ze automatisch getoond in het klantbeeld. een aandachtspunt is dat we moeten verzinnen hoe ze dan te onderscheiden zijn van 'gewone' contactmomenten (daarvoor controleren we op de aanwezigheid van het todo object: bij terugbelverzoeken wordt het onderliggende todo object van het contactmoment ingevuld, daarmee onderscheid hij zich van een gewoon contactmoment. 
- de completed date property van de todo kan gebruikt worden om te bepalen of het contactverzoek nog openstaat.

er zijn een aantal mogelijke situaties:
- bestaande klant: bestaande klant bij contactmoment opslaan (adhv bsn) out of scope: geen email/telnr bij bestaande klanten updaten en aanvullen. daar is een aparte story voor
- bestaande klant, maar tel/email is niet de juiste voor het contactverzoek (dan opnemen in het notitieveld, bestaande niet aanpassen)
- geen bestaande klant: 'leeg' klantobject toevoegen met alleen de benodigde tel/email velden.

**Vragen voor gebruikersgroep/ontwerpgroep:** 
- we kunnen dit als zaak of in het orc (objecten registratie component) opslaan. technisch maakt niet uit, maar de vraag is vooral hoe de persoon voor wie de terugbelnotitie bedoeld is hem gaat inzien (waarschijnlijk niet via kiss).

> *besproken 14/07/2022*
> Dit lijkt een vraag die niet door de gebruikersgroep beantwoord kan worden. PO Dimpact neemt het op met Architecten

- moet de terugbeller op de hoogte gesteld worden als er een nieuwe terugbelnotitie is. zo ja, hoe? via bv email en wie moet die dan versturen? kiss of het systeem waar die persoon het terugbelverzoek in afhandelt?

> Dit hoeft KISS niet te regelen, dat is aan het bronsysteem waar de notitie in terecht komt. (Dit hebben we besrpoken met PO / PL)

Besluit 26/07/2022: terugbelnotities gaan we opslaan als Contactmoment. 

**Vraag aan Architecten** 
- Het contactmoment object volstaat niet. we kiezen ervoor om hier een todo onder te hangen. dat matcht ook niet maar lijkt de beste balans tussen standaarden en de gewenste gegevens.

In afwachting van een besluit gaan we op deze weg door
 

### Acceptatiecriteria
- [x] Je maakt een terugbelnotitie aan door op een knop te klikken in de balk boven notities (zie ontwerp)
- [x] Bij een terugbelnotitie kun je via de interface opgeven: 
    - [x] gegevens van de klant: zie toelichting
    - [x] Van de collega: selecteer aan medewerker in de (smoelenboek)zoekresultaten. *(zie #222 voor het maken van een terugbelnotitie voor een afdeling of groep medewerkers binnen een afdeling)*
    - [x] Overig: de vraag van de klant en notities (wordt samengevoegd in 1 description veld in de todo)
- [x] De gegevens van de klant worden overgenomen uit het klantbeeld van de klant die je hebt gevonden. Als er nog geen klant is, of de gegevens volstaan niet, dan kun je de gegevens handmatig invullen
    - [x] Met deze gegevens wordt een nieuwe klant opgeslagen
    - [x] In deze klant is 'websiteUrl' niet verplicht
- [x] De gegevens van de collega worden overgenomen uit de collega die je hebt gevonden in de algemene zoekbalk. Je moet dus eerst een collega zoeken, voordat je voor die collega een terugbelverzoek kan maken
- [x] ~~De vraag van de klant wordt vooringevuld uit de titel van een kennisartikel, of als je nog geen kennisartikel had gevonden, is vrij in te vullen~~ 
- [x] De notities worden gekopieerd uit het notitieveld van het Contactmoment zelf, op het moment dat je op het telefoontje klikt. 
    - In gebruikersgroep is aangegeven: kopie. Dus vanaf aanmaken terugbelnotitie zijn er 2 notities binnen je contactmoment, en je terugbel-notities worden voor ingevuld met wat er op dat moment in de contactmomentnotitie staat. 
- [x] Bij het opslaan van de terugbelnotitie in het element klantcontactmomenten.todo.attendees het e-mailadres van de gevonden collega vastleggen.
- [x] Na opslaan van het terugbelverzoek, is dit in te zien bij de klant. Hier staat ook bij, bij welke collega het terugbelverzoek staat, en wat de status is: openstaand, of afgesloten.
- [x] het contactverzoek wordt gekoppeld aan het contactmoment via een object van het type contactmomentobject 

### Taken Conduction
- [x] verplaatsen todo van klantcontactmoment naar contactmoment
- [x] contactmoment en todo in 1 call aan kunnen maken
- [x] array velden voor telefoonnummers, emails (en adressen ) toevoegen en een issue maken (#223) om dit als aanvulling op de standaard aan te bieden. nb. adressen is voor ons niet relevant, alleen genoemd ivm consistantie voord de standaard uitbreiding. todo nog even bespreken of dit extra velde worden bij de todo of dat alles in de description opgeslagen wordt.
- [x] Zorgen dat websiteUrl niet meer verplicht is, bij het opslaan / aanmaken van een nieuwe klant (Zie [SH16 in Bevindingen_Terugbelnotitie.docx)](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20Sprint-05/Bevindingen_Terugbelnotitie.docx?d=w3dec209cb8ec4d50af5388d28ef5fc98&csf=1&web=1&e=VAzNsb)
- [x] Redoc bijwerken op 'websiteUrl niet meer verplicht'

### Taken ICATT
randvoorwaarde: we moeten de collega kunnen opzoeken waar de notitie voor bedoeld is.
- [x] tonen openstaande terugbelnotities bij het klantbeeld (in principe dus allemaal, want er is geen voorziening binnen kiss voor het sluiten van en terugbel notitie en het is ook niet duidelijk hoe dit in de api opgelost zou moeten worden. dit moet maar een aparte story worden)
- [x] nieuwe notitie aanmaken (direct versturen net als feedback op zoekresultaten) 
- [x] succes/error melding tonen en annuleer optie met bevestiging
- [x] het formulier bevat: zie toelichting  
- [x] er zijn een aantal gegevens verplicht (medewerker, naam, email of tel, notitie)
- [x] ~~de terugbel-contact-gegevens (telnr etc) zitten in de klant. als er nog geen klant is dan moet deze dus eerst aangemaakt worden~~
- [x] Zorgen dat het veld websiteURL leeg is in nieuwe klant (Zie [SH16 in Bevindingen_Terugbelnotitie.docx)](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20Sprint-05/Bevindingen_Terugbelnotitie.docx?d=w3dec209cb8ec4d50af5388d28ef5fc98&csf=1&web=1&e=VAzNsb)
- [x] Zorgen dat e-mailadres v.e. medewerker te selecteren is, ook als die in Array is opgeslagen. 
**LET OP: of ligt dit aan verkeerde structuur van het Mdw Object??** oplossing: dit heeft te maken met een wijziging in de klantenapi in een andere story. we gaan dit oplossen in story #122 

 

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik een terugbelnotitie kunnen maken voor een collega. Hierin wil
ik:
• de gegevens van de klant overnemen (naam, e-mailadres, postcode, huisnummer,
telefoonnummer)
• een notitie toevoegen voor mijn collega
• gewenste datum en tijdstip van terugbellen kunnen aangeven

**Comment by rubenvdlinde** [comment]
Voorstel is nader uitgewerkt onder #110 maar als we hier een ToDo van maken bewerken we bovenstaande zonder dat we data dupliceren

**Comment by WilcoLouwerse** [comment]
Er is een Note object toegevoegd aan de gateway die er zo uitziet:
https://conduction.stoplight.io/docs/huwelijksplanner/46705dc4098ec-note

**Comment by PascalIcatt** [comment]
Moet een terugbelverzoek als:
- zaak of
- orc object in de gateway (dit betekend dat toegang tot deze informatie door KISS geregeld moet worden terwijl de medewerker misschien geen KISS medewerker is

Hoe wordt de medewerker voor wie dit is bedoeld hiervan op de hoogte gebracht?

**Comment by rubenvdlinde** [comment]
eMail versturen? Dat is nu ook de gekozen richting voor overige ik moet iemand op de hoogste stellen momenten. Zo als feedback op objecten.

**Comment by rubenvdlinde** [comment]
Naar aanleiding van de refinement hebben we nu todo object nestbaar gemaakt in het contactmoment, zie ook de redoc -> https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/KlantContactMoment-contactmomenten-collection/operation/klantcontactmomenten%20KlantContactMoment_get

**Comment by felixcicatt** [comment]
Besproken met Mark:
- Contactverzoek moet valide zijn als je naar Einde contactmoment gaat
- Contactverzoek moet als contacmomentobject gekoppeld worden aan het contactmoment
- Als er een contactverzoek gemaakt is, mag het gespreksresultaat alleen "Terugbelnotitie gemaakt" zijn. MAAR: dat staat in een configurabel lijstje. Er moet dus in een instructie komen: er moet een gespreksresultaat zijn met de exacte naam "Terugbelnotitie gemaakt"

**Comment by felixcicatt** [comment]
Openstaande vraag: klantnummer is verplicht bij aanmaken nieuwe klant. Waar moet ik die vandaan halen?

**Comment by sytskevanhasselt** [comment]
@rubenvdlinde : volgens mij hadden we besproken dat we die 'automagisch' zouden genereren. Maar ik weet niet volgens welke regels. Hadden we daar al iets over afgesproken?

**Comment by mstokericatt** [comment]
de gekozen oplossing met het vullen van de klant gegevens obv de 
geselecteerde klant levert in bepaalde edge cases problemen op
zo kan een dezelfde klant niet meer geselecteerd worden nadat deze is 
verwijderd uit het formulier. (de verwijder optie is nodig omdat je
anders niet meer vrij klantgegevens kan invullen als er toevallig al 
een klant geselecteerd was in het contact moment. het is mogelijk dat je 
bv een klant selecteert om er vervolgens achter te komen dat dit toch niet
de juiste persoon is)

het zou beter zijn als alle tijdens het contactmoment gevonden klanten hier
uit een lijst geselecteerd zouden kunnen worden, met een 'anders namelijk' optie 
erbij voor het vrij invullen.

**Comment by sytskevanhasselt** [comment]
@GinaVerk zou jij naar bovenstaande comment van Mark willen kijken?

**Comment by sytskevanhasselt** [comment]
### Ontwerpgroep 04-10-2022
Deze is al uitgevoerd in de stories over notities maken en voorinvullen van gegevens in het contactmoment. 
Besluit ontwerpgroep 04-10-2022: Deze kan vervallen, want deze is gemaakt. De ontwerpgroep geeft wel aan dat deze niet voor alle gemeenten zal passen. De US is gerealiseerd, maar niet generiek toepasbaar. We zullen dit ook vastleggen in GitHub als discussie.
