### ISSUE TITLE
Als KCM wil ik gegevens uit contactregistratie meenemen in de terugbelnotitie

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#110]
### Toelichting
Als klantcontactmedewerker wil ik, wanneer ik kies voor het maken van een terugbelnotitie, extra invoermogelijkheden zien voor het maken van die notitie, zodat informatie die reeds beschikbaar is, niet nogmaals ingevuld hoeft te worden. 

alle info vcan het contactmometn, zoals de gekoppelde zaken zijn altijd terug te vinden, omdat de objecten aan elkaar gekoppeld zijn. deze data hoeft dus niet gedupliceerd te worden.
wat we in deze story wel doen is de gegevens van de klant (tel/naam/emial) voor zover bekend in het contactverzoek formulier voorinvullen

 zie #109
oppakken na #115, de gegevens die je daar invoert wil je waarschijnlijk hier aan de terugbelnotitie kunnen koppelen

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...
- [ ] ...

### Taken ICATT
- [ ] voorinvullen contactverzoek formulier
- [ ] ...

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Welke extra invoermogelijkheden zijn dat?

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik, wanneer ik kies voor het maken van een terugbelnotitie,
extra invoermogelijkheden zien voor het maken van die notitie, zodat informatie die reeds
beschikbaar is, niet nogmaals ingevuld hoeft te worden.
Toelichting: in de huidige oplossing is het maken van een terugbelnotitie een onderdeel van het
registreren van een gesprek. De onderdelen ‘contactregistratie’ en ‘terugbelnotitie’ bevatten veel
overlappende informatie. Het is de bedoeling om deze informatie maar één keer te registreren.

**Comment by rubenvdlinde** [comment]
Oke hier zijn een paar keuzes....

Met de kennis van nu is een terugbeld verzoek eigenlijk een to do (als in iCal) die je wilt toewijzen aan een medewerker, verplaatsen als die ziek is en waarvan het relevant is of die is uitgevoerd etc etc. Ik heb daarvoor nu het Agenda Component (een iCal implementatie) opgenomen in #134. 

Dat geeft de optie om to do's in te schieten op een gebruiker maar laat nog de keuze waar we die to do koppelen. Ik zou er geen fan van zijn om die aan een notitie te koppelen (ivm diepte van de stack) eerder zou ik een todo al "soort" van notitie  zien die aan een contact moment vast houd waarbij de inhoudenlijke tekst van de todo niet in een aparte notitie zit maar in de to do zelf.

**Comment by sytskevanhasselt** [comment]
Ik heb de indruk dat we het gros hiervan al doen, en dat dit al is gerealiseerd bij #109 . Ik schuif deze wat lager in de prio.

**Comment by felixcicatt** [comment]
@sytskevanhasselt is inmiddels duidelijk wat hiervoor moet gebeuren? Anders stel ik voor om deze helemaal naar beneden te schuiven.

**Comment by sytskevanhasselt** [comment]
@hannekevanderhorst, @rubenvdlinde , ik verplaats deze even naar Sprint 9. Ik heb de indruk dat we deze eigenlijk al af hebben gemaakt, bij het afronden van #109 .

**Comment by sytskevanhasselt** [comment]
Besluit ontwerpgroep 04-10-2022: Deze kan vervallen, want deze is gemaakt. De ontwerpgroep geeft wel aan dat deze niet voor alle gemeenten zal passen. De US is gerealiseerd, maar niet generiek toepasbaar. We zullen dit ook vastleggen in GitHub als discussie.
