### ISSUE TITLE
Als medewerker wil ik gegevens klant kunnen aanvullen met e-mail en telefoonnummers

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#112]
### Toelichting
Als medewerker wil ik op verzoek van de klant contactgegevens van de klant kunnen inzien en aanvullen. Het gaat dan om het toevoegen of aanpassen van het telefoonnummer of het e-mailadres, zodat de inwoner goed op de hoogte kan worden gehouden.

**Let op:** De api ondersteunt maar *1 telefoonnummer en 1 emailadres*. Aan de wens om meerdere telefoonnummers op te slaan gaan we op dit moment dus niet voldoen.

**vragen aan gebruikersgroep**
1. vraag gebruikersgroep: alleen nl tel nr's? de api dwingt niets af

>   *antwoord 14/07/2022* 
>   - e-mail: basale e-mailvalidatie met blokkerende foutmelding.  
>   - Telnr: mag bevatten: cijfers, spaties, + en -. 
>    idealiter een validatie die kijkt of er minimaal 10 cijfers in het telefoonnummer staan. En dan een waarschuwing maar géén blokkeren de foutmelding. 
*Er zijn nl. 0900-, 080- nummers die niet per sé 10 cijfers hebben, en er zijn de gemeentelijke 14-nummers, die ook geen 10 cijfers hebben.*

2. geen bevestiging vragen bij opslaan wel bij annuleren: is dit wenselijk?
>   *antwoord 14/07/2022* 
>  - Bij opslaan géén 'weet u het zeker' (behalve dus als telefoonnummers minder dan 10 cijfers bevat)
>  - Bij annuleren wél 'weet u het zeker'

RvL: Dit gaat over een verdere implementatie van de Klanten API die is reeds beschikbaar.

### Acceptatiecriteria
- [x] In het klantbeeld van één klant kan ik op een knop klikken, om telefoonnummer en e-mailadres in te vullen of te bewerken
- [x] ER is een controle op geldig e-mailadres: valideren op geldige invoer e-mailadres (a.b@c.dd)
    - [x] Je mag niet opslaan als het e-mailadres niet voldoet
    - [x] Als het voldoet mag je meteen opslaan, er verschijnt géén 'weet u het zeker'-melding
- [x] Er is een controle op geldige invoer telefoonnummer
    -  [ ] Telnr mag bevatten: cijfers, spaties, Plus-teken en Min-teken. 
    -  [x] De validatie kijkt of er minimaal 10 cijfers in het telefoonnummer staan. 
    -  [x] Als dat niet het geval is, volgt een waarschuwing, maar je mag wel opslaan
    -  [x] En dan een waarschuwing maar géén blokkeren de foutmelding.  
- [ ] Als je het invoeren of wijzigen annuleert, zie je een 'Weet je het zeker?'-waarschuwing. 
- [ ] De e-mail- en telefoonnummervalidatie zijn ook doorgevoerd in de terugbelnotitie over een nog onbekende klant. 

### Functionele teststappen
- [ ] ...
- [ ] ...

### Taken Conduction
- [x] Controleren of klanten API reeds beschikbaar is en zo niet beschikbaar stellen.
- [x] redoc bijwerken (oa delete mist en patch velden zijn onduidelijk) 
- [ ] ~~uitzoeken hoe de gateway omgaat met put en patch: put gedraagt zich als Patch, en patch ontbreekt nog. Voor nu: gaan we werken met Put. Het fixen hiervan verplaatsen we naar een aparte taak, zie [#233](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/233).~~

### Taken ICATT
- [ ] email en telefoonnummer in het klantbeeld beheerbaar maken.
- [ ] controle op geldige invoer telefoonnummer
    -  Telnr mag bevatten: cijfers, spaties, + en -. 
    - idealiter een validatie die kijkt of er minimaal 10 cijfers in het telefoonnummer staan. 
    -  En dan een waarschuwing maar géén blokkeren de foutmelding.  
- [ ] valideren op geldige invoer e-mailadres (a.b@c.dd): 
- [ ] opslaan via klanten api (via put of patch zie taken conduction)
- [x] confirmation/error message tonen
- [ ] annuleer optie
- [ ] geen bevestiging vragen bij opslaan wel bij annuleren
- [ ] De validaties telefoonnummer en mailadres ook doorvoeren in Terugbelnotitie

### Taken DIMPACT
- [x] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als medewerker wil ik op verzoek van de klant contactgegevens van de klant kunnen inzien en aanvullen. Het gaat dan om het toevoegen of aanpassen van het telefoonnummer of het emailadres, zodat de inwoner goed op de hoogte kan worden gehouden.

**Comment by rubenvdlinde** [comment]
Klanten API is beschikbaar

**Comment by sytskevanhasselt** [comment]
@mstokericatt  Antwoorden op vragen bij taken ICATT beantwoord met input gebruikersgroep

**Comment by WilcoLouwerse** [comment]
@rubenvdlinde Gaf bij mij aan dat de Conduction Taak op dit issue over Put & Patch omgezet zou zijn/worden naar een losse Taak (/issue). Ik kan deze alleen zo snel niet vinden op het bord 🤔

**Comment by mstokericatt** [comment]
@WilcoLouwerse, binnen deze story moet er in ieder geval iets werkends zijn  en je moet aan ons laten weten hoe we de api moeten gebruiken (put of patch). als jullie de gateway later nog willen veranderen/verbeteren ten aanzien van put/patch, dan zouden  jullie daar zelf een nieuw issue voor aan kunnen maken.

**Comment by sytskevanhasselt** [comment]
@lencodes , ik heb een vraag over het Acceptatiecriterium "Telnr mag bevatten: cijfers, spaties, Plus-teken en Min-teken." Hoe ingewikkeld is het, om dit af te dwingen?

**Comment by sytskevanhasselt** [comment]
@WilcoLouwerse , ik heb toevoegen en updaten getest. is VErwijderen nu ook al beschikbaar op de Gateway?

**Comment by sytskevanhasselt** [comment]
ER zijn al wat bevindingen, die staan in dit [document in Teams](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20Sprint-04,%20Sprint-05,%20Sprint-06/Bevindingen_R02.docx?d=w1cb58da6228b4db48967c108437cb1f3&csf=1&web=1&e=yQaj2u). 
Let op: we moeten nog testen: verwijderen van Tel / e-mail.

**Comment by sytskevanhasselt** [comment]
Hergetest. Bij héél snel klikken naar andere klant, heb ik nog één keer gezien dat een wijziging / toevoeging niet wordt opgepakt. Maar is heeeeeeel moeilijk reproduceerbaar, dus ik sluit de story.
