### ISSUE TITLE
Als KCM wil ik na het registreren van het gesprek weer uitkomen op het startscherm

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#114]
### Toelichting
Als klantcontactmedewerker wil ik na het registreren van het gesprek weer uitkomen op het startscherm, zodat ik snel verder kan met de volgende klant. 

Uit gebruikerstest van 7-juli-2022 kwam terug: 
1. Er zitten nu twee klikken tussen Opslaan contact moment en terugkomen op Startscherm die er wat hun betreft uit kunnen: 
    a. De dialoog 'weet u het zeker?' is bij Opslaan overbodig *NB: bij annuleren zeker niet!*
    b. Vervolgens moet je nu op ene link klikken om terug te gaan naar startscherm.

### Acceptatiecriteria
- [x] Als ik, na Einde contactmoment, op Opslaan klik, kom ik meteen terug in het Startscherm.
- [x] Als ik, na Einde contactmoment, op Opslaan klik, krijg ik eerst de vraag Weet u het zeker? Bij nee, keer ik terug in Contactmoment. Bij ja, keer ik terug in startscherm.

### Taken Conduction
- [ ] ...
- [ ] ...

### Taken ICATT
- [ ] De dialoog 'weet u het zeker?' is bij Opslaan weghalen
- [ ] na afsluiten direct terug naar het startscherm. dat betekent dat de succesmelding ook daar getoond moet worden. 

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Volgensmij is dit puur een frontend ding

**Comment by sytskevanhasselt** [comment]
Bevindingen staan [in Teams](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20Sprint-05/Bevindingen_Sprint05.docx?d=wc05639c9d3d6423eab863d7351911561&csf=1&web=1&e=dTdWLk)

**Comment by sytskevanhasselt** [comment]
Status = done
