### ISSUE TITLE
Als KCM wil ik notities kunnen maken zodra het gesprek met de klant start

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#115]
### Toelichting
Als klantcontactmedewerker wil ik notities kunnen maken zodra het gesprek met de klant start, zodat ik de informatie die de klant geeft kan gebruiken voor het oplossen van de klantvraag.

De notitie moet ook opgeslagen moet wordt bij het contactmoment. Dat zit echter niet deze story maar in #117 
het onderscheid tussen deze twee stories is onpraktisch. beiden oppakken en afronden in deze story!

we slaan dit op in het teskt veld van het contactmoment. 

**vraag voor gebruikersgroep**: 
kan je  binnen een contactmoment meerdere notities aanmaken? we gaan nu uit van 1 notitie.
> *Besproken 14/07/2022*:
> De term 'notities' in deze story heeft een iets andere betekenis dan in #116. 
> Binnen deze story gaat het om het maken van aantekeningen tijdens je gesprek. Dus de aanname klopt.
> Bij #116 gaat het erom dat je, vanuit je aantekeningen in je Contactmoment makkelijk en snel andere notities kunt maken zoals een notitie bij een Zaak, of een terugbelnotitie.

design
https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1

### Acceptatiecriteria
- [x] leeg notitieveld beschikbaar na het starten van een contactmoment
- [x] dit veld heeft de focus; dus als je contactmoment starten klikt, kun je meteen gaan typen.
- [x] dit veld is altijd zichtbaar tijdens het contactmoment
- [x] de notitie wordt opgeslagen bij het contactmoment
- [x] linebreaks ondersteunen (markdown optioneel?)
- [x] de notitie moet ook getoond worden op het afhandelscherm en kan daar nog bewerkt worden

### Functionele teststappen
- [ ] ...
- [ ] ...

### Taken Conduction
- [x] opslaan in contactmoment. de api is al beschikbaar

### Taken ICATT
- [x] een notitie veld beschikbaar tijdens het contactmoment.
- [x] bij het afhandelformulier kan je nog redigeren, wat er van opgeslagen wordt bij het contactmoment
- [x] meesturen bij het opslaan van het contactmoment in het tekst veld van de api https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/contactmomenten-collection/operation/ContactMoment_postId
- [x] voorstel: markdown en linebreaks ondersteunen om minimale opmaak te kunnen faciliteren. (besproken sytske/mark 3/8: de wenselijkheid van markdown is nog niet getoetst, daarom zien we daar nu vanaf. kan voor de gebruikerservaring namelijk ook in de weg zitten.).

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik notities kunnen maken zodra het gesprek met de klant start,
zodat ik de informatie die de klant geeft kan gebruiken voor het oplossen van de klantvraag.

**Comment by rubenvdlinde** [comment]
Het gaat hier dan om het klaarzetten van het Memo component voor het gebruik binnen kiss, daarbij is het de vraag aan ICATT of ze uit de voeten kunnen met hoe memo's nu zijn opgezet.

Oude component -> https://github.com/ConductionNL/memo-component

Nieuwe documentatie in wording -> https://conduction.stoplight.io/docs/huwelijksplanner/branches/main/ec3xyektxnzo8-memocomponent

**Comment by hannekevanderhorst** [comment]
Gebruikersgroep 16-6-22
Discussie over of apart kladblok nodig is, kan dit niet in de registratie van het contact?

Userstories gebruikersgroepe 1-4-22
Als klantcontactmedewerker wil ik notities kunnen maken zodra het gesprek met de klant start,
zodat ik de informatie die de klant geeft kan gebruiken voor het oplossen van de klantvraag.

**Comment by rubenvdlinde** [comment]
Voortschrijdend inzicht is dat we niet een heel memo  component nodig hebben maar hier een notitie  object voor kunnen gebruiken op het ORC. #134 is  hierop aangepast.

**Comment by PascalIcatt** [comment]
niet alle api's hebben ruimte voor het opslaan van notities. je kan dus niet rechtstreeks een notitie bij een klnat of een contactmoment opslaan. er moet dus gekopppeld kunnen worden aan een notitie api , maar die is er niet?? verder uitwerken/uitzoeken

**Comment by rubenvdlinde** [comment]
Zie opmerking over notitie object in ORC

**Comment by rubenvdlinde** [comment]
Note object is inmiddels beschikbaar voor de kiss omgeving. Zie [docs](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Note). 

Voor alle api's waar dat kan (zaken en contactmomenten) tekst opslaan in de api. Daar waar dat niet kan notitie maken in het notes register.

**Comment by sytskevanhasselt** [comment]
Bevindingen die horen bij deze story zijn allemaal opgelost

**Comment by sytskevanhasselt** [comment]
Status = done
