### ISSUE TITLE
Als KCM wil ik een notitie kunnen maken bij een zaak.

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#116]
### Toelichting
Als klantcontactmedewerker wil ik meerdere soorten notities kunnen maken tijdens en na het klantgesprek. Ik wil een notitie kunnen toevoegen aan een contactmoment, een zaak of aan een inwoner, zodat voor mij en mijn collega's bij een volgend contact zichtbaar is wat ik besproken heb.

Notities toevoegen aan contactmoment: S-01/#115, en S-03/#117
We begrijpen dat KCMs zelf geen notities mogen maken bij een Klant. Dus die nemen we hier niet mee. 
In deze story gaat het dus alleen om: notities kunnen maken bij een Zaak. 

Update 13/09: We implementeren voorlopig m.b.v. het Veld Toelichting: één veld waarin je toelichtingen kan bewerken en aanvullen. Zie disscussion #298 en issue #296 voor het vervolg, waarin het mogelijk moet worden om méérdere notities te hebben bij een zaak. 

### Acceptatiecriteria
- [ ] Tijdens een contactmoment kan ik bij een gevonden zaak een notitie bij die zaak aanmaken. of aanvullen. Zaken staan op meerder plekken: je kan ze los opzoeken, maar ze staan ook bij het klantbeeld. Binnen het klantbeeld kunnen ze rechtstreeks bij de klant staan, maar ook bij de eerdere contactmomenten van de klant. 
- [x] Je moet een zaken open klikken (naar detailview) om de notitie bij die zaak te maken. 
- [x] Een zaak heeft één veld waarin evt. eerdere notities staan. Hier kun je je eigen notitie aan toevoegen. 
- [x] Bij zaken die je in KISS vindt, kun je ook dit Toelichting-veld bij een zaak inzien (dus ook de notitie die je net hebt geplaatst)
- [x] Omdat we momenteel géén '1 of meer'-elementen hebben, wijken we af van het Design. Zie ook design: https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1, Blok sprint 5, S-02

### Bespreken / verifieren
- het feit DAT je een notitie hebt toegevoegd bij een zaak is een handeling die we NIET kunnen opslaan in een contactmoment, dus tonen we 'm ok niet in het Afhandelscherm

### Taken Conduction
- [x] ~~Notities api is reeds beschikbaar. een notie heeft een topic en dat kan verwijzen naar zowel een contactmoment, een zaak, een klant etc gaan.~~
- [x] Uitzoeken: notities bij een zaak, via ZGW 
Binnen zaken gebruiken we hier voorlopig het toelichtingen veld voor -> https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Zaak-zrc-collection/operation/zaken%20Zaak_post
~VRAAG: is Toelichtingen wel de juiste plek? het gaat 1 of meer notities~ Toelichting is zeer waarschijnlijk niet het juiste veld, maar ZGW lijkt niet te voorzien in een object waarmee je 1 of meer notities aan een zaak kan koppelen. 
- [ ] VRAAG: Moet hiervoor een PUT worden ingeregeld? We gaan geen nieuwe zaken aanmaken, dus geen Post, lijkt me
- [ ] Uitleg voor ICATT hoe ze deze te implementeren. 

### Taken ICATT
- [ ] Interface aanpassen, zodat je een zaak kunt inzien / openen (detailview)
- [ ] In die detailview zie je een veld om een comment in te vullen, én eventueel al eerder geplaatse comments. 
       _NB: de detailview bevat nog niet alle elementen die en KCM wil zien > dat pakken we op in #104 
- [ ] En een notitieveld, voor een nieuwe notitie bij de zaak._ 
- [ ] Zaakupdate-call inrichten. Die wordt verstuurd op het moment dat KCm notitie opslaat
- [ ] Als makkelijk: notitieveld voorinvullen met inhoud Notitieblok (net als bij Terugbelnotitie)

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] #298

**Comment by rubenvdlinde** [comment]
Voorgestelde oplossing richting is het toevoegen van een note object zo als voorgesteld in #134 waarmee aan ieder ander object een notitie kan worden toegevoegd

**Comment by rubenvdlinde** [comment]
Dit kan via het[ note object](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Note).

**Comment by rubenvdlinde** [comment]
Binnen zaken kan hier het toelichtingen veld voor worden gebruikt -> https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Zaak-zrc-collection/operation/zaken%20Zaak_post

**Comment by sytskevanhasselt** [comment]
Ah mooi. Dus vanuit kiss doen we dan een update op de zaak, met alleen info in de toelichting? En dat dan via Patch? 
NB: ik zie in de diverse schermen van deventer en utrecht dat een Zaak één of méér notities kan hebben. dat kan ook met toelichting?

**Comment by sytskevanhasselt** [comment]
Bij het nader bekijken van de API, zien we dat het veld Toelichting zeer waarschijnlijk een ándere betekenis heeft. 
Tegelijkertijd zien we bij ZAAK zelf géén aanknopingspunt voor 'één of meer notities bij een ZAAK'

Voor nu maken we een oplossing m.b.v. het veld Toelichting; hiermee kunnen we iig iets in de interface laten zien. 

Daarnaast 
1. Maken we een design-decision om het Notitie-object te gaan gebruiken hiervoor, die m.b.v. een ZAAKINFORMATIEOBJECT gekoppeld worden aan de ZAAK. Zie ook discussion ... 
2. Maken we een tweede story aan waarin een KCM wel een éigen notitie toe kan voegen.

**Comment by sytskevanhasselt** [comment]
Testen is klaar, bevindingen staan in [Teams: Bestanden > Testen + testdata > Bevindingen Sprint-04, Sprint-05, Sprint-06 > Bevindingen_S02_NotitieBijZaak](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20Sprint-04,%20Sprint-05,%20Sprint-06/Bevindingen_S02_NotitieBijZaak.docx?d=wa9a717ef8d7e482aa956e69a979a3b72&csf=1&web=1&e=ZqCq7l)

**Comment by hannekevanderhorst** [comment]
Hertest is klaar een nieuwe bevinding: als je in zoeken op zaken zoekt naar bsn verwacht je eerst een lijstje met personen en dan dooklikken naar zaakdetail. DAt lijstje ontbreekt zie zelfde bestand als hierboven

**Comment by sytskevanhasselt** [comment]
Status = Done
