### ISSUE TITLE
Als KCM wil ik dat de verschillende bronnen die aangeroepen worden overzichtelijk – als samenvatting - gepresenteerd worden (bijvoorbeeld naast of onder elkaar

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#118]
### Toelichting
Als klantcontactmedewerker wil ik dat de verschillende bronnen die aangeroepen worden overzichtelijk – als samenvatting - gepresenteerd worden (bijvoorbeeld naast of onder elkaar op basis van hoofdstuk, paragraaf, onderwerp, categorie, thema of titel), zodat ik snel kan scannen en met één druk op de knop of door een zoekterm toe te voegen de verdieping op kan zoeken. 

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

**Comment by hannekevanderhorst** [comment]
Als klantcontactmedewerker wil ik dat de verschillende bronnen die aangeroepen worden
overzichtelijk – als samenvatting - gepresenteerd worden (bijvoorbeeld naast of onder elkaar op
basis van hoofdstuk, paragraaf, onderwerp, categorie, thema of titel), zodat ik snel kan scannen
en met één druk op de knop of door een zoekterm toe te voegen de verdieping op kan zoeken.

![Image](https://user-images.githubusercontent.com/104772647/173600424-505c3bd4-c748-497d-9997-58fedd2345b9.jpg)

**Comment by sytskevanhasselt** [comment]
gelabled en gesloten
