### ISSUE TITLE
Als KCM wil ik dat de benodigde content (uit verschillende bronnen) op een logische manier in elkaar valt en gepresenteerd word

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#119]
### Toelichting
Als klantcontactmedewerker wil ik dat de benodigde content (uit verschillende bronnen) op een logische manier in elkaar valt en gepresenteerd wordt. Bijvoorbeeld: de informatie uit de verschillende kennisbronnen wordt gepresenteerd in één kennisartikel waarbij het nog wel duidelijk is welke informatie waar vandaan komt (dat zou door middel van labels kunnen). 

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22


![Image](https://user-images.githubusercontent.com/104772647/173601032-c6732f44-3298-49cb-ac37-a8bdd6e4da13.jpg)

Als klantcontactmedewerker wil ik dat de benodigde content (uit verschillende bronnen) op een
logische manier in elkaar valt en gepresenteerd wordt. Bijvoorbeeld: de informatie uit de
verschillende kennisbronnen wordt gepresenteerd in één kennisartikel waarbij het nog wel
duidelijk is welke informatie waar vandaan komt (dat zou door middel van labels kunnen).

**Comment by rubenvdlinde** [comment]
In mijn beleving is dit vooral een vraagstuk rondom de inrichting van Elastick search

**Comment by sytskevanhasselt** [comment]
gelabled en gesloten
