### ISSUE TITLE
Als KCM wil ik invloed uit kunnen oefenen op welke verdieping ik de informatie wil zoeken

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#120]
### Toelichting
Als klantcontactmedewerker wil ik invloed uit kunnen oefenen op welke verdieping ik de informatie wil zoeken. Bijvoorbeeld, dat er eerst een samenvatting gepresenteerd wordt, direct zoeken op een vraag, eerst zien wat er in de wijk aan de hand is, etc. 
Bijvoorbeeld: beginnen met zoeken op ‘paspoort’ en daarna kunnen verdiepen met het woord ‘buitenland’ (extra trefwoord). Er zijn heel veel extra trefwoorden aan VAC’s gekoppeld, zodat je ook verwante termen als zoekwoord kunt gebruiken. 
In de huidige situatie in Zwolle (MyLex) is de verdieping geregeld door op meerdere woorden in het zoekveld te zoeken. 

### Acceptatiecriteria
- [x] als je op AAA zoekt, moet je alleen resultaten vinden waar AAA in voorkomt. als je op AAA BBB zoekt moet je alleen resultaten vinden waar AAA en BBB in voorkomen. (nb. het resultaat hoeft dus niet exact de string 'AAA BBB' te bevatten, maar AAA en BBB moeten er elk ergens in voorkomen) 
- [x] op dit moment geeft 'eiken' meer resultaten dan 'eik'. dat kan niet kloppen. uitzoeken waarom dat is en herstellen.

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [x] inregeling elastic search aanpassen

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik invloed uit kunnen oefenen op welke verdieping ik de informatie wil zoeken. Bijvoorbeeld, dat er eerst een samenvatting gepresenteerd wordt, direct zoeken op een vraag, eerst zien wat er in de wijk aan de hand is, etc.

**Comment by rubenvdlinde** [comment]
IS dit iets wat we in Elastick search kunnen koppelen

**Comment by PascalIcatt** [comment]
Huidige "of" search aanpassen in "en"

**Comment by PascalIcatt** [comment]
Observatie: zoeken op eik geft minder resultaten dan eiken (?????)

**Comment by sytskevanhasselt** [comment]
Een van de acceptatiecriteria van deze (#120) was: 
- op dit moment geeft 'eiken' meer resultaten dan 'eik'. dat kan niet kloppen. uitzoeken waarom dat is en herstellen.

Dit hebben we opgelost door de Precision Heel Strak te zetten, op 8.
MAAR: dat leidt tot 'decreased typo tolerance', en het uitzetten van Fuzzy matching. 

Om dit op te lossen moeten we meer inregelen m.b.v. de demogelijkheden van 'Stemming' en het optimaliseren voor Taal. 
Zie ook https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis.html
