### ISSUE TITLE
Als KCM wil ik vanuit het kennisartikel in KISS feedback kunnen geven op geraadpleegde content

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#121]
### Toelichting
Als klantcontactmedewerker wil ik vanuit het kennisartikel in KISS feedback kunnen geven op geraadpleegde content, zodat de beheerders van de content deze up-to-date kunnen houden. 

nb. voorlopig is er geen mogelijkheid om feedback te koppelen aan een specifiek deel van een kennis artikel. daarvoor is de structuur (nog) niet geschikt genoeg.

nb. plain text mail. geen styling

### Acceptatiecriteria
- [x] mailto is instelbaar door implementeerder (zonder deployment). nu icatttest+kiss@gmail.com gebruiken
- [x] In de interface staat een interactie-element waarmee KCM feedbackbericht kan starten
- [x] In de Feedback staan een aantal onderdelen. deze kunnen door de kissmedewerker ingevuld worden en komen in de mail terecht:
  - Naam / link van het artikel, dit wordt door KISS in de feedback gezet
  - Specifieke content waar het over gaat; dit wordt door de KCM in de feedback gezet, door bv. het stuk tekst te selecteren, kopieren en te plakken
  - Opmerking; wat klopt er niet, wat is er mis: dit vult KCM in
  - Omschrijving bron of aanleiding: hoe kwam je erachter dat het niet klopt, van wie hoorde je dat; dit vult KCM in, niet verplicht
  - Contactgegevens van de betreffende KCM: e-mail. Let op als dit nog niet kan (omdat inloggen nog niet opgeleverd is, dan wordt dit een vrij invoerveld en dan voegen we een acceptatie criterium aan inloggen toe om dat veld alsnog automatisch te vullen)

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [x] mail sturen
- [x] reviewobject configureren
- [x] api opleveren aan ICATT
- [x] We hebben een mailgun url nodig
- [x] afzender adres moet matchen met het domein van de mailserver, om te voorkomen dat de mail in de spam folder terecht komt. het afzender adres moet dus configurabel zijn en dit moet gedocumenteerd worden
- [x] er staan quotes in de mail rond het blok Contnent....Contactgegevens

### Taken ICATT
- [x] ux design
- [x] feedback formulier
- [x] niet direct aan deze story gerelateerd maar een algemeen issue: de cache buster voor frontend bundles werkt niet. na deploy is ctrl+f5 nodig. svp fixen. apart issue van gemaakt

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik vanuit het kennisartikel in KISS feedback kunnen geven op
geraadpleegde content, zodat de beheerders van de content deze up-to-date kunnen houden.

**Comment by rubenvdlinde** [comment]
Hiervoor kunnen we het review component hergebruiken

https://github.com/ConductionNL/review-component

Word nu omgekat naar een nieuw component onder _> https://conduction.stoplight.io/docs/huwelijksplanner/branches/main/iuyk4p44gj610-reviewregistratie

**Comment by WilcoLouwerse** [comment]
Er is een review object toegevoegd aan de gateway die er zo uit ziet:
https://conduction.stoplight.io/docs/huwelijksplanner/999140b02c4ab-review

**Comment by WilcoLouwerse** [comment]
Het begin voor email versturen is er. Ik krijg nu een email als ik een review object post op de gateway met wat info uit het review object.

![Image](https://user-images.githubusercontent.com/3785488/177347873-4446b20c-5769-4d84-884b-80027e6808dc.png)

Mijn todo lijstje:
- We hebben een mailgun url nodig, ik heb voor nu eentje van een ander project gebruikt. Deze url moet zo worden opgeslagen dat deze niet uit de git repo te halen is
- Code abstracter maken / opruimen + docblocks toevoegen e.d.
  - Code omzetten naar gateway plugin
  - Configuratie toevoegen voor wanneer EmailSubscriber getriggered word, dit is nu altijd het zelfde en alleen aan te passen met een deploy.
  - Email template configuratie toevoegen, dit is nu altijd het zelfde en alleen aan te passen met een deploy.
- Mailto instelbaar maken
- Email ietsje netter maken
- Nadat inloggen is afgerond ipv een uuid gegevens van de user/persoon laten zien bij aanhef

**Comment by mstokericatt** [comment]
hoe mappen we de input op de api:
 
{
"id": "497f6eca-6276-4993-bfeb-53cbbbba6f08", 
leeg laten

"author": "94e8bb2c-e66b-11ec-8fea-0242ac120002", 
id van de persoon die fedback geeft. moeten we dat niet leeg laten vanaf de client en in de gateway vullen? anders kan je namens iedereen reviews versturen. 

"topic": "www.example.nl",
url van het artikel, mag leeg

"name": "string",
naam van het artikel, mag leeg

"description": "string",
Deze drie velden moeten er nog in. proppen we die samen in description? zo ja: hoe maken we onderscheid? json? \r\n?
-- Specifieke content waar het over gaat; dit wordt door de KCM in de feedback gezet, door bv. het stuk tekst te selecteren
-- Opmerking;  wat klopt er niet, wat is er mis: dit vult KCM in
-- Omschrijving bron of aanleiding: hoe kwam je erachter dat het niet klopt, van wie hoorde je dat; dit vult KCM in, niet verplicht

"rating": 1
gebruiken we (op dit moment) niet. moeten we het veld niet meesturen? of vullen met null, "", 0?
}

**Comment by sytskevanhasselt** [comment]
URL van het artikel: het gaat om een interne bron, hoe gaat die url eruit zien? 
Op het moment dat ID toch nuttig blijkt bij de ontvanger, kunnen we het dan makkelijk toevoegen?

**Comment by sytskevanhasselt** [comment]
Aanvullend: de verdere afronding van deze story wordt gehinderd door de nog openstaande vragen rondom Kennisartikelen / PDC / Kennisbank

**Comment by sytskevanhasselt** [comment]
### bevindingen
Zie document, bevindingen SH01, SH03 t/m SH07

[Bevindingen_Sprint04_20220725SvH.docx](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/9184689/Bevindingen_Sprint04_20220725SvH.docx)

**Comment by WilcoLouwerse** [comment]
Robert heeft de zender van de email geset op:
kiss@commonground.nu

Dit is aan te passen op de gateway door het email template te wijzigen op /admin/email_templates. Er is een newReviewTemplate email template, deze is te vinden door een get collectie api-call te doen:
![image](https://user-images.githubusercontent.com/3785488/182148288-82f8d9ba-ec00-4249-88a0-3d474cb39621.png)

Pak hiervan het id en dan is het mogelijk een PUT te doen op het email template om de sender aan te passen:
![image](https://user-images.githubusercontent.com/3785488/182148493-eee1310e-b3ca-4238-b95a-34c5e19f61b7.png)

**Comment by sytskevanhasselt** [comment]
[Bevindingen-document staat ook in Teams](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20Sprint-05/Bevindingen_Sprint05.docx?d=wc05639c9d3d6423eab863d7351911561&csf=1&web=1&e=g6znBV), daar werk ik het steeds bij.

**Comment by WilcoLouwerse** [comment]
@rjzondervan Gaf aan dat "de eerste zin die begint met 'test' " inderdaad van de dex user vandaan komt, maar dat het met de huidige testgebruikers niet mogelijk is dit aan te passen.
Voor meer vragen hier over: @rjzondervan

**Comment by rjzondervan** [comment]
Dat is correct, de (voor)naam van de gebruiker is in overleg ingeregeld als 'test'. De huidige inlogmethode (openldap met username en password) voorziet helaas niet in hele uitgebreide informatie over de user. Deze inlogmethode kan bijvoorbeeld al geen achternaam meegeven in dex.

Dit kan wel met uitgebreidere SSO inlogmethodes als Azure AD, daarvandaan kunnen veel meer gegevens worden overgenomen.

**Comment by sytskevanhasselt** [comment]
Oke! In het vervolg zou het fijn zijn als de gebruikers niet allemaal dezelfde naam hebben, dus dan minimaal test01 en test02. Maar voor nu is dit helder.

**Comment by WilcoLouwerse** [comment]
Voor sh07 was de wens om de tekst aan te passen in de mail naar:
[NaamKCM] heeft feedback gegeven op:  [Titel van het ding waarop feedback kwam]
Ik heb de tekst nu aangepast, maar [Titel van het ding waarop feedback kwam] is nog even een dingetje.

Bij het doen/aanmaken van een review word er een topic meegegeven, dit is een url verwijzing naar een object.
Om dus de titel van een object te tonen, moet ik eerst het object ophalen en dan moet er ook een veld aanwezig zijn op het object waar een titel in zit.
Ik weet alleen dat niet elk object waar ooit een review op gedaan kan worden ook een titel heeft die in het een veld word opgeslagen met altijd dezelfde naam, bijv. "titel".

Dus conclusie, het tonen van een titel van een object kan ik gaan toevoegen, maar afhankelijk van de topic zal ik een nuttige titel kunnen tonen. Ik zou dan kunnen zoeken of er een veld bestaat genaamd "titel" of "name", als die niet bestaat zal ik toch de url gebruiken.

**Comment by mstokericatt** [comment]
Alle info over het object is al aanwezig op het moment dat je het feedback formulier invult. als er extra info in de mail moet, dan ligt het dus voor de hand om dat mee te sturen met het feedbackformulier. In de gateway het object weer opnieuw gaan opzoeken lijkt me een omslachtige route.
Maar los daarvan hadden we volgens mij besloten om voorlopig geen titel in de mail te zetten, omdat de data nog te ongestructureerd is.

**Comment by sytskevanhasselt** [comment]
Wat ik er tot nog toe van gezien heb, staat de titel die ik bedoel, in het veld 'name': deze wordt ook gebruikt in het subject van de mail.
Dus wat mij betreft wordt de eerste zin [NaamKCM] heeft feedback gegeven op: [name]
NB: wat ik ervan gezien heb, gaat elk object dat in Elastic zit, een property 'title' krijgen, en komt die in 'name'.

**Comment by mstokericatt** [comment]
De naam wordt dus blijkbaar nu al meegestuurd in het formulier @WilcoLouwerse.

**Comment by WilcoLouwerse** [comment]
Oke, check. Dan ga ik dat nog even aanpassen

**Comment by sytskevanhasselt** [comment]
De mails met feedback komen niet meer aan in icatttest@gmail.com

**Comment by sytskevanhasselt** [comment]
Status = done
