### ISSUE TITLE
Als KCM wil ik dat de zoekindex voortdurend geactualiseerd wordt

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#122]
### Toelichting
Als klantcontactmedewerker wil ik dat de zoekindex voortdurend geactualiseerd wordt, zodat ik altijd een actueel zoekresultaten voor mijn klant krijg.

### Acceptatiecriteria
- [x] periodiek synchroniseren van bron naar elastic
- [x] pull of push bepalen per bron: dit documenteren per bron inclusief de daarbij te verwachten ververs-interval. 
nb. op dit moment zijn er nog geen externe bronnen elastic serach, alleen dummy data in de gateway zelf. we beperken ons tot het periodiek bijwerken van de elastic index wanneer een item in de gateway (handmatig) wordt gewijzigd.
- [ ] ~frequentie is instelbaar per installatie~ HH: 24-9: MVP is niet dat het  instelbaarmoet zijn per bron. 
- [x] ~er is een processchema van de werking van het proces van updaten~ nog niet van toepassing ivm gebrek aan standaard bronnen. voor de relatie tussen kiss/elastic en bronnen zie de architectuurpraatplaat

### Taken Conduction
- [ ] Zorgen dat de contactgegevens van de medewerker in het medewerkerobject zit dat naar elastic gaat
toelichting: op dit moment ziet de data er zo uit:
"contact" :{
    "emails": [
        "/api/KlantEmail/4a261243-0187-486e-8280-25b6f38afa3a"
  ],
  ....
}
Het emails veld moet de daadwerkelijke emails bevatten ipv verwijzingen.
nb. er is ook een los email veld, maar ook als er maar 1 emailadres is, moet dit in de emails lijst komen.  
nb. er zijn nu medewerkers met verschillende datastructuren in elastic, omdat er op verschillende manieren gegevens zijn ingevoerd. de oude testdata svp opruimen, zodat alle gevonden medewerkers dezelfde structuur hebben.
Dit hoort niet bij deze story maar bij een andere.... even uitzoeken welke

### Taken ICATT
- [ ] ~eerst een lijst vn de bronnen maken en per bron de strategie documenteren en bespreken... daarna de implementatie taken verder uitwerken~ nog niet vn toepasing ivm ontbreken 'echte' bronnen
- [x] omdat de manier waarop de emailadressen in de aangepaste klanten/medewerkers api worden opgeslagen (array ipv los email veld) veranderd is , moet in de interface op een aantal plaatsen aangepast worden:
de algemene zoekresulten en de mewerkers die je vindt bij het contactverzoek formulier moeten het emailadres uit deze array gebruiken 

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik dat de zoekindex voortdurend geactualiseerd wordt, zodat ik
altijd een actueel zoekresultaten voor mijn klant krijg.

**Comment by rubenvdlinde** [comment]
Voor PUB en PDC betekend dat het werken met notificaties richting elastic search. daarvoor is nu vanuit de Notificatie Hackathon van de VNG en aanvullend een project vanuit Nijmegen de eerste plugin voor de gateway voor in ontwikkeling.

**Comment by sytskevanhasselt** [comment]
Document met eerste testbevindingen [staat in Teams](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen_H-04_Zoekindex%20Actualiseren.docx?d=w944f2f86074842118a268a8cb6f8514b&csf=1&web=1&e=soYLvD).

SH03 is een issue dat gefixt moet worden, de anderen zijn niet storend.
Dat gaat om het verschil in opbouw tussen de Medewerker die via de Gateway komt, en de Medewerker die we handmatig hebben gedaan.

NB: ivm de test op 1 september, houden we voorlopig de structuur van handmatig aan, en zetten we evt. extra medewerkers handmatig in Elastic. Pas na 1 september gaan we weer updaten vanuit de gateway

**Comment by sytskevanhasselt** [comment]
Status = Done
