### ISSUE TITLE
Impactanalyse SDU integreren

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#124]
Het resultaat van deze analyse moet een globaal stappenplan zijn voor het maken van een adapter met daarbij een schatting.

@hannekevanderhorst hoeveel prioriteit wil je hier aan geven?

**Comment by hannekevanderhorst** [comment]
Voorstel is door Matthias en HAnneke met input van Sytske uitgewerkt en staat hier: https://icattnl.sharepoint.com/:b:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Notulen%20ontwerpgroep%20gebruikersgroep%20architecten/Ingebrachte%20stukken/Offerte%20SDU-SDG%20adaptor%2020220703.pdf?csf=1&web=1&e=k8oOsv

**Comment by sytskevanhasselt** [comment]
Status = done
