### ISSUE TITLE
Overzicht en zoeken in contactmomenten

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#133]
### Zie #103 
Dit pakken we op als onderdeel van https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/103 (klantbeeld tonen)

### Story
Als KCM wil ik op basis van het telefoonnummer of e-mailadres van de klant eerdere contactmomenten kunnen opzoeken.

### Acceptatiecriteria
- [ ] ZIE #103 

### Taken Conduction
- [x] api-endpoint om te zoeken

### Taken ICAT
- [ ]  ZIE #103 

### Discussie
- [ ] ...

**Comment by hannekevanderhorst** [comment]
Userstories 1-4-2022
Als KCM wil ik op basis van het telefoonnummer of e-mailadres van de klant eerdere contactmomenten kunnen opzoeken.
HH 20-6: deze story uitgebreid met: Als KCM wil ik een overzicht van alle contactmomenten

**Comment by rubenvdlinde** [comment]
Contactmomenten API en Klanten API draaien volgens mij op dit moment al?

**Comment by sytskevanhasselt** [comment]
Is deze niet afhankelijk van R-02, https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/112?

**Comment by bbrands02** [comment]
Er kan op het endpoint `/api/klantcontactmomenten?klant.telefoonnummer=string&klant.emailadres=user@example.com&extend[]=contactmoment` gezocht worden op emailadres en telefoonnummer en dan krijg de contactmomenten terug van die klant.

**Comment by sytskevanhasselt** [comment]
Status = done
