### ISSUE TITLE
Bug in paginering: om de 30 seconden reset de paginering naar pagina 1

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#137]

**Comment by sytskevanhasselt** [comment]
Ik heb gekeken naar Paginering in Startscherm, en naar paginering in Zoekresultaat van nieuwe/werkinstructies. Hieronder de stappen, en beschreven resultaat. Volgens mij is dit het gewenste resultaat. 

### Paginering in Startscherm
1.	Open kiss
2.	Ga in kolom nieuws naar pag 2 én ga in werkinstructies naar pag 2
3.	Wacht. 

**Ik zie:** 
1.	In startscherm wijzigt niets, ik blijf op de pagina 2.
2.	In de Networktab zie ik steeds verschijnen:
 

![Image](https://user-images.githubusercontent.com/53014699/176718778-2a8461ba-a88b-4201-83da-36f6e95eb119.png)

De lijst met deze calls wordt steeds een beetje langer. 

### Paginering in Zoekresultaat van nieuwe/werkinstructies
1.	Typ ‘de’ in het zoekveld 
2.	Vind 24 resultaten
3.	Blader naar pagina 2
4.	Wacht 1 á 2 minuten

**Ik zie:** 
1.	Er wijzigt niets in het zoekresultaat, ik blijf dezelfde berichten zien, en op pagina 2 staan
2.	In de Networktab zie ik steeds verschijnen:
 

![Image](https://user-images.githubusercontent.com/53014699/176718482-a607a1d0-16d0-4911-b98a-7701908a87ca.png)



5.	Blader naar pagina 3
6.	Wacht 1 a 2 minuten. 

**Ik zie:** 
1.	Er wijzigt niet in het zoekresultaat, ik blijf dezelfde berichten zien, en op pagina 3 staan
2.	In de Networktab zie ik steeds verschijnen: 


![Image](https://user-images.githubusercontent.com/53014699/176718445-6546a148-eeb3-4dd2-8646-af508758b3d3.png)

**Comment by sytskevanhasselt** [comment]
Status = done
