### ISSUE TITLE
Interactieontwerp en design R2

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#138]

**Comment by mstokericatt** [comment]
@hannekevanderhorst deze bestaat alleen als klokcode toch? kunnen we hem hier weghalen?

**Comment by hannekevanderhorst** [comment]
Ja kan - kunt hem ook gebruiken om voortgang van Gina af te tikken - dat is aan jullie

**Comment by sytskevanhasselt** [comment]
Status = Done
