### ISSUE TITLE
Als KCM wil ik meerdere contactmomenten tegelijk open houden

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#142]
### Toelichting
het moet mogelijk zijn om meerdere contactmomenten open te houden bijvoorbeeld bij het beantwoorden van mail of whatsapp. In tilburg hebben ze een apart tabblad per contact. 

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Gebruikersgroep 16-6-2022

**Comment by rubenvdlinde** [comment]
Volgensmij is dit  frontend functionaliteit waar geen backend uitbreidingen voor nodig zijn

**Comment by sytskevanhasselt** [comment]
@hannekevanderhorst in hoeverre is dit S-04: Als klantcontactmedewerker wil ik meerdere klantinteracties tegelijkertijd in KISS kunnen afhandelen. Bijvoorbeeld bij meerdere klantinteracties tegelijk via chat

**Comment by hannekevanderhorst** [comment]
Naar mijn mening is S-04 iets anders en meerdere contact,momenten tegelijk out of scope


Met vriendelijke Groet


Hanneke van der Horst

Directeur

***@***.******@***.***>



ICATT. menselijk digitaal.
Nieuwezijds Voorburgwal 120-126
1012 SH Amsterdam

+31 (0)20 638 3068
+31 (0)6 5570 4292



www.ICATT.nl<http://www.icatt.nl/>

ICATT op LinkedIn<https://www.linkedin.com/company/icatt-interactive-media/>

Meld je aan voor de nieuwsbrief<https://www.icatt.nl/nieuwsbrief>.

________________________________

**Comment by rubenvdlinde** [comment]
Als deze outof scope is hoeven we er volgensmij niks me en kan die worden gesloten. 

Als het inscope is dan is het leveren van tabbladen en per tablad bijhouden wat de uuid van het contactmoment is iets wat alleen vanuit de frontend kan worden ondersteund. De backend bied al mogenlijkheid om meerdere contact momenten "open" te hebben staan op één ingelogde gebruikers al medewerker.

**Comment by mstokericatt** [comment]
@hannekevanderhorst als s-04 iets anders is, wat is dit dan? graag toelichten

**Comment by sytskevanhasselt** [comment]
duplicate, met S-04 / #148
