### ISSUE TITLE
Als KCM wil ik kunnen zien welke terugbelnotities er nog open staan

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#146]
### Link naar Frame
https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=1792%3A2795

### Toelichting
Als klantcontactmedewerker wil ik bij een klant kunnen zien welke terugbelnotities er voor die klant bij welke collega uitstaan en nog niet afgehandeld zijn. 

NB: deze gebruiken we ook om ueberhaupt terugbelnotities te kunnen inzien.

Besluit 26/07/2022: terugbelnotities gaan we opslaan als Contactmoment. 
Besluit 01/09/2022: Terugbelnotities komen in een eigen lijst in het Klantbeeld te staan. 

**Aannames terugkoppelen aan Architecten** 
- We integreren een ToDo in Contactmoment: de persoon voor wie de terugbelnotitie is, staat met e-mailadress als attendee in de todo 
- De aansluitende gemeente zorgt zelf voor een applicatie waarin de opvolging wordt opgepakt. Het gaat dan om het opvolgen van Contactmomenten-met-ToDO. 

### Acceptatiecriteria 
- [x] In het klantbeeld staat, boven de contactmomenten, een tabel met Contactverzoeken (Terugbelnotities)
- [x] In deze tabel staan alle Contactmomenten die een ToDo hebben, gesorteerd op datum, nieuwste bovenaan. 
- [ ] De lijst met Contactverzoeken (Terugbelnotities) heeft de volgende kopjes: Datum , Status (open of afgerond), Behandelaar  Datum afgerond (alleen als het is afgerond)
- [ ] Ik kan in het overzicht zien óf het Contactverzoek (Terugbelnotitie) is afgerond, en als ja op welke datum. 
- [x]  In deze lijst kan je een Contactverzoek (Terugbelnotitie), open klikken, zoals bij Contactmomenten. 
    
Onderstaande vervallen, we gaan voor MVP
    - [x] ~Er kan maar één Contactverzoek tegelijkertijd open zijn. Dus als je een tweede openklapt, klapt de ander dicht~
    - [x] ~Dit voeren we ook door voor voor Contactmomenten.~      
- [ ] In een opengeklapt contactverzoek zie dan de inhoud van het veld _Tekst van het contactmoment-deel_  Description van het todo-deel van het Contactverzoek. 

- Behandelaar = Attendee
- Status: 
    - property completed is leeg  / null betekent Open. 
    - property completed heeft een datum. Dat laatste is ook de datum afgerond

**Aannames** 
- We tonen nu alle Contactverzoeken (Terugbelnotitie): zowel de openstaande als de afgeronde. Een KCM moet namelijk ook kunnen zien wat er is gedaan met het Contactverzoek (Terugbelnotitie). 
- Mogelijk gaan we op termijn Contactverzoeken (Terugbelnotities) die langer dan X TIJD geleden zijn afgerond niet meer tonen. Maar dat doen we nu nog niet. 
- Als er een zaak gekoppeld is aan het Contactverzoek, dan staan de gegevens van die zaak in beeld, op dezelfde manier als in een Contactmoment; _NB het is de vraag of we Zaken kunnen koppelen aan Contactverzoeken ... Of moet dat via het CM van waaruit dit Contactverzoek is aangemaakt?_

### Op te pakken bevindingen uit Gebruikertest
- [x] #278
- [X] ~#279~  >> VERPLAATST naar #312 
- [x] #294

### Taken Conduction
- [ ] In de testdata moeten drie afgeronde terugbelverzoek zitten. NB: als er een manier is om via bv. Postman een bestaand contactverzoek te updaten, is dat wrschl beter: op die manier kunnen we, ook na een evt reset van database, zelf de juiste data maken. 

### Taken ICATT
- [x] Ontwerp Klantbeeld uitbreiden met Lijst Terugbelverzoeken.
- [ ] Ontwerpje doorvoeren. (Let op! de status komt uit de todo van het contact moment)

### Discussie
- [ ] ty #..

**Comment by rubenvdlinde** [comment]
Er zit hier een architecturale keuze onder, maken we van een terugbel notitie een taak of een zaak? 

In bijde gevallen kunnen die via de extend functionaliteit van de gateway door een gebruiker worden opgehaald aan de hand van een klant contact of bsn

**Comment by sytskevanhasselt** [comment]
Vanuit de wensen vanuit gebruikersgroep, denken wij dat we de keuze 'Contactverzoek = Contactmoment Met ToDo' moeten herzien.

**Comment by sytskevanhasselt** [comment]
Bevinding bij terugbelverzoek: "Als je een collega opzoekt en niet kan bereiken, is het mogelijk om diens gegevens over te nemen voor een terugbelverzoek/contactverzoek "

**Comment by sytskevanhasselt** [comment]
Ik heb een aantal bevindingen uit de gebruikerstest release 02 verplaatst naar deze story. Ik zet het label Refinene weer even aan, om te bespreken of dit de juiste plek is. 
@GinaVerk , kun jij die meenemen in design waar nodig?

**Comment by sytskevanhasselt** [comment]
NB: ik heb de acceptatiecriteria bijgewerkt, omdat de inhoud van  het Contactverzoek, de notitie voor de collega, niet in het Contactmoment staat, maar in de Description van de TODO.

**Comment by sytskevanhasselt** [comment]
Getest, zie [Testen + testdata > Bevindingen release 04 > Bevindingen_J-03_#146_ContactVerzoekenInzien.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_J-03_%23146_ContactVerzoekenInzien.docx?d=w7ee6766ae23d44e5b75bbb01252a4584&csf=1&web=1&e=GYX6fm)

SH01, SH02, en SH03 zijn voor frontend
SH04 en SH05 voor Backend
