### ISSUE TITLE
Als KCM wil ik een telefoonnummer en/of e-mailadres kunnen vastleggen bij een nieuwe klant

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#147]
### Toelichting
Dit was: Als KCM wil ik andere gegevens (telefoonnummer, e-mailadres) kunnen koppelen aan een contactmoment;
Verrijken klantgegevens - Als klantcontactmedewerker wil ik naast contactgegevens van de klant uit het BRP, ook andere gegevens (telefoonnummer, e-mailadres) kunnen koppelen aan een contactmoment, zodat ik de contactmomenten eenvoudig terug kan vinden. 

In R-02 / #112 gaat het over het toevoegen / wijzigen van de e-mailadres en telefoonnummers aan klanten. 
In de gebruikersgroep is n.a.v. déze story de wens naar voren gekomen om een contactmoment te kunnen terugvinden, ook als er alléén een telefoonnummer aanhangt. Achtergrond: je wil contacthistorie kunnen inzien en opbouwen. 

In deze story gaan we dus een nieuwe klant aanmaken en opslaan. 
1. Het toevoegen van een telefoonnummer aan een bestaande klant die alléén nog maar gegevens uit het BRP had.
2. Het aanmaken van een klant met alléén een telefoonnummer (zie ook #248)

### Acceptatiecriteria
- [ ] Als iemand belt die nog geen klantbeeld heeft, kan ik het telefoonnummer en/of emailadres opslaan bij het contactmoment 
    - [ ] ~als er géén bijbehorende persoon uit het brp gevonden is, mag ook de naam opgeslagen worden bij de klant,~
    - [ ] ~als er wel een brp record gevonden is, dan slaan we het bsn op bij het nieuwe klant record.~
Zoeken/koppelen van klanten aan brp wordt in een aparte story

- [x] Bij het opslaan van het contactmoment, wordt een nieuwe klant aangemaakt. Note: de klant wordt aangemaakt voorafgaand het afronden van een contactmoment;
- [x] Het contactmoment wordt ook direct gekoppeld aan die nieuwe klant.
- [x] minimaal een telefoonnummer of een email adres invullen. de rest is optioneel

### Taken Conduction
- [ ] ...

### Taken ICATT
- [x] Ontwerpje voor: waar leggen we telefoonnummer en / of e-mailadres vast een contactmoment? En evt. naam?
- [x] Ontwerpje doorvoeren

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Is standaard onderdeel van klantgegevens API

**Comment by sytskevanhasselt** [comment]
NB: er zijn twee stories die erg op elkaar lijken: 

K-02 - Verrijken klantgegevens  (dat is deze) 
Als klantcontactmedewerker wil ik naast contactgegevens van de klant uit het BRP, ook andere gegevens (telefoonnummer, e-mailadres) kunnen koppelen aan een contactmoment, zodat ik de contactmomenten eenvoudig terug kan vinden. 

en 
R-02 - Registreren aanvullen contactgegevens (#112 )
Als medewerker wil ik op verzoek van de klant contactgegevens van de klant kunnen inzien en aanvullen. Het gaat dan om het toevoegen of aanpassen van het telefoonnummer of het emailadres, zodat de inwoner goed op de hoogte kan worden gehouden. 

Wat is precies het verschil tussen deze twee?

**Comment by sytskevanhasselt** [comment]
Deze is getest. Bevindingen staan in [Teams, bij Bestanden > Testen + testdata > Bevindingen Sprint-07, Sprint-08, document Bevindingen_K02_TelEmailNieuweKlant.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20Sprint-07,%20Sprint-08/Bevindingen_K02_TelEmailNieuweKlant.docx?d=w0887acf342e545c99d6446598cf11dbf&csf=1&web=1&e=pIDv8z)

**Comment by sytskevanhasselt** [comment]
Alle bevindingen opgelost.

**Comment by sytskevanhasselt** [comment]
Toch nog een nieuwe bevinding. Bij het aanmaken van een nieuwe klant, met bv. alleen e-mailadres, wordt er toch iets in Telefoonnummer opgeslagen. Namelijk: 
```
telefoonnummers [
  "/apiKlantTelefoon/e5d78213-505d-46ad-93cd-1a155e6579ed"
]

```

Het gevolg is dat áls je zo'n Klant later gaat bewerken, er een Leeg maar wel verplicht telefoonnummer veld komt te staan. 
Dit gebeurt niet bij het aanmaken van een klant via een terugbelverzoek. 
Zie de twee klanten met mailadressen: AlleenEmail@syps.nl, Nieuwe klant toegevoegd, en OokAlleenEmail@syps.nl, voor wie een contactverzoek is aangemaakt.

**Comment by sytskevanhasselt** [comment]
Nu is ook dat opgelost. Ik sluit deze.
