### ISSUE TITLE
Registreren acties bij contactmoment

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#149]
### Toelichting
Bij het registreren van het contactmoment wil ik vastleggen welke collega ik geraadpleegd heb, of ik het gesprek doorverbonden heb, etc. 

Deze gaan we oppakken samen met #171

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Ik interpreteer deze nu als uitgevoerde handelingen, voor een stuk kunnen we die natuurlijk uit de logs trekken maar voor alles wat niet een "klik" was natuurlijk niet.

Is er een overzicht beschikbaar van de te verwachten handelingen?

**Comment by rubenvdlinde** [comment]
We leggen het of in het contact moment zelf vast (e.g. eindstatus) of in een ContactmomentObject (koppelobject)

**Comment by sytskevanhasselt** [comment]
@mstokericatt , @rubenvdlinde , ik heb antwoorden geplaatst, en label question weggehaald

**Comment by bbrands02** [comment]
objectcontactmomenten kunnen tegelijk meegegeven/aangemaakt worden bij het maken van een contactmoment

**Comment by sytskevanhasselt** [comment]
Voorbeeldscenario 

1. Joske belt naar het 14-nummer van haar gemeente. 
2. KCM neemt telefoon op en Start contactmoment. 
3. Joske vraagt: wat is de status van mijn omgevingsvergunning. 
4. KCM zoekt Joske op bij Klanten, en zoekt van daaruit  de zaak erbij,  koppelt de status terug. 
5. Klant vraagt maar wat is nou de behandeltermijn?
6. KCM zoekt op Kennisbank naar de termijnen en werkwijzen van Omgevingsvergunning. 
7.  KCM Contstateert dat er inderdaad vertraging is, en suggereert een terugbelverzoek te maken. 
8. Op het moment dat KCM de terugbelnotitie aanmaakt; 
    a. zijn de velden 'Voor welke medewerker' en 'Voor welke afdeling' op dat moment vooringevuld met de naam van Karin Jansen, en de afdeling waar Karin Jansen werkt. 
    b. is het veld 'waarover gaat het terugbelverzoek' vooringevuld met het zaaknummer van Joskes aanvraag omgevingsvergunning
    c.  zijn de gegevens van de klant die teruggebeld moet worden, vooringevuld met de gegevens van Joske uit het Klantbeeld. 
9. KCM rondt vervolgens het contactmoment af. Ook hierbij
    a. is Joske ook al gekoppeld als klant, 
    b. kan KCM eenvoudig aangeven welke Productpagina's / Vragen relevant waren voor dit contactmoment.

Kortom: veel is al vooringevuld, dit scheelt bewerktijd.

**Comment by sytskevanhasselt** [comment]
Er moet nog een optie komen dat je buiten een contactmoment om, oom een zoekresultaat kan koppelen aan een contactmoment door middel van deze knop. Hij start dan ook automatisch een contactmoment.

![Image](https://user-images.githubusercontent.com/53014699/187194683-c0f0886c-3d19-4999-9fdf-5255d8e3ab46.png)

**Comment by lencodes** [comment]
Er is momenteel maar één medewerker die een link to self heeft, die we gebruiken om toe te voegen aan `onderwerpLinks`.

Om te testen kan je de gebruiker: "Suzanne Moulin".

**Comment by sytskevanhasselt** [comment]
Zie #171 : gehertest en akkoord
