### ISSUE TITLE
Als KCM wil ik zelf kunnen instellen hoeveel contactmomenten ik kan zien

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#151]
### Toelichting
Overzichtelijke presentatie contactmomenten
Als klantcontactmedewerker wil ik zelf kunnen instellen hoeveel contactmomenten ik kan zien (bijvoorbeeld 5 of 10). 

Besrpeken met PL/PO: hoe belangrijk is dit? 

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
De api ondersteund door door het meegeven van een Limit property op zoekopdrachten e.g. ?limit=5
