### ISSUE TITLE
Als KCM wil ik dat mijn zoekopdracht binnen maximaal een halve seconde resultaat oplevert,

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#152]
### Toelichting
Als klantcontactmedewerker wil ik dat mijn zoekopdracht binnen maximaal een halve seconde resultaat oplevert, vergelijkbaar met internetzoekmachines, zodat ik de klant snel kan helpen.

### Acceptatiecriteria
- [ ] zoekopdrachten naar gegevens in de geïndexeerde (elastic search) bronnen moeten binnen  een halve seconde resultat opleveren. We testen dit op de DEV omgeving, vanuit de browser.

### Functionele teststappen
- [ ] test via browser. uitkomst:

Resultaten zijn afhankelijk van vele factoren, maar op dit moment levert zoeken ruim binnen de gestelde tijd een resultaat op (zie screenshots). Daarmee voldoet de KISS aan de gestelde performance eis.

![Image](https://user-images.githubusercontent.com/43372165/192224571-e0fb1ac6-9277-44c8-848a-8d115a0c622e.png)

![Image](https://user-images.githubusercontent.com/43372165/192224604-06f0e099-4d19-4300-a2f2-f92b55eeb0f0.png)

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Op zicht lijkt met dit eerder een Definition of Done dan user story maar goed, hiervoor zijn we afhankelijk van de gekozen opvolging van Elastic search.

**Comment by rubenvdlinde** [comment]
Nu even ingeschat op 8 in de overweging dat we wellicht een custom build doen

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
