### ISSUE TITLE
Als KCM wil ik dat teksten zo kunnen worden ingericht dat ik een relevant deel direct kan kopiëren

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#155]
### Toelichting
Als klantcontactmedewerker wil ik dat teksten zo kunnen worden ingericht dat een relevant deel direct kan worden gekopieerd, zodat ik het in mijn communicatie naar de klant kan gebruiken.

Bespreken met PL / PO: wat was de achtergrond hiervan? Wat is de meerwaarde hiervan?

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Vanuit een content perspectief is de tekst wat die is, hooguit dat wij bij het scrappen nog wat kunnen fine tune but that about it.

Dat zou dus suggereren dat het hier gaat om het weergeven van de tekst in duidelijke alinea's met eventuele sub koppen en dergelijke. Dat maakt dit in mijn beleving een frontend issue zij het op  de invoer frontend (CMS/CRM) zij het binnen kiss.

**Comment by sytskevanhasselt** [comment]
**Besproken in Ontwerpgroep 04-10-2022:** 
De story betekent dat we per stukje tekst in een gestructureerde bron een copy knopje moeten invoegen. Hoeveel meerwaarde is dat ten opzichte vanzelf een stukje tekst selecteren en kopiëren? Voorstel is om deze story van de backlog te halen omdat de gewenste functies ook buiten KISS makkelijk op te lossen zijn met niet heel erg veel extra moeite voor de KCM.
Besluit ontwerpgroep 04-10-2022: deze is gerealiseerd.
