### ISSUE TITLE
Als KCM wil ik dat wanneer ik teksten kopieer en plak, de opmaak en het lettertype ongewijzigd blijven

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#156]
### Toelichting
Als klantcontactmedewerker wil ik dat wanneer ik teksten kopieer en plak, de opmaak en het lettertype ongewijzigd blijven en dat ook symbolen zonder problemen overgenomen kunnen worden.

Bespreken met PL / PO: wat was de achtergrond hiervan? Zie comment. Het gaat om het overnemen van inhoud uit bv een Kennisartikel naar communicatie naar de burger. Dit moet verder uitgewerkt worden, op het moment dat we de kanalen Contactformulier en E-mail gaan integreren. 

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Volgensmij is dit een kwestie van hoe de copy paste en eventueel een cleanup op de ui wordt ingeregeld?

**Comment by sytskevanhasselt** [comment]
@hannekevanderhorst naar aanleiding van gebruikersgroep 15 sept, heb ik deze verplaatst naar sprint 9.

**Comment by sytskevanhasselt** [comment]
behouden?

**Comment by sytskevanhasselt** [comment]
gelabled en gesloten
