### ISSUE TITLE
Als KCM wil ik na het uitvoeren van een zoekopdracht in de kennisbank een verfijning kunnen uitvoeren

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#157]
### Toelichting
Als klantcontactmedewerker wil ik na het uitvoeren van een zoekopdracht in de kennisbank een verfijning kunnen uitvoeren, zodat ik binnen de zoekresultaten stapsgewijs kan komen tot het antwoord op mijn specifieke vraag.

In #120 hebben we al gewerkt aan het verkleinen van je zoekresultaat naarmate je meer zoekwoorden invoert. Maar daar moet je nog Enter tikken om de zoekopdracht uit  te voeren. 
In deze story gaan we daar aan toevoegen: zoeken tijdens het typen. 

### Acceptatiecriteria
- [ ] Zodra je bijv. 3 tekens hebt ingevoerd, wordt er een zoekopdracht naar Elastic gestuurd, en wordt het resultaat getoond. 
- [ ] Tijdens het typen wordt je zoekresultaat bijgewerkt. 
- [ ] Hoe meer je typt, hoe specifieker je zoekresultaat. 

### Functionele teststappen
- [ ] ...

### Taken Conduction
-  geen

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Ik interpreteer deze als na mijn zoek opdracht moeten de filter opties blijven staan, en moet ik de mogelijkheid hebben om extra filters toe te voegen. 

In dat geval is het een frontend issue, op de api's zijn de filters immers al aanwezig.

**Comment by sytskevanhasselt** [comment]
Teststappen: 
steeds een paar letters typen, en kijken naar de eerste 10 resultaten. 
Dat vergelijken met de resultaten voor dezelfde zoekopdracht op /kiss-engine/relevance_tuning in Kibana
