### ISSUE TITLE
Als KCM wil ik zowel inwoners (burgers) als ondernemers in mijn gemeente kunnen opzoeken

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#158]
### Toelichting
Als klantcontactmedewerker wil ik zowel inwoners als ondernemers in mijn gemeente kunnen opzoeken, zodat ik contacten, zaken en notities op klantniveau kan vastleggen. Ondernemers zijn ook klanten. 

We gaan in deze story ook oppakken dat je klantinformatie, naast in het Klantregister, ook kan opzoeken in BRP (voor burgers) of het Handelsregister (HR, bij Ondernemers) 

~we slaan contactmomenten en dergelijke op gekoppeld aan het kvknummer of rsin: we kiezen RSIN, die meekomt uit de HR bevraging.~ Bij nader inzien, zie ook Aannames, slaan we contactmomenten en dergelijke, voor Bedrijven op, gekoppeld aan het Vestigingsnummer.  
In lijn met de klantbeelden van personen, maken we altijd een klantobject aan als koppelobject voor de contactmomenten, zaken etc.

### Ontwerpbeslissing ###
Er is geen mogelijkheid om een RsIn op te slaan en we doen de aanname dat een contactmoment betrekking heeft op een vestiging en niet het bedrijf... dus we gaan bij het aanmaken van een klant het vestigingsnummer opslaan ipv rsin

### Acceptatiecriteria
- [x] In het klantbeeld zoek je OF naar een Persoon, OF naar Bedrijf OF naar Zaken
    NB: in het Design staat Burger/Burgers, dat moet Persoon/Personen zijn, In het design staat Ondernemer/Ondernemers, dat moet Bedrijf/Bedrijven zijn
- [x] Per Persoon/Bedrijf zoekactie: één invoerveld, met daarbij een manier om aan te geven wát voor soort gegeven het is. 
    - [x] dus bij Burger: zoeken op: ~Naam,~ Geboortedatum, PC+Huisnr, Telefoonnr, E-mail, BSN
    _NB: BSN moet láátste optie zijn, deze optie wordt het minst gebruikt._  
    - [x] Bij Ondernemers: Zoeken op PC+Huisnr, KvK-nummer, Bedrijfsnaam, Telefoonnr , E-mail
- [x] Bij Personen:
    - [x] PC+Huisnr of Geboortedatum of BSN wordt opgezocht in BRP;
    -  ~Naam wordt opgezocht in BRP, en bij geen resultaat in Klantenregister~ > dit doen we voorlopig niet: hier zijn nog wat vragen over, zie ook [dit comment](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/158#issuecomment-1285250051).
    - [x] Telefoonnr of E-mailadres wordt opgezocht in Klantenregister
    - [x] TEL en EMAIL kun je zoeken op 'deel van'
    - [x] BSN, Geboortedatum en Postcode moeten geheel matchen; er zit validatie op deze velden, zodat duidelijk is hoe je een Postcode/huisnr, geboortedatum of BSN in moet vullen
- [x] Bij Bedrijven:
    - [x] KvK-nr wordt opgezocht in Handelsregister (HR)
    - [x] Bedrijfsnaam, PC+Huisnr, Telefoonr of e-mailadres wordt opgezocht in HR, ~en bij geen resultaat in Klantenregister~ dat laatste nog even niet, zie ook de moeilijkheid om te zoeken in twee registers.  
    - [x] TEL en EMAIL kun je zoeken op 'deel van' _Toevoeging 21/10: bedrijfsnaam ook op deel van_
    - [x] De overige gegevens moeten geheel matchen: KvK-nr en postcode huisnr; er zit validatie op deze velden, zodat duidelijk is hoe je een Postcode/huisnr, of KvK-nr in moet vullen
- [x] Bij Bedrijven:
- [x] Het zoekresultaat laat een tabel zien met per klant alle gegevens waar je op kunt zoeken (is ook verschillend per Persoon/Bedrijf
- [x] In de tabel staan kolommen voor elk gegeven, maar niet bij alle klanten zal voor elk gegeven iets staan.
- [x] Bij een klik op een zoekresultaat ga je door naar het klantbeeld. Als de gevonden persoon/vestiging nog géén gekoppelde klant had, wordt een klant aangemaakt, met daarin alleen een subjectType en een subjectIdentifiecatie.
- [x] In het klantbeeld van één klant komt, onder de Klantgegevens, een extra blok
    - [x] bij PERSONEN: gegevens BRP: naam geboortedatum, -plaats, -land. Adres.
    - [x] bij BEDRIJVEN: gegevens Handelsregister: KvKnummer, vestigingsnummer, vestigingsadres, telefoonnummer, e-mailadres
- [x] bij ZAKEN zoek je alleen op zaaknummer. 
- [x] Contactmomenten bij een Klant-die-een-onderneming-is, leggen we de koppeling met de onderneming uit het HR obv ~RSIN~ Vestigingsnummer. 
https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1

#### Aanname
We gaan ervan uit dat elke Onderneming (NietNatuurlijkePersoon in HR), óók altijd minimaal één Vestiging heeft. Dus we zoeken in Vestigingen.
 
#### Voorlopig out of scope
- [ ] Een zaak kunnen op zoeken op Locatie van de zaak. 
_Dit is zoeken op adres, maar dan niet het adres van één van de betrokkenen, maar van de zaak zelf. bijvoorbeeld: de locatie waarover de Melding Openbare Ruimte gaat of de locatie van het pand waarvoor een Omgevingsvergunning is aangevraagd._

### Taken Conduction
- [ ] Toelichten: hoe bevragen we vanuit de frontend het Handelsregister, op KvK. 
Aangeven hoe we vanuit de frontend het Handelsregister bevragen op Naam onderneming, Adres onderneming of vestiging, kvk nummer, telefoonnummer. dus een lijstje met velden maken svp. sommige velden kunnen op meerdere plekken voorkomen (bv post adres/verstigings adres, maar ook meerdere vestigingen. ook is er overlap bv eerstehandelsnaam en handelsnamen, wlek moeten we moeten gebruiken?). voorlopige aanname dat we aan het vestiging endpoint voldoen de hebben. 
- [ ] testdata invoeren
- [ ] overleggen met ontwerpgroep of het volstaat op een vaste aantal velden te zoeken, of moet er OR zoekfunctionaliteit ingebouwd worden 
- [ ] redoc corrigeren. subjectIdentificatie bij klant api bevat nu alleen natuurlijk persoon, maar daar moet ook een vestiging in kunnen.
- [ ] Zorgen dat Redoc matcht met KvK-documentatie

### Taken ICATT - Bedrijven:
- [ ] Invoegen van Bedrijven-zoekpagina (zie design) 
- [ ] Als er geen resultaat in het HR gevonden wordt en er op telnr of email gezocht is, dan proberen via het klantenregister. als daar een klant gevonden wordt met een vestigingsnummer, dan de HR-gegevens obv het vestigingsnummer proberen op te halen.
- [ ] Als er nog geen bedrijf-klant is dan aanmaken bij opslaan van het contactmoment, met in het klantobject het vestigingsnummer
    subjectType": "vestiging",
    "subjectIdentificatie": {
        "vestigingsNummer": "string"
    }
    
- [ ] Als er wel al een klant was met het vestigingsnummer dan die klant gebruiken (koppelen) bij opslaan van het contactmoment. 
- [ ] Bij het tonen van een klantbeeld ook de HR-gegevens tonen als er een vestigingsnummer is opgeslagen bij de klant.
    NB: design is nog niet helemaal volledig.

### Taken ICATT - Personen:
- [x] Klanten-zoekpagina ombouwen naar Personen-zoekpagina
- [x] Als er nog geen Persoon-klant is dan aanmaken bij opslaan van het contactmoment, met in het klantobject het BSN
    "subjectType": "natuurlijk_persoon" 
    "subjectIdentificatie": {
        "inpBsn": "string"
    }

- [x] Als er wel al een klant was met het BSN, dan die klant gebruiken (koppelen) bij opslaan van het contactmoment.
- [x] Bij het tonen van een klantbeeld ook de BRP-gegevens tonen als er een BSN is opgeslagen bij de klant.

### Taken ICATT - ZAKEN:
- [x] Zaken-zoekpagina uitkleden: alleen nog maar zoeken op Zaaknummer. 
- [x] Zoekresultaat aanpassen naar nieuw design (Fatale datum kan weg, Aanvrager erbij tonen)
- [x] contactmomenten tonen bij de zaak is nu zowel technisch als functioneel niet consistent met contactverzoeken tonen bij klantbeeld. voorstel: bij beiden als blok eronder (bij zaak is het nu een tab). dan kan het technisch ook correcter geïmplementeerd worden.

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Naast de zoekschermen vraag dit in de backend om twee API's, BRP HC en KvK. Voor BRP HC geld dat deze al in de omgeving aanwezig is voor KvK geld dat we deze zullen moeten toevoegen.

Verdere zoek criteria etc zullen moeten worden uitgevraagd bij de gebruikersgroep, maar voor BRP HC is het nog wel relevent dat je niet zo maar op elke willekeurige combinatie mag zoeken. Daarvoor zal een apart zoek formulier moeten worden gemaakt.

**Comment by rubenvdlinde** [comment]
KVK is beschikbaar gesteld op de KISS omgeving

**Comment by sytskevanhasselt** [comment]
@mstokericatt @rubenvdlinde: vraag over hoe zoeken beantwoord, label question weggehaald. 
Ik ging ervan uit dat de vraag over kvk of rsin niet voor gebruikers was.

**Comment by sytskevanhasselt** [comment]
Eerste bevindingkjes over zoeken naar zaken, staan in teams: [Testen + testdata > Bevindingen release 04 > Bevindingen_#158_K03_ZakenZoeken.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_%23158_K03_ZakenZoeken.docx?d=wa5e9488b7f7846a1aab8e42f2b461e51&csf=1&web=1&e=qBU5vF)

**Comment by felixcicatt** [comment]
Wat betekent zoeken op Naam van een Persoon? Er zijn losse properties voor de verschillende delen van een naam. Zoeken op combinaties daarvan lijkt me ingewikkeld. Voor nu heb ik alleen een optie zoeken op Achternaam toegevoegd.

**Comment by felixcicatt** [comment]
Wat betreft personen vs bedrijven: is er een gegeven op een klantrecord dat we kunnen gebruiken om een onderscheid te maken? Anders ga je personen en bedrijven gemengd in de zoekresultaten krijgen.

**Comment by mstokericatt** [comment]
> Wat betreft personen vs bedrijven: is er een gegeven op een klantrecord dat we kunnen gebruiken om een onderscheid te maken? Anders ga je personen en bedrijven gemengd in de zoekresultaten krijgen.

zie de 'redoc corrigeren' taak bij conduction. is die al uitgevoerd?

**Comment by sytskevanhasselt** [comment]
Het bovenliggende gegeven dat het onderscheid maakt, is: subjectType
Deze kan de waarden hebben: 

- natuurlijk_persoon - Natuurlijk persoon
- niet_natuurlijk_persoon - Niet-natuurlijk persoon
- vestiging - Vestiging

Wij gaan zelf in principe alleen gebruik maken van natuurlijk_persoon en vestiging. 
Maar er zou in de klantregistratie zelf ook al voor kunnen komen: niet_natuurlijk_persoon. 
En zowel vestiging als niet_natuurlijk_persoon gaan over bedrijven.

**Comment by felixcicatt** [comment]
Merci! Daarnaast denk ik dat het goed is om bij een nieuwe persoonklant het BSN verplicht te stellen, want daarmee koppelen we de klantgegevens aan de BRP gegevens. Hetzelfde geldt voor het KvK nummer bij bedrijven. Indien dat niet haalbaar is, moeten we een voorziening gaan maken om dubbele klanten samen te voegen in het geval van duplicaten.

**Comment by felixcicatt** [comment]
Aandachtspunt: als we gaan filteren op subjectType, kan je een hele hoop klanten in de testdata niet meer vinden. Die hebben daar namelijk geen waarde voor.

**Comment by sytskevanhasselt** [comment]
Als jij me op weg helpt, kan ik evt. m.b.v PUT zorgen dat de bestaande klanten een subecttype krijgen? 
En: moeten we er dan ook voor zorgen dat bij het aanmaken van een klant die waarde wél wordt gezet?

**Comment by felixcicatt** [comment]
@rubenvdlinde Hoe zoek ik een klant op vestigingsnummer? subjectIdentificatie.vestigingsnummer mag niet van de gateway

**Comment by sytskevanhasselt** [comment]
Goed idee, die schrijf ik op als Wens voor de volgende fase

**Comment by sytskevanhasselt** [comment]
Testbevindingen staan in Teams: [kanaal KISS > Files > Testen + testdata > Bevindingen release 04 > Bevindingen_#158_K03_Personen.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_%23158_K03_Personen.docx?d=w4427faa4a9b749c3aadaffd8d41cdb80&csf=1&web=1&e=Qgx1m5)

*Bevindingen: testen PERSONEN zoeken* 
In volgorde van prio
- SH06: Bij opslaan van een Klant obv BRP moeten we toch de naam overnemen: alles in de interface gaat over klantnaam, en die is nu leeg bij BRP-klanten. 
- SH08: Het adres ontbreekt in de BRP gegevens. Ontbrak ook in Design, dit is aangepast. Bij implementatie evt. overleggen over layout
- SH05: er zit géén bsn validatie op het veld als BSN is aangevinkt. Graag wel toevoegen, zie doc voor voorstellen
- SH04: Als ik zoek op BRP velden, en ik vind maar 1 hit, dan wordt er NIET automatisch doorgegaan naar Klantbeeld. 
- SH06: zoeken op geboortedatum MOET nu op dd-mm-jjjj (met streepjes) is het mogelijk om óók ddmmjjjj toe te staan? Zo zoekt men nu meestal.

NB: ten aanzien van niet kunnen zoeken op Naam bij personen: gaat dit ook spelen bij zoeke naar bedrijven? Want  daar is Naam wél een zeer belangrijke zoekingang.

**Comment by sytskevanhasselt** [comment]
_Bevindingen: bedrijven zoeken_
Testbevindingen staan in Teams: [kanaal KISS > Files > Testen + testdata > Bevindingen release 04 > Bevindingen_#158_K03_Bedrijven.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_%23158_K03_Bedrijven.docx?d=w570f9b30e5ce4c25b56de56ca87eff82&csf=1&web=1&e=0AKr88)

In volgorde van Prio: 
SH03: Plaats ontbreekt nog bij adres (staat nu alleen straat, huisnr etc, en Postcode)
SH05: in het Afhandelscherm wordt de bedrijfnaam niet goed getoond in de balk bij geselcteerde klant (vermodelijk nu alleen gekeken naar voornaam etc?)
SH02: Mogelijk om KvK-validatie toe te voegen? Vgl de opmerkingen over zoeken op BSN.
SH04: ik zie in json van de bedrijven staan: 'subjectIdentificatie: "/apiNatuurlijkPersoon/b10df1c0-08cd-437f-a23f-85b21a7565c9"' dat lijkt me niet goed?
SH06: graag kopje 'Openstaande contactverzoeken' wijzigen in Contactverzoeken (nb: ook bij Personen)
SH01: vraag over afstand tussen Zaken-blok en Contactmomenten blok

**Comment by sytskevanhasselt** [comment]
Alle bevindingen zijn opgelost. ik sluit deze story
