### ISSUE TITLE
Als gemeentelijke organisatie wil ik dat de KCM het antwoord op vraagniveau kan registreren

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#159]
### Link naar frame
https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=1748%3A2294

### Toelichting
Als gemeentelijke organisatie wil ik dat het antwoord op vraagniveau geregistreerd wordt, zodat ik weet over welke onderwerpen veel contact opgenomen wordt en daarop acties kan uitzetten.

**Besproken in Ontwerpgroep: 01/09/2022:**
De VNG standaard heeft één property, onderwerpLinks, voor "één of meerdere links naar een product, webpagina of andere entiteit zodat contactmomenten gegroepeerd kunnen worden op onderwerp.". Vanuit KISS wil men de mogelijkheid hebben om één van die onderwerpLinks als hoofdvraag te kunnen meesturen. 

In #111 en #159 realiseren we dat de geraadpleegde bronnen worden vastgelegd in het Contactmoment, in de property onderwerpLinks. In deze story gaan we de uitbreiding maken dat één van die onderwerpen als Hoofdvraag aangemerkt kan worden. 

Daarnaast gaan we in deze story aan het afhandelscherm een niet-verplicht veld toevoegen, 'vraag van de klant'. Hierin kan de KCM een afwijkende vraag invullen, als de eigenlijk vraag van de klant (niet) gedekt wordt door het geselecteerde kennisartikel

Voor deze story maken we de volgende uitbreidingen op het Contactmoment:
- toevoegen property primaireVraagVerwijzing
- toevoegen property primaireVraagWeergave
- toevoegen property afwijkendOnderwerp

### Aannames:
- we breiden het Contactmoment uit met 3 extra gegevens, die een 'managementinfo' eigenschap hebben.
- het zou mogelijk zijn omdat dit soort management info toe te voegen in de technische logging.
- Voor nu kiezen we er voor dat niet te doen. Mocht tzt vanuit de wens naar Managementinfo komen, dan gaan we dat eventueel wel doen

### Acceptatiecriteria
- [x] In het afhandelscherm is er een inputveld "Vraag"met een optielijst die alle geraadpleegde kennisbronnen toont [behalve smoelenboek] plus de optie "Anders"
- ~In het afhandelscherm is een niet-verplicht invoerregel (input), Vraag. Dit veld wordt standaard gevuld met de tekst van het element dat is aangegeven als hoofdvraag. De KCM kan hier ook handmatig wat invullen, of de vooringevulde tekst aanpassen.~
- [x] Als de KCM de optie Anders selecteert, dan moet die handmatig iets typen bij Specificatie
- [x] In het property primaireVraagVerwijzing slaan we de URL/id van het gekozen artikel/nieuwsbericht in
- [ ] ~Als het gekozen  artikel een Kennisartikel is, vullen we het property (bv. conditions of  dat als hoofdvraag is geselecteerd, in bij 'primaireVraagProperty'~ De leesbare weergave de primaireVraagVerwijzing stoppen we in primaireVraagWeergave. 
Dit is de titel van een Nieuws/werkinstructie of Kennisartikel. Als het een Kennisartikel is, zetten we erachter, de tab binnen dat kennisartikel (bv. Kosten, Voorwaarden)
- [x] Wat er is ingevuld bij Specificatie, zetten we in het property 'afwijkendOnderwerp'; nb: dit kán dus exact hetzelfde zijn als wat er staat bij primaireVraagWeergave.
- [x] Bij het ophalen van een contactmoment tonen we in het detailweergave van dat contactoment de tekst die hoort bij de primaireVraagWeergave, en afwijkendOnderwerp
- [x] SH30/09: bij _Contactverzoeken_ tonen we de primaireVraagWeergave, en afwijkendOnderwerp van het ContactMoment dat is gekoppeld aan het contactverzoek. NB: als er die koppeling er niet is, dan blijft dat leeg

### Taken Conduction
- [x] Toevoegen property primaireVraagVerwijzing in Contactmoment (URI en 
- [x] Toevoegen  property primaireVraagWeergave (string) in Contactmoment 
- [x] Toevoegen property afwijkendOnderwerp (string)

### Taken ICATT
- [x] Design voor het kunnen aangeven van de Primaire vraag, en voor invulveld voor afwijkende vraag / vraag van de klant
- [x] Design voor tonenen van deze inhoud in Detail Contactmoment
- [x] URL van aangevinkte primaire vraag in 'primaireVraag ' stoppen.
NB: als OpenDichtklikken nieuws/werkinstructie er nog niet is, dan die even lostrekken. 
- [x] Property van de primaire vraag als dot array in  'primaireVraagProperty' stoppen
- [x] Ingevulde waarde bij afwijkende vraag in property 'afwijkendOnderwerp' stoppen
- [x] In detailweergave van een opgeslagen Contactmoment de primarieVraag, primaireVraagProperty én afwijkendOnderwerp leesbaar tonen.

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Implementatie FAQ API

**Comment by sytskevanhasselt** [comment]
@rubenvdlinde let op, er gisteren bij Ontwerpgroep een Herzien Inzicht gekomen over Primaire vraag. 
Dus wij moeten deze nog even doorspreken.

**Comment by sytskevanhasselt** [comment]
@rubenvdlinde we spraken er gisteren over om primaireVraagProperty toe te voegen: hierin komt dan de naam van de property te staan, die hoort bij Tabblad waarin de KCM was. '
maar ik realiseer mij dat er niet echt een leesbare titel is van dat property, denk ik die we kunne ophalen. De vertaling naar Tabblad-namen doen we in de frontend (zie ook [dit comment bij #23](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/23#issuecomment-1229994273))
Is dat nog iets waar we naar moeten kijken?

**Comment by felixcicatt** [comment]
@sytskevanhasselt ik stel voor om niet met een vooringevuld veld te werken dat je kan aanpassen. Dat werkt bij het contactformulier namelijk ook voor geen meter. Wat doe je als je al wat hebt ingevuld, maar daarna een ander artikel als hoofdvraag selecteert? We zouden een optie kunnen toevoegen in de trant van: 'de hoofdvraag staat hier niet bij'. Als je die optie selecteert, verschijnt er een invoerveld waarin je zelf een hoofdvraag kan formuleren.

**Comment by sytskevanhasselt** [comment]
@felixcicatt ik heb vandaag een acceptatiecriterium toegevoegd, dat gaat over Contactverzoeken. Mocht het onduidelijk zijn, dan hoor ik het graag.

**Comment by hannekevanderhorst** [comment]
Een bevinding - ik zie Vraag en specificatie niet terug bij het opgeslagen contactmoment

**Comment by sytskevanhasselt** [comment]
Status = Done
