### ISSUE TITLE
Als KCM wil ik vanuit KISS met een link veel voorkomende acties kunnen starten

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#160]
### Toelichting
Als klantcontactmedewerker wil ik vanuit KISS met een link veel voorkomende acties kunnen starten, zoals het afsprakensysteem en formulieren om een melding te starten, zodat ik minder schermen hoef op te starten aan het begin van de dag.

**Input uit gebruikersgroep**
Het gaat om het opstarten van veel geraadpleegde applicaties (zoals afsprakensysteem, systeem voor melding openbare verlichting, Key2Belastingn), van veel gebruikte formulieren, zoals een Melding doen, e.d. 
Het is een gemeentespecifieke lijst, géén gebruikersspecifieke lijst.

Link naar design: https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=2194%3A5978

### Acceptatiecriteria
- [x] Er is een plek waar de KISS-beheerder een lijst met urls kan beheren (titel + url + categorie)
- [x] Categorie is een vrij invulbaar veld, de gemeente kan hiermee dus zelf de kopjes van de groepering instellen.
- [x] In KISS is een pagina, Links, waar deze lijst wordt getoond 
- [x] De links openen in een nieuw venster of tab
- [x] De links worden gegroepeerd getoond, naar Categorie. 

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [x] Objecttype maken (naam, en url)
- [x] Objecttype beschikbaar stellen voor de gateway
- [x] Bewerk-ingang in Gateway 'maken'? 

### Taken ICATT
- [x] Voorbeeld-objecten aanmaken in de Gateway
- [x] Design maken en toetsen bij Gebruikers
- [x] Design doorvoeren (als die hierboven af is)

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Dit lijkt mij puur een frontend wens

**Comment by rubenvdlinde** [comment]
Vraagen die dit bij mij oproept, 

- Om welke veel voorkomde acties gaat het dan?
- Waar plaatsen we de acties? (Menu?)
- Samenhang met #161 qua acties

**Comment by sytskevanhasselt** [comment]
@rubenvdlinde , ik heb de acceptatiecriteria bijgewerkt, naar aanleiding van het design en input uit gebruikersgroep

**Comment by WilcoLouwerse** [comment]
https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment.commonground.nu/openapi.json#tag/LinkOverige-objecten/operation/kiss/links/%7Bid%7D_Link_getId

Het link object bestaat nu op de dev gateway^

**Comment by felixcicatt** [comment]
Mag ik voor deze sorteren op categorie?

**Comment by WilcoLouwerse** [comment]
Zeker:
![Image](https://user-images.githubusercontent.com/3785488/197750451-f2d19073-0d15-4147-8685-3a57e2b5fbdd.png)

**Comment by WilcoLouwerse** [comment]
excuus, sorteren niet filteren.
dit werkt nu op dev:
![image](https://user-images.githubusercontent.com/3785488/197803493-8a112ce1-5104-40e2-85ea-9035acc250ea.png)

**Comment by sytskevanhasselt** [comment]
Meenemen met FrontendGateway bevindingen: status daarvan? bespreken met Lennart
