### ISSUE TITLE
Als KCM wil ik bij veelvoorkomende handelingen sneltoetsen kunnen gebruiken

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#161]
### Toelichting
Als klantcontactmedewerker wil ik bij veelvoorkomende handelingen sneltoetsen kunnen gebruiken, zodat ik niet constant met de muis hoef te klikken.

Het gaat er hier om dat je KISS met het toetsenbord kan bedienen, en je niet voor alles met je muis hoeft te klikken. Zodat je kan voorkomen dat je een muisarm krijgt.	
KISS moet dus voldoen aan de Niveau A-criteria binnen [WCAG criterium 2.1 Toetsenbordtoegankelijk](https://www.w3.org/Translations/WCAG21-nl-20200526/#toetsenbordtoegankelijk). 
- 2.1.1 Toetsenbord
- 2.1.2 Geen toetsenbordval
- 2.1.4 Enkel teken sneltoetsen

### Acceptatiecriteria
Je kan met alleen toetsenbordnavigatie en -interactie
- [ ] een zoekopdracht starten
- [ ]  een Contactmoment starten
- [ ] Klanten zoeken en vinden
- [ ] Klantbeeld bekijken
- [ ] Contactverzoek maken
- [ ] Tweede vraag toevoegen aan contactmoment
- [ ] ... 

### Taken Conduction
- [ ] geen

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
In mijn beleving gebeurd het registreren van sneltoetens in de browser en is het daarmee een frontend issue

**Comment by rubenvdlinde** [comment]
Vraagen die dit bij mij oproept, 

- omwelke veel voorkomde acties gaat het dan?
- Welke sneltoetsd (combinaties) moeten daaraan worden  verbonden

**Comment by sytskevanhasselt** [comment]
### Gebruikersgroep 15-09-2022
Gaat het hier om het inrichten van speciale toetscombinaties, zoals bv. Ctrl.-U  voor bepaalde handelingen? 
Nee, het gaat er vooral om dat je KISS met het toetsenbord kan bedienen, en je niet voor alles met je muis hoeft te klikken. 		
De code die we schrijven om de interface van KISS te maken volgt zoveel mogelijk de standaarden van het World Wide Web Consortium (W3C). Hierdoor worden standaarden voor toetsenbord bediening ondersteund: je kunt met tab-toets de verschillende velden langs. Keuze opties kun je met tabs of pijltjes langs en met de spatiebalk selcteren.
We zullen bij deze story de toetsenbordnavigatie nalopen. 

### Uit document User stories KISS, maart 2022
**S-06  Sneltoetsen** 
Als klantcontactmedewerker wil ik bij veelvoorkomende handelingen sneltoetsen kunnen gebruiken, zodat ik niet constant met de muis hoef te klikken.

**Comment by sytskevanhasselt** [comment]
Anouka heeft getest. haar bevindingen staan in een Excel bestand in TEams:[ Testen + testdata > Bevindingen release 04 > Bevindingen_#161_Testcase4_toetsenbord_20221006_as.xlsx](https://icattnl.sharepoint.com/:x:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_%23161_Testcase4_toetsenbord_20221006_as.xlsx?d=w3fe99b7c761f4fc4a223b6afb6d6f1e3&csf=1&web=1&e=qlThTX)

Er staan enkele bevindingen in die functionele fouten zijn, die iig verbeterd moeten worden, nl. 
Nummer 3
Nummer 9

Bevidningen 10 en 11 bespreek ik eest met Anouka.

**Comment by sytskevanhasselt** [comment]
Alle bevindingen nagelopen. Deze zijn opgelost, en als niet, dan verplaatsen we ze naar een andere story. Dus deze is af.
