### ISSUE TITLE
Startscherm tevoorschijn halen en verbergen

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#162]
### Toelichting
Als klantcontactmedewerker wil ik het startscherm naar voren halen als ik het nodig heb en wegklikken als ik het even niet nodig heb, zodat ik me goed kan focussen op mijn werk en tegelijkertijd altijd even een blik op het startscherm kan werpen. 

### Acceptatiecriteria
- [ ] Als je een contactmoment start, verschijnt er een menubalk. één van de tabs daarin is 'Startscherm'. 
- [ ] Als je daarop klikt, zie je het startscherm in je contactmoment; het Notitieblok blijft zichtbaar
- [ ] In dit deel kun je zoeken naar berichten en filteren
- [ ] Als je eigen startscherm al gefilterd was, zie je diezelfde filtering ook in je contactmoment
- [ ] Vanuit dát startscherm, kun je ook weer met een klik naar je lopende Contactmoment
- [ ] ~Klikken naar het startscherm en zoeken in startscherm (PUB) komt in de log te staan~
automatische logging wordt standaard geregeld in de gateway. het gericht loggen/opslaan van specifieke nieuwsberichten bij een contactmoment gaan we regelen in story #171 . het koppelen van een nieuwbericht/werkinstructie aan een contactmoment zou dan bij het openen/doorklikken van het bericht moeten gebeuren

- [ ] ~En ik kan het dus als actie registreren bij het contactmoment.~ wordt geregeld in #164 

### Taken Conduction
- [ ] ...

### Taken ICATT
- [x] styling startscherm: zoek/filter is breder dan nieuws/werkinstructies
- [x] styling: duidelijk maken dat je een zaak-zoekresultat kan aanklikken om naar de details te gaan. gelijk maken aan klant-zoekresultaten
- [ ] private stores automatisch wissen na afsluiten contactmoment. dit laatste punt moeten we komende week nog even bespreken. misschien nemen we het mee naar de story voor meerder vragen bij een contactmoment. komen we nog op terug

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Dit voelt voor mij als een puur frontend issue

**Comment by rubenvdlinde** [comment]
Gekke vraag maar dit voelt als een menu item?

**Comment by sytskevanhasselt** [comment]
Testen is klaar, bevindingen staan in [Teams: Bestanden > Testen + testdata > Bevindingen Sprint-04, Sprint-05, Sprint-06 > Bevindingen_A02_StartschermTijdensContactmoment.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20Sprint-04,%20Sprint-05,%20Sprint-06/Bevindingen_A02_StartschermTijdensContactmoment.docx?d=w24a5296f31eb4c8facbd2ea067cf2d3a&csf=1&web=1&e=fQXDzZ)

SH07 en SH08 zijn echte bugs. Mogelijk niet in dit deel, maar in Contactverzoek. SH07 komt ook uit Gebruikerstest. 
SH06 lijkt mij wel goed om op te pakken. 
SH02 en SH05 zijn eigenlijk restpunt van A03 / #25 .... 

Bij de overige punten: graag even overleg.

**Comment by sytskevanhasselt** [comment]
Hertest afgerond. Openstaande bevindingen zijn gefixed. 
t.a.v. de restpunten van n A03 / #25, zie ik dat er een Local Storage-element is toegevoegd, genaamd Preferences, waarin kanaal en skills worden opgeslagen. Ik denk dat dit geen probleem is, maar ik benoem het voor deze zekerheid hier wel. 
Deze issue is nu afgerond
