### ISSUE TITLE
Als KCM wil ik dat er afbeeldingen kunnen worden gebruikt bij de berichten

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#163]
### Toelichting
Als klantcontactmedewerker wil ik dat er afbeeldingen kunnen worden gebruikt bij de berichten, bijvoorbeeld om de categorie of andere dingen aan te geven, zodat ik overzicht kan houden en visueel geholpen wordt bij het filteren.

**Vraag voor gebruikersgroep**
- Gaat dit om iconen bij berichten? 
- Zoja: wat bepaalt welk icoon er getoond wordt? 
- Moet het icoon instelbaar zijn door berichtenbeheerder? 
- Wordt dit een uitbreiding op PUB, en zoja hoe (hard coded)? 

OF
- Gaat het om afbeeldingen _in_ de berichten?

Of gaat om Beide

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by sytskevanhasselt** [comment]
Het gaat hier om iconen oid bij de berichten, niet zozeer om afbeeldingen als onderdeel van de content van berichten?

**Comment by rubenvdlinde** [comment]
Dan klinkt het als een frontend wens?

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
