### ISSUE TITLE
Als KCM wil ik per bericht de titel en een stuk tekst zien, waarbij ik via openen dichtklikken het hele bericht kan tonen of verbergen,

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#164]
HH: 29-9. Gebruikersgroep geeft in gebruikerstest Release 3 aan dat zoals het nu is prima werkt. Het werkt nu als volgt:
- Nieuws en werkinstructie staan standaard opengeklapt 
- Je kan een bericht het het boekje op gelezen zetten en dan klapt het bericht dicht
- als je een contactmoment start komt er bij de nieuws en werkinstructie een vinkje bij om aan te geven dat dit opgeslagen kan worden bij het contactmoment

~~HH 23-9:
Deze story is nu anders ontworpen en anders geimplementeerd dan hieronder staat aangegeven. Reden is de overlap tussen het deze functie en de functie het bericht als gelezen markeren. Die overlap zit hem vooral in de de interface terugkoppeling van de handeling. Voorheen was de interface-terugkoppeling van boekje het ingeklapte bericht. Nu  alles is ingeklapt is de terugkoppeling vervallen:
- Gina heeft daarom in overleg met Lennard checkboxjes ontworpen ipv klik
- Vervolgens vonden Mark en Hanneke dat onduidelijk en heeft ze lees meer ontworpen maar de checkboxjes staan er nog
- Lennard heeft dit al gemaakt want dit heeft hij nodig voor het loggen van alle acties #171 

Hoe verder:

- checkboxjes en lees meer ... weer weghalen en story implementeren zoals hieronder staat
- onderscheidende state maken voor boekje (bv met een kleurtje) zodat interface-terugkoppeling boekje duidelijk is
- Als je teruggaat naar het startscherm binnen een contactmoment dan ziet het startscherm eruit zoals je het net hebt verlaten (met in en uitgeklpat wat je net hebt in en uitgekapt)
- als je terug gaat naar het startscherm als het contactmoment is afgehandeld, dan zijn alle berichten weer ingeklapt (want dit is nodig voor de nieuwe logging van gelezen niewsberichten bij het contactmoment)
- ik heb heel brutaal aanpassingen gemaakt in design - dat moet Gina natuurlijk doen en goed maken~~

### Link naar frame
https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=1815%3A2343

### Toelichting
Als klantcontactmedewerker wil ik per nieuwsbericht/werkinstructie de titel en een stuk tekst zien, waarbij ik via open- en dichtklikken het hele bericht kan tonen of verbergen, zodat ik overzicht kan houden over de berichten die mij aangeboden worden.

### Acceptatiecriteria
- [ ] Bij openen kis staat alles'half open' dat iszichtbaar: titel, datum, één of meer categorielabels, één regel van de inhoud
- [ ] Met een klik kan ik de hele inhoud zichtbaar maken. 
- [ ] Deze klik wordt bijgehouden in 'actielijst' en markeert het bericht als 'bron'voor je contactmoment
- [ ] met een andere klik, schuift 'ie weer half open
- [ ] Gelezen / ongelezen blijft een APARTE actie, zie ook #91 / A-05

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ..
- [ ] kijken naar  #208 
- [x] kijken naar  #201  _DIT IS INMIDDELS OPGELOST [svh29/09/2022]_

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Dit klinkt als een puur frontend funnctionaliteit

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
