### ISSUE TITLE
Als KCM wil ik het aantal zichtbare berichten kunnen kiezen

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#165]
### Toelichting
Als klantcontactmedewerker wil ik het aantal zichtbare berichten kunnen kiezen, zodat ik zelf de hoeveelheid informatie op m'n scherm kan bepalen.

**Vragen**
- moet dit per user opgeslagen worden, of geldt het alleen gedurende een sessie? Dit is wel eenvoudiger
- per apparaat / per user betekent dat ik het vandaag instel, en dat dit zo blijft totdat ik volgend week bedenk dat het iets meer moet zijn.
- 

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
De api ondersteund een ?limit= query parameter die hiervoor kan worden gebruikt

**Comment by sytskevanhasselt** [comment]
Hoe belangrijk is dit nog? Je kunt berichten in en uitklappen en op gelezen zetten. Daarnaast moeten we dan een soort settingen per persoon gaan opslaan. Willen we dat, en waar willen we dat dan opslaan? We kunnen ons voorstellen dat in de toekomst wellicht relevant wordt als je meer wil gaan instellen (bv vast kanaal of vaste skill), maar voor fase 1 lijkt het ons beter eerst maar een te kijken hoe het met de mogelijkheden van nu werkt. 
Besluit ontwerpgroep 04-10-2022: Deze kan vervallen. laat maar in gebruik zien wat handig is, degene die het nieuws beheerd heeft de verantwoordelijkheid om dit overzichtelijk te houden, en heeft daar ook alle middelen voor.
