### ISSUE TITLE
Als KCM wil ik dat belangrijke nieuwe berichten bij mij onder de aandacht worden gebracht

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#166]
design zie https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1 Bij A-11

### Toelichting
Als klantcontactmedewerker wil ik dat belangrijke nieuwe berichten bij mij onder de aandacht worden gebracht, ook als ik op dat moment niet op het startscherm zit. (bv: tramkaping aan de gang)

nb. de netste oplossing is implementeren via websockets. er is al een pull mechanisme wat opzich ook volstaat, maar als er ruimte voor is dan zouden we hier graag een websockets implementatie introduceren.

### Acceptatiecriteria
- [ ] Berichten kunnen in PUB gemarkeerd worden als Belangrijk (featured)
- [ ] Als er zo'n bericht wordt gepubliceerd / geüpdated, verschijnt deze (met speciale opmaak?) bovenaan in de lijst op de Startpagina
- [ ] Als er zo'n bericht wordt gepubliceerd / geüpdated, verschijnt dit bericht op een altijd zichtbare manier in de inteface. Dus ook: 
    - als ik in een contactmoment bezig ben
    - als ik het zoekpaneel heb opengeklapt.
 - [ ] Als je het bericht als gelezen markeert, verdwijnt de 'belangrijk'-markering uit beeld.
     NB: als ik het bericht weer ongelezen markeer, wordt de 'belangrijk'-markering weer zichtbaar
 - [ ] Een Featured bericht gedraagt zich verder net als andere berichten op het gebied van Gelezen/ongelezen

### Taken Conduction
- [x] ~websocket implementeren~ GAAT NAAR FASE 2
- [x] 'featured' optie toevoegen in pub
- [x] 'featured' property doorvoeren in Gateway

### Taken ICATT
- [ ] ontwerp
- [ ] implementatie: als een bericht featured = true en de Updatedatum nieuwe is dan de gelezen-datum (of het bericht is nog ongelezen): dan wordt de Belangrijk-markering getoond.

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Als in pop-up of featured? Nu even ingeschat als websocket implementatie

**Comment by rubenvdlinde** [comment]
Dit wordt een onderzoek issue ->PHP ondersteund niet native websockets. Dus welke tussen oplossing kiezen we.

Verwachte oplossings richting is een extra container, die distributie levert.

**Comment by rubenvdlinde** [comment]
Inmiddels wat meer onderzoek gedaan en op dit moment lijkt [swoole](https://dev.to/robertobutti/websocket-with-php-4k2c) de meest voor de hand liggende keuze.

Het is een PHP extensie die we kunnen draaien op de huidige container (dus geen extra container met belasting van dien noodzakelijk. En het bied [meer opties](https://tsh.io/blog/swoole-is-it-node-in-php-or-am-i-wrong/) dan alleen websockets.

**Comment by rubenvdlinde** [comment]
For now is er voor gekozen om dit te doen aan de hand van het reeds bestaande pull mechanisme. Dat betekend dat we dus niet meer worden geblocked door techniek maar door de wens van een design.

**Comment by sytskevanhasselt** [comment]
![image](https://user-images.githubusercontent.com/53014699/187166734-45d7c353-e9bb-4771-991c-39d2601a61a9.png)

**Comment by sytskevanhasselt** [comment]
Getest, zie ook doc in Teams: [Kanaal KISS > Files > Testen + testdata > Bevindingen release 04 > Bevindingen_#166_A11_belangrijkeberichtenpub.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_%23166_A11_belangrijkeberichtenpub.docx?d=w2fd10a822e264c9ca037eaa75c9da8ab&csf=1&web=1&e=bk7lnR)

Zijn meer PUB issues, dan specifiek voor deze story: 
- SH04: tekens in titel worden html-encoded weergegeven in de frontend. &gt; in plaats van >
- Berichten die in Wordpress worden verwijderd (naar Trash) blijven zichtbaar in de frontend, en staan ook nog in de json-responses. Hiervoor is een aparte bug aangemaakt: #386

**Comment by sytskevanhasselt** [comment]
SH04 is gefixt. het andere issue wordt bijgehouden in #386. 
Dus ik sluit deze als resolved
