### ISSUE TITLE
Als beheerder van de inhoud van het startscherm wil ik een begin- en/of einddatum kunnen zetten op berichten

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#167]
### Toelichting
Als beheerder van de inhoud van het startscherm wil ik een begin- en/of einddatum kunnen zetten op berichten, zodat ze automatisch weggaan zonder dat ik daar naar hoef om te kijken 

### Acceptatiecriteria
- [x] Als ik een bericht invoer in PUB, staat de publicatiedatum standaard op Vandaag. Ik kan deze wijzigen, als ik een publicatiedatum in de toekomst wil instellen 
- [x] Er is ook een einddatum. Deze staat standaard op 'vandaag over 100 jaar'. Als ik wil dat het bericht op een bepaalde dag verdwijnt, kan ik de einddatum naar voren halen. 
- [x] Als het bericht nog niet gepubliceerd is, kan ik de publicatiedatum nog wijzigen.
- [x] het bericht verschijnt pas op Startscherm, op publicatiedatum en later. 
- [x] Het bericht verschijnt NIET meer op het startscherm ná einde publicatie datum.

### Taken Conduction
- [x] Property 'Einde publicatie' toevoegen aan Plugin
- [x] Property mappen op de Gateway

### Taken ICATT
- [ ] Startscherm aanpassen zodat er óók gekeken wordt naar einde publicatiedatum. 

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Dit is standaard onderdeel van pub sub (De door jullie inmiddels gevonden publish datum)

**Comment by sytskevanhasselt** [comment]
Ik zie nu dat er een verschil is tussen de Publish date, en de Stardatum. Het staat idd niet expliciet vermeld hierboven, maar ik was er vanuit gegaan dat Publish date en Startdatum hetzelfde zijn.

**Comment by sytskevanhasselt** [comment]
===== #167 / B-02: begin- en einddatum.
=====


Verschijnen/verdwijnen op publicatie gaat goed. Bij publicaties met een publishdate ná vandaag (maar die wel vandaag zijn aangemaakt) is de sortering niet helemaal goed... En ik snap dat deze lastig is. 
Want de publicatie wordt gesorteerd op modified date (vandaag), en die moet dus eigenlijk gesorteerd zijn op publishdate. 
Maar alleen als Publishdate ná modified date ligt... 

Zie [Teams Kanaal KISS > Bestanden > Testen + testdata > Bevindingen release 04 > Bevindingen_#167_B02_BeginEinddatumPublicatie.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_%23167_B02_BeginEinddatumPublicatie.docx?d=w97f8dcc02ae64a759b695bbbf3a87f11&csf=1&web=1&e=u3Oj40)

**Comment by sytskevanhasselt** [comment]
De openstaande bevinding ta.v. sortering gaan we nu niet oplossen. 
1. Het moet blijken uit gebruik hoe belangrijk men dit vindt. 
2. Het is alleen een groot issue, als je heel veel andere berichten aanmaakt, nadat je het geplande bericht hebt gemaakt. 
3. Men kan hieromheen werken, door het bericht ook als Belangrijk te markeren, dan komt het bovenaan te staan.

Ik maak hiervoor een apart issue aan, bij wontfix. En ik sluit deze.
