### ISSUE TITLE
Als KCM wil ik relevante informatie op locatie en periode kunnen vinden

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#168]
### Toelichting
Als klantcontactmedewerker wil ik in één oogopslag kunnen zien welke activiteiten, werkzaamheden, uitloop van werkzaamheden, gebeurtenissen, meldingen, etc. er op stads-, wijk-, buurt-, straat-, rayonniveau, etc. in periode x (aanpasbaar) zijn, zodat ik snel weet naar aanleiding waarvan de inwoner, ondernemer of bezoeker contact opneemt, ik snel met de klant mee kan lezen en snel kan zien wat er aan de hand is.

**vragen**
- Bij de bronnen die we in Elastic ontsluiten staat niet echt een bron waarin informatie over "activiteiten, werkzaamheden, uitloop van werkzaamheden, gebeurtenissen, meldingen, etc. er op stads-, wijk-, buurt-, straat-, rayonniveau, etc. in periode x" zijn in te zien? 
- Wat is de bron voor geo-informatie in Objecten  (ofwel: hoe komt het in Elastic)? 
- Hoe staat die geo-informatie vervolgens in de objecten? 

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Hierbij gaat het eigenlijk om een aantal functionaliteiten

- Objecten kunnen koppelen aan een adres
- Dit adres geocoden
- Kunnen zoeken op geocode, en straal (ofwel x km in de buurt van)
- Kunnen zoeken op wijk, straat, gemeente niveau

**Comment by rubenvdlinde** [comment]
In lijn met het inzicht niet te doen in de gateway wat in elastic hoort de inschatting teruggebracht van 40 naar 10.

Het zoeken op geocode wordt door elastic  ondersteund onder geo queries -> https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-queries.html

**Comment by sytskevanhasselt** [comment]
### Gebruikersgroep 15-sept-2022
Om welke bronnen zou dit gaan, en kunnen we die in de ElasticSearch -index opnemen? Als je op locatie wil kunnen zoeken, dan moeten de locatie-gegevens als kenmerk zijn opgenomen in je bronnen. Dit is momenteel nog niet het geval. Zeker niet in de bronnen die we momenteel hebben opgenomen in KISS. 
Dus we stellen deze uit naar Fase 2. 


### Uit het document User Stories KISS, maart 2022
**D-01  Zoeken in kennisbronnen** 
Als klantcontactmedewerker wil ik de vraag van mijn klant kunnen opzoeken in kennisbronnen zodat ik goed in staat ben om de klant van het juiste antwoord te voorzien of op een andere manier van dienst te zijn.

**Comment by sytskevanhasselt** [comment]
gelabled en gesloten
