### ISSUE TITLE
(logging) Als KCM wil ik in afhandelscherm alles zien wat ik heb gedaan tijdens mijn contactmoment

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#171]
_Deze pakken we op samen met #149_

### Link naar frame
https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=1748%3A2294

### Toelichting
Als klantcontactmedewerker wil ik dat alle handelingen die ik tijdens het klantgesprek heb gedaan, automatisch gelogd worden, zodat ik aan het eind van het gesprek weinig nawerk-tijd heb om het gesprek vast te leggen

**Besproken 01/09/2022 met Ontwerpgroep**
Bij de stories N-03 (automatisch loggen), N-02/ #149 (Registreren acties bij contactmoment), N-01 / #159 (Registreren op vraagniveau) en R-02 / #111 (koppelen gegeven t.b.v. managementinformatie) gaat het steeds, náást wensen voor de KCM, om het verzamelen van extra informatie over/ rond contactmomenten t.b.v. management informatie. 
1. Men wil zoveel mogelijk relevante informatie koppelen aan een Contactmoment (N-01, R-01), en 
2. het moet voor de KCM zo makkelijk mogelijk zijn om dit te doen (N-02 en N-03). 

Met behulp van deze informatie in / aan contactmomenten kan een gemeente achterhalen hoe lang KCM's over contactmomenten doen, welke vragen vaak gesteld worden, via welke kanalen. Deze informatie kan een gemeente gebruiken om de informatievoorziening naar de medewerkers verder optimaliseren. 

Waar we binnen KISS echter tegenaanlopen is dat de (objecten binnen de) standaard-apis geen ruimte bieden om dit op te slaan. Daarom gaan we in eerste instantie alleen realiseren wat past binnen de huidige standaarden. WE rekken de standaarden op een beperkt aantal plekken op. 

We vatten deze story dus op als: 
Als KCM wil ik het afhandelscherm alles zien wat ik heb gedaan tijdens mijn contactmoment zodat ik aan het eind van het gesprek snel kan aangeven wat relevant was voor het gesprek.

NB: we trekken hierbij de story N-02/ #149 (registreren acties): we gaan indeze story ook de geselecteerde items vastleggen bij het contactmoment (CM)

### Acceptatiecriteria
- [x] In het afhandelscherm zie je een lijst van alle kennisartikelen die je in detail bekeken hebt; je kunt aangeven welke daarvan je bij het contactmoment wilt opslaan
- [x] In het afhandelscherm zie je een lijst met links naar de website die je hebt aangeklikt; je kunt aangeven welke daarvan je bij het contactmoment wilt opslaan
- [x] In het afhandelscherm zie je een lijst met Nieuwsberichten / Werkinstructies die je tijdens je contactmoment heb geopend / aangeklikt
- [x] In het afhandelscherm zie je een lijst van Zaken waarvan je de detailview hebt bekeken; je kunt aangeven welke daarvan je bij het contactmoment wilt opslaan
- [x] In het afhandelscherm zie je een lijst van de klanten waarvan je het klantbeeld bekeken hebt; ; je kunt aangeven welke daarvan je bij het contactmoment wilt opslaan
_NB: met alleen deze uitvoering bestaat de mogelijkheid om meer klanten aan een CM te koppelen. In deze story gaan we nog niets doen met dat risico_
- [x] In het afhandelscherm zie je een lijst van alle collega's je in detail bekeken hebt; je kunt aangeven welke daarvan je hebt geraadpleegt. 
_**Vraag:** hoe / waar moet je vastleggen 'welke collega's je hebt geraadpleegd'? Hebben medewerkers in het smoelenboek ook een URL zoals een Kennisartikel dat heeft en zetten we ze in onderwerpLinks? Of is onderwerpLinks niet de juiste plek? Tegelijkertijd hebben we geen andere plek ..._

- [ ] Alle geselecteerde items worden geregistreerd bij het Contactmoment: 
    - Zoekresultaten (webpagina's, kennisartikelen, collega's uit smoelenboek) word en URL met uuid opgenomen in het Contactmoment opgeslagen in onderwerpLinks
    - Nieuws/werkinstructies word ook met url in onderwerpLinks opgelsagen
    - Zaken worden gekoppeld
    - Klanten worden gekoppeld
- [x] Deze informatie wordt NIET getoond op het moment dat je op Klantbeeld een Contactmoment inziet. 

### Taken Conduction
- [ ] ~log api documentatie beschikbaar stellen~
- [ ] Zorgen dat op de Gateway in Contactmoment het property onderwerpLInks een Array is ([zie ook VNG](https://contactmomenten-api.vng.cloud/api/v1/schema/#operation/contactmoment_create)), en geen string

### Taken ICATT / frontend
- [x] Ontwerpje afronden voor eindscherm
- [x] Ontwerp realiseren in frontend
- [x] Zorgen dat geslecteerde items op de juiste manier bij het contactmoment worden geregistreerd.

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by sytskevanhasselt** [comment]
@mstokericatt  , @rubenvdlinde  , ik heb antwoorden geplaatst, en label question weggehaald

**Comment by rubenvdlinde** [comment]
Van deze moeten we echt dinsdag even de oplossings richting doornemen

**Comment by hannekevanderhorst** [comment]
HH26-2: getest - een bevindingen 
De vinkejes bij de bronnen die zijn geraappleegd moeten allemaal default aan staan. Nu staat er sal je meerdree medewerker, kennisartikelen en de website artiekel raadpleegdt ze we wel netjes allemaal in het overzicht maar er is er steedas maar van ieder tupe (mederwerkers, j]kenneisratikel, website) default aangevinkt.

**Comment by sytskevanhasselt** [comment]
Gehertest door SH en HH: is akkoord.
