### ISSUE TITLE
TAAK: uitzoeken  mogelijkheden SSO - PUB

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#177]
om redacteuren van nieuws en werkinstructies na inloggen in kiss ook automatisch in te loggen in de berichtenbeheeromgeving (wordpress/PUB). 
er is echter besloten om voorlopig losse beheeraccounts te gebruiken. deze taak vervalt dus

**Comment by rubenvdlinde** [comment]
Ik heb hem nu ingeplanned voor sprint 8 maar deze kan eigenlijk vervallen?

**Comment by rubenvdlinde** [comment]
Inmiddels hebben we een antwoord, de plugin https://wordpress.org/plugins/daggerhart-openid-connect-generic/ lijkt samen te werken met DEX

**Comment by mstokericatt** [comment]
> Inmiddels hebben we een antwoord, de plugin https://wordpress.org/plugins/daggerhart-openid-connect-generic/ lijkt samen te werken met DEX

fijn dat de mogelijkheid bestaat, maar zoals besproken: losse beheeraccounts hebben (voorlopig) de voorkeur.
