### ISSUE TITLE
Als KCM wil ik dat er hyperlinks in nieuwsberichten of werkinstructies kunnen staan

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#183]
### Toelichting
Als klantcontactmedewerker wil ik dat er linkjes in berichten kunnen staan, bijvoorbeeld naar nos.nl, een regionale omroep of informatie in de kennisbank, zodat de berichten zelf compact kunnen blijven en ik bij de bron aanvullende informatie kan opzoeken. 

SvH 26/07/2022: bespreken wie hoe wat waar we omgaan met HTML. 
In deze story verwerken we ook een aantal bevindingen over hoe we omgaan met html in Nieuws/werkinstrcucties, zie acceptatiecriteria

**Voorstel**
- In de beheeromgeving van PUB, kun je de berichten in allerleid html opmaken, dus ook links toevoegen
- Hiermee dekken we links naar pagina's op internet
- Links naar informatie in Kennisbank: **dit moeten we bespreken.** Want: 
    - Tonen we het Kennisbank artikel dan in de Kennisbank-applicatie, als ware het een link naar internet
    - OF: is het de bedoeling dat een link naar een Kennisartikel, het artikel opent _binnen KISS_? 
    - Voor dat dat tweede geval moeten we doorspreken 
        - of dit ueberhaupt mogelijk is 
        - wáár die content dan in de interface getoond moet wordne.

### Acceptatiecriteria
- [x] Linkjes in Nieuwsberichten / Werkinstrcuties openen altijd in een nieuw venster (ongeacht hoe het is ingevoerd in PUB).
- [x] Afbeeldingen, die in PUB in het bericht is gestopt, tonen we niet: als we dat wel willen, moet daar een andere story voor komen
- [x] Toegepaste styling op het gebied van lettertypes en kleuren wordt niet zichtbaar in KISS.

### Functionele teststappen
- [x] Maak een bericht in PUB, en voeg daar aantoe: inline styling in een span, een afbeelding, en een link zónder target
- [x] Bekijk het bericht in KISS, en constateer dat: 
    - [x] de styling is gestript
    - [x] het plaatje niet in de code staat
    - [x] de link tóch in een nieuw venster opent

### Taken Conduction
- [ ] ...

### Taken ICATT
- [x] ervoor zorgen dat links altijd in een nieuw venster openen.
hieronder nog twee bevindingen uit een eerdere story. meenemen als het weinig werk is, anders aparte story voor aanmaken
- [x] ervoor zorgen dat afbeeldingen niet getoond worden in werkberichten
- [x] ervoor zorgen dat styling uit werkberichten niet wordt overgenomen
- [x] kijken naar #207 

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by sytskevanhasselt** [comment]
Input uit gebruikersgroep: volgt

**Comment by rubenvdlinde** [comment]
Nieuwberichten en Werkinstructies kunnen gewoon HTML bevatten. Dus een hyperlink is daar goed mogenlijk.

**Comment by sytskevanhasselt** [comment]
@rubenvdlinde , @mstokericatt , in overleg met Hanneke, deze naar voren gehaald uit Release 3

**Comment by lencodes** [comment]
In dit issue wordt beschreven dat we (1) willen dat hyperlinks in een nieuw tabblad openen, (2) dat we geen images willen tonen en (3) geen styling willen toepassen. Dit is verwerkt (pull request staat open).
 
Echter zie ik het volgende waar misschien nog over nagedacht moet worden (ik weet niet wat de wens is):
	
1. Als gebruiker in Wordpress heb je momenteel toegang tot de volledige Gutenberg editor (waardoor je dus o.a. nu afbeeldingen kan toevoegen zonder dat we die tonen, maar ook audio kunt uploaden, bestanden, tabellen aan kunt maken, ... en nog veel meer);	
2. Nu hebben we een filter gezet waardoor we geen afbeeldingen meer tonen en geen styling meer tonen, maar gebruikers kunnen dus nog veel meer aanmaken (waar we momenteel niet op filteren).

 
Ik zie twee potentiële verbeterpunten:

1. De Gutenberg editor limiteren bij het aanmaken van een nieuw bericht (bij deze taxonomy zeggen dat je e.g. enkel paragrafen kunt aanmaken o.i.d.; dit is afhankelijk van hoeveel gebruikers moeten kunnen doen met zo'n bericht) en
2. In plaats van het uitsluiten van elementen (nu sluiten we het img element uit, maar kan een audio, table, ... etc allemaal nog ingeladen worden), kunnen we juist bepaalde elementen toestaan en de rest uitsluiten (e.g. enkel paragrafen zijn toegestaan).

 
Ik heb niet voldoende zicht op het concept van die berichten om te weten of bovenstaande voorstellen relevant zijn, voor nu is het in ieder geval nog mogelijk om bijvoorbeeld het volgende te maken (zie screenshot).

**Comment by sytskevanhasselt** [comment]
Ik vind dit zeer goede aanvullingen, en het lijkt me zeker zinvol om naar beide oplossingen te kijken. 

1. Ik denk dat we de eerste in ieder geval moeten meenemen. Nog even bespreken of dat in dit project zit, of een implementatievraagstuk is. 

2. T.a.v. de aanpak om een ‘allow’-lijst te maken (niet elementen uitsluiten, maar slechts specifieke elementen toestaan), vind ikhet lastig om die lijst te maken. Want het lijkt me meer dan <p>. In hoeverre moete we dan expliciet benoemen: 
<a>, <strong>,  <em>? En <table> lijkt potentieel een zinvolle tag. Tegelijkertijd kan je daarmee de hele opmaak vernaggelen. 

Voor nu noteer ik dit even op een bespreekpuntenlijst. 
Maar deze issue is akkoord, #207  nog niet helemaal.

**Comment by sytskevanhasselt** [comment]
Status = Done
