### ISSUE TITLE
correcte formatering environment variabelen

### ISSUE THREAD

**Issue by mstokericatt** [Klantinteractie-Servicesysteem/KISS-frontend#185]
in de env.js worden strings met getallen na een release vaak verkeerd geformatteerd:
gewenste output:  
window.organisatieIds = ["999990639"];
wordt vaak:
window.organisatieIds = ["9.99990639e+08"];

hoe maken we dit stabieler?

**Comment by sytskevanhasselt** [comment]
Opgelost door check in te bouwen in front end.
