### ISSUE TITLE
browser houdt oude versies van environmentvariabelen vast

### ISSUE THREAD

**Issue by mstokericatt** [Klantinteractie-Servicesysteem/KISS-frontend#186]
Er is geen cache buster voor de env.js. Na elke release zou er een timestamp of versienummer achter moeten komen.
dus, in plaats van dit: `  src="/env.js" `, zoiets  `  src="/env.js?v=123" `,

**Comment by rubenvdlinde** [comment]
Dit is een frontend issue

**Comment by rubenvdlinde** [comment]
Verwachten we trouwens dat deze waardes veel veranderen?

**Comment by felixcicatt** [comment]
@rjzondervan we hebben dit even overlegd, en het heeft onze voorkeur dat specifiek het env.js bestandje een `Cache-Control` header met waarde `no-cache` meekrijgt. Als de overige headers hetzelfde blijven, zorgt dat ervoor dat:

- er iedere keer een request voor env.js naar de server gaat
- er alleen als env.js gewijzigd is een body wordt meegestuurd en uitgelezen door de client
- er anders een statuscode 304 terugkomt, zonder body, en de client de browser cache uitleest.

Om daarvoor te zorgen hoeft dus alleen een Cache-Control header toegevoegd te worden. We hoeven dan ook niets met cache-busting te doen.

Klinkt dat logisch? Als je vragen hebt, kan je me bellen/chatten.

**Comment by sytskevanhasselt** [comment]
Status = Done
