### ISSUE TITLE
Als KCM wil ik kunnen zoeken in de nieuwsfeed en werkinstructies,

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#19]
...zodat ik direct een item kan vinden dat ik nodig heb.

**Projectcode**: A-04

### Acceptatiecriteria
- [x] zoeken op deel van de tekst/kop. niet op datum
- [x] zoeken in alleen nieuwsitems of alleen werkinstructies of beiden
- [x] paginering
- [x] nette melding als er geen items gevonden worden
- [x] Nieuwe of gewijzigde items verschijnen alleen als ze passen binnen je filter/zoekopdracht

### Functionele teststappen

1. Zoek op XXX
> Vind 1 werkinstructie en 2 nieuwsberichten
2. Beperk zoeken tot werkinstructie
> Vind alléén 1 werkinstructie; hoe je dit doet, staat beschreven in het [visueel ontwerp](https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schetsen-v.3?node-id=0%3A1)
4. Zoek op YYY
> Vind 4 werkinstructies en 8 nieuwsberichten, netjes gepagineerd
5. Zoek op XYZ
> Vind niets, dit wordt netjes teruggekoppeld.

### Taken Conduction
- [ ] #55

### Tijdinschatting 
- *Conduction* 8
- ICATT 2

**Comment by PascalIcatt** [comment]
@rubenvdlinde Zoeken via de api in text

**Comment by sytskevanhasselt** [comment]
Bevinding: er staan meer 'typen' berichtein bij het zoekveld, dan er zijn. Hier moet alleen staan: 
Nieuws
Werkinstructies

(met hoofdletters aan het begin)

![image](https://user-images.githubusercontent.com/53014699/175951972-9b51cd69-6075-4b9c-94ca-daa612303507.png)

**Comment by sytskevanhasselt** [comment]
Detail-bevinding, mogelijk is dit al besproken, @felixcicatt? Ik zie dat in de figma designs Werkinstructies links staan, en Nieuws rechts. In kiss-dev staat Nieuws links, en Werkinstrcuties rechts.

**Comment by sytskevanhasselt** [comment]
> Bevinding: er staan meer 'typen' berichtein bij het zoekveld, dan er zijn. Hier moet alleen staan:
> 
> > Alle
> > Nieuws
> > Werkinstructie
> 
> (met hoofdletters aan het begin)
> 
> Dit staat nu ook zo op Demodam. Wordt het daar gefixed met een deploy naar Demodam, of moet het daarin handmatig aangepast worden?
> 
> ![image](https://user-images.githubusercontent.com/53014699/175951972-9b51cd69-6075-4b9c-94ca-daa612303507.png)

Het issue van de meerdere opties in de pull down is opgelost. 

MAAR het issue van de Hoofdletters nog niet. Het blijkt dat als ik in de PUB-wordpress de naam van de Type aanpas, van 'nieuws' naar 'Nieuws', dan: 

1. Staat er netjes Nieuws met een hoofdletter in de pulldown, 
2. maar de berichten die het Type 'Nieuws' aan zich hebben hangen, verschijnen niet meer. 

Het lijkt (als ik kijk naar de Word-press omgeving) dat er gefilterd wordt op Name, waar je zou willen filteren op 'Slug' : 

![image](https://user-images.githubusercontent.com/53014699/176912229-e8eedae1-0a0c-4ee7-aa14-4944017df6f3.png)

**Comment by sytskevanhasselt** [comment]
### Bevinding: het Type is een Tag cloud en geen fixed list
Het veld waarin je het type instelt lijkt een soort tag-veld. Dat betekent dat je, als je gaat typen, suggesties krijgt van bestaande tags. Maar als je iets anders typt en Enter klikt, wordt het toegevoegd aan de lijst. 

Dat zou eigenlijk niet moeten: idealiter is het een fixed list waar je er altijd één uit kan kiezen.

**Comment by mstokericatt** [comment]
aanpassing doorgevoerd: slug wordt nu gebruikt ipv name.

**Comment by sytskevanhasselt** [comment]
Status = done
