### ISSUE TITLE
Documentatie Fix & PUB bijwerken naar update Wordpress

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#190]
**Vraag:** Sinds de wordpress update (ergens rond 8 juni was dat) klopt de PUB api documentatie niet meer. Is het mogelijk om die bij te werken

**Aanvullend :** Bij het overdragen van de Redoc is het Systke opgevallen dat de ReDoc van de Gateway en die van de onderliggende componenten uit een loopt. Bij controle bleek dat er bugs zitten in de generatie van de redoc waardoor deze minder goed leesbaar is. 

**Context:** De gateway genereerd automatisch documentatie van alle beschikbare API's, deze documentatie vormt het overdrachtspunt van Conduction naar ICATT en geeft daarmee in een belangrijke mate inzicht in de mate van voortgang op het project. Daarnaast is het de technische lijn waarlangs discussies moeten worden gevoerd  bij het refinen van user story's.  De volledige redoc vind je [hier](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json).

**Taken Conduction**

- [x] #444
- [x] Redoc overzichtelijk maken door API's te tags aan de hand van collecties zodat er clustering van endpoint ontstaat (feature)
- [x] Zorgen dat de descriptions worden weergegeven bij proporties (bug)
- [x] Zorgen dat type word weergeven bij properties, e.g. string (bug)
- [x] Zorgen dat enums worden weergegeven bij properties (bug)
- [x] Zorgen dat verplichte velden worden weergegeven bij properties (bug)
- [x] Zorgen nullable worden weergegeven bij properties (bug)
- [x] Zorgen dat bij Patch ook het verwachte schema van het object wordt weergegeven (bug)
- [x] Zorgen dat bij Put ook het verwachte schema van het object wordt weergegeven (bug)
- [x] Naamgeving objecten aanpassen (refactor)
- [x] No collection objecten vermelden onder Overige Objecten  (refactor)
- [x] Bij overige Objecten de objectnaam gebruiken ipv de beschrijving
- [x] Er lijken bij Handelsregisters en BRP dubbele calls in te staan
- [x] De beschrijving van de collection tonen ipv het woord "Collection"

**Acceptatie Criteria**
Het is ondoenlijk om alle eav objecten handmatig langs te lopen op parsing naar redoc. Als test casus kan echter de gevonden afwijking worden gebruikt tussen de [gateway redocs](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/ContactMoment/operation/ContactMoment_getId) en die van de VNG contact momenten [redocs](https://contactmomenten-api.vng.cloud/api/v1/schema/#operation/contactmoment_create).

**Comment by rubenvdlinde** [comment]
@bbrands02 de render service bevind zich in App\Service\OasDocumentationService en scheme rendering zit in de getSchema functie (en daarmee dus ook de bugs ;)

**Comment by rubenvdlinde** [comment]
@bbrands02 Voor het clusteren van de calls gebruiken we de collectie als tags, zie deze [tutorial](https://idratherbewriting.com/learnapidoc/pubapis_openapi_step7_tags_object.html).

Dat betekend dat er twee stappen moeten worden gezet

1. Alle Collecties moeten op root level worden toegevoegd aan het OAS schema waarbij we naam en beschrijving overnemen van de collectie
2. Alle endpoint moeten als tag de collectie krijgen waar ze in zitten

**Comment by rubenvdlinde** [comment]
@bbrands02 de naamgeving loopt nu vreemd, met {objectNaam}_getId etc

Ik zou voor de naamgeving verwachten
Get a list of {objectnaam] <- GET collection
Create a {objectnaam] <- POST collection
Get a single {objectnaam] <- GET object
Update a  {objectnaam]  <- PATCH object
Replace a  {objectnaam]  <- PUT object
Delete a  {objectnaam]  <- Delete object

**Comment by rubenvdlinde** [comment]
Vervolgstap is nu het automatisch genereren van een OAS voor PUB en deze weer inlezen in de gateway. Daarvoor is een plug-in beschikbaar:

https://wordpress.org/plugins/document-generator-for-openapi/#developers

**Comment by smisidjan** [comment]
Met de nieuwe manier van het generen van de documentatie wordt er per schema een beschrijving getoond ipv per collectie. Hierbij de vraag of het laatste punt nog relevant is?

**Comment by rubenvdlinde** [comment]
Ipv uitgebriede wordpres docs doen een uitleg van wat we nodig hebben aan data ongeacht de bron

**Comment by sytskevanhasselt** [comment]
- toevoegen calls voro ophalen lijsten Skills en Types
- verwerken wordpress-aanpassingen voor het pubobject: oude manier weghalen, en zorgen dat nieuwe manier klopt

**Comment by lencodes** [comment]
Voor het opschonen van de `openpub_skill` en `openpub_type` schemas staat een pull request open: https://github.com/Klantinteractie-Servicesysteem/KissBundle/pull/1.

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
