### ISSUE TITLE
frontend wijzigingen na release niet zichtbaar 

### ISSUE THREAD

**Issue by mstokericatt** [Klantinteractie-Servicesysteem/KISS-frontend#191]
los van het issue mbt de caching van de environmentvariabelen, gaat ook de caching van de rest van de applicatie niet goed. wijzigingen in de interface zijn pas na crl+f5 zichtbaar.

een voor de hand liggende, maar onwaarschijnlijke, verklaring zou zijn dat de js en/of css bundle steeds dezelfde filename heeft.
ter referentie, op dit moment zijn het deze 
 /assets/index.434dbcfc.js 
 /assets/index.3e611c8a.css
maar, in de actions is bij npm run build stap te zien dat er wel nieuwe namen gegenereerd...
svp uitzoeken waarom dit gebeurd

DIM@4967

**Comment by sytskevanhasselt** [comment]
Status = done
