### ISSUE TITLE
PUB: Veldtypes voor Type en Skill moet een optielijst zijn

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#202]
Bij het invoeren van de een Nieuwsbericht of WErkinstructie kun je in de rechterbalk het Type en de Skill invullen 

Dit zijn nu een soort 'tag cloud' velden. Met als gevolg dat allerlei spellingsvarianten van Type en Skill worden toegevoegd. 
Dit is niet de bedoeling: het moet een optielijst zijn, waarbij de opties worden beheerd bij 
Publications > Type, en bij Publications > Skill

- [x]  De lijst met types staat vast, en bevat twee items: Nieuws en Werkinstructie
  - Bij het Bericht **kies** je vervolgens één item uit de lijst. 
  - Let op: het veld type moet verplicht zijn

- [x]  De lijst met Skills zijn per gemeente verschillend, maar voer je in en pas je aan bij het bewerken van de lijst bij Skill.

  - Bij het Bericht **kies** je vervolgens een of méér items uit de lijst. 

- [x] als het goed is wordt hiermee deze gefixed: [Nieuws / werkinstructies: bij zoeken vind je ook berichten zónder Type #212](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/212)

![image](https://user-images.githubusercontent.com/53014699/181066527-d9b64650-1630-40c1-af99-e0286628c751.png)

**Comment by lencodes** [comment]
Onderstaand is besproken met @rubenvdlinde en @sytskevanhasselt.

Het limiteren van het _Type_ veld tot minimaal en maximaal één gaat niet laagdrempelig lukken. De andere punten van dit ticket zijn wel opgepakt (pull request staat open).

**Comment by lencodes** [comment]
@WilcoLouwerse er zijn een aantal GitHub issues die allemaal over de Wordpress omgeving gaan, ik documenteer hieronder op één plek waar alles staat in de WP REST API.

**Publicaties**

De endpoints _waar_ de publicaties staan (`kiss_openpub_pub`), zijn niet veranderd. Onderstaand een reminder.

- GET ALL: `/wp-json/wp/v2/kiss_openpub_pub`
- GET ONE: `/wp-json/wp/v2/kiss_openpub_pub/{id}`

**De grootste change waar we rekening mee moeten houden** is de manier waarop de data van een publicatie terugkomt, voorheen gebeurde dat via het standaard Wordpress object, nu gaat dat verlopen via het `acf` object _in_ het Wordpress object.

```

{ // Single Publication
  ...,
  "acf": {
    "publication_title": "Titel",
    "publication_content": "Content",
    "publication_type": 2,
    "publication_skill": [
        5,
        7,
        8
    ],
    "publication_start_date": "2022-10-15 00:00:00",
    "publication_end_date": "2022-10-27 00:00:00",
    "publication_featured": true
  },
  ...
}

```

**Skills**

De endpoints _waar_ de skills staan (`openpub_skill`), zijn niet veranderd. Onderstaand een reminder.

- GET ALL: `/wp-json/wp/v2/openpub_skill`
- GET ONE: `/wp-json/wp/v2/openpub_skill/{id}`

**Types**

De endpoints _waar_ de types (`openpub_type`) staan, **zijn wel veranderd**. Voorheen was het `openpub-type`, onderstaand de huidige implementatie (change is gemaakt voor consistency):

- GET ALL: `/wp-json/wp/v2/openpub_type`
- GET ONE: `/wp-json/wp/v2/openpub_type/{id} `

**Comment by WilcoLouwerse** [comment]
In de gateway moeten 2 referentielijsten komen voor skill en type. Ipv in WP
@WilcoLouwerse

**Comment by sytskevanhasselt** [comment]
Geen bevindingen, dit is akkoord. 
Ik laat 'm nog even openstaan, tot dat de Skills/Types uit de Gateway is geimplementeerd.

**Comment by WilcoLouwerse** [comment]
Na wat laatste dinge afstemmen met Lennart, staan de referentielijsten nu op dev
{{environment}}/api/ref/openpub_types
{{environment}}/api/ref/openpub_skills

**Comment by sytskevanhasselt** [comment]
Ik sluit deze toch af: ik zie dat de twee wensen zijn doorgevoerd. 
Bij het afronden van #285 zullen we opnieuw even checken: 
- of het nog steeds een single select en een multiple select is
