### ISSUE TITLE
Registreren gespreksresultaat bij contactmoment

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#21]
Bij het registreren van het contact wil ik kunnen aangeven hoe het contact afgehandeld is, zodat er managementinformatie beschikbaar is over het percentage contacten dat het KCC zelfstandig oplost.
Als beheerder van KISS wil ik zelf minimaal 10 gespreksresultaten kunnen aanmaken en wijzigen.

Voorbeelden van gespreksresultaten zijn: 

• Zelfstandig 
• Zelfstandig na ruggespraak met een collega 
• Doorverbonden, of 
• Terugbelnotitie gemaakt, etc.

### toelichting
Bij een contactmoment moet een gespreksresultaat gekozen kunnen worden. 
De lijst met mogelijke opties moet onderhouden kunnen worden.

@rubenvdlinde waar gaan we de lijst opslaan? Er is een selectielijsten register in het catalogi register, dat beheerd kan worden via OpenZaak. Wordt misschien een te zware oplossing voor het onderhouden van een simpel lijstje. Ruben komt met een voorstel. : We gebruiken de selectielijst

**Projectcode**: N-05

### Acceptatie criteria
- [x] de gekozen waarde wordt opgeslagen bij het contactmoment
- [x] de lijst met mogelijke gespreksresultaten moet beheerd kunnen worden. er zijn nog geen rechten/rollen voor alsnog kan iedereen dit dus doen. 
- [x] als een optie verwijderd wordt waar al contactmomenten aan gekoppeld waren, dan behouden die hun waarde. de verwijderde optie kan dan niet meer geselecteerd worden bij nieuwe contactmomenten
- [x] documentatie selectielijsten beheren in teams zetten. done staat hier: https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Handleiding/Beheer%20gespreksresultaten%20optielijst.docx?d=w5dc2d8dec8cb43e9a6ae082a655238dd&csf=1&web=1&e=ozwuX4

### Taken Conduction
- [x] #66
- [x] #67
- [x] #68
- [x] #78
- [x] #79
- [x] #82

### Tijdinschatting 
- *Conduction* 16
- *ICATT* 1

**Comment by rubenvdlinde** [comment]
Klant [ contactmomenten](https://contactmomenten-api.vng.cloud/api/v1/schema/#operation/contactmoment_create) ondersteun op dit moment (opvallend genoeg) nog geen resultaat.

Vanuit de gateway kunnen we deze "extenden" dus daar hebben we voor nu geen last van, maar wel goed die weer even terug te legen bij standaardisatie. 

Met betrekking tot status zouden die idealiter in de selectie lijsten horen, voor nu kunnen we echter ook een applicatie specifiek object gebruiken. Die zouden we kunnen spiegelen op het zaakstatus object

**Comment by mstokericatt** [comment]
wat als er meerdere onderwerpen/vragen behandeld worden in 1 contactmoment (telefoongesprek)?

**Comment by rubenvdlinde** [comment]
Dan krijg je meerdere onderwerp links of gekoppelde (objecten bij voorkeur die laatste)

**Comment by mstokericatt** [comment]
Het omschrijving veld in de gateway van een gespreksresultaat (ResultaattypeOmschrijvingGeneriek) heeft een maximale lengte van 20 tekens. dat is wel erg kort. svp langer maken. (100 karakters bv)

**Comment by mstokericatt** [comment]
Je kan geen gespreksresultaten verwijderen (ResultaattypeOmschrijvingGeneriek). svp verwijder optie toeveogen.

**Comment by rjzondervan** [comment]
Ter verduidelijking van het omschrijving vs definitie-veld de documentatie van de referentielijsten API van de VNG: https://referentielijsten-api.vng.cloud/api/v1/schema/#operation/resultaattypeomschrijvinggeneriek_list

**Comment by sytskevanhasselt** [comment]
Status = done
