### ISSUE TITLE
Zaak koppelen: interface is niet zo duidelijk

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#211]
Nadat we 

BEVINDING UIT RONDE 1.
De manier van oppelen van een zaak aan een contactmoment is niet zo duidelijk. Er staat alléén een vinkje, dat een íets andere kleur krijgt als je koppelt

Interface voorstellen: 
-	Koppelvinkje uitvoeren als checkbox? 
-	Ook boven dat vinkje een kopje, bijv. ‘koppelen’. In lijn met kopjes boven de andere ‘kolommen’. 
-	De hele regel van de gekoppelde zaak duidelijke andere weergave geven.

**Comment by hannekevanderhorst** [comment]
Deze is niet meer relevant. We koppelen geen zaken buiten een contactmoment. Binnen het kantmoment wordt dit automatische gelogd

**Comment by sytskevanhasselt** [comment]
Dit issue is inmiddels opgelost, doordat we zaken koppelen via het inzien van de DetailView.
Dus ik sluit deze.
