### ISSUE TITLE
Demodam en deploystraat op orde

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#213]
Ik wil naar echt continuous integration en de gebruikerstest op demodam doen:
- Op demodam staat nog een fout, de link items beheren op het startscherm wijst nog naar de dev omgeving
- Vaker en geautomatiseerd deployen, ICATT moet dat ook kunnen
- testdata op Demodam op orde brengen
- 
-  
### Taken
- [ ] zorgen dat we gemakkelijk via een json-bestand testdata ingelezen kan worden
- [ ] zorgen dat ICATT ook weet hoe dat moet
- [ ] Testdata aanvullen
- [ ] Het deployen moet zodanig gedocumenteerd zijn, dat je deploy via die documentatie kunt overdragen aan iemand anders (implementatie-voorwaarde)

**Comment by sytskevanhasselt** [comment]
We gaan niet meer werken met Demodam
