### ISSUE TITLE
Beter inzicht in Common Gateway

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#214]
We hebben een leesbaar overzicht nodig van hoe de Gateway is ingeregeld:

- Welke standaard APi's gebruiken we (met verwijzing naar de standaard)
- Wat zijn de aanpassingen op de standaard
- Waar worden zaken opgeslagen

**Comment by sytskevanhasselt** [comment]
Status = Done
