### ISSUE TITLE
Architectuurplaat updaten

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#215]
De architectuurplaat van Martijn moet aangepast worden zodat deze klopt met hoe het nu werkt. Deze moet iedere sprint als nodig worden bijgewerkt. https://icattnl.sharepoint.com/:i:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Designsprint/KISS%20Architectuurplaat%2020220426.png?csf=1&web=1

**Comment by sytskevanhasselt** [comment]
Status = Done
