### ISSUE TITLE
Als klantcontactmedewerker wil ik de vraag van mijn klant kunnen opzoeken in kennisbronnen

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#22]
...zodat ik goed in staat ben om de klant van het juiste antwoord te voorzien of op een andere manier van dienst te zijn.

### Toelichting
Het gaat bij deze story nog niet om het ontsluiten van bronnen, maar alleen over de presentatie en interactie binnen KISS.
Er worden in deze story dummy zoekresultaten gebruikt.

**Projectcode**: D-01

### Acceptatiecriteria
- [x] De user interactie van het zoeken is uitgewerkt en geïmplementeerd (nb. let op de scope, het gaat om een basis, het zoeken wordt later nog verder uitgewerkt in d-02 t/m d-09)

### Functionele teststappen
Is afhankelijk van detailniveau van de uitwerking: 
1. Hoe ziet een zoekresultaat eruit met hits uit verschillende bronnen?
2. Hoe ziet een zoekresultaat eruit dat veel meer hits bevat dan in het scherm passen? 

### Taken Conduction
Niks, dit gaat puur over de voorkant

### Tijdinschatting 
- *Conduction* 0
- *ICATT* 2

**Comment by sytskevanhasselt** [comment]
Status = done
