### ISSUE TITLE
TAAK: uitloggen configurabel

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#226]
Uitloggen werkt momenteel via een een API call op kissdevelopment-dimpact.commonground.nu/api/users/logout, daarmee wordt de cookie unset waarmee je uitgelogd raakt. Dit is dus een API call die onder water moet gebeuren, maar voorkomt gekkigheid met de redirects op de gateway.

Maar: voor werken op local development moet de e set-cookie header SameSite=none bevatten. Idealiter is dat configurabel op dezelfde manier als bij het inloggen.

**Comment by rjzondervan** [comment]
Na afstemming met Sytske sluit ik dit issue
