### ISSUE TITLE
Als KCM wil ik dat bij een contactmoment kunnen zien wie het heeft aangemaakt

### ISSUE THREAD

**Issue by mstokericatt** [Klantinteractie-Servicesysteem/KISS-frontend#228]
...zodat ik bij eerdere contactmomenten kan zien wie welk contactmoment heeft afgehandeld en er een lijst van mijn contactmomenten gemaakt kan worden

_ZIE OOK #244_

### toelichting
Bij de realisatie van het opslaan van contactmomenten, voor N-04, [#20](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/20), waren er nog geen inloggende gebruikers. Het was derhalve nog niet mogelijk op te slaan wie een contactmoment afhandelt. Inmiddels is dat wel mogelijk en moet dat dus via deze extra story alsnog gerealiseerd worden.

Gegevens van de medewerker halen op volgens NL GOV Assurance profile for OAuth 2.0. 

**HH Afgestemd met PM/PO 15-9-22. Als de medewerker niet meer in  ADFS staat (niet meer in dienst is) tonen we**
- medewerker niet gevonden

### Acceptatiecriteria
- [x] De ingelogde medewerker (user) wordt vastgelegd bij het contactmoment

Onderstaande gaan we parkeren, omdat we niet 100% zeker weten of we altijd de naam hebben.
- [ ] ~Bij het klantbeeld en eventuele andere plekken waar de contactmomenten getoond worden, wordt nu ook de naam van de bijbehorende KCM-user getoond.~
- [ ] ~Als de medewerker niet meer in de ADFS voorrkomt tonen we "medewerkers niet gevonden"~

### Taken Conduction
- [x] opslaan ingelogde gebruiker invullen bij medewerker en / of medewerkerIdentificatie in het contactmoment, 
- [ ] Extenden van die user in Contactmoment met Userobject, zodat de Voornaam Tussenvoegsel Achternaam getoond kan worden in Klantbeeld.
- [ ] Implementatiehandleiding aanvullen met informatie over gebruik van NL GOV Assurance profile for OAuth 2.0

### Taken ICAT
- [ ] Tonen van de Naam van de user bij de contactmomenten 

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by WilcoLouwerse** [comment]
![image](https://user-images.githubusercontent.com/3785488/187923682-3279e6d4-0d0a-45e7-a72e-6e565ab41d3e.png)
