### ISSUE TITLE
Zoeken en tonen kennisartikelen (PDC) - incl detailweergave

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#23]
### Toelichting
Er wordt een bron gekoppeld om de zoekresultaten bij D-01  dynamisch te maken.
We proberen hiervoor de Deventer: SDU, binnen het onderdeel PDC voor te gebruiken. Als er géén adapter is, dan gebruiken we de output van de Koppeling, om handmatig enkele producten in Elastic te zetten.

Voor deze story gaan we uit van een gestructureerde bron, waarmee een index met een vaste afgedwongen datastructuur opgebouwd kan worden. Voor deze structuur gebruiken we als basis de api van de sdg-invoervoorziening. Deze api is uitgebreid op basis van de structuur van de SDU VIND-pdc. Deze api noemen we voorlopig **SDG-plus.** 

### Besluiten over SDG-plus
- De volgende 5 elementen zijn toegevoegd na bestudering SDU: 
    - conditions; in de website is dit de inhoud die staat onder Voorwaarden
    - notice; in de website is dit de inhoud die staat bij Bijzonderheden
    - contact; in de website is dit de inhoud die staat bij Contact
    - deskMemo: bij SDU-vind is dit de informatie (1 pagina) die alléén door interne medewerkers te zien is. 
    - synonyms, een array waarbinnen één of meer synoniemen kunnen worden opgenomen.
- Eventuele opgemaakte content in de inhoudelijke blokken, moet in HTML worden weergegeven. Achtergrond hiervan is het uitgangspunt dat de meeste applicaties waarin deze content wordt beheerd, met HTML zullen werken.
    - NB: KISS stript deze html van styling en scripts. De kale html wordt weergegeven in de details van een Kennisartikel
    - KISS doet nu dus niets met ver-json-de MarkDown in de inhoudelijke blokken.
    - Als deze HTML onverhoopt ge-escape-te html bevat, dan heeft KISS logica om die te unescapen.  

### Acceptatiecriteria
- [x] Met de in story #22 gerealiseerde user interface kan gezocht worden in een beperkte set data ~gebaseerd op Producten in de SDG Invoervoorziening~ gebaseerd op standaard "SDG-plus" en op de VIND-catalogus van Deventer.
- [x] Er wordt niet rechtstreeks gezocht in de  ~~SDG Invoervoorziening~~ bron-PDC, maar in een (elastic search) index. De index wordt gevuld met data uit de hiervoor benoemde beperkte set.
- [x] De zoekresultaten worden in KISS getoond, de resultaten uit deze bron worden gelabeld als Kennisartikel
- [x]  Als een KCM doorklikt in op een gevonden Kennisartikel, wordt de inhoud van het Kennisartikel getoond in het zoekpaneel.
[zie dit comment](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/23#issuecomment-1229994273), [Zie ook Figma](https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1), bij onderdeel 'zoeken > resultaten overzicht > zelf aanvinken buiten contactmoment' of 
- [x] De html die in de Kennisartikel-objecten staat wordt gerendered in KISS, in het zoekpaneel
- [x] inlezen mock data, api endpoint communiceren met felix, felix zorgt dat de data dynamisch in de frontend komt
- [x] ~de feedback knop is alléén zichtbaar bij Kennisartikelen.~ deze vervalt

### Functionele teststappen
- [x] Zoek op 'briefadres': je ziet een aantal resultaten waaronder een Kennisartikel, "Briefadres aanvragen"
- [x] Constateer dat de inhoud gelijk is aan die van de pagina https://www.deventer.nl/briefadres. 
- [x] Constateer dat er extra inhoud staat voor de KCM's (in de api in het blok deskMemo)

### Taken ICATT
- [x] zorgen dat het in het zoekresultaat mark down en linebreaks netjes getoond / verwerkt worden. 
- [x] #179

### Taken Conduction
- [x] #48
- [x] #49
- [x] #50
- [x] #52
- [x] #53
- [x] #51

### Tijdinschatting 
- *Conduction* 60
- *ICATT* 2 front-end, 3 elastic 

### Discussie
- [ ]  #32
- [ ]  #35 
- [ ]  #34

**Comment by PascalIcatt** [comment]
@rubenvdlinde Wie gaat het vullen van Elastic Search met data uit Deventer SDU regelen?

**Comment by rubenvdlinde** [comment]
n.b. We gaan nog een SSO inregelen op de WP installaties van PUB en PDC, voor nu dus iedereen inloggen met dezelfde ADMIN acount. Betekend wel dat ik IP Whitelisting wil hebben op die omgeving.

**Comment by felixcicatt** [comment]
@hannekevanderhorst  De PDC mock data lijkt heel beperkt, maar als je op huwelijksplanner zoekt dan vind je in ieder geval iets.

**Comment by mstokericatt** [comment]
@PascalIcatt de data in kiss wijkt te veel af van de echte pdc data. ondudielijk waar het mis gaat: is er geen andere test data ingevoed? gaat het inderxreen niet goed etc.... even uitzoeken.

**Comment by PascalIcatt** [comment]
Taak https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/51 staat nog open en is hier onterecht afgevinkt.
@rubenvdlinde is hier van op de hoogte en moet een adapter schrijven voor de PDC data, voor nu staat er in elastic alleen een lijst met geimporteerde mockdata die overeenkomt met de properties van de crawler zodat de zoekpagina hier goed mee om kan gaan.

@hannekevanderhorst : ter info

**Comment by sytskevanhasselt** [comment]
@bbrands02 , we begrijpen dat op dit moment de SDG is geimplementeerd. Maar dit zit nog niet helemaal goed, wnat we krijgen helemaal niets terug. Voor nu heeft Pascal wat dummy data in Elastic gezet. 
Kun jij hier nog naar kijken? 
Wij kunnen eventueel aanvullende mockdata aanleveren. Heb jij voor ons de structuur die die data moet hebben?

**Comment by sytskevanhasselt** [comment]
@hannekevanderhorst , ik heb de omschrijving iets aangepast. Op dit moment denk ik dat er voor Acceptatiecriterium 4 (na doorklikken volledige content zien) nog best wat werk nodig is. De inregeling van Elastic moet worden uitgebreid. En Felix moet weten wie/hoe de detail-data van een product terugkomt. En vervolgens moet daar vermoedelijk nog html op worden gemaakt.

**Comment by sytskevanhasselt** [comment]
### Bevinding: structuur van output uit het endpoint /pdc/producten moet aangepast

We moeten de mapping rondom het PDC-component nog een keer goed doorspreken en vastleggen. 

Twee problemen: 
1. Om een Product te kunnen terugvinden, moeten er twee properties in de root van het Product staan, title en body_content. We moeten afspreken welke Properties uit het Vertalingen-object daarvoor gebruikt gaan worden.
2. De property-namen in SDG en dus ook die in het producten-endpoint, bevatten camelCase. Maar Elastic accepteert geen hoofdletters in property-namen. 

> ![image](https://user-images.githubusercontent.com/53014699/176929966-4faf4351-b7fc-48dc-a90c-06fa43941287.png)

**Comment by sytskevanhasselt** [comment]
## Bevinding: wat spreken we af over opmaak in de PDC-content

De inhoudelijke blokken in het Product-object kunnen Opmaak bevatten. Die is in de content uit de VNG Catalogus opgenomen als Markdown. Maar: gemeentes mógen ook uitgecommentarieerde html gebruiken. 

Voor KISS is het prettig als dit één van de twee wordt: óf HTML, óf Markdown. 
Twee mogelijkheden: 
1. Wij kiezen een format, en gemeenten kunnen alleen hun PDC in KISS krijgen, als ze hun content met dát format aanleveren
2. We zorgen ervoor dat de Gateway de opmaak omzet naar het juiste format. 

Hier moet iemand een keuze in maken.

**Comment by sytskevanhasselt** [comment]
## Bevinding: front end moet iets gaan doen moet opmaak in de PDC-content

Op dit moment bevatten de kennisartikelen in Elastic markdown in de vorm van JSon escaped text. Bijvoorbeeld: 
`U moet minimaal 4 weken vóór het starten, wijzigen of uitbreiden van uw bedrijf de melding doen.\r\n\r\n### Omgevingsvergunning\r\n\r\nHeeft u een type C-bedrijf?`

of: 
` Via het [Omgevingsloket online](https://www.omgevingsloket.nl/) controleert u of u een melding moet doen `

Op dit moment gaat de frontend daar nog niet goed me om in het zoekresultaat: deze tekst wordt niet geparsed.

Het lijkt er ovverigens op dat \r\n wel gestripped wordt (maar niet geparsed). Maar \n\n niet.  Zie onderstaande twee screenshots.  Ik weet niet wat de input was voor huwelijksplanner. Aan deze comment zitten de jsonfiles voor de Omgevingsvergunning milieu en voor de Gehandicaptenparkeerkaart. 


> ![image](https://user-images.githubusercontent.com/53014699/176933015-1a5cbfe9-ec71-409f-a861-c1fdb48ca51a.png)

> ![image](https://user-images.githubusercontent.com/53014699/176934524-5d9af04f-e96e-4511-a2d3-7badf07c690a.png)








[omgevingsvergunning brandveilig gebruik.json.txt](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/9030390/omgevingsvergunning.brandveilig.gebruik.json.txt)
[gehandicaptenparkeerkaart.json.txt](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/9030392/gehandicaptenparkeerkaart.json.txt)

**Comment by sytskevanhasselt** [comment]
## Bevinding: er ontbreekt een detailpagina
In de designs zie een voorbeeld van een gevonden artikel, "Hoe vraag ik toeslag aan?" Daarin staat alle content van een Product. Op dit moment tonen we in KISS, alléén nog maar de inhoud van het vertaling-property specifiekeTekst, en wel door dit als body_contentn in de root te zetten. 

Maar het object heeft veel meer inhoudelijke properties. Hoe gaan we die op het scherm zetten? 

En: is een scherm met alleen de body_content voor een Kennisartikel wel nuttig? 

> ![image](https://user-images.githubusercontent.com/53014699/176936294-e306fe90-0c98-4b72-8d16-959eabfab780.png)

**Comment by mstokericatt** [comment]
@hannekevanderhorst mee eens dat we deze story op 'won't fix' zetten, met de opmerking "éérst meer beeld krijgen of SDG-api gaat bieden wat de klant wil hebben."

**Comment by sytskevanhasselt** [comment]
Besproken vandaag met Pascal en Ruben: we gaan dit object gebruiken voor SDG-plus, zie onderstaande afbeelding. Daaronder staat een tekstbestand met de inhoud. 
- de groene elementen zijn toegevoegd na bestudering van SDU-pdc
- De paarse elementen zijn specifiek voor SDG. bij een koppeling met VIND zullen deze niet gevuld worden. Het gaat hier om elementen die gebaseerd zijn op kwaliteitseisen in de SDG-verordening. De informatie die er in staat, zal bij VIND verspreid zijn over de elementen "procedureBeschrijving","conditions" en "notice"
![image](https://user-images.githubusercontent.com/53014699/181483155-2735462f-521c-40c2-9a7e-b8610ee5a85e.png)
[Product_SDG-PLUS.json.txt](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/9208176/Product_SDG-PLUS.json.txt)

**Comment by sytskevanhasselt** [comment]
#### openstaande bevinding over het zoekpaneel en het detailscherm.
1. Als je naar het detailscherm van een zoekresultaat gaat, dat heel lang is, dan verdwijnt de link naar 'alle zoekresultaten' buiten beeld. Bij een korter zoekresultaat én een ingeklapt zoekpaneel, is de link ook niet meer in beeld. 
2. In het verlengde daarvan: als je het paneel inklapt in de lijst met zoekresultaten, dan zie je nog wel een klein stukje van het bovenste label

Twee mogelijke voorstellen: 
-‘alle zoekresultaten’ link sticky maken.
-bij ingeklapt paneel het hele paneel verbergen en het uitklap pijltje direct onder de zoekbalk plaatsen

**Comment by WilcoLouwerse** [comment]
ik heb vandaag 2 kennisartikelen ingeladen in elastic search.
Deze zijn ook terug te vinden in [teams](https://icattnl.sharepoint.com/:f:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/_testData/SDG-kennisartikelen?csf=1&web=1&e=MgQ2Zn)

**Comment by rubenvdlinde** [comment]
Deze stond nog open op de implementatie van de objectMeta property, of althans de keuze hoe we meta data beter filterbaar en waardeerbaar maken voor elastic objecten.

Voorstel is dus om een objectMeta property toe te voegen. die is nu afgevangen onder #122

**Comment by sytskevanhasselt** [comment]
Vandaag ontdek ik in sommige XML-berichten uit SDU een node <introduction>. Deze staat niet in de implementatiehandleiding. 

Na een steekproef op een aantal artikelen, heb ik de indruk dat in <introduction>de algemene, SDU-VIND-beschrijving staat. En dat in <description> de gemeente-specifieke beschrijving staat.

**Comment by sytskevanhasselt** [comment]
![image](https://user-images.githubusercontent.com/53014699/187166837-654699d7-3e45-4e8e-b372-cbf9e8cf390a.png)

**Comment by felixcicatt** [comment]
> DESIGN: zie ondertaande afbeelding. In theorie kunnen de ondestaande tabs voorkomen in het bericht. In de praktijk komen ze, zeker bij Deventer, nooit allemaal voor. Alle properties die we hiervoor gebruiken, staan in het subobject Vertalingen, waarbij "taal": "nl". De Titel van het Artikel staat in vertalingen.productTitelDecentraal
> 
> Tekst in scherm	property, binnen vertalingen.
> Inleiding	specifiekeTekst
> Aanvraag	procedureBeschrijving
> Voorwaarden	conditions
> Bewijs	bewijs
> Kosten	kostenEnBetaalmethoden
> Termijn	uitersteTermijn
> Bezwaar	bezwaarEnBeroep
> Vereisten	vereisten
> Bijzonderheden	notice
> Geen reactie	wtdBijGeenReactie
> Contact	contact
> KCC	deskMemo
> ![image](https://user-images.githubusercontent.com/53014699/187166837-654699d7-3e45-4e8e-b372-cbf9e8cf390a.png)

Kan ik de volgorde van het tabelletje aanhouden?

**Comment by sytskevanhasselt** [comment]
Ja. Hoe ingewikkeld is het om één blok te verplaatsen? Ik twijfel over de positie van KCC: daar staat nl. de interne informatie, en die is dus best belangrijk. Dus wellicht is het handiger om die bovenaan te zetten.

Anderzijds is het het meest logisch om, bij het openklikken van een item te landen op Inleiding.

**Comment by felixcicatt** [comment]
Niet ingewikkeld. We kunnen daarvoor ook op de input van de gebruikersgroep wachten.

**Comment by sytskevanhasselt** [comment]
Ik realiseer me één aspect uit de SDG, dat niet zo handig is voor PDC. End at is het feit dat er in "doelgroep" maar één waarde mag staan: ofwel "eu-burger", ofwel "eu-bedrijf". Dat betekent dat een product, dat relevant is voor beide doelgroepen, eigenlijk TWEE keer opgenomen zou moeten worden. 

Dat is een aspect waar KISS momenteel geen rekening mee houdt. En dat is ook een aspect dat ánders werkt in SDU: daar kan één Produt wel degelijk meerdere Target_groups hebben.

**Comment by sytskevanhasselt** [comment]
Status = Done
