### ISSUE TITLE
TAAK bijwerken paden van de endpoints bijwerken naar NL standaard

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#231]
Op dit moment gaan de endpoints voor de api's meteen naar objectnaam. Volgens de NL-api-strategie moet in dit pad altijd zijn opgenomen: de versie en het code (bv. ztc, zrd). 

Dit moeten we nog netjes maken. Dit moeten we goed afstemmen.

### Taken Conduction
- [ ] ...

### Taken ICATT
- [ ] ...

**Comment by WilcoLouwerse** [comment]
@rjzondervan niet vergeten ook even de postman config runner te dubbel checken

**Comment by rubenvdlinde** [comment]
Vandaag refinenen, en dan terugkoppelen in Teams.

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
