### ISSUE TITLE
TAAK: In klanten-api zorgen dat patch, put en delete zich gedragen zoals het hoort (is redoc bijgewerkt?)

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#233]
In de klanten-api zijn nog een aantal zaken niet helemaal goed, dit moet worden gefixed. 

### Taken Conduction
- [x] zorgen dat put zich gedraagt als put in de klanten-api
- [x] patch en delete toevoegen aan de klanten-api
- [x] patch toevoegen aan openpub-api
- [ ] Redoc bijwerken

### Taken ICATT
- [x] PUT-call bij klanten opzetten als echte PUT
- [x] PUT-cal bij zaak toelichting omschrijven naar PATCH
- [x] PUT-call bij gelezen markeren van PUB berichten, omschrijven naar PATCH

**Comment by WilcoLouwerse** [comment]
@WilcoLouwerse heeft notities voor wijzigingen op de gateway hiervoor

**Comment by WilcoLouwerse** [comment]
(#255)

**Comment by WilcoLouwerse** [comment]
https://conduction.atlassian.net/browse/GW-1237
https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/112

Patch toevoegen
Put is volledig body valideren en dan updaten, patch eerst volledig object pakken, dan alleen de velden in de body die zijn opgegeven er overheen plakken en dan weer valideren en updaten.

https://duckduckgo.com/?q=put+versus+patch+required+fields&atb=v314-1&ia=web
https://rapidapi.com/blog/put-vs-patch/
https://www.geeksforgeeks.org/difference-between-put-and-patch-request/
https://stackoverflow.com/questions/28459418/use-of-put-vs-patch-methods-in-rest-api-real-life-scenarios

**Comment by sytskevanhasselt** [comment]
Ik weet niet of dit hier aan raakt. Maar: voor het testen van #245 heb ik een Medewerker geupdate via PUT. Hierbij heb ik in eerste instantie dezelfde inhoud gepakt, als de POST die ik had gebruikt om de medewerker aan te maken. En vervolgens een waarde aan te passen. 

Maar daarna heb ik een PUT-body verstuurd, die maar gedeeltelijk gevuld was. Zou hierbij niet eigenlijk de afwezige informatie uit de PUT-body moetn worden gewist uit het oorspronkelijke object? Voor zover ik kan zien gebeurt dat niet. Zie screenshot hieronder. De environment variabele staat ingesteld op: https://kissdevelopment-dimpact.commonground.nu
@WilcoLouwerse 

![image](https://user-images.githubusercontent.com/53014699/202712711-cb6577a2-3c43-4452-8924-565407fd288a.png)

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
