### ISSUE TITLE
Als klantcontactmedewerker wil ik zoeken naar informatie op de eigen gemeentelijke website

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#24]
...zodat ik de klant hierover kan informeren en desgewenst ook kan doorverwijzen naar deze publieke informatie.

### Toelichting & acceptatiecriteria
zie E-01 #23 . alleen nu een extra (ongestructureerde)  bron

**Projectcode**: E-02

zoals besproken gaan we hier uit van ongestructureerde data, waarbij het zoekresultaat bestaat uit een link naar de bron (a la google).

Uitzoeken of mbv elastic search een website gecrawled kan worden, of dat er vanuit de bron website een xml/json bestand aangeleverd moet worden.
Uitzoeken hoe de data gecombineerd kan worden met de index die bij  E-01 #23 is opgebouwd

### Acceptatiecriteria
- [x] de data is vindbaar in kiss
- [x] zoekresultaten linken naar de juiste pagina in de bron website

### Taken Conduction
- [x] Installeren Elastic Search (reed ingeschat in #22)
- [x] Basale inregeling Elastic search (reed ingeschat in #22)
- [x] #58

### Tijdinschatting 
- *Conduction* 32
- *ICATT* 0,5 front-end, 3 elastic

**Comment by rubenvdlinde** [comment]
Het is overigens de ervaring van Conduction dat het goed inrichten van een crawler voor Elastic search best pittig kan uitvallen, dus laten we deze even timeboxen.

**Comment by PascalIcatt** [comment]
Uitzoeken: hoe halen we de data op bij Deventer? Welke data endpoints zijn er?
Wie is de technisch contactpersoon die we hiervoor moeten benaderen?

**Comment by sytskevanhasselt** [comment]
Status = done
