### ISSUE TITLE
Als KCM wil ik bij Conctactmomenten kunnen zien wie het heeft aangemaakt.

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#244]
_ZIE OOK #228_

Op het moment dat we Contactmomenten opslaan gingen maken, hadden we géen ingelogd gebruikers. 
Die hebben we nu wel. 

Afstemmen met PM/PO: wat te doen bij medewerkers uit dienst. 
- of we tonen medewerker niet gevonden
- of gemeente moet ze in de ADFS houden 

- [ ] Bij het opslaan van een contactmoment vult de Gateway de gegevens van gebruiker van de lopende gebruikerssessie in bij het Contactmoment. Welke gegevens en hoe precies specificeren we bij het oppakken.
- [ ] Medewerker ophalen via de metadata (extend[]=_owner)

**Comment by rubenvdlinde** [comment]
We slaan de gebruiker die een object aanmaakt op in de metadata (per gateway) daar kan die ook uitgehaald worden via de extend query paramater _owner.

**Comment by sytskevanhasselt** [comment]
Deze issue is op zich afgerond: we kunnen de medewerker ophalen bij Contactmomenten. 
Op dit moment zien we echter alleen e-mailadres. 
Ik verplaats de Openstaande vraag aan PM/ PO naar #228 , en ik sluit deze
