### ISSUE TITLE
Als KCM wil ik dat wijzigingen in Kennisartikelen vrijwel direct zichtbaar zijn de zoekindex.

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#245]
In story #122  is de het direct updaten van medewerkergegevens gerealiseerd. 
Het updaten van Kennisartikelen in elastic op deze manier is een wenst

### Acceptatiecriteria
- [ ] als er een Kennisartikel wordt aangepast, is die aanpassing vrijwel direct zichtbaar in de zoekindex in KISS

**Comment by sytskevanhasselt** [comment]
Op dit moment zie ik het kennisartikel Milieumelding aanvragen meerdere keren in. 
Structuur is ook anders ?

**Comment by sytskevanhasselt** [comment]
Vandaag de medewerkers sync naar Elastic getest. M.b.v. de calls van  /api/medewerker op [kiss-dev.commonground.nu/](https://kiss-dev.commonground.nu/). Het POST en PUT gaat goed: wat ik aanmaak of wijzig zie ik bijna onmiddelijk terug in de frontend, in het Zoekpaneel. 
 
De belangrijkste bevindingen die ik heb gaan over een verschil in datastructuur tussen de objecten waarop de frontend is ontwikkeld, en de objecten zoals ze nu bij /api/medewerker horen. Waardoor er veel niet zichtbaar is. Zie ook het document in  teams, kanaal KISS: [Testen + testdata\Bevindingen release 04\Bevindingen_H-04_Zoekindex Actualiseren.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_H-04_Zoekindex%20Actualiseren.docx?d=w944f2f86074842118a268a8cb6f8514b&csf=1&web=1&e=AAEs7l)
 
 
Tenslotte ook nog een vraag/bevinding over het updaten van de gegevens binnen contact, en hoe de gateway weet dat die gewijzigd zijn. Misschien test ik het verkeerd. Idem voor het verwijderen van een medewerker.

**Comment by WilcoLouwerse** [comment]
(Bij het wijzigen van een klant/persoon word nu ook de medewerker die bij deze klant/persoon hoort netjes bijgewerkt in elastic)

**Comment by sytskevanhasselt** [comment]
Nieuwe bevindingen toegevoegd aan het document in teams, kanaal KISS: [Testen + testdata\Bevindingen release 04\Bevindingen_H-04_Zoekindex Actualiseren.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_H-04_Zoekindex%20Actualiseren.docx?d=w944f2f86074842118a268a8cb6f8514b&csf=1&web=1&e=AAEs7l)

- SH11: de api /api/sdg/kennisartikel verwacht een string bij 'versie'. Maar dat moet integer zijn 
- SH12: het property url moet in elastic wél een waarde hebben, anders crasht POST contactmomenten
- SH02: update: het is WEL problematisch als de het gehele object óók naar body_content gaat. Dit ivm. de huidige implementatie van #153 (H-02)

**Comment by WilcoLouwerse** [comment]
Boven genoemde 3 punten zijn op acc opgelost

**Comment by sytskevanhasselt** [comment]
Bij hertest nog een issue geconstateerd: 
- SH15: De medewerkers uit de gateway staan nu (26/10, 12h00) dubbel in Elastic. Ik weet helaas niet hoe dit komt:  
    - Doordat ik de mdw niet goed heb verwijderd uit de gateway 
    - Doordat ik de mdw heb geüpdatet via put 
    - Of doordat ik de klant ónder de medewerker heb geüpdatet.

**Comment by WilcoLouwerse** [comment]
Ik kan de dubbele medewerker bug niet lokaal reproduceren.
(technisch:)
Het posten en putten van een medewerker, klant of medewerker+contact (klant) als uuid verwijzing of cascading met body resulteert nooit in 2 uitgaande api-calls of een api-call met verkeerde data wat tot een 2de object zou kunnen leiden

**Comment by WilcoLouwerse** [comment]
Dus mijn verklaring voor het probleem met de data/kennis die ik nu heb zou zijn: 
- Dat er (per ongeluk) 2x dezelfde medewerker is toegevoegd via de gateway. 
- Doordat er een medewerker uit de gateway is verwijderd met de verwachting dat deze ook uit elastic verwijderd zou worden. Waarna dezelfde medewerker nog eens is toegevoegd.
- Of misschien andersom dat er een medewerker uit elastic is verwijderd met de verwachting dat deze ook uit de gateway verwijderd zou worden.

Tot ik online op acc kan testen kan ik hier voor nu niet meer over zeggen.

**Comment by sytskevanhasselt** [comment]
Ik heb zojuist nog een aantal tests gedaan m.b.v. Postman en de KISS-frontend:
1. Medewerker aangemaakt, via POST op _https://kissdevelopment-dimpact.commonground.nu/api/medewerkers?extend[]=all_, voor contactgegevens, de klant de270414-fd26-4568-b67d-3ce5ea886e97 gebruikt (Sytske van Hasselt)
Resultaat: de medewerker verschijnt in de zoekresultaten (bij een search op 'skills'): OK
2. Vervolgens twee keer de klant aangepast: eerste keer een extra nummer toegevoegd, tweede keer een nummer aangepast
Resultaat: gegevens van de medewerker staan geupdated in het zoekresultaat: OK
3. Vervolgens twee keer een update gedaan op de medewerker, via _https://kissdevelopment-dimpact.commonground.nu/api/medewerkers/f3561cca-1b78-44b3-b6da-e169636096cd_ . 
Resultaat: gegevens van de medewerker staan geupdated in het zoekresultaat: OK


Ik zie geen dubbele Medewerkers in de KISS frontend, en ook niet in Elastic. 

Dus dit probleem treedt niet meer op. 

Dus dit issue is nu klaar.
