### ISSUE TITLE
Als KCM wil ik categorieën of skills kunnen selecteren als filter op de nieuwsfeed en werkinstructies

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#25]
...zodat ik informatie in beeld kan brengen die relevant is voor de werkzaamheden die ik op dat moment aan het doen ben

### toelichting
Er is geen onderscheid tussen categorien en skils. Er komt één filter op nieuwsberichten en werkinstructies. 
er is geen story voor het beheer hiervan.  We gaan er vanuit dat dit in deze story geregeld wordt binnen het systeem voor newsfeeds/werkinstructies.
 

**Projectcode**: A-03

### Acceptatie criteria
- [x] nieuws berichten en werkinstructies kunnen taggen in het bronsysteem (zie B1)
- [x] er kunnen meerdere categorieën/skills aan een bericht/instructie gekoppeld worden
- [x] categorieën/skills worden getoond bij de berichten en de medewerker heeft de mogelijkheid hierop te filteren
- [x] als je een filter kiest zie je berichten/instructies waar helemaal geen categorie/skill aan hangt niet

nb. het is niet erg als je nieuwe/gewijzigde berichten niet meteen ziet als je een filter hebt ingesteld. voor het onder de aandacht brengen van urgente berichten is een aparte story.

### Voorlopig lijstje Skils
afspraken, algemeen, burgerzaken, werk en inkomen, belastingen, vergunningen, bouw en ruimtelijke ordening. Ik zet ze in het issue erbij

### Taken Conduction
- [x]  Aanvullen inrichting PUB Component met filters

### Tijdinschatting 
- *Conduction* 8
- *ICATT* 1

**Comment by rubenvdlinde** [comment]
@bbrands02 we kunnen sowieso al wat skills toevoegen aan de Taxanomie van PUB en PDC zodat er op gezocht kan worden

**Comment by felixcicatt** [comment]
@hannekevanderhorst ik heb voor deze ook maar gezorgd dat voor het lijstje met berichttypes de lijst uit pub gebruikt wordt. Dan blijkt dat het lijstje een beetje een rommeltje is maar daar kom je vast wel uit.

**Comment by sytskevanhasselt** [comment]
Status = done
