### ISSUE TITLE
TAAK: fixen van de e-mails met Feedback (zie ook #121)

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#250]
Edit: in #121  hebben we functionaliteit gemaakt, die zorgt dat de inhoud van het feedbackformuliertje verstuurd wordt naar icatttest@gmail.com. 

Maar: die mails komen niet meer aan. Graag fixen. 
Voor zover ik kan zien gaan er nog wel berichtjes naar https://kissdevelopment-dimpact.commonground.nu/api/reviews
Met bijvoorbeeld deze inhoud: 

> {
> 	"id": "79a74543-79c9-42d8-bc64-d91a229494ab",
> 	"author": "Peter",
> 	"description": "De tekst waar het om gaat:\r\n\r\n\r\nFeedback:\r\nDit moet gemaild worden naar icatttest@gmail.com\r\n\r\nAanleiding:\r\n\r\n\r\nContactgegevens:\r\ntest01@kiss.commonground.nu",
> 	"name": "Johanne Tersteege",
> 	"rating": null,
> 	"topic": null
> }

**Comment by WilcoLouwerse** [comment]
Ik heb hier in de configuratie staan dat de emails naar icatttest+kiss@gmail.com verzonden (zouden moeten) worden.
Maar dat is als het goed is dezelfde inbox als icatttest@gmail.com...

ik ga even testen en kijken of ik kan achterhalen waardoor emails niet verzonden worden

**Comment by sytskevanhasselt** [comment]
Ja dat klopt. het '+nogiets@' is een onderdeel van de mail specs, waar we gebruik van maken om meer testadressen te hebben. Gmail stopt dat allemaal in de mailbox van icatttest@gmail.com.
NB: het hééft wel gewerkt, naar dat mailadres. Zie de .eml-files in Teams, in Testen + testdata\Bevindingen Sprint-04, Sprint-05, Sprint-06\G-02

MAAR: als dit een blokkerend ding is, gooi het er dan inderdaad maar vanaf.
