### ISSUE TITLE
TAAK: Configuratie van de delete endpoints corrigeren

### ISSUE THREAD

**Issue by rjzondervan** [Klantinteractie-Servicesysteem/KISS-frontend#255]
Er is in de code die de configuratie inlaad een fout gevonden die maakt dat de delete endpoints niet aan de juiste objecten zijn gekoppeld. Daarvoor is nu een oplossing beschikbaar, maar deze vraagt wel dat de configuratie van de betreffende api's kan worden bijgewerkt.

**Comment by rubenvdlinde** [comment]
Is deze niet verdampt toen we de omgeving (per onegluk) opnieuw inrichte?

**Comment by rjzondervan** [comment]
Zojuist door alle endpoints heen gelopen, en op DEV zouden nu alle DELETE endpoints die volgens de originele OAS aanwezig zouden moeten zijn, ook moeten werken.

**Comment by WilcoLouwerse** [comment]
Ik heb getest en er waren nog een aantal Handlers in de gateway die nog niet delete in hun methods hadden staan. Hierdoor werkte sommige delete endpoints nog niet. Ik heb deze nu geupdate waardoor dit geen probleem meer zou moeten zijn.

Verder lijkt alles in orde 👍

**Comment by sytskevanhasselt** [comment]
Status = Done
