### ISSUE TITLE
Als klantcontactmedewerker wil ik zoeken naar zaken in het zaaksysteem

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#26]
...zodat ik de klant gericht kan helpen met een vraag over een lopende of gesloten zaak.

### toelichting
zoeken via de zaken Api.
@rubenvdlinde regelt een dummy register met wat basis testdata. Meer realistische data voor gebruikerstests wordt later geregeld

Je kan in het zaaksysteem direct zoeken op basis van een zaaknummer, of op basis van het bsn van de klant.

Als het bsn gebruikt wordt, dan moet eerst in het BRP het bsn opgezocht worden.  Dat kan bijvoorbeeld op basis van  huisnr postcode, geboortedatum + achternaam, etc (zie documentatie gedeeld in teams). Let op dat betekend dat je altijd een tussenscherm hebt waarop een persoon wordt geselecteerd. Zelfs als er maar één persoon is.

let op. niet iedereen zit in brp (alleen nederlanders). Het zoeken zal later uitgebreid worden met bv een klantregister, maar dat is nu buiten scope.

**Projectcode**: E-06

### Acceptatie criteria

- [x] we tonen: zaaktype, zaaknummer, status, (behandelaar voorlopig niet), datum ingediend. 
doorklikken... we beginnen minimaal. de invulling van de detailpagina wordt een aparte story 

### Taken Conduction
- [x] Installatie Open Zaak of andere ZGW mock
- [x] Basale ZGW inrichting met test data
- [x] Installeren BRP
- [x] Basale BRP inrichting met test data
- [x] overdragen aan icatt (mark) 

### Tijdinschatting 
- *Conduction* 50
- *ICATT* 1

**Comment by rubenvdlinde** [comment]
In dit issue verbinden we de twee meest complexe componenten uit het project (ZGW en Elastic) aan elkaar. Vandaaruit wat negatief ingeschat.

**Comment by mstokericatt** [comment]
dinsdag afstemmen tussen wilco en mark

**Comment by WilcoLouwerse** [comment]
Ik heb een agenda afspraak gemaakt:
👍 

![Image](https://user-images.githubusercontent.com/3785488/173036194-9ae9f4d4-ce0e-4003-9d5e-54a415715990.png)

**Comment by mstokericatt** [comment]
zoeken in brp op geboortedatum skippen we voorlopig even ivm onvoorziene complexiteit en de toegevoegde waarde nog niet helemaal duidelijk. svp even hier toelichten.

**Comment by rjzondervan** [comment]
Het issue met zoeken op geboortedatum heeft te maken met hoe geboortedatums in de HC BRP API zijn omschreven en moeten worden gezocht. In het datamodel geldt de geboortedatum als een apart object bestaande uit dag, maand en jaar (die in theorie allen 0 kunnen zijn als onbekend), maar als zoekparameter geldt dat wordt verwacht dat dit als string wordt gezocht.

Er moet dus een mapping tussen het datum-object en een string komen om te zorgen dat er met een string gezocht kan worden in de geboortedata

**Comment by sytskevanhasselt** [comment]
Status = done
