### ISSUE TITLE
TAAK: Link naar Terugbelnotitie vanuit Contactmoment

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#260]
Om goed te kunnen bespreken: 

- wat we op dit moment kunnen tonen over een Terugbelnotitie
- Wat het gevolg is van de keuze 'opslaan als contactmoment'.

Willen we op een zo simpel mogelijke manier van een Contactmoment de bijbehorende Terugbelnoitite kunnen inzien. 

Als we dit hebben, kunnen we bespreken met PL/PO hoe we J-03, #146  precies gaan uitvoeren.

### Acceptatiecriteria - J-03-Deel 1
- [ ] Ik kan in het klantbeeld een lijst / tabel zien van de 'Contactmomenten Met Een ToDO'
- [ ] In die lijst zie ik iig: 
    - DAtum 
    - Medewerker (die het heeft Aangemaakt, dat is medewerker of medewerkerIdentificatie)
    - _Kanaal hoeft niet, want ik zie dat die op dit moment altijd null is bij een Contactverzoekcontactmoment_
    - Behandelaar: hier tonen we op wiens naam de ToDo staat, dat is op dit moment een e-mailadres)
    - Status; wat Men hier wil zien is of de Terugbelnotitie is Afgehandeld. Daarvoor kunnen we kijken naar "completed", of naar "status"
- [ ] Dit bespreken met PL/PO
- [ ] Waarmee Ontwikkelteam heeft voldoende informatie heeft om op te pakken: #146
- 

### Taken ICATT - J-03-Deel 1
- [ ] Linkje maken waarmee je de inhoud van de terugbelnotitie kan inzien; hoe: zo makkelijk mogelijk.

**Comment by hannekevanderhorst** [comment]
Oplossingsrichting is besproken tijdens gebruikerstest. Deze is niet meer nodig
