### ISSUE TITLE
Als klantcontactmedewerker wil ik een contactmoment kunnen koppelen aan een zaak

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#27]
...zodat voor de inwoner en de zaakbehandelaar vast ligt dat er contact over de zaak is geweest.

### toelichting
In story E-06 wordt het mogelijk gemaakt zaken te vinden. Nu is het de bedoeling dat er informatie over het contactmoment opgeslagen wordt bij de zaak. (technisch gezien is het andersom: de zaak wordt opgeslagen bij het contactmoment)
#26 
**Projectcode**: P-01

 
### Acceptatie criteria
- [ ] binnen een contactmoment moet van een opgezochte zaak aangegeven kunnen worden dat deze bij het contactmoment hoort. (ux uitzoeken: moet dit automatisch gebeuren met alle gevonden zaken binnen het contactmoment, of moet dit een expliciete actie van de medewerker zijn). De zaak wordt opgeslagen bij het contactmoment.

nb. we hebben nog geen mogelijkheid om eerdere contactmomenten ter te kunnen vinden. hoe bewijzen we dat de opslag geslaagd is? voorlopig alleen technisch te controleren via devs

### Taken Conduction
- [x] Installatie Contactmomenten API of mock

### Tijdinschatting 
- *Conduction* 4
- *ICATT* 1

**Comment by rubenvdlinde** [comment]
Binnen de[ Contacten API](https://contactmomenten-api.vng.cloud/api/v1/schema/#tag/contactmomenten) kennen we contactmomenten (het gesprek) met daarbinnen Klant ContactMomenten (berichten binnen het gesprek).

Aan een gesprek (contactmoment) kunnen objecten worden gekoppeld door middel van ObjectContactInformatie koppel objecten. Daarmee kunnen we zaken koppelen maar bijvoorbeeld ook producten of werk instructies (ten behoeve van statistische gegevens).

Waar we hierbij even op moeten letten is dat in theorie één gesprek kan gaan over meerdere zaken.

**Comment by sytskevanhasselt** [comment]
Status = done
