### ISSUE TITLE
De Skills-lijst verplaatsen naar de Gateway

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#285]
De skills zijn nu eigenschappen van een PUB artikel. Maar het is eigenlijk een referentielijst en zou dus in de gateway moeten staan. 

### Acceptatiecriteria
- [x] In de Gateway kan een beheerder de skills invoeren en beheren
- [x] In de Gateway zijn de twee typen Publicaties aangemaakt: Nieuws, en Werkinstructie
- [x] In de PUB-editor kan een redacteur in de lijst met Skills uit de gateway aangeven welke er bij de publicatie horen
- [x] In de PUB-editor kan een redacteur aangeven of het een Nieuwsbericht of Werkinstructie is: het keuzelijstje bevat opties uit de Gateway
- [x] In de Frontend worden die koppelingen tussen Bericht / Skill weergeven met Labels
- [x] In de Frontend kijkt het filter voor Skills naar de lijst uit de gateway

**Comment by lencodes** [comment]
[Pull request](https://github.com/Klantinteractie-Servicesysteem/Openpub/pull/8) staat open voor het koppelen van de gateway lijsten met de wordpress plugin.

**Comment by sytskevanhasselt** [comment]
Ik heb getest: 

1. nieuwe toevoegen > OK
2. bestaande verwijderen  > niet zo ok
3. bestaande wijzigen > niet zo ok

Zowel bestaande verwijderen als bestaande wijzigen geven nu issues, op het moment dat een skill al aan een bericht is gekoppeld. Dit heeft te maken met het feit dat WordPress bij het importeren van de skills eigenlijk de lijst dupliceert. 

Dit gaan we niet op korte termijn oplossen. Ik sluit dit issue, en maak een nieuw issue aan voor het hierboven beschreven punt.
