### ISSUE TITLE
Issues Startscherm en PUB

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#288]
Sinds de opleveringen op donderdag 8 september werken er een aantal zaken rond Startscherm en PUB niet meer zoals het moet. Het is niet helemaal zeker of dit te maken heeft met de refactor van het startscherm, of met aanpassingen aan de wijze waarop PUB naar de frontend gaat. 

- [x] (1) Startscherm: Als je filtert staat er nog een regel 'resultaten gevonden' dat is niet de bedoeling
- [x] (2) Zoekresultaten in zoekpaneel zijn niet zichtbaar; wel klikbaar en de detailviews doen het ook nog goed. 
- [x] (3) Startscherm: Filterknopjes zijn te klein, en de tekst van het filter is niet
- [x] (4) Bij contactmoment afhandelen: het invoervak heeft geen rand meer.
- [x] (5) Startscherm: paginering werkt niet
- [x] (6) Startscherm: Als je zoekt binnen nieuwsberichten / werkinstructies staat er alleen 'resultaten gevonden' zonder het aantal gevonden resultaten
- [x] (7) Startscherm: zoeken naar Nieuws/werkinstructies werkt niet meer: als ik zoek op een woord uit een zichtbaar bericht (in titel of in body), vind je nooit iets, terwijl dat wel zou moeten. 
- [x] (8) Startscherm: Filter van nieuwsberichten is AND. Ik weet 99% zeker dat het OR was. Het moet ook OR zijn. 
- [x] (9) Startscherm: Er worden veel te weinig berichten geladen. ik zie maar een beperkt aantal Werkinstructies, terwijl er zeker 21 in PUB staan
- [x] (10) Startscherm: wijzigingen in berichten worden niet consistent gesynced: 
    - ik heb de titel van een nieuwsbericht gewijzigd, en ik blijf de oude titel zien. 
    - Ik heb de titel van een werkinstructie gewijzigd, en daarvan zie ik wél de nieuwe titel  
- [x] (11) Startscherm: berichten zijn niet meer gesorteerd op Datum Gewijzigd, met meest recente wijziging bovenaan. 
- [x] (12) Startscherm: Filteren op categorie algemeen geeft ook objecten terug met categorie openingstijden (die geen categorie algemeen hebben)

**Comment by WilcoLouwerse** [comment]
Snelle constateringen over genoemde punten^ :
7: Ook via het gateway/api/elastic/api/as/v1/engines/kiss-engine/search endpoint (met bijv. query: test) geeft 0 results terug.
9: De source die ik hiervoor heb gekregen, vanaf waar wij syncen naar de gateway heeft maar 10 objecten (GET https://openweb.kiss-dev.commonground.nu/wp-json/wp/v2/kiss_openpub_pub)

**Comment by WilcoLouwerse** [comment]
7: zoeken gaat niet over elasticSearch maar zoeken op nieuws berichten

**Comment by WilcoLouwerse** [comment]
8: afgevinkt, oplossing besproken met Lennart. front-end moet query-param aanpassen.
![image](https://user-images.githubusercontent.com/3785488/189630410-5b6941e0-cc75-4695-a3e3-0325fa758962.png)

**Comment by WilcoLouwerse** [comment]
11: oplossing besproken met Lennart. front-end moet query-param aanpassen.
![image](https://user-images.githubusercontent.com/3785488/189631104-3579b627-577f-4657-8f54-b44c679d1902.png)

**Comment by WilcoLouwerse** [comment]
9: Blijkbaar gaat de gateway nog niet om met pagination op de wp api. Dus ik zal deze even goed instellen zodat alle objecten worden gesynchroniseerd

**Comment by WilcoLouwerse** [comment]
10: Samen getest met Lennart, conclusie hier is dat bij nieuwe objecten dit gewoon goed gaat. Dus dat door door punt 9 waar sync geen rekening hield met pagination dit ook mis gaat. Een aanpassing op een object wat al langer bestond word niet herkent hierdoor. 
Er is ook een kleine kans dat er nog oude objecten bestaan in de gateway van vorige tests die nu 'corrupted data' zijn, om dit uit te sluiten zal ik ook nog even sync uitzetten, alles opschonen en dan weer sync aanzetten.

**Comment by WilcoLouwerse** [comment]
7: Dit deden we voorheen met de ?search=value query parameter. Omdat we blijkbaar toen 2 losse velden (attributen) hadden waar we searchPartial op konden toepassen (heeft nog steeds beter naam nodig, lees searchMultiple ipv searchPartial) .
Alleen heeft het huidige nieuws object de 2 velden waar we op willen zoeken in een subresource zitten, dus ipv nieuws.title is het nu nieuws.title.rendered.
We staan alleen nog niet dit toe met de search query param code. Dus dit zal ik nog moeten toevoegen.

**Comment by WilcoLouwerse** [comment]
Ik ben nu bezig met een oplossing deployen voor punt 9, 10, 11 & 12

**Comment by WilcoLouwerse** [comment]
punt 7 is afgerond en ga ik nu deployen.
Er is nog wel een kleine bug, hier terug te vinden:
#301

**Comment by sytskevanhasselt** [comment]
Ik heb gezien dat zoeken nu goed gaat. Updates en Nieuwe berichten verschijnen na ong. 2 minuten. 

Ik blijf alleen vreemde dingen zien, waarbij soms ineens berichten met een hele versie updatedatum bovenaan komen te staan, terwijl ze niet gewijzigd zijn. Even later 'verdwijnen' ze ook weer, en hebben ze hun oorspronkelijke update datum, die ik ook kan matchen aan wat ik zien PUBpress. Bijgevoegde RAR bevat een aantal screenshots die kort achterelkaar gemaakt zijn
- In de eerste NieuwEvelien zie je het Evelien-bericht bovenaan met een wijzigdatum van 16-09-14:39. Als ik vervolgens zoek op Evelien, vind ik het bericht met de eigenlijk wijzigdatum: 27-06- om 14:09. Aan de bestandsnaam, maar ook aan de taakbalk-klok helemaal links onderin beeld, zie je dat de tweede NA de eerste is gemaakt. 
- Iets gelijksoortigs zie je in de Nieuwskolom, met het bericht Zomerborrel. 
- De drie Werkinstructie-screenshots zijn kort achterelkaar gemaakt, steeds met een ándere werkinstructie als eerste. In de Derde staat het eigenlijke, meest recent gewijzigde bericht, Nunc de eerste. 

IN alle drie de gevallen lijken de de berichten dus verschillende DateModified's te hebben. Alsof ze zijn geupdate dóór de sync. 
Ik kan niet zo goed achterhalen of hier een verband is met story #91 

[IssuesSync_220916.zip](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/9584985/IssuesSync_220916.zip)

**Comment by sytskevanhasselt** [comment]
Opmerking uit vorige comment gaan we verplaatsen naar nieuw issue. En we sluiten deze af.
