### ISSUE TITLE
Als KCM wil ik zonder risico op overschrijven, een notitie toevoegen aan het veld Toelichting

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#296]
Vervolg op : #116. 

In hebben we ervoor gezorgd dat er in KISS één veld is, dat je kan bewerken, en waarin je je notitie kwijt kan. We hebben dit gedaan in het property toelichting, van een Zaak. Maar: ZGW ként geen één-of-meer-property bij een zaak dat je hiervoor kunt gebruiken. Om het echt goed te doen, moet er een uitkomst zijn van Discucssion #298. Maar dat gaat niet lukken in Fsae 1. 

### Uit ontwerpgroep 04-10-2022
De ontwerpgroep geeft wel aan dat de uitvoering van het bewerken van 'toelichting' nu erg fragiel is. Je kunt onverhoopt de inhoud helemaal weggooien. Dus gaan we in Fase 1 nog wel zorgen dat je het veld toelichting kunt aanvullen, zonder dat je daarmee de inhoud van 'toelichting' overschrijft. 

Link naar design; https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=2194%3A5822

### Acceptatiecriteria
- [ ] Op de plek waar nu het Veld Toelichting staat, Tónen we allen de inhoud van toelichting. 
- [ ] Daaronder staat een invoerveld. Dit kan de KCM invullen
- [ ] Op het moment dat de invoer in dat invoerveld wordt opgeslagen, voegt KISS op de achtergrond deze input toe aan het property 'toelichting', voorafgegaan door 2 linebreaks. 

### Taken ICATT
- [ ] ...

### Discussions: 
-= [ ] #298

**Comment by lencodes** [comment]
Doordat we line breaks toevoegen (zoals omschreven in de acceptatiecriteria) om de verschillende toelichtingen te kunnen scheiden, betekent dat ook dat we geen line breaks meer kunnen hebben in een individuele toelichting.

Dit betekent effectief nu dat we de volgende mapping moeten maken (e.g.):

```
Dit is een toelichting.

Met een nieuwe regel erin.

En nog een afsluitende regel, ook weer op een nieuwe regel.


==> 


Dit is een toelichting. Met een nieuwe regel erin. En nog een afsluitende regel, ook weer op een nieuwe regel.
```

Een mogelijke oplossing hiervoor zou zijn dat we i.p.v. het toevoegen van line breaks om het onderscheid tussen toelichtingen aan te duiden een unieke code gebruiken.

Voordeel van een unieke code gebruiken: hierdoor kunnen we line breaks in individuele toelichtingen in stand houden.

Nadeel van een unieke code gebruiken: hierdoor moeten we de content die het zaaksysteem ingeschoten wordt vervuilen (de unieke code is namelijk enkel in de implementerende context bekend).
