### ISSUE TITLE
Zoeken naar Nieuws/werkinstructies met een nummer kan nog verkeerde resultaten terug geven

### ISSUE THREAD

**Issue by WilcoLouwerse** [Klantinteractie-Servicesysteem/KISS-frontend#301]
Bug gespot tijdens het uitbreiden van de search query op de gateway voor #288 punt (7).

(meteen even in back-end partialSearch hernoemen naar multipleSearch)

![Image](https://user-images.githubusercontent.com/3785488/190368910-78326dc5-2934-4196-909a-3eacff6f3d10.png)
![Image](https://user-images.githubusercontent.com/3785488/190368956-52ca885a-cca2-49c9-a053-78992f1bedf0.png)
![Image](https://user-images.githubusercontent.com/3785488/190368990-26c3983b-1bae-4a92-9bef-a2beab246881.png)
![Image](https://user-images.githubusercontent.com/3785488/190369044-eb4a2414-e166-4f39-a188-6e16d16fb7b6.png)

**Comment by WilcoLouwerse** [comment]
![image](https://user-images.githubusercontent.com/3785488/198034180-136221b3-8d9b-40c7-b257-412b9a7ae6f0.png)

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
