### ISSUE TITLE
Als KCM wil ik op een consistentie wijze klanten aanmaken en bewerken

### ISSUE THREAD

**Issue by mstokericatt** [Klantinteractie-Servicesysteem/KISS-frontend#303]
Bij het aanmaken van een klant kan je nu maar 1 telnr en 1 email adres opvoeren. bij het bewerken kan je meerdere emailadressen en telnr's opvoeren. Het is wenselijk dat je bij het aanmaken ook meteen meerdere telnr's en emailadressen kan opvoeren.

nb. ook via het contactverzoek kan je een nieuwe klant aanmaken (dan mag je twee telefoonnummers en 1 emailadres invoeren) dat zou ook gelijk getrokken moeten worden, maar er is ook een voorstel om het toevoegen van een klant bij een contactverzoek anders op te lossen (#304), dus dan is dit laatste misschien niet meer relevant

**Comment by sytskevanhasselt** [comment]
Dit wordt opgelost met #312
