### ISSUE TITLE
Known issues

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#310]
Hier houden we een lijst bij van known issues

1. gelezen berichten inklappen: Als je in nieuws en werkinstructies zoekt op bv een woord en je haalt dat woord daarna weg om alle berichten te zien, zie je op gelezen gezette berichten even uitklappen en dan weer inklappen. Hetzelfde geldt voor aan/uitvinken van een skill-filter. Dit heeft te maken met de cache. Mogelijke oplossing is de cache uitzetten maar dan wordt het startscherm traag, of de cache bijwerken met de laatste zoekopdracht. Dit komt dus alleen voor in het scenario dat je het zoekwoord / skillfilter weghaalt om alle berichten weer te zien.  Voor nu is het goed werkbaar dus laten we het zo.

**Comment by sytskevanhasselt** [comment]
Status = Done
