### ISSUE TITLE
Naar klantbeeld vanuit zaakdetail

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#313]
Zoeken naar burgers en zoeken naar ondernemers geeft als eindresultaat een klantbeeld
Zoeken in zaken heeft als eindresultaat zaakdetails.  Als je klikt op de aanvrager kom je bij zijn klantbeeld.

Link naar design: https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=2053%3A2807

### Acceptatiecriteria
- [ ] In een zaakdetail-pagina kun je klikken op Aanvrager; daarmee ga je naar het klantbeeld van die aanvrager
- [ ] Op dat moment komt deze klant ook in de loggingtrail waarmee je die klant aan het contactmoment kan koppelen (zoals altijd bij inzien klantbeeld van 1 klant). 

### Taken
- [ ] Zorgen dat bij de Zaken > Rollen > betrokkeneIdentficatie, naast 'voornamen' en 'geslachtsnaam'  ook voorvoegselGeslachtsnaam de juiste waarde krijgt (vooral relevant voor betrokke met BSN 999993872, die heet officieel Peter-Jan _van der_ Meijden)
- [ ] Zorgen dat bij allerhande Zaak-weergaven, in de kolom 'Aanvrager', de gekoppelde 'Indiener' wordt getoond; 
De eigenlijke manier is naam ophalen uit BRP? In de testdata zitten de namen ook in rolbetrokkeneIdentificatie
- [ ] Als mogelijk: linken naar klant.subjectIdentificatie.inpBSN = Zaak.rollen.betrokkeIdenfiticatie.inpBsn

**Comment by sytskevanhasselt** [comment]
Deze is nog even on hold; we wachten tot we K-03 / #158 hebben afgerond. Op dat moment kunnen we beter beslissen: 

1. of het mogelijk is om o.b.v. BSN van de aanvrager een Klantbeeld-pagina te openen
2. of dat we andersoortige interface oplossingen kunnen bieden, zoals een kruimelpad met  b.v. de laatste 3 pagina's die je hebt gezien.

**Comment by sytskevanhasselt** [comment]
Is story in 1C
