### ISSUE TITLE
Contactverzoek - bug je kunt geen medewerkers meer kiezen

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#315]
Ik kan bij een contactverzoek geen medewerkers meer selecteren

**Comment by sytskevanhasselt** [comment]
Dit is vandaag opgelost: lag zowel aan instelling in de Gateway, als aan code in de frontend. 
Beide zijn opgelost voor de acceptatieomgeving
maar het moet nog voor de dev-omgeving.

**Comment by sytskevanhasselt** [comment]
@rjzondervan , ik heb deze nog even open laten staan. Omdat het configuratie-ding dat jij gisteren hebt gedaan voor kiss-dev, nog doorgevoerd moet worden voor kissdevelopment-frontend. Maar dat is m.i. nog de enige openstaande

**Comment by sytskevanhasselt** [comment]
Gefixed
