### ISSUE TITLE
Gespreksid ontbreekt?

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#338]
De story N-00, #108 zou een gespreksid geimplementeerd moeten zijn. Maar: 
- in de story zelf staat deze taak niet afgevinkt. 
- als ik de json bekijk, heb ik niet de indruk dat er een gespreksid wordt ingevuld. Zie ook screenshot 

![Image](https://user-images.githubusercontent.com/53014699/193665753-28cee375-88ec-482e-b15c-4645c3cf13b2.png)

**Comment by sytskevanhasselt** [comment]
Twee bevindingen (zie document in teams: [kanaal KISS > Bestanden > Testen + testdata > Bevindingen release 04 > Bevindingen_#338_Gespreksid.docx ](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_%23338_Gespreksid.docx?d=w6c939686548c4cde8f10a85af3c24ef6&csf=1&web=1&e=mag1r6)

- SH01: er wordt náár de gateway gestuurd: een property 'gespreksId', in het Contactmoment. MAAR: er komt terug uit de gateway: een property 'gesprek', in het Klantcontactmoment (dat is 1 niveau 'te hoog'). 
Gaarne propertynaam 'gespreksId' gebruiken, én het in het Contactmoment stoppen en niet in het Klantcontactmoment
    NB: ik zie dat dit ook niet goed staat in de Redoc .... 
- SH02: bij twee Contactmomenten binnen één klantinteractie zie ik twee verschillende waarden bij 'gesprek', Maar dit wordt vermoedelijk veroorzaakt door SH01.

**Comment by sytskevanhasselt** [comment]
Beide bevindingen gehertest: nu gaat het goed: 
- Contactmoment dat zónder GesprekID wordt gepost, krijgt gespreksId terug
- Vervolgens wordt een evt. tweede vraag gepost met het gespreksId van vraag 1
- Hiermee krijgen de twee contactmomenten hetzelfde gespreksId 

Ik heb ook gezien dat de Redoc is bijgewerkt

**Comment by sytskevanhasselt** [comment]
Dit gaat momenteel niet goed op ACC. 
Dus ik open dit issue weer, en hang 'm even in minihackaton, en zet 'm op Wilco

**Comment by rjzondervan** [comment]
Zojuist dit ook op acceptatie aangepast, zou dit kunnen worden hertest?

**Comment by sytskevanhasselt** [comment]
Gespreksid zit nu op de goede plek. Maar: na het posten van een een Contactmoment, krijgt gespreksid geen waarde mee. 
ER onder staat een property 'id', ik vermoed dat díe een uuid krijgt. 


![Image](https://user-images.githubusercontent.com/53014699/204255752-1dd90a77-91eb-429d-82e4-bac2f08e999b.png)

**Comment by rjzondervan** [comment]
Ik was vergeten de generator van het gespreksId aan te zetten, zou je kunnen hertesten?

**Comment by sytskevanhasselt** [comment]
GespreksID komt nu mee. Maar het wordt niet meegegeven aan de tweede vraag die gepost wordt.

**Comment by sytskevanhasselt** [comment]
Dit werkt op de kissdevelopment-frontend-omgeving. En op de dev.kiss-demo-omgeving. 
Daarmee verklaar ik deze voor compleet uitgevoerd.
