### ISSUE TITLE
restpunten WCAG

### ISSUE THREAD

**Issue by felixcicatt** [Klantinteractie-Servicesysteem/KISS-frontend#347]
- wit/groen combinatie heeft onvoldoende contrast. dit zien we bv in de startknop en in de uitklap met actieve contactmomenten
- De Hoverrand is nauwelijks zichtbaar bij de Afronden-knop
- De Hover-rand is slecht zichtbaar bij het element om de zoekbalk in te klappen. de lijn lijkt minder vet, dat bijv. die om de zoekresuttaten

Design: https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=2194%3A6249

**Comment by sytskevanhasselt** [comment]
Wordt opgepakt bij restyle 1C
