### ISSUE TITLE
Sortering van de PUB-berichten verspringt soms

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#367]
Dit is een issue dat eerst geconstateerd is bij #288. Maar we nu even los trekken. 

### Wat gebeurt er?
De sortering van nieuws/werkinstructie laat soms vreemde dingen zien, waarbij soms ineens berichten met een hele nieuwe updatedatum bovenaan komen te staan, terwijl ze niet gewijzigd zijn. Even later 'verdwijnen' ze ook weer. 

Oorzaak lijkt te liggen in het property: x-commongateway-metadata.dateModified: 
- deze zou dezelfde waarde moeten hebben als het property 'modified'. 
- maar deze krijgt blijkbaar soms de waarde van 'nu'
	
Oplossing: 
- [x] We passen de sortering aanpassen naar sortering op 'modified' en niet op 'x-commongateway-metadata.dateModified'. 
- [ ] We kijken naar de logica rondom Gelezen/ongelezen, en zorgen dat die óók kijkt naar 'modified' en niet meer naar  'x-commongateway-metadata.dateModified' (zie ook de comments)

**Comment by sytskevanhasselt** [comment]
We hebben in de frontend gezorgd dat er nu gesorteerd wordt op  'modified'. 
Maar: ik zie dat voor de Read-status nog steeds gekeken wordt naar 'x-commongateway-metadata.dateModified'. En dat levert dan soms nog onverwachte issues op ...

**Comment by lencodes** [comment]
Staat klaar op dev om getest te worden.

**Comment by sytskevanhasselt** [comment]
#367  lijkt opgelost op Acc in ieder geval. Code aanpassingen van Lencodes zijn gedeployed op Dev. Ik ben geneigd deze akkoord te beschouwen...

**Comment by sytskevanhasselt** [comment]
Niet meer gezien op DEV, de afgelopen week. ik sluit deze
