### ISSUE TITLE
Als gebruiker wil ik dat alle security issues zijn afgerond

### ISSUE THREAD

**Issue by rubenvdlinde** [Klantinteractie-Servicesysteem/KISS-frontend#371]
### Taken Conduction
- [x] #60
- [x] #61
- [x] #62
- [x] #63
- [x] #255 
- [x] <s>#86</s>
- [x] #327
- [x] #399
- [x] De workflow en keuzes daaromtrend zijn uitgelegd in de security.md
- [x] #435
- [ ] NOG TESTEN Als developer wil ik dat ook unit test onderdeel is van de git workflow

**Hoe te testen**
- #60 Er staat een SECURITY.MD in de root folder van de gateway repro, er staat een link hiernaartoe op de org pagina onder documentatie, Robert en PAscal zijn het er over eens dat het af is
- #61 het resultaat van de postman testset is opgeneomen als artifact in de [gateway workflow ](https://github.com/ConductionNL/commonground-gateway/actions)
- #62 er is een stap in de workflow die dit aftest EN ZO HEET, die heeft groen vinkje en publiceerd zijn resultaat als een artifact
- #399 Er is een workflow, met duidenlijke stappen, artifacts, en de vinkjes staan op groen.
- Pentest PDF is aangeleverd en akkord bevonden door pascal ,  De resulaten zijn positief , de PDF is geupload in de repro, er  staat onder documentatie in de ORG pagina een link naar de resultaten.
-

**Comment by WilcoLouwerse** [comment]
@rjzondervan 
#60
#62
(^Met Pascal aftikken)

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
