### ISSUE TITLE
Als gebruiker wil ik dat de documentatie is afgerond

### ISSUE THREAD

**Issue by rubenvdlinde** [Klantinteractie-Servicesysteem/KISS-frontend#373]
### Taken Conduction
- [x] Ik wil dat er op de op de [githomepage een blokje documentatie ](https://github.com/Klantinteractie-Servicesysteem)staat met daarin de links naar alle documentatie (te testen via [homepage](https://github.com/Klantinteractie-Servicesysteem))
- [ ] #79 (te testen via [configuratue](https://github.com/Klantinteractie-Servicesysteem/.github/blob/main/docs/CONFIGURATIE.md))
- [x] Er is een lijst van alle in kiss gebruikte componenten  (te testen via [homepage](Klantinteractie-Servicesysteem/KISS-frontend))
- [x] Bij iedere component wat binnen kiss wordt gebruikt is een verwijzing naar een open source oplossing  (te testen via [homepage](Klantinteractie-Servicesysteem/KISS-frontend))
- [x] Bij iedere open source oplossing is er een verwijzing naar een installatie instructie voor die oplossing (staat op de oplossings pagina hierboven)
- [ ] Er is een stap voor stap handleiding over hoe kiss op een omgeving moet worden geinstaleerd  (te testen via [installatie](https://github.com/Klantinteractie-Servicesysteem/.github/blob/main/docs/INSTALLATION.md))
- [x] Er is een handleiding voor het schrijven van uitbreidingen op kiss 
- [ ] Er is een handleiding voor het koppelen van nieuwe applicaties op kiss (te testen via [configuratue](https://github.com/Klantinteractie-Servicesysteem/.github/blob/main/docs/CONFIGURATIE.md))
- [ ] @PascalIcatt heeft deze stap voor stap handleiding gerepliceerd
- [ ] ReadTheDoscs.io (status checken)

**Comment by sytskevanhasselt** [comment]
## Opmerkingen

### Openpub
- moeten er, binnen elke Readmy, ook weer onderdelen voor Contributing etc? Of staat dat alleen op het Hoofdniveau (Klantinteractie Servicesysteem readme)? 
- Wat staat er bij het onderdeel 'Opzet van de plugin'? Wat moet er hier duidelijk worden? 
- Als je het hebt over 'plugin': is het dan een plugin voor KISS? Of een plugin voor de Gateway? Of een plugin voor Wordpress?

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
