### ISSUE TITLE
Als gebruiker wil ik dat de wordpress plugin (PUB) is afgerond

### ISSUE THREAD

**Issue by rubenvdlinde** [Klantinteractie-Servicesysteem/KISS-frontend#374]
### Acceptatiecriteria
- [x] #167 
- [x] #166 
- [x] #202 
- [x] #209 
- [x] #285
- [ ] De skill, link, afdelingen, gespreks resultaten staat als short cut card op het dashboard van acc + dev

**Comment by WilcoLouwerse** [comment]
@WilcoLouwerse 
#202
+ Installatie Dev WP

**Comment by WilcoLouwerse** [comment]
#386 is afhankelijk van [#441](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/411)

**Comment by sytskevanhasselt** [comment]
De skills staan nog NIET in de gateway. 
1. Er is wel een Schema kiss_openpub_skill
2. Maar in Wordpress kun je bij een artikel alléén maar skills selecteren,[ die in Wordpress zelf staan](https://openweb.kiss-dev.commonground.nu/wp-admin/edit-tags.php?taxonomy=openpub_skill&post_type=kiss_openpub_pub)
3. Ook in de frontend zijn alléén de skills zichtbaar, die in Wordpress zelf staan

**Comment by sytskevanhasselt** [comment]
Andere bevinding over de koppeling tussen Wordpress en GAteway: er gebeuren vreemde dingen met de Types in Wordpress, op de [pagina om types te beheren in Wordpress](https://openweb.kiss-dev.commonground.nu/wp-admin/edit-tags.php?taxonomy=openpub_type&post_type=kiss_openpub_pub), zie hieronder. Deze heeft een Zeer Lage Prio. 

> Ik ben als Admin ingelogd op Wordpress. 
> Daar heb ik alleen toegang tot Publications > Types en Publications > Skills
> 
> 1.	Ik wijzig bij Types de Name en Slug van Nieuws naar Nieuwzz
> 2.	In Wordpress zie ik onmiddellijk een Nieuwe Type verschijnen: ‘Nieuws’
> 3.	De KISS-redacteur ziet in zijn lijst Artikelen dat alle artikelen nu van het type Nieuwzz zijn
> 4.	Bij het bewerken van een artikel staan nu 3 opties bij type: Nieuws, Nieuwzz en Werkinstructie
> 5.	In de KISS-frontend verdwijnen alle artikelen. Pas als de redacteur de type weer wijzigt van Nieuwzz naar Nieuws, verschijnt een artikel weer in de frontend.
> 6. Ik zie dat de frontend wel meteen het nieuwe typeID opvraagt in de call (bv. acf.publication_type=40)
> 
> Hetzelfde gebeurt bij het wijzigen van de Type ‘Werkinstructie’ naar ‘Werkinstructiezz’ ….
> 
> 
> HOE werkt de communicatie over de types tussen Gateway en Wordpress?

**Comment by sytskevanhasselt** [comment]
Dus ik sluit deze
