### ISSUE TITLE
Als gebruiker wil ik dat de Gateway admin UI kiss voldoende ondersteunt (ng open: Objecten hebben een Naam)

### ISSUE THREAD

**Issue by rubenvdlinde** [Klantinteractie-Servicesysteem/KISS-frontend#375]
- [x] #160 
- [x] #79
- [ ] #443
- [x] De skill, link, afdelingen, gespreksresultaten staat als short cut card op het dashboard van acc 
- [x] #445

**Comment by sytskevanhasselt** [comment]
Bevindingen over de Gateway UI vanuit andere stories (zie ook [Teams > Testen + testdata > Bevindingen release 04 > Bevindingen_CGGUI_KISS1.docx](https://icattnl.sharepoint.com/:w:/r/sites/EXTERN-Conduction/Gedeelde%20documenten/KISS/Testen%20+%20testdata/Bevindingen%20release%2004/Bevindingen_CGGUI_KISS1.docx?d=w02a12eca7fa543e4bc77c763e9dc4038&csf=1&web=1))
