### ISSUE TITLE
zoeken op geboortedatum in BRP geeft rare resultaten

### ISSUE THREAD

**Issue by felixcicatt** [Klantinteractie-Servicesysteem/KISS-frontend#380]
Reproduceren:
- doe een GET op [deze url](https://kissdevelopment.commonground.nu/api/ingeschrevenpersonen?geboorte.datum.datum=1985-12-01&extend%5B%5D=all)
- of een GET op [deze url](https://kissdevelopment.commonground.nu/api/ingeschrevenpersonen?geboorte.datum.jaar=1985&geboorte.datum.maand=12&geboorte.datum.dag=1&extend%5B%5D=all)
- Nu krijg je 1 record terug dat daadwerkelijk die geboortedatum heeft, maar ook nog meer records met hele andere geboortedatums.

**Comment by rjzondervan** [comment]
Deze bug is onderzocht, maar nog niet verholpen. Het probleem is als volgt: in het zoeken naar een persoon met een geboortedatum wordt er gezocht met de naam van een attribute op een entity. Echter, het kan zijn dat deze attribute op een dieper niveau leeft dan bovenin de entity. Wat er nu gebeurt is dat niet alleen gefilterd wordt op de geboortedatum van de persoon zelf, maar ook op de geboortedata van de eerstegraads familieleden (ouders, kinderen, partner). Omdat in de testset die nu is ingeladen iedereen eerstegraads familie van elkaar is, levert dat op dat iedereen altijd gevonden wordt.

Omdat @WilcoLouwerse dieper in deze logica zit, ga ik deze even met Wilco oppakken morgen.

**Comment by WilcoLouwerse** [comment]
Ik heb er naar gekeken en een poging gedaan het probleem op te lossen door ook de nesting/depth level mee te nemen in de aliases van sql joins. Dit heeft helaas niet geholpen dit probleem op te lossen.
Ik merk dat dit issue mij voor nu veel tijd kost. Dus ik ga eerst dingen oppakken waar ik wel op vooruit kom voor ik hier weer verder naar ga kijken.

**Comment by WilcoLouwerse** [comment]
![Image](https://user-images.githubusercontent.com/3785488/198002622-fc1f40c9-4537-4a7b-b030-5e063cb387d2.png)

**Comment by sytskevanhasselt** [comment]
Volgens mij is het nu goed: 

1. zoeken op 1-12-1985 levert nu alleen Suzanne Moulin als resultaat op. Dus dat klopt
2. Heb op nog wat datums gezocht, en krijg alleen resultaten die ik verwacht. 

Dus ik sluit deze af. 

LET OP dit is momenteel geimplementeerd op https://kissdevelopment-dimpact.commonground.nu/
Moet nog wel op https://kissdevelopment.commonground.nu/
