### ISSUE TITLE
Availabilities in Medewerkerobject uit Gateway klopt niet

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#394]
We hebben een aanpassing gedaan op het Medwerkerobject, waarbij availablities openomen zijn als een Array, met daarin per dag en dagdeel: de beschikbaarheid. 

Zo zit het nu wel in de handmatig ingevoerde medewerkers, en daarop wordt de beschikbaarheid getoond.

Maar: zo zit het nu niet in de Medewerkers die vanuit de Gateway naar Elastic worden gepushed. 
Zie bijgevoegde bestanden: 

- Handmatige toegevoegde medewerker: [Mdw_b4e5e1a3-fe44-47df-803e-a75f065bd2ae_Francine-object.json.txt](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/9850606/Mdw_b4e5e1a3-fe44-47df-803e-a75f065bd2ae_Francine-object.json.txt)
- Medeweker via Gateway: [Mdw_d9e82930-2d7e-4955-82ae-2e58e0e469c2_Dalal-object.json.txt](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/9850605/Mdw_d9e82930-2d7e-4955-82ae-2e58e0e469c2_Dalal-object.json.txt)

### Taken: 
- [ ] implementatie medewerker-api bijwerken naar availabilities zoals te zien in Mdw_Francine-object.
- [ ] Push-mechanisme naar Elastic bijwerken naar juiste versie Medewerker-api

**Comment by sytskevanhasselt** [comment]
Deze even kort checken met Ruben

**Comment by WilcoLouwerse** [comment]
Availabilities moet op medewerker niveau, ipv calendar.availabilitites waar de array in hangt.
Hiervoor zal de front-end ook moeten worden aangepast.

**Comment by sytskevanhasselt** [comment]
- [ ] één handmatig object bijwerken naar availabilities in Medewerker ipv in Calendar [SYTSKE]
- [ ] frontend aanpassen: zodat gekeken wordt naar de juiste availabilities [LENCODES] 
- [ ] gateway aanpassen: zorgen dat availabilities op het juiste niveau staan en als zodanig doorgepassed naar elastic [WILCO]
- [ ] sync testen met nieuwe aanpassingen [SYTSKE]

**Comment by WilcoLouwerse** [comment]
![image](https://user-images.githubusercontent.com/3785488/203342009-ee8f5fbd-8234-438e-9612-012986bc6f02.png)
![image](https://user-images.githubusercontent.com/3785488/203342027-5b5adb4e-9cf8-457c-b4eb-b75c3dc6159d.png)
![image](https://user-images.githubusercontent.com/3785488/203342039-974467df-e787-4bee-a4c0-2ec9c9e72d8b.png)
![image](https://user-images.githubusercontent.com/3785488/203342045-c3fc5dd9-51a5-466f-bfac-137e720eed89.png)

**Comment by sytskevanhasselt** [comment]
Ik heb getest: 
- POST medewerker, met de availabilities
- PUT medewerker, 
    - met gewijzigde availabilities
    - met foutieve of onvolledige availabilities (hele dag null, of hele dag ontbreekt)
    - Met waardes 'null' voor middag en ochtend (wordt door frontend goed opgepakt: als afwezig)

Dus deze is ok, ik sluit 'm af.
