### ISSUE TITLE
In Zaakdetail: tonen van de naam bij Aanvrager en Behandelaar

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#395]
*Aanleiding*
Op dit moment staat bij de naam van de Aanvrager altijd onbekend. Terwijl er in onze testdata alleen maar aanvragers zitten, die ook in de test-brp staan. Ook bij medewerker wordt altijd Onbekend getoond.
We willen hier wel een naam zien.

### **Acceptatiecriteria Indiener**
- [ ] In zaak-informatie halen we de naam van de aanvrager op via Rol.roltype.omschrijving = "indiener", in combinatie met de waarden van Rol.BetrokkenType en Rol.betrokkeneIdentificatie
- [ ] Rol.BetrokkenType = "natuurlijk_persoon" EN rol.Rol.betrokkeneIdentificatie.inpBSN = gevuld, dan naam ophalen uit BRP, op basis van dat BSN 
- [ ] Rol.BetrokkenType = "natuurlijk_persoon" EN Rol.betrokkeneIdentificatie.inpBSN = leeg, dan naam tonen uit  Rol.betrokkeneIdentificatie.voornamen, Rol.betrokkeneIdentificatie.geslachtsnaam  en Rol.betrokkeneIdentificatie.voorvoegselGeslachtsnaam
- [ ] Rol.BetrokkeneType = "vestiging" EN Rol.betrokkeneIdentificatie.vestigingsNummer = gevuld, dan naam ophalen uit KvK-vestigingen, op basis, op basis van dat vestigingsNummer
- [ ] Rol.BetrokkeneType = "vestiging" EN Rol.betrokkeneIdentificatie.vestigingsNummer = leeg: dan naam tonen uit, Rol.betrokkeneIdentificatie.Handelsnaam 

### **Acceptatiecriteria behandelaar**
NB: voordat deze aanpassingen goed getest kunnen worden, moet de testdata worden aangepast, zoals beschreven in: #396 
- [ ] In zaak-informatie halen we de naam van de aanvrager op via Rol.roltype.omschrijvingGeneriek = "behandelaar", in combinatie met de waarden van Rol.BetrokkenType = "natuurlijk_persoon"
- [ ] Als er een URL aanwezig in Rol.betrokkeneIdentificatie: dan halen we de naam daaruit op
- [ ] Anders halen we de naam op uit Rol.betrokkeneIdentificatie.voornamen, Rol.betrokkeneIdentificatie.geslachtsnaam  en Rol.betrokkeneIdentificatie.voorvoegselGeslachtsnaam

**Comment by sytskevanhasselt** [comment]
Openstaande vraag, voor @rubenvdlinde  en @hannekevanderhorst : in de acceptatiecriteria staat beschreven dat de naam opgehaald moet worden uit de 'verwijzing' als die er is (inpBSN voor aanvrager; een url in geval van behandelaar). 

MAAR: de vraag is wáár dit moet gebeuren.

Op dit moment gebeurt het NIET in de frontend, voor wat betreft BSN. 
Daarnaast: een aanvrager kán vast ook een 'vestiging' zijn, met een 'vestigingsNummer'. 

Voorstel: zullen we hiervoor een apart issue aanmaken?

**Comment by hannekevanderhorst** [comment]
dit gaat goed op DEV - MAAR niet goed op ACC

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
