### ISSUE TITLE
Testdata zaken aanvullen met minimaal één behandelaar

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#396]
Op dit moment zit er in onze testdata voor zaken maar één roltype: Indiener. 
NB: dit leidt ik uit af uit de informatie in [**ztc_publiccode**](https://github.com/ConductionNL/ztc_publiccode/blob/main/data/ztc.json). 

Hier moeten we aan toevoegen: één Behandelaar van wie we de naam kunnen tonen in de frontend. 
- [ ] In ZTC: moet er een Roltype bijkomen, met omschrijvingGeneriek (denk ik? Of Omschrijving) = "behandelaar"
- [ ] Vervolgens: in ZRC moet er voor elke zaak een definitie worden ingevoegd voor deze rol. Hierbij moeten de volgende properties worden ingevuld: 
    - Rol.betrokkeneIdentificatie.voornamen =  "Jan-Hendrik"
    - Rol.betrokkeneIdentificatie.geslachtsnaam =  "Bovenkarspel"
    - Rol.betrokkeneIdentificatie.voorvoegselGeslachtsnaam =  "van"

**Comment by rjzondervan** [comment]
Ik heb zojuist alle zaaktypen in het ZTC op Development voorzien van een 'behandelaar' roltype, ik zal aan alle zaken voor nu ook een behandelaar toevoegen. Ik heb ook in de ztc_publiccode een behandelaar-roltype toegevoegd.

**Comment by rjzondervan** [comment]
Inmiddels ook de behandelaars toegevoegd aan zaken.

**Comment by sytskevanhasselt** [comment]
Deze is done.
