### ISSUE TITLE
Als gebruiker wil ik een uitgebreide test workflow voor de gateway

### ISSUE THREAD

**Issue by rubenvdlinde** [Klantinteractie-Servicesysteem/KISS-frontend#399]
Branche: https://github.com/ConductionNL/commonground-gateway/tree/feature/kiss-371/security-checks

Op dit moment worden de images nog gepassseerd tussen de stages als artifacts, das langsaam gana een paar minuten verloren we kunnen de stages ook onderling een gedeelde temp mag geven. 

**Tesbare eisen**

- [ ] Unit test 
- [ ] Imge test (o.a. snyk)
- [ ] Postman test
- [ ] Database integriteit
- [ ] Licentie voorwaarden
- [ ] Dependencies

**Acceptatie creteria**
- Voor alle testbare eisen is er een losse github workflow stage (zodat we in een oogopslag kunnen zien wat er wel en niet goed gaat)
- Iedere stage publiceerd zijn resultaten als een artifact.

**Comment by rubenvdlinde** [comment]
Handige link = https://github.com/docker/build-push-action/issues/225

**Comment by sytskevanhasselt** [comment]
GatewayIssue, gesloten ivm. 1C
