### ISSUE TITLE
CI/CD tasks

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#40]
- [x] commonground repos master branches hernoemen > main
  - [x] feature-cleanup naar main brengen (trunk of branche, maar is de nieuwe default in dit project)
  - [x] snyk (SAST)
  - [x] inrichten deployment naar dev/accept mbv PR/push triggers
  - [x] styleCI
  - [x] #63
  - [x] postman testset minimaal 1
  - [x] #61
  - [ ] readthedocs
  - [x] #60
  - [x] #62
  - [x] #86

controle:
- [x] of snyk alles meepakt wat we doen dmv het framework composer/symfony

**Comment by rjzondervan** [comment]
Ik heb nu de oude master branch hernoemd naar depracticed, en de feature cleanup naar main. Daarnaast main ook als default branch ingesteld en een nieuwe development branch daar uit getrokken. Ook heb ik dezelfde branch rules ingesteld als op KISS-Frontend.

**Comment by sytskevanhasselt** [comment]
Status = done
