### ISSUE TITLE
Delete calls op Gateway geeft 500

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#411]
Geconstateerd met Wilco, bij testen van #245 : delete calls op de Gateway geven een 500 error terug. Maar de delete wordt wel uitgevoerd.

NB: dit hoeft niet gefixed voor de test op 27-okt

**Comment by WilcoLouwerse** [comment]
#386 Is afhankelijk van dit issue

**Comment by sytskevanhasselt** [comment]
Ik heb vandaag getest op zowel: 
ACC (https://kissdevelopment-dimpact.commonground.nu), als
DEV (https://kissdevelopment.commonground.nu)

Getest met de call: DELETE {{environment}}/api/medewerkers/{id}

- Op Beide omgevingen zie ik in Postman een 500- error
- Op ACC: als ik daarna een GET {{environment}}/api/medewerkers/{id}, krijg ik WEL een medewerker terug. ik zie wel dat het property 'contact' geen waarde meer heeft
- Op DEVV: als ik daarna een GET {{environment}}/api/medewerkers/{id}, krijg ik netjes de melding: "Could not find an object with id a6296639-2a3c-4b52-8125-61c378475665 of type Medewerker"

Ik heb niet op andere endpoints getest, omdat ik Contactmomenten te eng vind (daar hangt zoveel aan elkaar)
En Klant heeft geen DELETE endpoint.

**Comment by rubenvdlinde** [comment]
Timeboxen 2 uur en dan een keuze maken oplossen of uitwijken, keuze terug leggen in teams.

**Comment by sytskevanhasselt** [comment]
Deze is gefixed op/na 15 dec.
