### ISSUE TITLE
Volgorde zoekbronnen

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#424]
Uit het gebruikersonderzoek komen meerdere issues naar voren met zoeken op burgers. Omdat er veel onduidelijkheid bestaat over wanneer je in welke bron mag zoeken gaan we deze pas oplossen in Fase 2. Voor nu gaan we alleen de volgorde van de zoekcategorieen wijzigen. 

De volgorde is nu:
E-mail     Telefonnumer     BSN
Geboortedatum    Postcode + huisnummer

Dat moet worden:
Geboortedatum    Postcode + huisnummer
E-mail     Telefonnumer     BSN

**Comment by sytskevanhasselt** [comment]
Status = Done
