### ISSUE TITLE
validatie op contactgegevens bij contactverzoek weghalen

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#425]
Er is veel discussie over het het klantregister. Hoe men hiermee binnen KISS wil omgaan is onderdeel van Fase2. Voor nu wil de men niet verplicht zijn om contactgegevens in het klantregister op te voeren en als dat kan de naam van de klant niet tonen in het klantgegevens stuk boven in het scherm.

To do:

- Je kunt een contactmoment met een contactverzoek niet afronden als er geen contactgegevens zijn ingevuld. Deze validatie moet eraf
- De validatiemelding weghalen, deze staat in het afhandelscherm (geen klant geselecteerd en geen contactgegevens bij klant bekend)
- In het klantbeeld de naam van de klant weghalen

![Image](https://user-images.githubusercontent.com/104772647/199964579-d75bc0e8-cb95-47fa-ad20-ec2424668439.jpg)

![Image](https://user-images.githubusercontent.com/104772647/199964626-951a6be3-7e92-4855-a572-0cf308544705.jpg)

**Comment by hannekevanderhorst** [comment]
Bovenstaande is goed opgepakt. Er staat echter ook nog een validati in het terugbelvezoekscherm. Graag deze ook weghalen


![Image](https://user-images.githubusercontent.com/104772647/201342517-514cf42f-2a10-4b8e-afe8-7bdadd59944d.jpg)

**Comment by sytskevanhasselt** [comment]
Status = Done
