### ISSUE TITLE
Afdelingslijst in contactverzoek

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#426]
Contactverzoeken worden niet naar een persoon maar naar een afdeling of groep gestuurd. Er is discussie over hoe we dit in KISS zouden kunnen realiseren. Er is bij de gemeente geen register met groepjes (met een groepsnaam, een groepsmailbox, namen van deelnemers en en e-mail-adressen van medewerkers) waar we mee kunnen koppelen en we willen in de Gateway dit soort informatie niet gaan opslaan. Het oplossen van dit probleem hoort bij Fase 2. Voor nu wil de ontwerpgroep graag dat de afdeling wel als mm-info kan worden opgeslagen.

To do:
- Gemeenten moeten een lijst kunnen aanmaken in de Gateway met afdelings/groeps-namen
- Deze lijst toont bij het contactverzoek boven de medewerker:
    Contactverzoek sturen naar:
    Groep*
    Medewerker
- Bovenstaande ook het afhandelscherm doorvoeren
- De Groep wordt opgeslagen mm-info (in het contactverzoek bij gerellateerde bronnen oid)

**Comment by lencodes** [comment]
Om deze functionaliteit te maken hebben we een endpoint gemaakt op de gateway.

```
GET {env}/api/ref/afdelingsnamen
```

Deze lijst kan gebruikt worden om de drop-down van afdelingsnamen te vullen. Het beheren van deze lijst kan via de gateway-ui gebeuren.

[Documentatie van het endpoint.](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json?nocache#tag/AfdelingsnaamOverige-objecten).

Er moet nog gekeken worden naar wáár in het contactmoment deze data opgeslagen kan worden.

**Comment by felixcicatt** [comment]
Deze is geimplementeerd en staat op [dev](https://kissdevelopment-frontend.commonground.nu/). De afdelingsnaam wordt nu gemapt naar het attendees veld van het contactverzoek, samen met de gekozen medewerker. Als dat anders moet, hoor ik het graag.

**Comment by sytskevanhasselt** [comment]
één aanvulling: ik zie idd dat de naam van de afdeling is opgenomen bij Attendees. Maar: in de interface is het verder nergens zichtbaar. 


![Image](https://user-images.githubusercontent.com/53014699/202995287-0dc963aa-7610-4ff4-9532-4a215978530e.png)

**Comment by sytskevanhasselt** [comment]
Status = Done
