### ISSUE TITLE
testen via API-testvoorziening VNG

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#427]
Inregelen VNG-api testplatform:
SGW
Klanten-api
- [ ] Wacht op #437

**Comment by rubenvdlinde** [comment]
Voorwaarde hiervoor is het makkenlijk resetten van testdata

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
