### ISSUE TITLE
Testdata toevoegen en testdata verwijderen

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#437]
Als tester wil ik oude testdata van contactmomenten en contactverzoeken opruimen / weggooien, zodat de Test 'klanten', en de testZaken, slechts enkele of geen Contactmomenten/Contactverzoeken meer hebben

**Comment by sytskevanhasselt** [comment]
Dit zijn we aan het testen.

**Comment by sytskevanhasselt** [comment]
Testdata toevoegen werkt nu, met de set testdata die in [Release 0.0.55 zit van de KissBundle](https://github.com/Klantinteractie-Servicesysteem/KissBundle/releases/tag/0.0.55).

Wat we nog moeten testen is de zg. Rode Knop: de actie waarmee de alle demo/testdata wordt verwijderd, en opnieuw de basis-set uit de KissBundle wordt ingeladen.

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
