### ISSUE TITLE
Als gebruiker wil ik dat objecten alltijd een naam hebben ipv uuid

### ISSUE THREAD

**Issue by rubenvdlinde** [Klantinteractie-Servicesysteem/KISS-frontend#443]
Bij de twee schema's, bevatten de daaronder getoonde Objecten nog geen Naam o.i.d. 
Bij kiss_openpub_skill en Afdelingsnaam is Naam al wel aanwezig. 
- [ ] ResultaattypeOmschrijvingGeneriek; hier staat wel een Naam, met 'NVT' erin. Hier zou de waarde van 'definitie' te lezen moeten zijn
- [ ] Link; hier staat wel een Naam, met 'NVT' erin. Hier zou de waarde van 'title' te lezen moeten zijn.

**Comment by sytskevanhasselt** [comment]
Gateway-issue, gesloten ivm. 1C
