### ISSUE TITLE
Redoc Sluitend maken door vernieuwde PUB documentatie op te nemen in Algemene Redoc (refactor)

### ISSUE THREAD

**Issue by rubenvdlinde** [Klantinteractie-Servicesysteem/KISS-frontend#444]
- [x] Redoc skills en types lijsten > niet in redoc gezet, maar in documentatie van de Openpub-plugin
- [ ] pub object oude velden weghalen

**Comment by WilcoLouwerse** [comment]
Redoc skills en types lijsten + pub object oude velden weghalen

**Comment by sytskevanhasselt** [comment]
Op dit moment zie ik op [de redoc](https://redocly.github.io/redoc/?nocors&url=https://kissdevelopment-dimpact.commonground.nu/openapi.json#tag/Kiss_openpub_pubPub-collection) alléén calls staan naar: /api/kiss_openpub_pub/{id}

In de frontend zie ik ook nog twee calls, om de types en de skills op te halen. 
- /api/openpub/openpub_skill
- /api/openpub/openpub_type

Deze kan ik niet vinden op de redoc.

**Comment by lencodes** [comment]
Mijn bevindingen ter documentatie en (jammer genoeg) nog zonder conclusie:

De huidige implementatie:

1. We halen alle `openpub_skills` op via een Wordpress proxy, hier krijgen we (o.a.) het door **Wordpress** gealloceerd `id` mee per skill;
2. We doen een `GET` op alle `openpub_pub` berichten via een Wordpress proxy en gebruiken hier als filter de `id` uit stap 1.

Verwachtte implementatie (ook kloppend met de **huidige ReDoc**):

1. We halen alle `openpub_skills` op via de referentie lijst (en dus **niet via** Wordpress), hier krijgen we (o.a.) het door de **Gateway** gealloceerd `id` mee per skill;
2. We halen alle berichten op via de Gateway met de `id` uit stap 1.

Het is mij (nog) niet duidelijk of de laatste stap mogelijk is. Mogelijke oplossingsrichtingen voor dit issue:

1. (Waarschijnlijk het netste, maar ook het meeste werk): de _Verwachtte implementatie_ implementeren;
2. (Waarschijnlijk, by far, het snelste): de twee proxy calls toevoegen aan de ReDoc.

**Comment by sytskevanhasselt** [comment]
Besproken: We vermelden de twee calls naar Types en Skills in de documentatie van Openpub. Dat heeft lencodes gedaan.

**Comment by sytskevanhasselt** [comment]
PUB-issue, gesloten ivm. 1C
