### ISSUE TITLE
De skill, link, afdelingen, gespreksresultaten staat als short cut card op het dashboard van dev

### ISSUE THREAD

**Issue by rubenvdlinde** [Klantinteractie-Servicesysteem/KISS-frontend#445]

**Comment by sytskevanhasselt** [comment]
Gezien, dit is m.i. klaar.

**Comment by sytskevanhasselt** [comment]
Deze heropen ik weer: op dit moment geven de Dashboardcards op DEV een 500 melding
![image](https://user-images.githubusercontent.com/53014699/208379502-954bfb2a-220e-4157-9b04-5450ccd5e00b.png)

**Comment by sytskevanhasselt** [comment]
Gateway-issue Gesloten i.v.m. Fase 1C
