### ISSUE TITLE
Inlezen SDU Deventer (PDC API)

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#51]

**Comment by PascalIcatt** [comment]
ICATT en Conduction samen inlezen

**Comment by PascalIcatt** [comment]
Documentatie aanleveren SDU

**Comment by PascalIcatt** [comment]
inrichten inlezen data en opnemen in elastic index, push of pull, Pascal onderzoekt Pull optie Elastic

**Comment by sytskevanhasselt** [comment]
Status = done
