### ISSUE TITLE
Zoekresultaten VAC

### ISSUE THREAD

**Issue by ramonfasel** [Klantinteractie-Servicesysteem/KISS-frontend#578]
### Description

Als klantcontactmedewerker wil ik kunnen zoeken in de vraag-antwoord-combinaties (vac’s) als nieuwe bron naast de PDC, zodat we PDC en VAC naast elkaar kunnen gebruiken.

Bron https://github.com/orgs/Klantinteractie-Servicesysteem/projects/3/views/2?pane=issue&itemId=25860802

### Estimate

5 pt

### Acceptance criteria

- Er is een Objecttype gedefinieerd voor de VAC
- Er is een testregister met verschillende VAC's
- De kennisbron VACs worden m.b.v. de Objecten API in Elastic gezet
- In de zoekresultaten verschijnen óók VAC's: 
- Je kunt VAC aanvinken, zodat je alléén VAC's vindt.
- De synchronisatietool neemt de nieuwe bron ook mee
- Handleiding rondom installatie en configuratie is bijgewerkt.

### Specific details

- Het testregister maken we voorlopig aan in Objecten (waar ook medewerkers staan)

### Test plan

- Zoek in KISS een VAC op, en controleer of de inhoud klopt met de VAC in Objecten
- Kijk of het filter werkt
- Voeg een VAC toe en kijk of deze na 59 minuten tijd vindbaar is in KISS

**Comment by sytskevanhasselt** [comment]
RF/RB/SvH: story nagekeken

**Comment by sytskevanhasselt** [comment]
VACs die momenteel aanwezig zijn: 
- bromfietsrijbewijs
- welk sooort rijbewijzen
- Container voor glas
- Wat kost inburgeren
- Krijg ik een vergunning voor een evenement?

**Comment by sytskevanhasselt** [comment]
Testen: 
- op dit moment kan inhoud controleren alleen via Netwerk tab, we tonen alleen nog maar de titel in de interface. 
- filter: ok
- Updaten VAC, getest door Pascal: OK

Bevinding: in de interface staat VAG ipv VAC

**Comment by Astrid-Utrecht** [comment]
AB -  Objecten (toevoegen VAC) kan ik niet toetsen. VAC koppelen en filteren op VAC getest en werkt.

**Comment by sytskevanhasselt** [comment]
Screenshot van de VAC over Klein chemisch afval, met daarnaast: de inhoud van het Object in de objectenregistratie


![Image](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/assets/53014699/d3cca810-154b-4cd0-b3e6-efbfe29dd286)
