### ISSUE TITLE
VAC kunnen bekijken

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#579]
### Description

Als KCM wil ik doorklikken naar een detailscherm met alle informatie van een VAC, zodat ik de klant het juiste antwoord kan geven, en zodat deze vraag wordt gelogd bij mijn contactmoment.

### Estimate

3

### Acceptance criteria

- Er is een detailweergave voor VAC's
- In dit detailscherm kun je de Vraag, het Antwoord en de Toelichting lezen van een VAC
- Het is duidelijk voor een KCM dat de Toelichting interne informatie voor KCM's bevat
- Als je een detailweergave bekijkt, komt de VAC ook in het lijstje bekeken bronnen te staan
- De VAC kan ook worden opgeslagen in het Contactmoment, net als Kennisartikelen en websites
- Je laatst bekeken bron, dus ook een VAC, komt vooringevuld te staan in het afhandelscherm 

### Specific details

- zie [design in figma](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=571-1152&mode=design&t=MsGqPS446uoFluHG-0)

### Test plan

- Zoek een aantal VAC's en controleer of de inhoud klopt met de VAC in Objecten (bekijk géén andere bronnen)
- Controleer Vraag, Antwoord en Toelichting van deze VAC's
- Controleer dat alle bekeken VAC's bij bronnen opgenoemd staan in het afhandelscherm
- Controleer dat je laatst bekeken bron vooringevuld staat bij Vraag
- Vink een VAC uit
- Sla je contactmoment op, en check dat alléén de aangevinkte bronnen (waaronder VAC) in Contactmoment worden opgeslagen

**Comment by sytskevanhasselt** [comment]
RF/RB/SvH: story nagekeken

**Comment by sytskevanhasselt** [comment]
Ik weet niet helemaal zeker of er in het Design al een voorzet was voor de VAC. 
Maar er zijn 3 inhoudelijke properties die getoond moetn worden: 
- Vraag
- Antwoord
- Toelichting. 

Vraag en Antwoord zijn er altijd, Toelichting niet altijd. 
Vraag is de titel van het item. 
Lijkt mij zinvol om daaronder het kopje Antwoord te plaatsen, met de inhoud van antwoord
en daaronder het kopje Toelichting: 
- maar alleen 'als er een toelichting is
- en daar de tekst onder.

**Comment by mstokericatt** [comment]
besproken (sytske mark): er komt op het afhandelscherm een lijstje geraadpleegde bronnen, met daarin de kennisartikelen, websites en VAC's)

**Comment by mstokericatt** [comment]
wat doen we met de opmerking "Het is duidelijk voor een KCM dat de Toelichting interne informatie voor KCM's bevat". voorstel: niets, dat zou uit de inhoud moeten blijken.

**Comment by sytskevanhasselt** [comment]
Screenshot van de VAC over Klein chemisch afval, met daarnaast: de inhoud van het Object in de objectenregistratie


![Image](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/assets/53014699/d3cca810-154b-4cd0-b3e6-efbfe29dd286)

**Comment by guyharrisutrecht** [comment]
"Het is duidelijk voor een KCM dat de Toelichting interne informatie voor KCM's bevat"

Dit lijkt een requirement, geen acceptatiecriterium?

Ik neem aan dat de 'interne toelichting' mogelijk informatie bevat die niet aan de 'Klant' mag worden gegeven. Een 'requirement' om ervoor te zorgen dat dergelijke informatie niet aan de Klant wordt gegeven, kan worden opgelost door training (gezond verstand?) en/of een UX-element: bijvoorbeeld de 'Interne toelichting' gesloten laten totdat deze wordt geopend op standaard waarschuwingspictogram met uitleg ...

Ik zou dit promoten tot een Information Security requirement of het degraderen tot een notitie in de User Story, afhankelijk van wat het risico is dat een KCM informatie 'lekt' die in een 'toelichting' staat.
