### ISSUE TITLE
Taak: Inrichting voor Crawlen van de Gemeentelijke website (bijvoorbeeld Deventer) voor Producten en Nieuws

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#58]

**Comment by PascalIcatt** [comment]
Onderzoeken of we
- elastic crawler kunnen gebruiken of (Pascal & Robert)
- data mappen vanuit rss/soortgelijke feed (Robert & Pascal)
- kleine inventarisatie onder gemeentesites (Ruben)
-

**Comment by sytskevanhasselt** [comment]
Status = done
