### ISSUE TITLE
Uitzoeken: meerdere indexen bij Elastic - deel 1

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#583]
### Description

We willen uitzoeken of we de zoekresultaten uit Elasticsearch kunnen verbeteren, als we gaan werken met aparte indexen voor de 'API-bronnen'.
Doel is om te bewijzen dat het kan. We gebruiken de testdata uit de mock SDG en de objecten api. Om te queryen kan je gebruik maken van Postman. Om gegevens in te schieten is het wellicht handig om de ElasticSync applicatie aan te passen en lokaal te draaien.

### Estimate

36 uur

### Acceptance criteria
De volgende vragen zijn beantwoord, waarbij we stoppen zodra ergens blijkt dat het niet kan: 
- Kunnen we aparte indexen per bron maken in Elastic, en kunnen we die verschillende indexen (al dan niet gecombineerd) 'querien' vanuit de zoekbalk in KISS zoeken, [hier staat beschreven hoe]?(https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-multiple-indices.html).
- Kunnen we de onderliggende index van de crawler (in een aparte engine, let op NL) op een stabiele manier benaderen, zodat we die zoekresultaten kunnen combineren met de overige bronnen?
- "Voor de gestructureerde gegevens betekent dit dat we niet vanuit Kibana van relevance tuning gebruik kunnen maken, maar per bron kunnen we wel (in code) definiëren [welke velden belangrijk zijn](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/mapping-boost.html), en [de relatieve relevantie van de bronnen onderling](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-multiple-indices.html#index-boost) " schreef Felix [in Teams](https://icattnl.sharepoint.com/:w:/r/sites/ProjectenINTERN/Gedeelde%20documenten/Dimpact/KISS%20-%20ontwikkelen/DIM-KISS-BFF-23/Elastic/Onderzoeksvragen%20Elastic.docx?d=wc6d6c359b7d74562b87d8715c12e4904&csf=1&web=1&e=gVOzR3)
- Wat moeten we aanpassen in KISS frontend
- Wat moeten we aanpassen aan de handleiding / het configuratiescript voor elastic?

### Specific details

Zie ook de argumenten om met één index te werken: 

> De argumenten om alle bronnen in 1 engine/index te stoppen komt voort uit de volgende overwegingen:
> 
> - Aparte indexen hebben eigen endpoints en moeten apart aangeroepen worden
> - Zoekresultaten tonen voor meerdere indexen geeft complexiteit welke we zelf moeten oplossen zonder meta-engine
>   - Combineren van de zoekresultaten obv score
>   - Paginering over deze zoekresultaten
> - Toekomstige bronnen kunnen niet automatisch toegevoegd/ontsloten worden in Elastic
>   - Nieuwe endpoints voor het uitlezen moeten handmatig toegevoegd worden
> Bovenstaande zaken worden bij het gebruik van een meta-engine intern al geregeld.

**Comment by sytskevanhasselt** [comment]
Besproken (volgt)

**Comment by sytskevanhasselt** [comment]
Sent: Monday, July 18, 2022 13:21
Subject: RE: Elastic 
 
Goedemiddag,
 
De argumenten om alle bronnen in 1 engine/index te stoppen komt voort uit de volgende overwegingen:
- Aparte indexen hebben eigen endpoints en moeten apart aangeroepen worden
- Zoekresultaten tonen voor meerdere indexen geeft complexiteit welke we zelf moeten oplossen zonder meta-engine
  - Combineren van de zoekresultaten obv score
  - Paginering over deze zoekresultaten
- Toekomstige bronnen kunnen niet automatisch toegevoegd/ontsloten worden in Elastic
  - Nieuwe endpoints voor het uitlezen moeten handmatig toegevoegd worden
 
Bovenstaande zaken worden bij het gebruik van een meta-engine intern al geregeld.
 
Vanmiddag om 14:00 heb ik hier een overleg over met een Elastic architect.
Daarbij zal ook de optie van het gebruik van meerdere indexen besproken worden. Dit had ook onze voorkeur bij het gebruik van een meta-engine, we verkennen nu de andere opties.
 
Met vriendelijke groet,
 

Senior Developer
 
ICATT. menselijk digitaal.
Nieuwezijds Voorburgwal 120-126
1012 SH Amsterdam
+31 (0)20 521 3553

======== 
Verzonden: Monday, 18 July 2022 10:11

Onderwerp: Elastic
 
Goedemorgen,
 
Hierbij de reactie van Maykin
 

> Waarom willen jullie de informatie combineren in 1 index?
> Je kan prima met Elastic over meerdere indexes indexeren vanuit verschillende bronnen en tegelijkertijd doorzoeken. Je hoeft ze helemaal niet te combineren in 1 index om ze tegelijkertijd doorzoekbaar te maken, het kan wel maar dat werkt een stuk minder handig.
> Bovendien werkt Elastic prima met meerdere indexes over grote hoeveelheden documenten. We hebben bijvoorbeeld een applicatie op Kubernetes voor IenW draaien over 5 verschillende indexes met 1.8M documenten over deze indexes. Werkt als een trein.

**Comment by felixcicatt** [comment]
BEVINDINGEN

Code ingecheckt in storybranches voor zowel de Kiss frontend als de Sync Tool.

Elasticsearch 'vanilla'
- zoeken op meerder indices tegelijk kan, inclusief de index achter de crawler
- onderling prioriteren van indices in zo'n zoekopdracht is eenvoudig. als je dat instelbaar wil maken per gemeente kan dat, maar daar moeten we zelf een voorziening voor treffen, bv een tabel in de database + beheerscherm
- zoeksuggesties zijn nauwkeuriger te krijgen dan in app search, maar dat vereist configuratie per bron. deze configuratie hoeft wat mij betreft niet custom per gemeente
- diezelfde zoeksuggesties tonen voor de crawler is bewerkelijk, maar te doen
- wat nu precies de juiste soort zoekopdracht in elasticsearch is, is mij niet helemaal duidelijk.
  In versie 8 van elasticsearch kan je achterhalen wat de precieze zoekopdracht is die app search uitvoert in elasticsearch. dat zou flink helpen

Elasticsearch via een engine
- Geneste objecten zijn niet doorzoekbaar. Wat wel kan: plaatslaan. bv { "object.bevoegdeOrganisatie.naam": "Deventer" }
  Dat maakt de score van de objecten die we indexeren (dus niet de crawler) waarschijnlijk al een stuk beter
- In versie 8 van elasticsearch kan je een engine bevragen als ware het een gewone index. Dan kunnen we gebruik maken van een script_score om bijvoorbeeld een bepaalde bron hoger te scoren dan andere bronnen.

Voorgestelde vervolgstappen
- upgrade naar elasticsearch 8
- beide scenarios implementeren. voor het 'vanilla' scenario de configuratie nog niet beheerbaar maken maar afstemmen op onze testdata
- zoekresultaten en zoeksuggesties vergelijken

ter naslag, zo maak je een veld voor autocomplete aan en stop je daar de headings van geindexeerde webpagina's in:
```http
PUT /.ent-search-engine-documents-hier-naam-van-de-engine/_mappings
content-type: application/json
{
    "properties": {
        "_completion_all": {
            "type": "completion"
        },
        "headings": {
            "copy_to": "_completion_all",
            "type": "text",
            "index_options": "freqs",
            "analyzer": "iq_text_base"
        }
    }
}
```
