### ISSUE TITLE
Afdelingen en groepen ophalen m.b.v. Objecten API

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#590]
### Description

Als Applicatie KISS wil ik een lijst met afdelingen, en een lijst met groepen zodat ik die afdelingen/groepen kan gebruiken in de registratie van het contactmoment/contactverzoek. 

Deze story is de basis voor twee andere functionele behoeften: 
- ~Als KCM wil ik bij een Contactmomenten kunnen registreren voor welke afdeling het is afgehandeld, zodat ik dat kan doorbelasten~ _dit is vervallen: afdeling bij contactmoment komt uit kennisartikelen_
- Als KCM wil ik een Contactverzoek kunnen doorzetten naar een afdeling of een groep of een medewerker, zodat een andere collega in de organisatie het contactverzoek kan oppakken. 
  - Als KCM wil ik bij doorzetten van Contactverzoeken, als ik een afdeling heb gekozen, één van de onderliggende groepen kunnen selecteren
  - Als KCM wil ik bij het doorzetten van Contactverzoeken, als ik een afdeling of een groep heb gekozen, één van de bijbehorende medewerkers kunnen selecteren.

### Estimate

4

### Acceptance criteria

- Er is een testregister met Groepen en Afdelingen ingericht in het objecten register
- Dit testregister is te bevragen met Postman (voorbeelden van de calls zoals we die vanuit KISS gaan doen opleveren) : 
  - lijst afdelingen ophalen
  - lijst groepen ophalen o.b.v. afdeling id  
  - NB: voor de call op Medewerkers, moet eerst het Objecttype Medewerker worden aangepast. Dit doen we in story [Medewerker toevoegen aan contactverzoek obv lijst medewerkers #634](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/634)  

### Specific details

- Afdeling en Groep zijn elk een eigen Objectttype: 
  - Er is een objecttype voor Afdeling gedefinieerd; zie [schema in Teams](https://icattnl.sharepoint.com/:f:/r/sites/ProjectenINTERN/Gedeelde%20documenten/Dimpact/KISS%20-%20ontwikkelen/DIM-KISS-fase1c-23/040%20-%20Naslag%20Objecten%20en%20types/Afdeling%20en%20Groep?csf=1&web=1&e=PH9hcZ) (dit moet nog naar github)
  - UUID Afdeling: 9e102194-15d7-4909-9a8c-3d7115d4200a
  - Er is een objecttype voor Groep gedefinieerd; zie [schema in Teams](https://icattnl.sharepoint.com/:f:/r/sites/ProjectenINTERN/Gedeelde%20documenten/Dimpact/KISS%20-%20ontwikkelen/DIM-KISS-fase1c-23/040%20-%20Naslag%20Objecten%20en%20types/Afdeling%20en%20Groep?csf=1&web=1&e=PH9hcZ) (dit moet nog naar github)
  - UUID Groep: d57e4579-a0e7-4c79-9d6e-86f59b747b4f 
- Het objecttype van een groep bevat ook altijd een afdeling. 
- Er staan een aantal voorbeeld Afdelingen en Groep-objecten [in Teams](https://icattnl.sharepoint.com/:f:/r/sites/ProjectenINTERN/Gedeelde%20documenten/Dimpact/KISS%20-%20ontwikkelen/DIM-KISS-fase1c-23/040%20-%20Naslag%20[Objecten](https://icattnl.sharepoint.com/:f:/r/sites/ProjectenINTERN/Gedeelde%20documenten/Dimpact/KISS%20-%20ontwikkelen/DIM-KISS-fase1c-23/040%20-%20Naslag%20Objecten%20en%20types/Afdeling%20en%20Groep/Objecten?csf=1&web=1&e=zl99bM)%20en%20types/Afdeling%20en%20Groep/Objecten?csf=1&web=1&e=zl99bM). LET OP: er is één voorbeeld afdeling.json. Daarin moet nog de juiste Afdeling ID worden ingevuld. Dat kan pas als éérst de afdeling is aangemaakt. 
  - Daar staat ook een tekstbestandje met meer afdelingen en groepen

### Test plan

- Vraag een lijst Afdelingen op m.b.v. Postman
- Vraag een lijst Groepen op m.b.v. Postman

**Comment by sytskevanhasselt** [comment]
RF/RB/SvH: story nagekeken

**Comment by Astrid-Utrecht** [comment]
@sytskevanhasselt deze hebben we vorige week tijdens de ontwerpgroep besproken. Met name de langetermijn oplossing moet worden meegenomen. Maar voor nu was de oplossingsrichting die jullie hebben gepresenteerd werkbaar.  We hebben dit donderdag ook bij de gebruikersgroep getoetst. Afdeling is hoogste niveau, dan groep, dan medewerker. Medewerker kan in meerdere groepen zitten

**Comment by sytskevanhasselt** [comment]
Bijgaand twee keer het resultaat van een GET-call op de Objecten API. Bestanden de extensie .txt gegeven om te kunnen uploaden. 

- GET: alle objecten van het type Afdeling:
[response_get-objects-by-type_Afdelingen.json.txt](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/12370810/response_get-objects-by-type_Afdelingen.json.txt)

- GET: alle objecten van het type Groep:
[response_get-objects-by-type_Groep.json.txt](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/12370809/response_get-objects-by-type_Groep.json.txt)
