### ISSUE TITLE
Restyle doorvoeren

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#597]
### Description

Als KCM medewerker wil ik een consistente vormgeving van KISS.

### Estimate

9

### Acceptance criteria

**1. Algemene veranderingen**
- De interactieve knoppen met ronde hoeken zijn minder rond geworden: 7 px. Dit is gelijk aan de invulvelden.
- De knoppen "opslaan" en "Annuleren" zijn kwa grotote en vorm ook veranderd.
- De zoekbalken met ronde hoeken zijn minder rond geworden.
- De uitklapjes met ronde hoeken zijn minder rond geworden.
- Als je een uitklapje openklapt, zijn de afgeronde hoeken ook minder afgerond, zelfde afronding als de uitklapknop zelf. En er komt een rand omheen.
- De ‘uitloggen’ knop staat nu uitgelijnd met de menu items.
- Alle icoontjes (chevron, vergrootglas etc) hebben nu dezelfde grootte: 16 px.
- In de filters bovenaan: ‘Kennisartikel’ wordt ‘kennisbank’.
- De groene streep bovenin een contactmoment verdwijnt
- De volgorde en termen van het menu worden anders binnen een contactmoment. De volgorde: 
- Contacten (NIET-geauthenticeerde klant), Personen (Geauthenticeerde klant), bedrijven, zaken, nieuws en werkinstructies, links. (Dit gaaat alléén om de volgorde. Als de splitsing tussencontacten en personen nog niet is opgepakt, laten we het voor nu gewoon 'personen').

**Tabellen**
De interface van de tabellen is nu anders: 
- De kleur van de bovenste balk is lichter
- De tabel heeft nu om en om per rij een andere kleur, om meer onderscheid te maken tussen de rijen.
- De tabel bij “contacten” wordt korter, omdat daar alleen telefoonnummer en e-mailadres in staan.
- De volgorde van de tabelgegevens van het zoeken in de BRP verandert. De volgorde wordt: Naam; geboortedatum; postcode+huisnr; BSN; e-mailadres; tel. nummer

Schatting: 2 / 3 = 3

**2. Nieuws en werkinstructies**
- De titel verandert van 'Startscherm' naar 'Nieuws en werkinstructies'
- De informatiestructuur van de nieuws- en werkinstructiekaartjes is veranderd. 
- De “belangrijk” tag is veranderd kwa kleur en vorm
- De skilltags zijn veranderd: Het waren echt tags, het zijn nu gewoon woordjes. Zowel in de kaartjes als hoe ze onder de dropdown komen te staan.
- De hoeken van de kaartjes zijn nu volledig vierkant
- Als je een kaartje nu op “gelezen” zet, wordt hij ook iets korter (DESIGN TAAK nog even bespreken, maakt het wat onrustig) dan de openstaande kaartjes, zodat er visueel meer verschil zit tussen dichtgeklapte en opengeklapte kaartjes.
- De witruimtes tussen de kolom ‘nieuws’ en ‘werkinstructies’ is kleiner geworden. responsiveness nog uitwerken in het design design (DESIGN TAAK: erg wenselijk, geen must. pragmatische oplossing kiezen). 

Schatting: 2 / 2 = 2

**3. Linker contactmoment balk**
- De “afronden” knop verschuift naar beneden.
- Het kopje “vragen” wordt kleiner
- Het plusje dat staat voor ‘vraag toevoegen’ wordt verplaatst naar rechts van de cijfers.
- in plaats van icoontjes voor notitieblok en contactverzoek, worden nu de woorden ‘notitieblok’ en ‘contactverzoek’ gebruikt.
- Als er in het notitieblok niets geschreven staat, staat er cursief in het grijs: “Schrijf een notitie…”

**Personen, bedrijven, zaken zoeken**
-Je hebt nu meerdere zoekvelden: Elk zoekveld staat voor maar 1 term (bijvoorbeeld telefoonnummer. Of e-mailadres). Ook heb je nu een fysieke “zoeken” knop. 
DESIGN TAAK: toegestane combinaties bij personen zoeken zijn niet duidelijk

**Klantbeeld**
- De informatie die op het klantbeeld staat wordt onderverdeeld in tabjes. Deze tabjes verschillen per klantbeeld waar je inzit. De informatie zelf blijft hetzelfde.

Schatting: 1 / 2 = 2

**4. Kennisbank zoekresultaten**
- De tags bij de zoekresultaten zijn veranderd: Zowel vorm als kleur.
- De detailweergaven van een kennisartikel is ook veranderd: De tabs staan nu horizontaal boven de tekst en de achtergrond van de tekst + actieve tab is wit. Dit om het consistenter te maken met de tabjes van de klantbeelden.
- Rechts van het scherm verschijnt een pijltje wat naar boven wijst. Hiermee kan je het zoekresultaat scherm inklappen. Dit pijltje scrollt ook mee als jij naar beneden scrollt, tot het onderaan het artikel komt.
- Bij inklappen van de zoekresultaten is het nu duidelijker dat er is ingeklapt, en het ziet er minder stuk uit.

**Feedback op kennisartikel**
- De knop om feedback te versturen heet nu “opslaan”. Deze moet “verzenden” worden.

Schatting: 1 / 1 = 1

**5. Afhandelscherm**
-	De vinkjes zijn weg, er staat in plaats daarvan nu een prullenbakje. Als je een klant verwijderd, kan je dit ongedaan maken. De data van de klant blijft wel staan.
-	De geraadpleegde kennisbronnen komen allemaal bij elkaar te staan; Hierdoor bevatten ze nu wel hun bijbehorende tag, zodat alsnog duidelijk is waar ze vandaan komen. (DESIGN TAAK: wat zijn kennisbronnen? ook zaken, bedrijven etc. of alleen resultaten uit de bovenste zoekbalk) 
-	Ook zijn de gerelateerde bronnen om en om wit-grijs, net als de tabellen. 
-	De witruimte tussen  het label en het invulveld zijn kleiner.
-	 De term “specificatie” is veranderd naar “specifieke vraag”.
-	De volgorde van de in te vullen waardes is veranderd. De volgorde is nu:
o	Vraag
o	Specifieke vraag
o	Notitie
o	Afdeling
o	Kanaal
o	Afhandeling
o	Indien contactverzoek gemaakt:
	Afdeling
	Contactpersoon
	Bericht aan conractpersoon
(DESIGN TAAK: soms staan labels boven velden soms ernaast. het doel is duidelijk maar het resultaat is dat het er een beetje inconsistent rommelig uitziet)

Schatting: 1 /1 = 1

Zie ook de styleguide voor meer specificaties.

### Specific details

https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=171%3A1313&mode=design&t=mwmKpjYB7pKGPBDB-1

**Comment by sytskevanhasselt** [comment]
Deze is gesplitst naar:
- [Redesign doorvoeren - algemene veranderingen en tabellen #613](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/613)
- [Redesign doorvoeren - nieuws en werkinstructies #614](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/614)
- [Redesign doorvoeren - contactmoment balk, personen/bedrijven/zaken zoeken, klantbeeld #615](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/615)
- [Redesign doorvoeren - Kennisbank en feedback geven #616](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/616)
- [Redesign doorvoeren - afhandelscherm #617](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/617)

**Comment by Astrid-Utrecht** [comment]
AB - Deze is nog niet doorgevoerd in de dev. Kan dus niet testen

**Comment by sytskevanhasselt** [comment]
Dat klopt: allle info in deze story is verplaatst naar andere stories. Dus deze is nu overbodig en dubbel. 
ik haal 'm uit dit bord.

**Comment by Astrid-Utrecht** [comment]
AB - alleen uitgevraagde wijziging worden meegenomen. Overige onderaan de lijst. Akkoord splitsing
