### ISSUE TITLE
Zoekfunctie Elastic onafhankelijk maken van ingerichte webcrawler

### ISSUE THREAD

**Issue by ramonfasel** [Klantinteractie-Servicesysteem/KISS-frontend#599]
### Description

Het lijkt erop dat er foutmeldingen ontstaan als de web crawler nog niet is ingesteld. Dit geldt zowel voor de suggesties als de lijst met bronnen. We zouden 'm wat slimmer kunnen maken, dat-ie eerst checkt wat voor velden er beschikbaar zijn. Zie ook [https://stork.icatt.nl/DefaultCollection/ScrumProjects/_workitems/edit/9155](https://stork.icatt.nl/DefaultCollection/ScrumProjects/_workitems/edit/9155)

**Comment by sytskevanhasselt** [comment]
Is opgelost bij aanpassingen aan Synctool
