### ISSUE TITLE
Taak: owasp docker top 10 (https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html)

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#60]
inregeling is klaar. alleen nog vastleggen hoe we dit borgen in de toekomst. (security.md)

**Comment by rjzondervan** [comment]
Even de link hier klikbaar plakken

https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html

**Comment by Xiliath** [comment]
@rjzondervan Waar staat de security.md om te reviewen?

**Comment by rjzondervan** [comment]
Hi Pascal, zie bovenstaande PR (https://github.com/ConductionNL/commonground-gateway/pull/798)

**Comment by sytskevanhasselt** [comment]
Status niet helemaal duidelijk, maar we sluiten 'm toch
