### ISSUE TITLE
Elastic installatie heroverwegen na onderzoek

### ISSUE THREAD

**Issue by ramonfasel** [Klantinteractie-Servicesysteem/KISS-frontend#605]
### Description

Er zitten bij de installatie 2 scripts, die gaan over Elastic, 

- Het eerste script configureert Elastic: zorgt dat er een Engine is met de juiste naam. Maar ook: zorgt dat er een crawler voor een Website wordt ingericht. Welke website dat is, kun je bovenin het script instellen met een Variabele
  - Met dit script wordt dus voor BFF een crawler voor deventer aangemaakt en ingericht. 
- Het tweede script stelt de Relevance Tuning in
  - Vraag is of dat scriptmatig moet of niet
  - Daarbij: die kun je pas doen NADAT je de crawler hebt gedraaid, en medewerkers en/of kennisartikelen hebt geindexeerd: het gaat namelijk uit van Properties van de je geindexeerde 'documenten' die pas worden aangemaakt, als je webpagina's en medewerkers of kennisartikelen in je index hebt staan.

Vraag is even of / hoe dit hoort bij de Installatie van KISS, en welk deel daarvan hoort bij Implementatie

DAARBIJ: een Gemeente kan KISS willen gaan gebruiken, maar zonder website, of zonder medewerkers. IN dat geval zal dat Relevance Tuning script falen (hoewel dat bij Medewerkers wel mee valt, als je er maar Kennisartikelen bij hebt). 

Oplossing bedenken: tweede script uit installatie halen of conditioneel maken.

**Comment by sytskevanhasselt** [comment]
Deze is opgepakt: 
- inregelen engines gebeurt door sync tool
- relevance tuning staat beschreven in de handleiding, is in principe aan een gemeente
