### ISSUE TITLE
Taak: postman testset compleet

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#61]
- standaard postman testset generator toepassen

**Comment by rubenvdlinde** [comment]
Acceptatie critirium: Bij de gtihub  workflow staat een vinkje dat deze test is uitgevoerd.

**Comment by Xiliath** [comment]
@rubenvdlinde Waar kan ik deze testset vinden en controleren? Wordt deze nu bij elke build uitgevoerd?

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
