### ISSUE TITLE
Verplicht afdeling selecteren bij Contactmoment

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#611]
### Description

Als Manager KCC wil ik dat een KCM bij het afronden van een Contactmoment de afdeling moet selecteren voor wie het contactmoment is afgehandeld, zodat ik kan monitoren of het KCC de afspraken nakomt die per afdeling zijn gemaakt (zoals percentage zelf afgehandeld of doorverbonden, aantal telefoontjes dat namens de afdeling is verwerkt, etc.).

### Estimate

3 pt

### Acceptance criteria

- In het afhandelscherm is een lijst waarin een KCM de afdeling kan selecteren
- Dit is een verplicht veld. 
- Het gedrag van het veld: 
  - Als er bij het contactmoment een Kennisartikel of VAC is geselecteerd bij Vraag, dan wordt de Afdeling van dat Kennisartikel of VAC vooringevuld bij Afdeling
  - Als de KCM een ander Kennisartikel / VAC selecteert, wijzigt ook de keuze bij Afdeling
  - Als de KCM géén Kennisartikel / VAC heeft geselecteerd, dan moet de KCM zelf een afdeling kiezen. 
  - Als bij het Kennisartikel een afdeling hoort, die niet gematched kan worden met een afdeling in het Afdelingenregister, of die daar niet voorkomt, dan moet de KCM zelf een afdeling kiezen
- Bij het inzien van een Contactmoment (op klantbeeld of bij zaken) is de gekozen afdeling te zien, deze staat na de kolom Gespreksresultaat

### Specific details
- [Aanpassen structuur Kennisartikelen#642](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/642) moet zijn gedaan
- ~De items in de lijst Afdelingen worden opgehaald uit Elastic: de afdelingen bij Kennisartikelen en VAC's.~ De items in de lijst Afdelingen worden opgehaald uit de ObjectenAPI
- Dit veld wordt zo goed mogelijk vooringevuld o.b.v. de afdeling in het Kennisartikel of de VAC die is geselecteerd bij Vraag. Dit gaat o.b.v. 'best text match': als er een verschil in schrijfwijze is tussen de afdeling in de Objecten API, en de afdeling in Kennisartikel / VAC, dan kan het veld niet vooringevuld worden, en moet de KCM zelf een afdeling kiezen. 
  - NB: het veld afdelingen in Kennisartikel / VAC is een array. Op dit moment hebben alle VAC's en Kennisartikelen maar één Afdeling. T.b.v ontwikkeling en test is er aan twee Kennisartikelen van de afdeling Parkeren, een tweede afdeling toegevoegd.-
- Als er meerdere afdelingen zijn gekoppeld wordt de eerste gekoppelde gekozen
- ~Let op: er kunnen alleen afdelingen worden gekozen die gekoppeld zijn aan een kennisartikel~
- Het selectieveld Afdeling is een Auto Complete veld: tijdens het typen zie je steeds minder opties, zodat je makkelijk de juiste kan selecteren.
- De naam van de gekozen afdeling wordt opgeslagen in een nieuwe property, `verantwoordelijkeAfdeling`; zo is het ook zichtbaar in de managementinformatie.

### Test plan

- Maak een contactmoment aan, koppel dit aan een klant en aan een bron, zoek 3 kennisartikelen
- Rond contactmoment af, kijk of de juiste afdeling is geselecteerd.
- Overrule de afdeling door zelf iets te typen.
- Kies een ander kennisartikel bij de vraag en kijk of de bijbehorende afdeling wordt gekozen.
- Maak het veld leeg en controleer dat je niet kunt afronden (het is een verplicht veld).
- Rond het contactmoment af.
- Controleer bij het opslaan de Payload van postcontactmoment-call 
- Ga naar de [managementinformatie](https://dev.kiss-demo.nl/api/managementinfo/contactmomenten), en controleer of afdeling en resultaat te zien is bij je opgeslagen contactmoment
- Start een nieuw contactmoment op, zoek dezelfde klant op, en bekijk het zojuist aangemaakt contactmoment: hier zie je ook de Afdeling rechts naast het Gespreksresultaat in beeld.

**Comment by ramonfasel** [comment]
RF/SH/WB/HH: story nagekeken

**Comment by sytskevanhasselt** [comment]
Herschreven n.a.v. voortschrijdend inzicht
