### ISSUE TITLE
Redesign doorvoeren - algemene veranderingen en tabellen

### ISSUE THREAD

**Issue by GinaVerk** [Klantinteractie-Servicesysteem/KISS-frontend#613]
### Description

Als KCM medewerker wil ik een consistente vormgeving van KISS.

### Estimate

3

### Acceptance criteria

**Algemene veranderingen**
- De interactieve knoppen met ronde hoeken zijn minder rond geworden: 7 px. Dit is gelijk aan de invulvelden.
- De knoppen "opslaan" en "Annuleren" zijn kwa grootte en vorm ook veranderd.
- De knop "nieuw contactmoment" verandert van groen naar lichtblauw: Kleurcode is (#ACC8E5) / (RGB 172/200/229). De hover state heeft als kleurcode (#cfe4f7) / (RGB 207, 228, 247)
- De knop "Afronden" verandert van felrood naar lichtrood/zalmroze: Kleurcode is (#FF8585) of (RGB 255/133/133). De hover state heeft als kleurcode (#ffb8b8) of (RGB 255, 184, 184)
- De zoekbalken met ronde hoeken zijn minder rond geworden.
- De uitklapjes met ronde hoeken zijn minder rond geworden.
- Als je een uitklapje openklapt, zijn de afgeronde hoeken ook minder afgerond, zelfde afronding als de uitklapknop zelf. En er komt een rand omheen.
- De ‘uitloggen’ knop staat nu uitgelijnd met de menu items.
- Alle icoontjes (chevron, vergrootglas etc) hebben nu dezelfde grootte: 16 px.
- ~In de filters bovenaan: ‘Kennisartikel’ wordt ‘kennisbank’.~
_Dit is géén designwijziging, naam Kennisartikel grijpt in op Elasticinregeling / synctool; past niet binnen deze story_
- De groene streep bovenin een contactmoment verdwijnt
- Het menu-item Beheer is NIET zichtbaar binnen een Contactmoment
- De volgorde en termen van het menu worden anders binnen een contactmoment. De volgorde: 
  - Contacten (NIET-geauthenticeerde klant), 
  - Personen (Geauthenticeerde klant), 
  - Bedrijven, 
  - Zaken, 
  - Nieuws en werkinstructies, 
  - Links. (Dit gaaat alléén om de volgorde. Als de splitsing tussencontacten en personen nog niet is opgepakt, laten we het voor nu gewoon 'personen').

**Gedrag van de applicatie**
- De mogelijkheid om te refreshen moet geblokkeerd worden. (F5, refresh knop etc)
- Alle "< Terug naar...." knoppen moeten niet naar een vaste link gaan, maar altijd naar de laatst bezochte pagina. De linktekst wordt dan "< Terug"

**Tabellen**
De interface van de tabellen is nu anders: 
- De kleur van de bovenste balk is lichter
- De tabel heeft nu om en om per rij een andere kleur, om meer onderscheid te maken tussen de rijen.
- De tabel bij “contacten” wordt korter, omdat daar alleen telefoonnummer en e-mailadres in staan.
- De volgorde van de tabelgegevens van het zoeken in de BRP verandert. De volgorde wordt: Naam; geboortedatum; postcode+huisnr; BSN; e-mailadres; tel. nummer
- De data in de contactmomenten tabel is iets veranderd wanneer een contactverzoek is gekoppeld aan een zaak. Zie [Figma design](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=184%3A2925&mode=design&t=GslNSLZAp7GF5Ex6-1)

**Zaakscherm**
- De mogelijkheid om Toelichting bij een Zaak toe te voegen, moet weg. 
- De volgorde van de informatie die bij het tabje "algemeen" staat is veranderd. Zie [Figma design](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=184%3A3301&mode=design&t=GslNSLZAp7GF5Ex6-1)

Zie ook de styleguide voor meer specificaties.

### Specific details

-  Zie [Figma Design](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=171%3A1313&mode=design&t=mwmKpjYB7pKGPBDB-1)

### Test plan
 -  Controleer de acceptatiecriteria aan de hand van het design
 - Testdata: 
    - zoek personen, op 1074HK, huisnr 1, om de tabel zoekresultatn te zien.
    - zoek bedrijven op bedrijfsnaam: test
    - Zoek Suzannen Moulin, 01-12-1985; om door te klikken naar Zaken.

### Delivery notes
Naamwijziging naar Kennisbank liever los uitvoeren, daarvoor moet de Sync Tool aangepast worden en de bestaande engine weggegooid

**Comment by Astrid-Utrecht** [comment]
AB/MK ook hier graag de specifieke stories benoemen
