### ISSUE TITLE
Redesign doorvoeren - contactmoment balk, personen/bedrijven/zaken zoeken, klantbeeld

### ISSUE THREAD

**Issue by GinaVerk** [Klantinteractie-Servicesysteem/KISS-frontend#615]
### Description

Als KCM medewerker wil ik een consistente vormgeving van KISS.

### Estimate

2

### Acceptance criteria

**Linker contactmoment balk**
- De “afronden” knop verschuift naar beneden.
- Het kopje “vragen” wordt kleiner
- Het plusje dat staat voor ‘vraag toevoegen’ wordt verplaatst naar rechts van de cijfers.
- in plaats van icoontjes voor notitieblok en contactverzoek, worden nu de woorden ‘notitieblok’ en ‘contactverzoek’ gebruikt.
- Als er in het notitieblok niets geschreven staat, staat er cursief in het grijs: “Schrijf een notitie…”

**Klantbeeld**
- De informatie die op het klantbeeld staat wordt onderverdeeld in tabjes. 
- De verschillende onderdelen van het Klantbeeld staan onder Tabjes
  - Het eerste tabje is Contactgegevens, hierop staan e-mailadres en telefoonnummer
  - Het tweede tabje is BRP-gegevens, hierop staan de gegevens uit de BRP. Alleen beschikbaar bij KLANTen die gevonden zijn via BRP-ingangen
  - Het derde tabje is Contactmomenten
  - Het vierde tabje is Zaken. Alléén beschikbaar bij KLANTen die gevonden zijn via BRP-ingangen
  - Het vijfde tabje is Contactverzoeken.
- Deze tabjes verschillen per klantbeeld waar je in zit. De informatie zelf blijft hetzelfde.

Zie ook de styleguide voor meer specificaties.

**Zaakdetailpagina**
- het veld om toelichtingen toe te voegen is definitief weg, net als de knop die daar bij hoort. 
_dit was foutieve manier van 'notitie bij zaak toevoegen'_

### Specific details

- [Figma Design](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=546%3A3604&mode=design&t=J34bFwePpiy5nK8I-1)

### Test plan
 - Controleer KISS met de uitwerking in het design  voor de genoemde acceptatiecriteria

_No response_

**Comment by sytskevanhasselt** [comment]
Geschat als onderdeel van #597

**Comment by Astrid-Utrecht** [comment]
AB/MK volgens mij gaat dit om enkele bevindingen. Kunnen jullie aangeven welke specifieke userstories hieronder vallen?

**Comment by sytskevanhasselt** [comment]
RF/SH: story nagekeken
