### ISSUE TITLE
Redesign doorvoeren - Kennisbank en feedback geven

### ISSUE THREAD

**Issue by GinaVerk** [Klantinteractie-Servicesysteem/KISS-frontend#616]
### Description

Als KCM medewerker wil ik een consistente vormgeving van KISS.

### Estimate

1

### Acceptance criteria

**Kennisbank zoekresultaten**
- De tags bij de zoekresultaten zijn veranderd: Zowel vorm als kleur.
- ~De detailweergaven van een kennisartikel is ook veranderd: De tabs staan nu horizontaal boven de tekst en de achtergrond van de tekst + actieve tab is wit. Dit om het consistenter te maken met de tabjes van de klantbeelden.~
- Rechts van het scherm verschijnt een pijltje wat naar boven wijst. Hiermee kan je het zoekresultaat scherm inklappen. Dit pijltje scrollt ook mee als jij naar beneden scrollt, tot het onderaan het artikel komt.
- Bij inklappen van de zoekresultaten is het nu duidelijker dat er is ingeklapt, en het ziet er minder stuk uit.

**Feedback**
- De knop om feedback te versturen heet nu “opslaan”. Deze moet “verzenden” worden.
- De knop om feedback te versturen moet ook toegevoegd worden aan VAC.

Zie ook de styleguide voor meer specificaties.

### Specific details

-  Zie [Figma Design](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=171%3A1313&mode=design&t=mwmKpjYB7pKGPBDB-1)

### Test plan
 - Controleer de acceptatiecriteria aan de hand van het design

_No response_

**Comment by sytskevanhasselt** [comment]
Geschat als onderdeel van #597

**Comment by Astrid-Utrecht** [comment]
AB/MK Deze lijkt over F-11 te gaan, klopt dat?

**Comment by sytskevanhasselt** [comment]
Ja, dat klopt.

**Comment by ramonfasel** [comment]
RF/WB/HH: story nagekeken

**Comment by DeAstrid** [comment]
AB - Akkoord
