### ISSUE TITLE
Redesign doorvoeren - afhandelscherm

### ISSUE THREAD

**Issue by GinaVerk** [Klantinteractie-Servicesysteem/KISS-frontend#617]
### Description

Als KCM medewerker wil ik een consistente vormgeving van KISS.

### Estimate

1

### Acceptance criteria

**Tab contactgegevens (bij bedrijf en bij persoon) [bugfix]**
- het 'editknopje' om telefoonnummer / e-mailadres toe te voegen of aan te passen staat niet meer in beeld. 

**Afhandelscherm**
- ~De vinkjes zijn weg, er staat in plaats daarvan nu een prullenbakje. Als je een klant verwijdert, kan je dit ongedaan maken. De data van de klant blijft wel staan~.
- ~De geraadpleegde kennisbronnen komen allemaal bij elkaar te staan; Hierdoor bevatten ze nu wel hun bijbehorende tag, zodat alsnog duidelijk is waar ze vandaan komen (zie #616  voor de weergave van de tags)~
  - ~Kennisbronnen is alles dat via Elastic kunt vinden. Dus alleen zaken en Klant NIET~
  - ~De bronnen staan allemaal onder één kopje, maar zijn wel gegroepeerd. De volgorde is: VAC, Kennisartikel, website, werkinstructie, nieuwsbericht~
- ~Ook zijn de gerelateerde bronnen om en om wit-grijs, net als de tabellen.~ 
- De witruimte tussen  het label en het invulveld zijn kleiner.
- ~De term “specificatie” is veranderd naar “specifieke vraag”.~ (is al gedaan)
- De volgorde van de in te vullen waardes is veranderd. De volgorde is nu:
  - Vraag
  - _Specifieke vraag (Dit is al uitgevoerd in #610 )_
  - Notitie
  - Afdeling
  - Kanaal
  - Afhandeling
  - Indien contactverzoek gemaakt: de velden van het Contactverzoek
 

Zie ook de styleguide voor meer specificaties.

### Specific details
- LET OP: schermaanpassingen Contactverzoek wellicht even lostrekken (dus die bullets 'Indien contactverzoek gemaakt', en diens subitems)

-  Zie [Figma Design](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=518%3A2631&mode=design&t=J34bFwePpiy5nK8I-1)

### Test plan
 - Maak een contactmoment, zoek een aantal bronnen, klik op opslaan en controleer of de vinkjes zijn vervangen door prullenbakjes, controleer de werking
 - kijk of de bronnen gegroepeerd zijn in een blok
 - Controleer de schermen aan de hand van het design en de acceptatiecriteria

_No response_

**Comment by sytskevanhasselt** [comment]
@GinaVerk ik heb wat vragen opgenomen die we bij de Gebruikersgroep kunnen / moeten checken. Of weet jij het antwoord al?

**Comment by GinaVerk** [comment]
@sytskevanhasselt Nee ik weet het antwoord niet. Dus goed om te vragen donderdag inderdaad

**Comment by Astrid-Utrecht** [comment]
AB/MK volgens ons is er een uitspraak gedaan dat eerst kennisartikelen getoond moeten en dan web. Graag check op user-stories. Lijkt niet te kloppen. B-03 en B-04 lijken hier niet aan te raken. Ook notitie (F-12) lijkt hier niet in naar voren te komen.

**Comment by sytskevanhasselt** [comment]
**Besproken 20/7:** 
1. CHECK BIJ GEBRUIKERS: Kennisbronnen is alles dat via Elastic kunt vinden. Dus zaken en Klant NIET?
   -  er is wat twijfel over Medewerker. Tegelijkertijd is erg nog geen zicht op wat er daadwerkelijk gezocht gaat worden. Dus voorlopig doen we het idd zo. 
2. CHECK bij Gebruikers: kunnen de bronnen bij elkaar staan, of moet het door elkaar in volgorde waarin je ze zocht?
   - alles bij elkaar gegroepeerd heeft de voorkeur

**Comment by Astrid-Utrecht** [comment]
AB/ MK Akkoord

**Comment by ramonfasel** [comment]
RF/WB/HH: story nagekeken
