### ISSUE TITLE
Voorbereiden Testdata invoeren

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#619]
### Description

Als PO wil een meer relevante testset van bronnen zodat ik de werking van Elastic beter kan zien. Deel 1: voorbereiden aanlevering en import eerste input om te kijken of het werkt. (deel 2 Testbronnen inlezen #663)

### Estimate

2 punten

### Acceptance criteria

- In het testregister staan een aantal Kennisartikelen
- In het testregister staan een aantal VAC's, die overlap hebben met de Kennisartikelen
- In het testregister staan een aantal medewerkers, waarvan de afdelingen overlap hebben met de Kennisartikelen en VAC's

### Specific details

- Onderzoeken: kunnen we een format opstellen, waarmee gemeenten Nep Medewerkers kunnen aanleveren? 
  - eventueel: gegevens van bestaande medewerkers invullen, BEHALVE naam, e-mailadres en evt. telefoonnummer
  - Rest aanvullen met 'random naam generator'? 
- Idem voor Kennisartikelen
  - Aandachtspunt: de opmaak moet in HTML-code worden aangeleverd
- Idem voor VAC's  
  - Aandachtspunt: de opmaak moet in HTML-code worden aangeleverd

### Test plan

 - Verwerk een aantal testbestanden tot jason
 - Controleer de handleiding

**Comment by Astrid-Utrecht** [comment]
AB/MK loopt. Graag estimate en testplan toevoegen.
