### ISSUE TITLE
Taak: Oplossen vulnerability meldingen Snyk & andere tools

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#62]
todo: token beheer overleggen robert/pascal
todo: false positives vastleggen in security.md

**Comment by Xiliath** [comment]
@rjzondervan Waar staat de security.md om te reviewen? Staat daar ook een uitleg over het tokenbeheer?

**Comment by rjzondervan** [comment]
Hi Pascal, zie bovenstaande PR (https://github.com/ConductionNL/commonground-gateway/pull/798)

**Comment by sytskevanhasselt** [comment]
Status niet helemaal duidelijk, maar we sluiten 'm toch
