### ISSUE TITLE
Contactmoment sorteren

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#622]
### Description

Als KCM wil ik dat het meest recente contactmoment bovenaan staat, in lijsten waar contactmomenten getoond worden. 

### Estimate
2

### Acceptance criteria

- Op het klantbeeld staan de Contactmomenten gesorteerd op registratiedatum, de meest recente bovenaan. 
- Bij zaken staan de Contactmomenten gesorteerd op registratiedatum, de meest recente bovenaan

### Specific details

- Hiervoor gaan we de AANPASSINGEN gebruiken die Maykin heeft gedaan in de [Contactmomenten-](https://open-klant.dev.kiss-demo.nl/contactmomenten/api/v1/schema/) en [Klanten API](https://open-klant.dev.kiss-demo.nl/klanten/api/v1/schema/), zoals geïmplementeerd in Open Klant. 

### Test plan

- Start een Contactmoment, en zoek een klant op met een aantal Contactmomenten
- Controleer dat de Contactmomenten juist gesorteerd staan
- Zoek een ZAAK op (ZAAK-2023-001) en ga naar de tab Contactmomenten
- Controleer dat de Contactmomenten juist gesorteerd staan
- Rond het contactmoment af, zorg dat zowel de klant als de bekeken zaak zijn gekoppeld
- Sla het contactmoment op
- Start een nieuw contactmoment, zoek dezelfde klant op
- Controleer dat je zojuist aangemaakt contactmoment bovenaan staat
- Ga opnieuw naar de zaak ZAAK-2023-001
- Controleer dat je zojuist aangemaakt contactmoment bovenaan staat

**Comment by Astrid-Utrecht** [comment]
AB Bovengenoemde kan ik me in vinden

**Comment by ramonfasel** [comment]
RF/HH: story nagekeken

**Comment by sytskevanhasselt** [comment]
Deze story is afhankelijk van een restpunt van BFF, namelijk: het opslaan van Klantcontactmomenten zoals het hoort. Dit is weer afhankelijk van het upgraden van ons testregister

**Comment by RutgerICATT** [comment]
Testplan uitgevoerd: geen bevindingen. 
Extra test: Ook bij twee contactmomenten op dezelde dag komt de nieuwste bovenaan te staan.
