### ISSUE TITLE
Ongeauthentiseerd klantbeeld zoeken

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#623]
### Description

Als KCM wil ik dat als ik zoek op telefoonnummer of e-mailadres ik alleen Contactgegevens vind, die NIET gekoppeld zijn aan de BRP, zodat ik geen informatie zie die ik niet nodig heb voor het afhandelen van mijn Contactmoment.

### Estimate
8  

### Acceptance criteria

- Er is een zoekscherm, waar je personen zoekt op alleen telefoonnummer en/of e-mailadres
(_NIET-geauthentiseerde klantbeeld_)
  - Dit scherm staat onder menu-item "Contacten",
  - Je kunt zoeken op alleen e-mailadres, alléén telefoonnummer, maar ook op een combinatie
  - In het zoekresultaat toont géén KLANTen met een BSN opgeslagen bij KLANT (koppeling met BRP)
  - In het zoekresultaat staan de gegevens uit openklant. We gaan ervan uit dat dit alleen email en/of telefoonnummer zal zijn. We gaan geen klanten meer aanmaken vanuit kiss (tzt wel weer bij contactverzoeken, maar dat is hier out of scope en niet relevant). De verantwoordelijkheid van de inhoud ligt buiten KISS. We volgen de api specs en gaan ervan uit dat er geen andere data dan email/telnummer ingevoerd wordt en dat er uiteindelijk ook een aparte contactgegevens api hierop zal worden vastgesteld. Vooralsnog gebruiken we de klanten api en accepteren we de potentiele situatie dat er meer data dan alleen telnummer/email aanwezig zal zijn. Binnen de dev en prod omgeving beheren we zelf het bronregister en vullen dit uitsluitend met klanten die alleen een email en of telefoonnummer hebben.    
  - Het zoekresultaat is éérst gesorteerd op telefoonnummer, en daarna op  e-mailadres

-  Er is een scherm in KISS waar je kunt zoeken op persoonsgegevens: naam + geboortedatum, postcode + huisnummer, BSN (_Geauthentiseerde klantbeeld_)

    - Dit scherm staat onder menu-item Personen
    - Je kunt zoeken op 
      - alléén naam + geboortedatum, 
      - alléén postcode + huisnummer, en evt huisnummertoevoeging, 
      - of alléén BSN
    - Bij het invullen van de achternaam is duidelijk dat je dan ook een geboortedatum moet invullen
    - Bij het zoeken op achternaam is het mogelijk om alleen de eerste 3 letters van de achternaam in te vullen. 
    - In de lijst gevonden personen, staan alléén klanten met een koppeling met het BRP (BSN opgeslagen bij klant)
    - Het zoekresultaat is gesorteerd: 
      - Bij zoeken op Achternaam en geboortedatum:  op Achternaam;
      - Bij het zoeken op BSN: op Achternaam 
      - Bij het zoeken op Postcode huisnummer: op [huisletter + huisnummertoevoeging]

**Aanvullende criteria:** 
- Een KLANT uit het Klantenregister bevat nooit een NAAM. De naam van een persoon staat alléén in het BRP

### Specific details
- Manier waarop een KLANT wordt aangemaakt, obv van zoekresultaat alléén uit BRP moet dus worden aangepast: naam mag niet mee, alléén BSN
- het ophalen van een klant zonder bsn lijkt te kunnen met dit format: '.../api/v1/klanten?page=1&subjectType=natuurlijk_persoon&emailadres=aa@aa.nl&subjectNatuurlijkPersoon__inpBsn=null'
- Wanneer een persoon gevonden wordt, wordt in de huidige situatie, meteen een klantrecord aangemaakt en aangevuld met brp gegevens. Dat gaan we niet meer doen.
- De Haal Centraal API biedt géén mogelijkheid een sortering mee te geven. Maar: de HaalCentraal API levert nooit meer dan 10 resultaten. Dus die sorteren we binnen KISS zelf: 
  - Bij zoeken op Achternaam en geboortedatum: eerst op achternaam, dan op tussenvoegsel, dan op voornaam
  - Bij het zoeken op BSN: zelfde als hierboven
  - Bij het zoeken op Postcode huisnummer: eerst op adresregel 1, dan op adresregel 2, dan op adresregel 3, dan op achternaam, dan op tussenvoegsel, dan op voornaam

### Test plan
**Benodigde testset:**
 - Meerdere OA met hetzelfde e-mailadres of telefoonnummer
- OA en GA met zelfde e-mailadres of telefoonnummer
- Meerdere GA met het zelfde naam en geboortedatum (zit dit in de testset van BRP?)
- Meerdere GA met zelfde postcode huisnummer  (zit dit in de testset van BRP?)

**Ongeautoriseerde klant**
 - Controleer of het menu-item  "Contacten" alleen zichtbaar is als je een contactmoment hebt gestart
 - Zoek op telefoonnummer (ongeautoriseerde klant)
 - Zoek op e-mail (ongeautoriseerde klant)
 - Controleer dat in een zoekresultaat en het notitieblok nergens BRP gegevens tonen (naam, geboortedatum, postcode huisnummer)
 - Zoek op een niet bestaand telefoonnummer, e-mail adres, combinatie en controleer de terugmelding en foutmeldingen
 - Controleer de sortering van de zoekresultaten
 
 **Geautoriseerde klant**
 - Controleer of het menu-item  "Personen" alleen zichtbaar is als je een contactmoment hebt gestart
 - Controleer of je alleen kunt zoeken op  alléén naam + geboortedatum, alléén postcode + huisnummer, of alléén BSN
-  Controleer dat er in het zoekresultaat alleen geautoriseerde klanten staan
 - Kijk of het duidelijk is in de interface dat je na het invullen van een naam ook nog een geboortedatum moet invullen
 - Controleer of zoeken ook werkt met de eerste drie letters (met sterretje) en geboortedatum
 - Controleer bij zoeken op meerdere criteria of dit werkt op basis van AND-search
 - Controleer de sortering van de zoekresultaten

**Comment by sytskevanhasselt** [comment]
Deze moet eigenlijk opnieuw geschat: is alleen i.c.m. #624 geschat, en dat was in totaal 17.

**Comment by Astrid-Utrecht** [comment]
Ab/MK vanwaar eerst sorteren op mail ipv telefoonnummer? Lijkt logischer om om te draaien. Testplan ontbreekt nog.

**Comment by sytskevanhasselt** [comment]
Ik heb mail en telefoonnummer omgedraaid in de acceptatiecriteria

**Comment by Astrid-Utrecht** [comment]
AB op inhoud akkoord, testplan moet nog worden meegenomen.

**Comment by sytskevanhasselt** [comment]
Verwijzing naar F-04 opgenomen

**Comment by ramonfasel** [comment]
RF/SvH/HH: story nagekeken

**Comment by Astrid-Utrecht** [comment]
AB - er komen vervolgstories op dit onderwerp. Bovenstaande verder akkoord
