### ISSUE TITLE
Ongeauthentiseerd klantbeeld tonen [VERVALT?]

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#624]
### Description

Als KCM wil ik als ik iemand heb gezocht op telefoonnummer, géén BRP gegevens zien op dienst klantbeeld, zodat ik geen informatie zie die ik niet nodig heb voor het afhandelen van mijn Contactmoment.

### Estimate
7

### Acceptance criteria
- De verschillende onderdelen van het Klantbeeld staan onder Tabjes
- Het eerste tabje is Contactgegevens, hierop staan e-mailadres en telefoonnummer
- Het tweede tabje is BRP-gegevens, hierop staan de gegevens uit de BRP. Alleen beschikbaar bij KLANTen die gevonden zijn via BRP-ingangen
- Het derde tabje is Contactmomenten
- Het vierde tabje is Zaken. Alléén beschikbaar bij KLANTen die gevonden zijn via BRP-ingangen
- Het vijfde tabje is Contactverzoeken.
- In het contactmomentblok staat alleen een naam boven de notitie bij het klantbeeld als je heb gezocht naar geautoriseerde klanten via de knop BRP-gegevens. Bij zoeken naar ongeautoriseerde klanten via Contactgegevens staat hier niets

### Specific details
- Zie [Figma design](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=184%3A2311&mode=design&t=KrBCo4MMD2TjCYv9-1)

### Test plan
 - Klik op contactmoment starten
 - Klik op het menu Contacten
 - Zoek een OA
 - Klik op het zoekresultaat
 - Controleer of het klantbeeld uit de volgende tabjes bestaat: Contactgegevens, Contactmomenten, Contactverzoeken
 - Controleer de inhoud van de tabjes (contactverzoeken is nu nog leeg)
 - Sluit het contactmoment af
 - Klik op contactmoment starten
 - Klik op het menu Personen
 - Zoek een AG
 - Klik op het zoekresultaat
 - Controleer of het klantbeeld uit de volgende tabjes bestaat: Contactgegevens, BRP-gegevens, Contactmomenten, Zaken, Contactverzoeken
 - Controleer of de naam van de klant boven het notitieblokje staat bij GA klantbeeld en niet bij OG klantbeeld

_No response_

**Comment by sytskevanhasselt** [comment]
8 (was 17 samen met #623  moet opnieuw geschat)

**Comment by Astrid-Utrecht** [comment]
AB/MK Bovenstaande klopt. 

Note: Morgen moeten we in de ontwerpgroep het gegeven meldingen openbare ruimte kort bespreken. Bij sommige gemeenten is dit een zaak, echter deze moeten we kunnen opvragen via een e-mail /telefoonnummer. Ook een check bij de privacy officers in het volgend overleg.
