### ISSUE TITLE
pentesting (DAST)

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#63]
### Taken
- [x] Pentest inrichten
- [ ] documenteren hoe de pentest wordt uitgevoerd

**Comment by PascalIcatt** [comment]
Voorlopig gaan we dit periodiek handmatig uitvoeren, niet in de CI-CD straat

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
