### ISSUE TITLE
Medewerker koppelen aan afdeling / groep

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#634]
### Description

Als KISS wil ik dat het object Medewerker wordt aangepast, zodat ik de medewerker kan koppelen aan een afdeling of groep. 

**Achtergrond** op basis van de afdeling die aan de medewerker is gekoppeld, kan de KCM de juiste VragenSet selecteren, om het contactverzoek zo veel mogelijk al in te vullen (zie ook [#646 Eenvoudige vragensets beheren en gebruiken in een contactverzoek](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/646) en [#645 De juiste vragenset tonen obv afdelingen](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/645))

### Estimate

1

### Acceptance criteria
- Het object Medewerker is aangepast. 
- De medewerkerobjecten zijn aangepast aan de nieuwe structuur
- De synctool is bijgewerkt op de nieuwe structuur
- De weergave van een gevonden medewerker in het zoekpaneel is aangepast aan de nieuwe structuur. 
- de `identificatie` van  de medewerker wordt in de Actor opgeslagen bij het contactverzoek.

### Specific details

- De velden die de synctool in `titel` zet zijn op een iets andere plek in de structuur gekomen
- De Synctool moet de waarde van het veld ID nu opbouwen m.b.v. `identificatie`, omdat `id` is vervallen
- Het veld `identificatie` is ook op een andere plek in de structuur gekomen. Daar moet de functionaliteit rondom Contactverzoek voor Medewerker op worden aangepast.  

### Test plan
- zoek een medewerker op, en bekijk de details; controleer dat hier ongeveer de informatie staat, die er moet staan.
- maak een contactverzoek voor een medewerker, en controleer dat `identificatie` juist wordt overgenomen in de interneTaak.

_No response_

**Comment by sytskevanhasselt** [comment]
RF/SH story bekeken

**Comment by DeAstrid** [comment]
AB - Wanneer het gaat over het overnemen van de naam, dan is deze opgeleverd.
