### ISSUE TITLE
Contactverzoek opslaan als interne taak

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#636]
### Description

Als Ontwerpgroep KISS wil ik dat een Contactverzoek van KISS wordt opgeslagen als een Interne Taak die gekoppeld is aan een contactmoment, omdat we hiermee voorbereiden op de Klantinteracties-standaard die in ontwikkeling is. 

### Estimate

5

### Acceptance criteria
- er is een Objecttype Interne Taak.
- Er is een standaard formuliertje voor het aanmaken van een Contactverzoek
- In het formulier kun je de medewerker invullen
  - Medewerker is zoekveld waar mee je kunt zoeken in alle medewerkers (dit was al voorheen gebouwd)
  - Als ik een medewerker heb gezocht tijdens het contactmoment, dan wordt deze vooringevuld (de laatste).
- In het formulier kan je de gegevens van de Klant invullen. 
  - Velden: naam, e-mailadres en 2x telefoonnummer. Bij tweede telefoonnummer kun je een korte omschrijving opgeven
  - Klantvelden vooringevuld vanuit geselecteerde klant, maar kunnen overschreven
  - Contactverzoek voor een al bestaande / geselecteerde klant: gewijzigde contactgegevens alleen opslaan in Contactverzoek
  - Als geen klant geselecteerd, kan je alle velden vrij invullen. In dat geval wordt er een altijd een Klant aangemaakt (ongeacht of er een klant is met die contactgegevens) bij opslaan van de Interne taak en die nieuwe klant wordt gekoppeld aan het Contactmoment en de Interne taak. De contactgegevens worden opgeslagen bij het Contactverzoek én bij de Klant
- Toelichtingveld; hierbij is het duidelijk voor de KCM dat informatie in dat veld alléén bestemd is voor de collega's
- Je moet minimaal een contactgegeven (e-mail of telefoonnummer) , een Medewerker, en de Toelichting invullen.
- Het Contactverzoek wordt opgeslagen als interne taak, en gekoppeld aan het Contactmoment.

### Specific details
- zie Objecttype [ObjecttypeInterneTaak-schema-230811.json.txt](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/12320008/ObjecttypeInterneTaak-schema-230811.json.txt)
- zie [figma design](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=719%3A1300&mode=design&t=GslNSLZAp7GF5Ex6-1)
- Bij het opslaan van een Contactverzoek wordt er een interne taak aangemaakt in het Objecten-register
- Mapping gegevens: 
  - `toelichting`: notitietekst bij het contactverzoek
  - `medewerkerIdentificatie`, subproperties: Gegevens vd KCM die het aanmaakt
  - `actor.identificatie`: identificatie van de medewerker, of de afdeling
  - `actor.soortActor`: medewerker; als Afdeling of groep: organisatorische eenheid
  - `actor.naam`: de volledige naam van de mdw, of de naam van de afdeling of groep
  - `betrokkene.rol`: klant
  - `betrokkene.klant`: url van de klant voor wie contactverzoek is. Dit is
    - de door de KCM gekoppelde klant;
    - als geen klant gekoppeld: de klant die is aangemaakt bij het contactgegeven / de contactgegevens. 
  - `betrokkene.persoonsnaam`: voornaam, tussenv, achternaam van de Klant; 
  - `betrokkene.organisatie`: als de klant een bedrijf is: de naam van het bedrijf
  - `digitaleAdressen.digitaalAdres`: per contactgegeven een `digitaleAdressen.digitaalAdres.adres` aanmaken.
- Als er een Klant is gekoppeld, wordt het ID van die klant ook bij de Taak opgeslagen.
- MedewerkerID en Naam opgeslagen in Actor-velden
- De Interne Taak wordt gekoppeld aan het Contactmoment.
- Eerst het contactmoment opslaan dan het contactverzoek.
  - het contactverzoek wordt opgeslagen in Openobjecten als interne taak.
  - De url van het contactmoment wordt in de interne taak opgeslagen
  - Vervolgens wordt er ook nog objectcontactmoment in open-klant opgeslagen die verwijst naar het contactmoment en het interne taakobject 

### Test plan
- Start een contactmoment
- Zoek een testburger op zodat het contactmoment wordt gekoppeld aan die persoon
- Maak een contactverzoek
- Rond het contactmoment af
- Controleer in de Objectenregistratie of de interne taak is aangemaakt, en of de contactgegevens van de burger zijn opgeslagen en of de interne taak is gekoppeld aan het contactmoment
- Start een nieuw contactmoment zonder klant te zoeken.
- Zoek eerst een aantal Medewerkers, en maak een contactverzoek aan: controleer of de laatst bekeken medewerker vooringevuld staat in het Contactverzoek., rond deze af (vul dan klantgegevens in), controleer of er een nieuwe klant is aangemaakt.

_No response_

**Comment by ramonfasel** [comment]
RF/SvH/HH: story nagekeken

**Comment by sytskevanhasselt** [comment]
Afbeelding Contactverzoek op prod.kiss-demo.nl: 

![Image](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/assets/53014699/5ae00f83-1fe6-463f-a2c8-c7839ada80e1)

Afbeedling van het bijbehorende object in de Objectenregistratie: 

![Image](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/assets/53014699/207b69b5-bfa8-4de2-9715-0c8b87762275)
