### ISSUE TITLE
Redesign Klantbeeld Bedrijven

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#639]
### Description

Als KCM wil ik dat de opbouw van het Klantbeeld van een Bedrijf gelijk is aan de opbouw van het Klantbeeld van een Persoon, zodat mijn interface consistent is opgebouwd

### Estimate

1

### Acceptance criteria

- De verschillende informatie onderdelen staan achter tabjes
- Het eerste tabje is Contactgegevens, hierop staan e-mailadres en telefoonnummer
- Het tweede tabje is KvK-gegevens, hierop staan de gegevens uit de KvK. 
- Het derde tabje is Contactmomenten
- Het vierde tabje is Zaken. 
- Het vijfde tabje is Contactverzoeken.

-indien het heel eenvoudig te regelen is dan ervoor zorgen dat er alleen kvk resultaten **met** vestigingsnummer gevonden worden. Als dat complex is, aparte story aanmaken

### Specific details

- Aanname is: we gaan nooit werken met bedrijven als KLANT die zijn opgevoerd zónder koppeling met KvK
- Zie [Figma design](https://www.figma.com/file/09JW2ox3Tw1HCco0ySVOYB/Herontwerp-KISS?type=design&node-id=184%3A3301&mode=design&t=KrBCo4MMD2TjCYv9-1)

### Test plan
- Klik op contactmoment starten en klik op het menu-item "Bedrijven"
- Controleer of alle tabjes er staan in de juiste volgorde met de juiste inhoud

_No response_

**Comment by Astrid-Utrecht** [comment]
AB/MK Graag aangeven welke stories hieronder liggen zodat we kunnen toetsen. Heeft ook nog geen estimate.

**Comment by ramonfasel** [comment]
RF/HH: story nagekeken

**Comment by felixcicatt** [comment]
Vraag: wat doen we als een bedrijf (nog) geen contactmomenten / contactverzoeken / zaken heeft? Tonen we die tabs dan wel?
