### ISSUE TITLE
Aanpassen structuur Kennisartikelen

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#642]
### Description

Als KISS wil ik dat de structuur van Kennisartikelen wordt bijgewerkt naar de geupdate structuur, gebaseerd op SDG 1.7.2 én naar het toevoegen afdeling aan dit object, zodat ik aansluit op hernieuwde inzichten uit de Ontwerpgroep.

**Achtergrond**: zie eerste comment

### Estimate

ms/sh/jm = 3/3/3 = 3

### Acceptance criteria

- Er is een Objecttype Kennisartikel gedefinieerd dat bestaat uit de properties zoals gedefinieerd in de [SDG-Invoervoorziening API, versie 1.7.2](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/maykinmedia/sdg-invoervoorziening/1.7.2/src/openapi.yaml&nocors)
- Dat objecttype is aangevuld met de aditionele velden, zoals die in de ontwerpgroep zijn besloten
- Er zijn Objecten aangemaakt met testartikelen, volgens dit nieuwe Objecttype
- De Synctool is bijgewerkt met de nieuwe structuur
- De weergave van Kennisartikelen in KISS, bij bronnen zoeken, is bijgewerkt op deze nieuwe structuur. 

### Specific details
- Een overzicht van de structuurwijzigingen staat in het document  [Overzicht properties Objecttype PDC.docx](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/files/12410323/Overzicht.properties.Objecttype.PDC.docx)
- Het testregister voor Kennisartikelen wordt verplaatst naar de Objecten-api
  - Achtergrond: de Objecten API zou sowieso nodig zijn voor de aanvullende velden die KISS nodig heeft
  - Door het geheel te ontsluiten via de Objecten API wordt de complexiteit verminderd 
- De Synctool wordt aangepast, zodat Kennisartikelen uit het Objectenregister worden gehaald. 
- Het objecttype Kennisartikel bevat de SDG-1.7.2-velden (met soms aangepaste namen), plus de additionele velden die KISS nodig heeft. 
- de SD-plus onderdelen moeten worden opgeruimd

### Test plan

- zoek een kennisartikel op, en kijk in de Netwerk-tab of je de nieuwe structuur ziet. Dus: 
  - `vertalingen.trefwoorden` in plaats van `vertalingen.synonyms`
  - `afdelingen` als array erbij

**Comment by sytskevanhasselt** [comment]
**Achtergrond**<br />
- Binnen de ontwerpgroep is besloten dat we bij KISS, voor Kennisartikelen, uitgaan van een PDC-model dat is gebaseerd op SDG-Invoervoorziening 1.7.2, uitgebreid met de velden die horen bij de aanvullende informatiebehoefte van KISS. KISS is in fase 1B gebaseerd op SDG-Invoervoorziening-AI versie 1.3, dus er moet een update plaatsvinden. 
- Daarnaast is besloten dat we bestaande API's niet gaan aanpassen, maar dat de 'plus'-velden die nodig zijn voor KISS uit de Objecten API moeten worden opgehaald. 
- Naast de plus-velden die in Fase 1B zijn aangegeven, is besloten dat Afdeling een onderdeel moet zijn van het PDC-model. Dit gegeven hebben we nodig voor aanvullende stories in KISS, o.a. [Verplicht afdeling selecteren bij Contactmoment #611](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/611). In de informatieschets worden deze velden in de Objecten API geplaatst. Om complexiteit tegen te gaan, stellen wij voor om het hele Kennisartikel op te vragen m.b.v. de Objecten API. 

**Let op:** Als de invloed van de uitkomst van [Uitzoeken: meerdere indexen bij Elastic#583](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/583) duidelijk is, kan het zijn dat ook deze story moet worden bijgewerkt.

**Comment by sytskevanhasselt** [comment]
RF/SH bekeken

**Comment by Astrid-Utrecht** [comment]
Hier moet ik vanuit kunnen gaan, maar is niet te testen voor mij.
