### ISSUE TITLE
Afdeling / groep in Contactverzoek selecteren met Auto-aanvullen

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#644]
### Description

Als KCM wil ik makkelijk de juiste Afdeling of groep kunnen selecteren door een deel van de naam te typen, zodat ik sneller de juiste afdeling/groep heb gevonden

### Estimate

1

### Acceptance criteria

- De keuzelijst Afdeling (zie ook #633 ) is nu een zoekveld waarin je kunt typen, en terwijl je typt wordt de lijst met afdelingen kleiner: deze toont alle beschikbare afdeling waarin de getypte letters voorkomen. 
- De keuzelijst voor Groepen een zelfde soort veld. 

### Test plan

- Start een contactmoment, zoek een klant op, en maak een Contactverzoek aan
- Kies een afdeling uit de lijst Afdelingen: controleer de auto-aanvullen werking
- Kies een groep en controleer de auto-aanvullen-werking
- Rond het contactverzoek afen het contactmoment af.
- Start een nieuw Contactmoment, zoek de klant uit de vorige stappen op, en controleer dat de juiste gegevens van het Contactverzoek inzichtelijk zijn op het klantbeeld.
- Doe hetzelfde voor een Contactverzoek op Groep

**Comment by sytskevanhasselt** [comment]
RF/SH: story nagekeken

**Comment by Astrid-Utrecht** [comment]
Functie werkt, performance is even een vraag. Zit een kleine vertraging in
