### ISSUE TITLE
Claim voor medewerkeridentificatie configureerbaar maken

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#647]
### Description

Als gemeente wil ik bij de installatie van KISS kunnen configureren via welke Claim de Medewerkeridentificatie in OIDC meekomt, en of en vanaf hoeveel karakters deze afgekapt dient te worden, zodat er altijd voor kan zorgen dat het juiste gegeven daarvoor gebruikt wordt. 

Achtergrond van deze story: [Medewerkeridentificatie: welke claim uit OIDC #63](https://github.com/Klantinteractie-Servicesysteem/Ontwerp-1c/issues/63)

### Acceptance criteria
- in kiss-demo.nl bepalen we een claim uit de AD, die we via een Envrionment variabele configureren als medewerkeridentificatie. 
- Daarnaast configureren we via een Environment variabele of en vanaf hoeveel karakters deze claim afgekapt dient te worden
-  Bij de installatie van KISS kan een gemeente de naam van de OIDC-claim invullen, waar KISS de `medewerkerIdentificatie` uithaalt. 
- In de handleiding is beschreven waar dat moet, en wordt uitgelegd dat je in het geval van koppeling met Open Klant moet afkappen op 24 tekens. 
- De BFF zal die claim toevoegen bij registratie van het Contactmoment

### Specific details
- Uitgangspunt is dat de gemeente niet verplicht is gebruik te maken de [standaard JWT-claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) 
- Fallback-mechanisme als er geen claim is geconfigureerd in KISS is dat we terugvallen op dat wat we nu gebruiken: het e-mailadres
- oplossing implementeren voor het opslaan van de gegevens uit de claim en alleen de verwijzing naar die gegevens in de header mee te sturen.  

### Test plan

- Er wordt 2x getest, 1x met claim ingesteld en 1x zonder dat een claim is geconfigureerd.
- Start een contactmoment, en rond het af. 
- Controleer bij het opslaan dat niet (maar de nieuwe claim) of wel de eerste 24 tekens van het e-mailadres  in het veld `medewerkerIdentificatie.identificatie` staat (middels call postcontactmoment in de Netwerktab, tab Response in de dev console).
- Controleer de handleiding

### Tasks
- [ ] Code aanpassen
- [ ] Installatiehandleiding aanpassen

**Comment by ramonfasel** [comment]
RF/SH/HH/MS: story nagekeken

**Comment by DeAstrid** [comment]
AB - akkoord on hold. Meenemen bij implementatie. Tussentijds hebben we de 24 tekens email als identificatie medewerker

**Comment by sytskevanhasselt** [comment]
Bij ontwikkeling mee begonnen. We liepen tegen een issue met de omvang van het cookie aan. Omdat dit alleen goed testbaar is in een gemeentelijk landschap, hebben we deze niet afgerond.
