### ISSUE TITLE
Testbronnen inlezen

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#663]
### Description

Als PO wil ik een meer relevante testset van bronnen zodat ik de werking van Elastic beter kan zien. Deel 2: import en nabewerking alle input. 

### Estimate

1

### Acceptance criteria
- In het testregister staan minimaal Kennisartikelen (afhankelijk van wat gemeenten kunnen aanleveren)
- In het testregister staan ongeveer 250 VAC's, die overlap hebben met de Kennisartikelen
- In het testregister staan ongeveer 250 medewerkers, waarvan de afdelingen overlap hebben met de Kennisartikelen en VAC's

### Specific details

- Deze kan pas als we een register voor Kennisartikelen hebben in objecten #642
- Medewerker-structuur #634

### Test plan
 - Ga naar het objecten register en controleer bij VAC en bij Medewerkers of er ongeveer 250 objecten per register  in staan
 - Zoek in KISS op "Publiekszaken".

**Comment by sytskevanhasselt** [comment]
RF/SH story bekeken

**Comment by sytskevanhasselt** [comment]
Een overzicht van de aanwezige VAC's, Kennisartikelen en Medewerkers, staat in SAM

**Comment by DeAstrid** [comment]
AB - lijkt mij akkoord. Ik zie resultaten en ga ervan uit dat dit compleet is.

**Comment by sytskevanhasselt** [comment]
Deze is op een iets andere manier opgelost: er is voldoende testdata
