### ISSUE TITLE
Vooringevuldevraag instellen op laatst bekeken tab (F-19)

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#664]
### Description

Als KCM wil ik dat de laatste tab die ik heb aangeklikt in een kennisartikel vooringevuld is in het afhandelingsscherm, zodat ik zo min mogelijk nabewerkingstijd heb bij het afsluiten van het contactmoment.

### Estimate

2

### Acceptance criteria
- Van een kennisartikel staat in het afhandelscherm in de lijst: 
  - ~Alleen de titel~
  - Alleen de titel; deze staat gelijk aan de tab inleiding
  - ~Voor elke tab (dus óók de tab Inleiding): de titel van het kennisartikel, gevolgd door de titel van de tab~
  - Voor elke tab, behálve voor de tab Inleiding: de titel van het kennisartikel, gevolgd door de titel van de tab
- KISS houdt van Kennisartikelen nu ook bij welke tabs binnen een Kennisartikel zijn bekeken (aangeklikt)
- Deze tabs worden niet getoond in de lijst 'Bekeken bronnen': daar staat alléén de Titel van het Kennisartikel
- De logica van voorinvullen van het item VRAAG in het afhandelingsscherm wordt een kleine beetje uitgebreid: 
 Als het laatst aangeklikte kennisartikel een PDC bron is dan wordt de titel van het artikel _met_ de laatst aangeklikte TAB van dat artikel vooringevuld (Bomen kappen - Kosten)
- Als ik geen TAB in PDC artikel heb aangeklikt dan wordt de algemene de titel van het artikel vooringevuld (Bomen kappen)
- De KCM kan de voorinvulling altijd wijzigen. 

### Test plan
scn. 1: 
- Klik op nieuw contactmoment, en zoek een klant erbij (om later het opgeslagen contactmoment te kunnen inzien). 
- Zoek een kennisartikel
- Klik een TAB van het kennisartikel aan
- Klik op afronden en controleer of de juiste informatie is vooringevuld bij het item vraag (Titel kennis artikel - titel tab)
- Sla het contactmoment op
- Start een nieuw contactmoment, zoek dezelfde klant op, en controleer dat (Titel kennis artikel - titel tab) bij Vraag staat.

scn. 2
- Klik op nieuw contactmoment
- Zoek een kennisartikel
- Klik op afronden en controleer of de juiste informatie is ingevuld bij het item vraag (Titel kennsartikel)

sn3
- Klik op nieuw contactmoment
- Zoek in verschillende bronnen en klik verschillende artikelen aan
- Klik op afronden en controleer of de juiste informatie is ingevuld bij het items vraag (laatst aangeklikte bron)

### Delivery notes

- Het heeft grote impact om in de dropdownlijst bij Vraag: én een regel te hebben voor [Titel artikel] - Inleiding, én voor alléén [Titel artikel]. Dus dit hebben we niet uitgevoerd. Als je de Inleiding alleen bekijkt, of de inleiding als laatste bekijkt, dan staat alléén de titel van het artikel vooringevuld bij Vraag. 
- Op het moment dat je ín een kennisartikel zit, en je klikt dan op afronden, dan staat de laatste tab netjes vooringevuld. Maar: als je vervolgens teruggaat vanuit het Afhandelscherm, dan wordt je kennisartikel opnieuw geladen, en kom je weer in Inleiding. Als dan meteen weer naar het afhandelscherm gaat, staat dus alléén de titel vooringevuld. Om dit gedrag in het zoekpaneel aan te passen, heeft ook grote impact. Dus dit laten we voor nu bestaan als known issue.

**Comment by ramonfasel** [comment]
RF/HH/WB: story nagekeken
