### ISSUE TITLE
Vanuit KISS deeplinken naar een Zaak

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#671]
### Description

Als KCM wil ik vanuit het zaakdetail-scherm in KISS de zaak kunnen openen in het Zaaksysteem, zodat ik snel bij alle informatie van de zaak kan en de klant goed kan informeren. 

### Estimate

1 punt

### Acceptance criteria

- In het Zaakdetailscherm staat een knop, waarmee je de zaak in kwestie kan openen in het Zaaksysteem.
- Deze knop opent het Zaaksysteem, en meteen het scherm van de zaak in kwestie, in een nieuw venster. 
- Deze knop staat er niet bij gemeenten, die een zaaksysteem hebben dat géén deeplinks aan kan. 

### Specific details

- Randvoorwaarden:
  - Een gemeente heeft een zaaksysteem gebruikt dat deeplinks naar zaken mogelijk maakt. 
  - Deze deeplinks kunnen vanuit elke webapplicatie aangeroepen worden, mits deze webapplicatie maar wordt gebruikt binnen het gemeentelijke netwerk; wat je kan zien van zo'n zaak is verder afhankelijk van de rol die de KCM heeft in het Zaaksysteem. 
  - De Deeplinks kunnen in KISS worden opgebouwd o.b.v.:  
    - één Basis-url en 
    - één Gegeven van de Zaak uit ZGW, waarmee de zaak geidentificeerd kan worden (Zaaknummer of uuid). 
  - De basis-url én het gegeven uit ZGW kunnen bij installatie van KISS worden geconfigureerd. Indien niet geconfigureerd, dan geen link.

### Test plan

**Let op:** deze story is niet testbaar binnen de testregisters van kiss-demo.nl; dit omdat ons testregister voor zaken (open zaak) géén deeplink mogelijkheid heeft

**Comment by ramonfasel** [comment]
RF/WB/HH: story nagekeken

**Comment by DeAstrid** [comment]
AB - bij implementatie wordt deze getest / in gebruik genomen
