### ISSUE TITLE
Eenvoudige vragensets beheren voor Contactverzoek

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#687]
### Description

Als KCC wil ik vragensets kunnen beheren, om te gebruiken in Contactverzoeken, zodat de KCM's contactverzoeken kunnen maken, die al zoveel mogelijk specifieke informatie bevatten, zodat de collega's de klant beter kunnen helpen als ze contact opnemen.

### Estimate

4

### Acceptance criteria

- Een Redacteur (of een nieuwe rol?) kan in de beheeromgeving uit een lijst een afdeling selecteren, om bij die afdeling VragenSets (custom formulieren) aan te maken en te beheren
- Per afdeling kunnen er meerder custom formulieren gedefinieerd worden;
- Een formulier bestaat uit een platte lijst met een of meerdere vragen (geen logica).
- Elk formulier heeft een uniek onderwerp (vrij tekstveld).
- Er kan gebruik worden gemaakt van open vragen (text en textarea), en eenvoudige 'meerkeuzevragen' zoals optielijsten (drop down), radiobuttons en checkboxes.
- Bij een (meer)keuze geeft de redacteur de waarden in, waaruit een invuller kan kiezen; deze waarden worden als vaste statische lijst toegevoegd.
- Er is nog geen validatie mogelijk, ook geen verplicht-validatie
- De volgorde van de vragen kun je nog niet wijzigen
- Formulieren kunnen op elk moment verwijderd/toegevoegd/aangepast worden, en wijzigingen zijn zichtbaar, zodra een KCM een nieuw Contactmoment start.

### Specific details

- We slaan de formulierdefinities op binnnen KISS.

### Test plan

- Log in als Redacteur, ga naar het onderdeel Contactverzoekvragen
- Kies een afdeling, en maak een nieuwe vragenset aan, zorg dat van elk vraagtype een vraag in het formulier aanwezig is.
- Kies een andere afdeling en maak daarbij ook een nieuwe vragenset aan.
- Start een contactverzoek met de nieuwe vragenset (niet afronden).
- Pas de vragenset aan voltooi het eerder aangemaakte contactverzoek (deze bevat _nog niet_ de nieuwe vragen)
- Pas de vragenset aan en maak weer een nieuw contactverzoek,
- Verwijder de vragenset en verifieer dat bij het starten van een nieuwe contactverzoek dat je deze set niet meer kan selecteren.
- Maak tenslotten een contactverzoek aan, met het formulier met alle vraagtypes; vul alle vragen in. 
- Rond het contactverzoek af. 
- Start daarna nieuw contactverzoek en controleer dat alle antwoorden goed in de Toelichting staan.

**Comment by sytskevanhasselt** [comment]
Deze story is afgesplitst vanuit [Eenvoudige vragensets gebruiken in een contactverzoek#646](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/646). Die was in zijn geheel al ready bevonden door PO. Daarna opgesplitst. Dus deze ook ready gezet.

**Comment by DeAstrid** [comment]
AB - Akkoord
