### ISSUE TITLE
Definition of Done

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#71]
### Discussed in https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **sytskevanhasselt** May  3, 2022</sup>
In de projectaanpak staat onderstaande lijst voor de Definition of Done. 

- is van alles duidelijk wat dit concreet inhoudt?
- wat ontbreekt daar nog op, zeker vanuit het Ontwikkelteam.

- Accepatie creteria zijn afgevink door PO
- Coderen (ontwikkeling) is gereed
- - Code voorzien van automatische tests (alle shared code is voorzien van unit tests)
- - Code voorzien in incode  documentatie (b,v, docblocks en opmerkingen, code moet leesbaar zijn)
- - Code moet  gerviewd zijn door minimaal één andere developer 
- - Automatische tests moeten zijn uitgevoerd (als badges op  de readme)
- - - Unit Test
- - - Snyk (vulnerability en OWASP scanning)
- - - Docker vulnerablity check
- - - Bettercodehub (code quality)
- - - WCAG
- - - Pentests (frontend en backend) 
- Er is gecontroleerd op ongewenste variabelen (tokens etc) (kijken of hier een tool voor is)
- Handmatige checks zijn uitgevoerd
- De pentestresultaten van de vorige release zijn opgelost
-  Documentatie voor zowel engineer als eindgebruiker is gereed en beschikbaar 
gemaakt. 
- - Docs  zijn gupubliceerd op read the docs
- - Changes.md is aangevuld  met release notes aan de hand van symantic versioning
- - 

- [ ] Refactoren (Engels: refactoring) van de code is uitgevoerd indien noodzakelijk. 
Hiermee wordt bedoeld het herstructureren van de broncode van het geleverde stukje 
software met als doel de leesbaarheid en onderhoudbaarheid te verbeteren of het 
stuk code te vereenvoudigen. 
- [ ] UX (user experience) voldoet aan NL design system, gereviewd en geaccepteerd. 
- [ ] Code base voldoet aan het standardformaat van de gebruikte ontwikkeltaal en daarbij 
behorende conventies. 

- [ ]
- [ ] Testen is gereed (unit-testen, integratietesten, regressietesten, platformtesten en 
taaltesten). 
- [ ] Bugs zijn al tijdens de sprints opgelost. Release is bij oplevering door leverancier al 
technisch getest. Gebruikers doen alleen een test om na te gaan of de functionaliteit 
voldoet aan de behoeften. </div>

**Comment by mstokericatt** [comment]
de DoD staat nog in de discussions: https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/discussions/36 (en daar staat ook in waar we naartoe deployen) ,
misschien moeten we hem hier even weg halen. dit is verwarrend.

**Comment by PascalIcatt** [comment]
- Discussie sluiten en md bestand in root project
