### ISSUE TITLE
One of the tables in the documentation on readthedocs is broken

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [Klantinteractie-Servicesysteem/KISS-frontend#740]
**Describe the bug**
One of the tables in the documentation on readthedocs is broken.

**To Reproduce**
1. Go to https://kiss-klantinteractie-servicesysteem.readthedocs.io/en/latest/INSTALLATION/#configuratie-environment-variabelen

**Expected behavior**
Show a nice table

**Screenshots**
![image](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/assets/7829083/4f5d9582-177a-42d3-8858-fb48cb2875a0)

**Comment by sytskevanhasselt** [comment]
Thank you for reporting. We have fixed this.
