### ISSUE TITLE
Synctool naar Elastic moet ook opschonen

### ISSUE THREAD

**Issue by Astrid-Utrecht** [Klantinteractie-Servicesysteem/KISS-frontend#752]
### Description

Als Gemeente wil ik dat items in elastic ook verwijderd worden als ze niet meer relevant zijn, zodat ik geen verouderde informatie kan vinden

Op dit moment haalt de synctool alle items op uit een bron, voegt een aantal vaste properties toe aan het object zodat ze ook in Elastic unieke én stabiele identifers krijgen, en stuurt alles naar Elastic. o.b.v. de unieke, stabiele identifier worden bestaande items daarmee alleen maar geupdated. elke bron heeft hierbij een eigen index, en ook een eigen Engine

Het gevolg is dat als een item verdwijnt uit het onderliggende register (medewerker gaat uit dienst, een VAC bestaat niet meer), dan blijven deze items nog wel aanwezig in Elastic, en dus kan je informatie vinden in KISS die niet meer relevant of verouderd is. 

### Acceptance criteria

Als een item in Elastic niet meer aanwezig is in het bronregister, wordt het ook verwijderd uit de Elastic -index.

### Specific details

Er zijn twee mogelijke oplossingsrichtingen: 

1. De Synctool maakt steeds een nieuwe index aan. Als deze is opgebouwd wordt de bestaande engine van die specifieke index vervangen door de nieuwe. De oude index wordt weggegooid. Aandachtspunten: 
    - De bron-engine moet wel behouden blijven (die zorgt dat er een vinkvakje voor die betreffende bron is in de frontend). Nog niet duidelijk of je een bestaande engine aan een nieuwe index kan koppelen; 
    - de naam van de MetaEngine ligt vast: die moet zijn: "kiss-frontend"
    - het mechanisme moet om kunnen gaan (voorbereid zijn op) met nieuwe, nog aan te sluiten bronnen
2. Synctool wordt uitgebreid met een delete-schedule (kan mogelik op een andere frequentie liggen dan de andere cron):
    - Haalt identifiers uit Elastic op 
    - Haalt ID's uit de bron op
    - Vergelijkt die twee lijsten, en gaat op basis daarvan een aantal deletes uitvoeren op de betreffende index. 

Bij oppakken van de story bepalen we welke aanpak het beste / makkelijkste is, die de minste performance impact heeft. 

### Definition of Done

**Documentatie is bijgewerkt** 
- [ ] Readme ([Readme KISS](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/blob/main/README.md) ; [Readme Elastic-Sync](https://github.com/Klantinteractie-Servicesysteem/KISS-Elastic-Sync/blob/main/README.md) ; [Readme PodiumD Adaper](https://github.com/ICATT-Menselijk-Digitaal/podiumd-adapter/blob/main/README.md))
- [ ] Installation (voor [KISS in Installation.md](https://github.com/Klantinteractie-Servicesysteem/.github/blob/main/docs/INSTALLATION.md) ; voor [PodiumD Adapter in Readme](https://github.com/ICATT-Menselijk-Digitaal/podiumd-adapter/blob/main/README.md))
- [ ] Configuration (voor [KISS in Configuration.md](https://github.com/Klantinteractie-Servicesysteem/.github/blob/main/docs/CONFIGURATIE.md) ; voor [PodiumD Adapter in Readme](https://github.com/ICATT-Menselijk-Digitaal/podiumd-adapter/blob/main/README.md))
- [ ] Descicions (voor [KISS in Decision-record.md](https://github.com/Klantinteractie-Servicesysteem/.github/blob/main/docs/DECISION-RECORD.md) ; voor [PodiumD Adapter in Confluence](https://dimpact.atlassian.net/wiki/spaces/PC/pages/48758833/Decision+Record))  
- [ ] Testreport  (voor KISS: Toevoegen aan de root van de [KISS-frontend repository in Github](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend) ; Adater ??
- [ ] PodiumD Adapter documentatie (in [Confluence](https://dimpact.atlassian.net/wiki/spaces/PC/overview?homepageId=37716365))

**Overig**
- [ ] Er is vastgelegd welke calls er naar extern gedaan worden in de onder hande story, en in welke volgorde (nog afspreken: waar) 
- [ ] Regressietest (end-to-end-test) is bijgewerkt 
- [ ] Testbestanden, tijdelijke kopieën van databases, bestanden, tijdelijke clusters, etc zijn opgeruimd 
- [ ] Code staat op live, of er is een vervolg story op de backlog voor verdere afronding 
- [ ] Branches zijn opgeruimd

**Comment by mstokericatt** [comment]
todo
functioneel beheerhandleiding toevoegen aan de kiss documentatie, met daarin:
dat kiss bronnen synct met elastic.
hoe je een bron toevoegt en hoe vaak die gesynct wordt 
hoe je het resultaat van de synchronisatie kan achterhalen

**Comment by mariusvandam** [comment]
@sytskevanhasselt is deze niet al uitgevoerd?
