### ISSUE TITLE
Bedrijven zonder vestigingsnummer kunnen vinden

### ISSUE THREAD

**Issue by Astrid-Utrecht** [Klantinteractie-Servicesysteem/KISS-frontend#753]
### Description

Als Gemeente wil ik een klantbeeld kunnen inzien van bedrijven zonder vestigingsnummmer, zodat ik ook stichtingen en verenigingen als klant kan helpen.

In [Issue #158 van KISS](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/158) hebben we de aanname gedaan dat organisaties in het Handelsregister zonder vestigingsnummer, géén klant kunnen zijn, en dat alle organisaties altijd minimaal één vestiging hebben. Dit laatste blijkt niet het geval voor Stichtingen en Verenigingen. Dit betekent dat KISS ook om moet kunnen gaan met Klanten zonder vestigingsnummer. 

De huidige Klanten-API biedt die mogelijkheid wel: een klant kan van het type Vestiging, óf van het type Niet-Natuurlijke Persoon zijn. Die laatste hebben als identificerend nummer het RSIN van een organisatie. 
Hiervoor moeten we ook uitzoeken hóe we het RSIN kunne ophalen uit het Handelsregister.

### Acceptance criteria

- Als ik zoek in het Handelsregister, zie ik in KISS óók resultaten uit het Handelsregister, die geen vestigingsnummer hebben.
- Als ik een resultaat aanklik ga ik naar het klanbeeld van dat resultaat, daarop zie ik de gegevens uit het eigen gemeentelijke Klantenregister, en de gegevens uit het landelijke Handelsregister

### Specific details

- Op de pagina met zoekresultaten van bedrijven, tonen we alle resultaten van de call op zoeken-api van de KvK.
- Deze resultaten zijn met én zonder Vestigingsnummer
- Er is een kolom type toegevoegd, direct na de naam, daarin staat of het gaat om een Rechtspersoon, een Hoofdvestiging of een Nevenvestiging: 
- Als een resultaat een vestigingsnummer heeft dan gaat KISS op zoek naar een KLANT met `subjectType = vestiging`, en `subjectIdentificatie.vestigingsNummer = vestigingsnummer`. Als deze KLANT nog niet bestaan, maakt KISS deze aan met diezelfde gegevens.
- Als een resultaat géén vestigingsnummer heeft, dan gaat KISS op zoek naar een KLANT met `subjectType = niet_natuurlijk_persoon` en `subjectIdentificatie.innNnpId = RSIN`. Als deze KLANT nog niet bestaat, dan maakt KISS deze aan, met diezelfde gegevens. 

_No response_

### Test plan

- Ga in KISS, binnen een een contact, naar de tab bedrijven, en zoek op bedrijfsnaam = ‘test’
- Bekijk  het klantbeeld van alle resultaten. 
- Kijk of je een contactmoment kunt aanmaken voor een NNP-klant
- Kijke of je een contactverzoek kunt aanmakenn voor een NNP-klant.
- Kijk of je zaken kunt inzien van een NNP-klant 
  - Voorbereiding testdata: zorgen voor een ZAAK met een NNP-klant
- Kijk of je zaken kunt inzien, waarbij de NNP-klant een betrokkene is
  - Voorbereiding testdata: zorgen voor een ZAAK met een NNP-betrokkene

### Delivery notes

Op de Bedrijven-zoekpagina kun je ook zoeken naar bedrijven op telefoonnummer of e-mailadres. KISS zoekt hiervoor in de Klanten API, op contactgegeven. Het blijkt echter dat je in die API alleen kunt zoeken op één specifieke SubjectType. Je kunt dus niet zoeken op Klanten met subjectType = (vestiging óf niet natuurlijke persoon). 
Dit betekent dat je Bedrijven zonder vestigingsnummer NIET kan vinden op telefoonnummer of e-mailadres, alleen op KvK nr, naam of postcode + huisnr.

**Comment by sytskevanhasselt** [comment]
Deze story wordt opgepakt binnen het project van Dimpact om KISS aan te sluiten op de e-Suite. Daarom de story uitgebreid met de informatie uit dat project.

**Comment by sytskevanhasselt** [comment]
Bij het oppakken van deze story blijkt dat de versie van de Klanten API die KISS gebruikt, géén KvK-nummer accepteert in het property `subjectIdentificatie.innNnpId`. Daarom story aangepast: KISS slaat het RSIN van de Niet Natuurlijke Persoon op.

**Comment by sytskevanhasselt** [comment]
**Testbevinding:** 
- Zoeken op 'amsterdamse' vindt twee resulaten in https://dev.kiss-demo.nl/api/kvk/v2/zoeken?pagina=1&naam=amsterdamse
  - een rechtspersoon, met basisproffiel 
https://dev.kiss-demo.nl/api/kvk/v1/naamgevingen/kvknummer/90006186
  - en een Hoofdvestiging, met vestigingsprofiel https://api.kvk.nl/test/api/v1/vestigingsprofielen/990000996088
- In de response van api/kvk/v1/naamgevingen/kvknummer/90006186 staat: `"rsin": "999999999",`

Dus: de link naar het klantbeeld van deze rechtspersoon (NNP), is een POST naar de Klanten APi, met als Payload: 
`{
	"bronorganisatie": "999990639",
	"klantnummer": "zctWgqO4",
	"subjectIdentificatie": {
		"innNnpId": "999999999"
	},
	"subjectType": "niet_natuurlijk_persoon",
	"bedrijfsnaam": "Amsterdamse Stichting"
}`

MAAR: daarop geeft de Klanten API als response een 400, invalid input, met als reden: 
`"reason": "Onjuist RSIN nummer."`
Deze response komt uit het Register dat gebruikt wordt in de KISS-demo omgeving. Dat is Open Klant, [v0.5-pre]

Hoe groot is de kans dat de KvK een RSIN teruggeeft, die door het onderliggende als ongeldige RSIN wordt beschouwt?
