### ISSUE TITLE
Selectielijst beheren via admin-UI (Barry)

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#78]

**Comment by hannekevanderhorst** [comment]
BUG: 
Het lukt niet om een nieuw item toe te voegen. de submit knop wordt nooit actief

**Comment by bbrands02** [comment]
De knop om objecten te verwijderen is toegevoegd in het overzichtslijst van de objecten.

**Comment by sytskevanhasselt** [comment]
Status = done
