### ISSUE TITLE
Documentatie uitvoeren beheer selectielijsten (Lennard)

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#79]
Hieronder valt ook: 

- [ ] aanleveren van de URL van de beheer-interface van de gateway van DEV (https://kissdevelopment-frontend.commonground.nu/)

**Comment by sytskevanhasselt** [comment]
Wacht op implementatie nieuwe UI vd Gateway
