### ISSUE TITLE
Uitbreiding van /api/contactmomentendetails - II

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#798]
### Description

Als gemeente wil ik dat de Contactmomentdetails API is afgeschermd, zodat de data veilig overgehaald kan worden. 

**Achtergrond:**
 Op dit moment is de data van /contactmomentendetails benaderbaar, als je bent ingelogd op KISS, met de rol Redacteur. 

Op het moment dat externe systemen zoals een datawarehouse de data wil uitlezen, moet er een andere manier van authenticatie komen. 

Onderstaande is een voorstel uitgewerkt voor authenticatie m.b.v. een JWT Bearer Token. 

### Estimate

2

### Acceptance criteria

- De API is afgeschermd m.b.v. JWT  Bearer Token. 
  - Beide partijen hebben een secret, de afspraak over hoe het berichtje eruit ziet. 
- Deze aanpassing wordt alleen in de huidige KISS branch meegenomen. Indien deze ook voor Deventer al relevant wordt voordat deze over zijn op Open Klant 2.0 moet er een nieuwe story komen om Deventer branch aan te passen. 
- In de documentatie opnemen hoe de token opgehaald moet worden. 

### Specific details

- De bevragende applicatie moet een JWT-token kunnen generen. 
  - Dat betekent dat je altijd van uit een applicatie de data moet opvragen die dat kan.  
 - Omdat ICATT geen PowerBI heeft is de test het aantonen dat aan de hand van calls vanuit Postman de data opgehaald kan worden.

**Comment by pva-u** [comment]
Het JWT bearer token moet ook bij een centrale IDP (Entra ID - Enterprise applications) via oAuth 2.0 opgehaald kunnen worden door de client applicatie. De API dient de JWT bearer tokens van opgegeven IDP te vertrouwen en de claims te kunnen verwerken.

**Comment by sytskevanhasselt** [comment]
Bovenstaande opmerking van @pva-u zou een vervolg-story worden. We beginnen met de opzet zoals in deze story beschreven.
