### ISSUE TITLE
Klantcontact bij een ZAAK aanmaken > `onderwerpobject`

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#808]
### Description

Als KCM wil ik een klantcontact aan een Zaak kunnen koppelen, zodat alle betrokkenen bij die zaak kunnen zien dat er contact is geweest en wat daar is besproken. 

### Estimate

3

### Acceptance criteria
- Na opslaan van het Klantcontact kun je in OpenKlant bij het Klantcontact zien dat er een onderweprObject aanhangt. 
- Je hoeft na deze story nog geen twee zaaksystemen tegelijk te supporten (dat gebeurt in #873 en #904 ), maar het moet adhv een feature switch (implementeren als environment variabele) mogelijk zijn om OK2 of esuite+adapter hierbij te gebruiken. 
- Na deze story kun je maar 1 zaaksysteem koppelen aan KISS: ofwel een een zaaksysteem dat met OpenKlant2 kan praten, ofwel de e-Suite. 
- in de documentatie staat dit duidleijk uitgelegd
- In de documentatie staat hoe je de FeatureSwitch moet instellen op dit punt (dus: Klanten en klantcontacten in OK2 bij een zaak uit, OF klanten en contacten in e-Suite)

### Specific details
- Let op, oude code niet verwijderen: opslaan op de OK1 wijze (voor esuite+adapter moet mogelijk blijven)
- Het koppelen van een contactmoment en een zaak gebeurd op twee plekken: in het zaaksysteem en in openKlant. Dat eerste blijft technisch gezien ongewijzigd, Dat tweede werkt anders in OK2. Er moet een onderwerpObject aangemaakt worden van het type Zaak. Deze wordt gekoppeld aan het Klantcontact.
Dit werkt met een [`POST` op `/onderwerpobjecten`](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/maykinmedia/open-klant/2.1.0/src/openklant/components/klantinteracties/openapi.yaml#tag/onderwerpobjecten/operation/onderwerpobjectenCreate), met de volgende body
```
 {
  "klantcontact": {
    "uuid": [id van het bijbehorende contactmoment]
  },
  "wasKlantcontact": null [altijd null],
  "onderwerpobjectidentificator": {
        "objectId": [het uuid van de zaak. bijcvoorbeeld: 59a9b073-e21a-4249-97dd-02c4498d39a2],
	"codeObjecttype": "ZGW-Zaak" [vaste waarde],
	"codeRegister": "OpenZaak" [vaste waarde],
	"codeSoortObjectId": "uuid" [vaste waarde]
  }
}
```
  - Gebruik bij `objectId` en `codeSoortObjectId` gegevens die in OpenZaak gebruikt kunnne worden om een zaak op te halen. Mogelijk is dat niet identificatie maar uuid. 

- Voor de vaste waardes wordt wellicht tzt de referentielijsten api gebruikt. voor deze story is dat buitenscope. [opmerkingen over Refentielijsten API in slack](https://podiumd.slack.com/archives/C059ZJF5PMK/p1721554524451439) 

- NB: als het koppelen van meerdere zaken aan één klantcontact het werk complex maakt, dan beperken we het tot één. 

- achtergrond info:
Zie ook het onderdeel [Onderwerp van het klantcontact, in de Basisterminologie](https://github.com/VNG-Realisatie/klantinteracties/blob/cf57c15119cc15fbdf7fdc36e65c48a1bd602943/docs/basisterminologie.md#onderwerp-van-het-klantcontact)
![image](https://github.com/user-attachments/assets/efe61e43-ae7c-4b14-9354-92aa318f34aa)

**Comment by sytskevanhasselt** [comment]
Ik denk het wel, we gaan het hier bespreken (@mstokericatt). Dank voor de input.

**Comment by sytskevanhasselt** [comment]
Hoi @swrichards , 
Wij vroegen ons af of "bij welke API de zaak kan worden opgevraagd" niet volgt uit heet CodeRegister. 
Maar dat zou wel betekeken dat we, waar wij nu vaste waarde ZRC zetten, we daar een code moeten gebruiken voor het speccifieke zaaksysteem: e-Suite, OpenZaak, Roxit, etc.

**Comment by mstokericatt** [comment]
Ik ben het helemaal eens met het laatste voorstel
