### ISSUE TITLE
Klantcontacten bij een Zaak tonen

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#809]
### Description

Als KCM wil ik de klantcontacten die bij een Zaak horen, kunnen inzien op het scherm Zaakdetail, zodat ik weet wat er allemaal aan contacten is geweest over deze zaak. 

### Acceptance criteria

- het doel van deze story is het kunnen ophalen van klantcontacten uit OK2 bij een zaak uit OpenZaak. 
  - In het Zaakdetailscherm staan bij de tab Contactmomenten de Contactmomenten die horen bij die zaak
    - Ofwel: OK2+OpenZaak; Ofwel: e-Suite
  - Als een contactmoment aan een zaak is gekoppeld, zie je in de tab Contactmoment van een klantbeeld het Zaaknummer van de zaak, bij de details van het Contactmoment
  - Als zo'n contactmoment óók een Contactverzoek aan zich heeft, zie je in de tab Contactverzoek van een klantbeeld, óók het Zaaknummer van de zaak bij de details van het Contactverzoek
- Na deze story kun je nog steeds maar 1 zaaksysteem koppelen aan KISS: ofwel een een zaaksysteem dat met OpenKlant2 kan praten, ofwel de e-Suite (documentatie is uitgevoerd in [#808](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/808)). 
- Na deze story worden Contactmomenten opgehaald uit maar één register  (de bestaande code voor het ophalen van contactmomenten op de OK1 wijze moet dus in tact blijven)
- Het ophalen van deze gegevens uit esuite/adapter moet ook blijven werken, maar het is niet nodig meerdere zaaksystemen tegelijk te ondersteunen (dat gebeurt in #875)

### Specific details
- LET OP: welke contactmomenten bij een zaak horen halen we op uit het contactmomentenregister, niet uit het zakenregister. dat moet zo blijven.
- zie PC-316 / #808 voor informatie over hoe een zaak en een contactmoment aan elkaar verbonden zijn in OK2

**Scope van de werkzaamheden:**

- bij een persoon of bedrijf staat bij de contactmomenten het zaaknummer (als het contactmoment aan een zaak gekoppeld was)
- bij een persoon of bedrijf staat bij de contactverzoeken het zaaknummer (als het contactmoment aan een zaak gekoppeld was)
- bij een zaak staat bij de contactmomenten het zaaknummer

Deze drie werken allemaal op dezelfde manier met hetzelfde component en verwachten dezelfde input (zaakurl)
dit werkt waarschijnlijk allemaal al, maar dat weten we nu niet, want we kunnen nog geen contactmomenten opslaan met zaken in OK2 (pc-316 / #808 ) en voor OK1 werkt het weer als de featureswitch (PC-414 / #872 ) klaar is.

- Bij een persoon of bedrijf staat een lijst met alle zaken waarover die persoon contact heeft gehad. Dit blijft ongewijzigd; deze lijst is hetzelfde component als de zoekresultaten op de zaken pagina. ze linken ook beiden naar de detailpagina van /zaken

- De contactmomenten bij een zaak ophalen gebeurt via het contactmomenten register adhv de url van het zaakobject in het contactmomentenregister (useContactmomentenByObjectUrl) vanaf de zaakdetailview. deze moet dus obv de feature switch de contactmomenten anders ophalen en terugmappen naar hetzelfde model. dan werkt de zaak detailpagina. voor ok1 en ok2

Conclusie: waarschijnlijk volstaat het dus om alleen useContactmomentenByObjectUrl afhankelijk van de featureswitch de gegevens uit het andere register te laten halen

Voor de OK2 api betekent dit dat je het /onderwerpobjecten/?onderwerpobjectidentificatorObjectId =... opvraagt. Je krijgt dan het id  van de betrokkene waarmee je op dezelfde wijze als bij het ophalen van contactmomenten verder de contactmoment gegevens kan binnenhalen.

**Comment by mstokericatt** [comment]
@sytskevanhasselt is de opmerking over rol relevant? Dat gaat over hoe we de in het zaaksysteem gegevens ophalen. dat verandert niet in deze story.

**Comment by felixcicatt** [comment]
@sytskevanhasselt  @mstokericatt Ik zie dat we bij een klantcontact over een zaak alleen de guid van die zaak vastleggen als objectId. Hoe kunnen we dan achterhalen uit welk zaaksysteem die komt, zodat we informatie over de zaak kunnen tonen?

**Comment by sytskevanhasselt** [comment]
In #808 staat beschreven wat we vastleggen in een Onderwepobject. In de discussie eronder is vastgelegd hoe de ándere properties van het Onderwerpobjectidentificator hun waarde krijgen. In het [laatste comment van Sidney Richards](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/808#issuecomment-2357637675) staat vastgelegd wat we bespraken: Code Register verwijst naar het Zaaksysteem. 

Op dit moment schrijven we volgens mij in het Onderwerp object: `OpenZaak`. 
Ik weet alleen niet wiehoewatwaar kiss dan moet weten, dat 'ie in onze huidige installatie van OpenZaak moet zoeken. 

Ik zal dit nog met @mstokericatt  proberen te bespreken, wat we hiermee doen op het moment dat we #904 en #875 gaan oppakken.
