### ISSUE TITLE
optielijsten api endpoint beschikbaar stellen

### ISSUE THREAD

**Issue by PascalIcatt** [Klantinteractie-Servicesysteem/KISS-frontend#82]

**Comment by hannekevanderhorst** [comment]
[ ] Ik kan een nieuw item toevoegen maar hij verschijnt niet in de lijst, Heeft mogelijk te maken met rechten want ik (hanneke) iets aanmaken wordt owner niet ingevuld
[ ] Ik kan geen optie verwijderen

**Comment by sytskevanhasselt** [comment]
Status = done
