### ISSUE TITLE
Helderheid  over versienummers

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#821]
### Description

Als Ontwikkelaar van ICATT wil ik een duidelijke richtlijn hebben rondom versienummering van KISS en omgang met releases, tags en packages, zodat ik weet hoe we tewerk willen gaan als we versies van KISS willen gaan aanbieden

### Estimate

16 uur spike

### Acceptance criteria

- Als iemand KISS wil gaan installeren, kan die duidelijk zien welke versies er zijn. per versie wil je kunnen zien:
  - waar de package (en eventuele andere benodigde installatiebestanden) te vinden is
  - welke code gebruikt is voor deze release (bijvoorbeeld adhv een verwijzing naar een tag of commit. uitzoeken wat handig/gebruikelijk is)
  - waar de bijbehorende documentatie te vinden is 
    - nb. dat wil niet per se zeggen dat elke release eigen documentatie heeft, er kan best overlap zijn, zolang dan maar binnen de documentatie duidelijk is of iets op alle of bepaalde specifieke versies betrekking heeft. hoe we dit aanpakken hangt ook van de mogelijkheden af: zoek uit of we ook Versies van Read the Docs willen/kunnen aanbieden
  - wat de verschillen zijn (release notes). nb. het gaat vooral om breaking changes. een (handmatige) summary van belangrijke nieuwe features zou ook fijn zijn en is waarschijnlijk veel nuttiger, dan en eindeloze lijst commitmessages

- In de readme van KISS is vastgelegd wat je moet doen om een nieuwe versie te maken
- in de installatiehandleiding is vastgelegd wat je moet doen om een specifieke versie te installeren en hoe je de versies vind
 

- Als de uitkomsten van deze story gevolgen hebben voor ons werkproces, dan is dat vastgelegd en gedeeld.
- We weten wat daarvan de gevolgen zijn voor de gemeentes die al KISS hebben draaien.  
- We weten wannéér we een nieuwe versie maken. vastleggen in de readme van kiss

### Specific details
- belangrijk: de focus ligt NIET op automatiseren!!!. eerst maar eens gewoon bekijken wat het proces zou moeten zijn, en handmatig releases kunnen aanmaken en handmatig voorzien van de benodigde gegevens.
- hoe er rekening mee dat KISS bestaat uit meerdere repositories (kiss front-end, synctool, .github, ..?)  in hoeverre is versie beheer voor elke repo relevant? hoe hangen verschillende versies van de verschillende repo's samen? neem dit mee in de story.
- de adapter laten we buiten scope. we verachten daarop geen doorontwikkeling. hooguit bugfixes, waarbij je dus altijd de laatste versie wil.

### Delivery notes

De uitkomst van de Spike staan:
[Versiebeheer.md in .github](https://github.com/Klantinteractie-Servicesysteem/.github/blob/main/Versiebeheer.md)

**Comment by mstokericatt** [comment]
zie https://dimpact.atlassian.net/browse/PC-239
