### ISSUE TITLE
Implementatie referentielijsten API

### ISSUE THREAD

**Issue by RutgerICATT** [Klantinteractie-Servicesysteem/KISS-frontend#841]
### Description

Als PO van KISS wil ik dat KISS gebruik kan maken van de Referentielijsten API om te zorgen dat binnen een gemeente op alle plekken binnen het PodiumD landschap dezelfde begrippen worden gebruikt. 

### Specific details

REDOC van de API: https://github.com/maykinmedia/referentielijsten

**Comment by sytskevanhasselt** [comment]
Deze gaan we voorlopig niet doen. Dus ik sluit dezen
