### ISSUE TITLE
Nieuwe Partij registreren, Bedrijf

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#847]
### Description

Als KCM wil ik dat KISS een nieuwe partij kan registreren, zodat ik een klantbeeld kan maken/inzien voor bedrijven uit het Handelsregister die nog niet in OpenKlant 2.0 staan.

### Acceptance criteria

- Van gevonden bedrijf wordt gecheckt of er al een Partij bestaat:
  - van Vestigingen met het gevonden vestigingsnummer + KvK-nummer.
  - van resultaten zonder vestigingsnummer (Niet-natuurlijke personen) met het gevonden rsin + KvK-nummer
- Als er nog géén Partij bestaat met een van de bovenstaande combinaties, dan maken we een partij aan.
- Alle gebruikte vaste waardes, zoals 'vestigingsnummer', 'rsin', 'kvk-nummer' en 'telefoonnummer' zijn gedocumenteerd in https://klantinteractie-servicesysteem.readthedocs.io/en/latest/DECISION-RECORD/
- nb. het gaat hier alleen om het aanmaken van de klant, niet om het terugvinden en inzien van die gegevens
- aan de DoD is voldaan: https://icattnl.sharepoint.com/:o:/r/sites/ProjectenINTERN/Gedeelde%20documenten/Dimpact/Projecten%20Dimpact%20Notitieblok?d=w51e8cd12d22642b5b3a9cc922eff44f2&csf=1&web=1&e=elb2cR

als je obv vestigingsnr of rsin niet gevonden wordt dan maken we een nieuwe aan 
als je obv rsin of versitignsnr wel gevonen wordt en er hangt geen kvk aan dan voegen we die toe
als je obv rsin of versitignsnr wel gevonen wordt en er hangt een ander kvk aan dan:
  of kvk toevoegen. risico is dat er ergens een fout is gemaakt en we tenonrechte data van verschilledne bedrijven samenvoegen en moelijk een data lek creeeren
  of  als hele nieuwe partij opvoeren, maar dan krijg je duplicaat rsins of vesitigensnummer, zodat we bij een volgend contactmoment niet meer kunnen bepalen welk record het juiste is.
  dus hier is een signalereing nodig . todo: story opstellen (mogelijk bij openklant om unieke waardes af te dwingen) 
conclusie: in dat geval geen partij en partijidentificatoren opslaan, een melding tonen voor de kcm en ervoor zorgen dat de kcm het CM/CV verder als anoniem CM/CV kan voltooien

### Specific details
- Een Klant is in OpenKlant 2.0 een Partij bestaande uit een Partij en een of meerdere PartijIndicatoren. 
  - POST partij
    - `null` bij: `digitaleAdressen` , `voorkeursDigitaalAdres`, `rekeningnummers`, `voorkeursRekeningnummer`
    - `"soortPartij": "organisatie"`
    - `"indicatieActief": true`
    - `"indicatieGeheimhouding": false` gebruiken we (nog) niet binnen KISS, tenzij we uit de reeds gebruikte BRP call een gegeven terugkrijgen wat hier ondubbelzinnig op mapt, zetten we dit default op false
    -  de overige velden spreken waarschijnlijk voor zich en kunnen tijdens de realisatie verder uitgewerkt worden 
  - POST partij indicator > vestiging
    - partijIdentificator__codeObjecttype=vestiging (vast)
    - partijIdentificator__codeRegister=handelsregister (vast)
    - partijIdentificator__codeSoortObjectId= vestigingsnummer (vast) 
    - partijIdentificator__objectId=123456789012 (de waarde van het vestigingsnummer)
    - zie hiervoor ook #807, de waardes voor de vaste velden moeten gelijk zijn met wat er in die story beschreven is. 
  - POST partij indicator > nietNatuurlijkPersoon
    - partijIdentificator__codeObjecttype=nietNatuurlijkPersoon(vast)
    - partijIdentificator__codeRegister=handelsregister (vast)
    - partijIdentificator__codeSoortObjectId= rsin 
    - partijIdentificator__objectId=123456789 (de waarde van het rsin)
  - POST partij indicator > nietNatuurlijkPersoon OF vestiging
    - partijIdentificator__codeObjecttype=nietNatuurlijkPersoon OF vestiging (vast)        
    - partijIdentificator__codeRegister=handelsregister (vast)
    - partijIdentificator__codeSoortObjectId= KVK-nummer
    - partijIdentificator__objectId=123456789 (de waarde van het KvK-nummer)
    nb. de naam van de indicator/objecttype is hier niet eenduidig. we volgen de omschrijving van de KvK website: "_In het Handelsregister staan alle bedrijven en organisaties .._"
    - zie hiervoor ook #807, de waardes voor de vaste velden moeten gelijk zijn met wat er in die story beschreven is. 
  - Mogelijk wordt in de toekomst de Referentielijsten api gebruikt voor dergelijke vaste gegevens, maar dat valt ver buiten de scope van deze story.

**Comment by felixcicatt** [comment]
Vraag: hoe doen we dit voor niet-natuurlijke personen als gemeentes met de e-suite werken? Dan gaat de e-suite klantgegevens synchroniseren met OpenKlant2.0, maar betekent dat dat de e-suite moet gaan mappen van rsin naar kvknummer? Of moeten we in dat geval zelf regelen dat er een kvknummer gekoppeld wordt aan de Partij

**Comment by mstokericatt** [comment]
> Vraag: hoe doen we dit voor niet-natuurlijke personen als gemeentes met de e-suite werken? Dan gaat de e-suite klantgegevens synchroniseren met OpenKlant2.0, maar betekent dat dat de e-suite moet gaan mappen van rsin naar kvknummer? Of moeten we in dat geval zelf regelen dat er een kvknummer gekoppeld wordt aan de Partij

in welke mate hier rekening mee gehoudenis bij de e-suite <> openklant sync en of dat voor problemen gaat zorgen weten we niet. zo ja, dan kunnen wij daar mogelijk nog wel iets in betekenen in de adapter. @sytskevanhasselt, @RutgerICATT  bespreken jullie dat met andy? 
wat we in ieder geval kunnen doen is altijd zowel het kvkvnummer als vestigingsnummer/rsin op te slaan bij een partij (dat kan in OK2). Baat het niet dan schaadt het niet.
