### ISSUE TITLE
Taak: Unit tests voor wordpress plugins

### ISSUE THREAD

**Issue by rjzondervan** [Klantinteractie-Servicesysteem/KISS-frontend#86]
Ruben maakt documentatie af. 
Als klaar: via teams vragen wie er van Icatt mee kan kijken

**Comment by rubenvdlinde** [comment]
We zien het PUB register (in dit geval wordpress) als onderdeel van het externe ecosysteem en daarme out of scope

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
