### ISSUE TITLE
Maar één zaak kunnen koppelen aan één contactmoment

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#863]
### Description

Als KCM wil ik dat, als ik meerdere zaken heb bekeken tijdens het contactmoment, ik toch altijd maar één zaakaan mijn contactmoment kan koppelen, omdat één contactmoment maar over één ondewerp kan gaan.

Achtergrond:
Alle zaken die je hebt bekeken tijdens een klantcontact zijn zichtbaar op het afhandelscherm en ze zijn ook allemaal aangevinkt. Op dit moment is het mogelijk meerdere zaken aan één contactmoment te koppelen. Maar dat is niet wenselijk: één contactmoment moet maar over één onderwerp  gaan, en als dat een zaak is, moet het ook maar over één zaak gaan. Als de vraag van een klant over meerdere zaken gaat, dan zal een KCM meerdere vragen moeten aanmaken tijdens het contactmoment.

**Comment by mariusvandam** [comment]
Als ik het goed begrijp wordt elke aparte vraag in KISS als apart contactmoment opgeslagen, correct?

**Comment by sytskevanhasselt** [comment]
Ja dat klopt. Als je, binnen de je Contactmoment, meerdere vragen aanmaakt, dan wordt elke vraag een eigen contactmoment

**Comment by sytskevanhasselt** [comment]
* Deze wordt meegenomen in #873
