### ISSUE TITLE
Implementatie herontwerp Bedrijven zoeken

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#880]
### Description

Als KCM wil ik dat het scherm voor zoeken van bedrijven er net zo uitziet als het zoeken naar Personen, zodat ik een consistente interface heb. 

**Achtergrond:**
In een eerdere fase is de aanpak van Personen Zoeken gewijzigd, hierbij is Bedrijven zoeken over het hoofd gezien. Bij het ontwerp voor personen (#706) is bedrijven ook meegenonemen. 

### Acceptance criteria

- het scherm voor zoeken bedrijven is aangepast zoals in het ontwerp (zie [Figma link](https://www.figma.com/design/G44nNKeLweTPgm2ymaGNas/NIEUW-ONTWERP?node-id=193-637&t=4HpuDdlZVCgQwuJ8-1))
- het zoeken op telefoonnummer of e-mailadres komt te vervallen.
- Het zoekveld dat voorheen alleen voor KvK was, kun je nu gebruiken om te zoeken op KvK-nummer óf vestigingsnummer:  
  - als de input 8 cijfers is, dan zoekt KISS op KvK
  - Als de input 12 cijvers is, dan zoekt KISS op Vestigingsnummer
  - De foutmelding is gewijzigd naar: 
  "Vul de 8 cijfers van het KvK-nummer in, bv. 12345678, of vul de 12 cijfers van het Vestigingsnummer in, bv. 123456789012"
    - vestigingsnummer staat nog niet in resultaat, dat pakken we op in #884 
- Boven het zoekresultaat staat: "[aantal] resulaten gevonden voor" met daarachter de termen waarop is gezocht

**Comment by sytskevanhasselt** [comment]
![3 Bedrijven zoeken](https://github.com/user-attachments/assets/12f6e133-07a0-443b-8bf5-9c537a22bfdc)

**Comment by mariusvandam** [comment]
@sytskevanhasselt kan gesloten worden?
