### ISSUE TITLE
Vestigingsnummer in zoekresultaat bedrijven

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#884]
### Description

Als KCM wil ik in het zoekresultaat van bedrijven ook het vestigingsnummer van een gevonden bedrijf kunnen zien.

### Acceptance criteria

* In het zoekresultaat bedrijven is de kolom 'Type' niet meer aanwezig
* In het zoekresultaat bedrijve is een kolom 'vestigingsnummer' toegevoegd
* Dit is verwerkt in een schermvoorstel, en doorgevoerd in de interface

Afbeelding:
![image](https://github.com/user-attachments/assets/71572b24-7d6f-4a80-a078-c167fbf3fa25)

**Comment by mariusvandam** [comment]
@sytskevanhasselt kan gesloten worden? https://dimpact.atlassian.net/browse/PC-433
