### ISSUE TITLE
Klantcontacten en Contactverzoeken kunnen inzien bij Bedrijven

### ISSUE THREAD

**Issue by sytskevanhasselt** [Klantinteractie-Servicesysteem/KISS-frontend#892]
### Description

Als KCM wil ik op het Klantbeeld van een Klant zien welke Contactmomenten/Klantcontacten dit bedrijf heeft gehad en welke Contactverzoeken er recentelijk zijn geweest.

### Acceptance criteria

- Uit Open Klant 2.0 komen de klantcontacten bij de Partij met dat Vestigingsnummer, of met dat KvK-nr/RSIN
- Uit Open Klant 2.0 komen de Contactverzoeken: interne taken, inc gekoppelde betrokkene, actor, digitale adressen, klantcontact
- Als er een e-Suite koppeling is geconfigureerd: Uit e-Suite komen de Contactmomenten bij de klant met dat Vestigingsnummer, of met dat KvK-nr (dan er verandert er nix)
- E-Suite koppeling: aan contactverzoeken verandert niets.
- Featureswitch aanpak: aan het eind van deze story halen we
  - ófwel Klantcontacten en Contactverzoeken op uit OpenKlant 2.0
  - ófwel Contactmomenten en Contactverzoeken op uit de e-suite Contactmomenten API
- De En-En-situatie gaan we organiseren in ONN-project.

### Specific details

Dit is de Bedrijven-variant van #802

**Comment by mstokericatt** [comment]
volgens mij is dit inmiddels in de slipstream van andere stories al geïmplementeerd. 
Er zit nog wel een bug in: gespreksresultaten laden niet (en de spinner ziet er raar uit). zowel bij podiumD als op dev. Deze story zou dus gereduceerd kunnen worden tot het fixen van de bug.

**Comment by sytskevanhasselt** [comment]
Afgerond in sprint 12
