### ISSUE TITLE
Als KCM wil ik berichten kunnen afvinken die ik gelezen heb

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#91]
... zodat ik nieuwe of aangepaste berichten waar ik nog naar moet kijken, direct kan herkennen.
A-05

### toelichting

In de discussie wordt gesproken over het verplaatsen/sorteren van gelezen berichten. Dit zorgt echter voor lastige en verwarrende situaties met paginering en andere regels die invloed hebben op de volgorde van berichten. Berichten blijven dus vooralsnog gewoon altijd op dezelfde plek ongeacht of ze wel/niet gelezen zijn. Er komt ook geen filter (gelezen/ongelezen).

design : https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1

### Acceptatiecriteria
- [x] medewerker kan een bericht als gelezen markeren. dit wordt opgeslagen
- [x] gelezen berichten worden anders gepresenteerd: 'ingeklapt' met alleen de titel zichtbaar
- [x] als een bericht is aangepast na de datum waarop het als gelezen gemarkeerd is, dan wordt het als ongelezen bericht getoond 
- [x] zowel in het startscherm als in de zoekresultaten kan je berichten als wel/niet gelezen markeren en worden gelezen berichten op dezelfde manier gepresenteerd

### Functionele teststappen
- [x] Log in als sytske@icatt.nl, en markeer twee berichten als gelezen
- [x] Verifieer dat deze berichten ook in het zoekresultaat als 'gelezen' gemarkeerd zijn. 
- [x] Markeer een ander bericht als gelezen, vanuit het zoekresultaat
- [x] Constateer dat ze nog steeds als gelezen gemarkeerd staan, op de Startpagina. 
- [x] Ga naar PUB-beheer, en breng een wijziging aan in één van de artikelen, en publiceer
- [x] Constateer dat het bericht op de startpagina bovenaan staat, met status ongelezen.

### Taken Conduction
- [x] opslaan in een aparte tabel in de gateway (niet via logging oplossen). logging heeft wel de voorkeur van Ruben, wilco gaat de varianten nog even naast elkaar leggen en een afweging maken dat dat dan eerst nog even bespreken.
- [x] er komt een aparte call om de status op ongelezen te zetten. om hem op gelezen te zetten zou je ook het item kunne opvragen (zie volgende punt) een aparte call is misschien duidelijker, maar dus niet noodzakelijk. 
- [x] als je een enkel bericht ophaalt wordt de status automatisch op gelezen gezet, niet als je een collectie opvraagt.
- [x] bevraagbaar maken via json-hal op niewsberichten en website instructies. dwz je hoeft geen aparte call te doen om de status op te vragen, de data zit als 'extend' bij de berichten
- [x] overdragen aan ICATT: aangeven hoe de call voor het markeren (niet)gelezen eruit zien. en hoe de call/response voor het ophalen van de read informatie bij de nieuwsberichten eruit ziet
- [x] deze data groeit: nadenken over schonen van database. zal dat noodzakelijk zijn? zo ja, hoe kunnen we dat doen.

### Taken ICATT
- [x] een bericht gelezen/niet gelezen markeren en dit opslaan via de api.  
- [x] bij ophalen berichten, ook de read status ophalen
- [x] de gelezen berichten visueel markeren
- [x] bij het verversen van de berichten aangepaste berichten weer als ongelezen tonen

### Tijdinschatting 
- *Conduction* 8 <-- is anders dan wat er in de losse property velden van deze story staat. welke waarde klopt?

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik berichten kunnen afvinken die ik gelezen heb, zodat ik nieuwe
of aangepaste berichten waar ik nog naar moet kijken, direct kan herkennen.

**Comment by rubenvdlinde** [comment]
Los van de visuele weergave moet de onderliggende data set dit wel ondersteunen. Mijn voorstel is om een read object toe te voegen wat op object basis  gekopeld kan worden. Het read object zelf is uitgewerkt onder #134 . Logica zou dan als volgt zijn

- Een object heeft geen aanhangig read opbject = ongelezen
- Een object heeft een aanhangig read object, de datum van het read object is *later* dan de last change datum van het hoofd object = gelezen
- Een object heeft een aanhangig read object, da datum van het read object is *eerder* dan de last change datum van het hoofd object = ongelezen

**Comment by mstokericatt** [comment]
@rubenvdlinde, wordt dit een aparte api die vanuit de client aangeroepen wordt? of worden de bericht in de gateway verreikt met de read informatie?
Per bericht  een aparte call doen naar een read api lijkt me qua performance niet wenselijk. hoe haal je in een keer voor meerdere  berichten tegelijk de read info op?

**Comment by PascalIcatt** [comment]
Oplossingsrichting: niet via logging implementeren, wel in een aparte tabel in de gateway.
Het wordt dus niet automatisch als lezen gemerkeerd, er komt een aparte call om de status op gelezen/ongelezen te zetten

**Comment by PascalIcatt** [comment]
Geen filteren in deze story

**Comment by mstokericatt** [comment]
ter referentie, de voorgestelde oplossingsrichting van Ruben. in overleg met architecten is besloten dit niet te doen. te groot voor nu.

_Dat vraagt eigenlijk om een read object, dat is er een waar we al langer in gedachte mee spelen ook vanuit PDS. het read object zou er relatief simpel uit kunnen zien en bestaan uit

wie heeft het gelezen, uri van medewerker of klant
wat is er gelezen, uri van gelezen object 
wanneer is het gelezen, datetime

het is hierbij wel goed om van de lezer en gelezen object zelf ook weer objecten te maken die een uri bevatten (ipv alleen een uri) het is denkbaar dat we in de toekomst ook willen vastleggen dat iets is gelezen door iets of iemand die geen uri heeft (ik noem maar wat een bruger) of dat er iets is gelezen waarvan we geen uri hebben. 

Overigens zou dit op termijn ook uit de verwerkingen api kunnen komen, maar dat is echt even twee stappen verder_

**Comment by WilcoLouwerse** [comment]
Ik heb hier op het Conduction Jira board 2 epics voor uitgewerkt:
https://conduction.atlassian.net/browse/GW-1181
https://conduction.atlassian.net/browse/GW-1191

**Comment by WilcoLouwerse** [comment]
Ondertussen heb ik de eerste Epic over het markeren als gelezen uitgewerkt https://conduction.atlassian.net/browse/GW-1181
Vanaf vandaag ben ik bezig met de 2de over het ongelezen markeren https://conduction.atlassian.net/browse/GW-1191

**Comment by WilcoLouwerse** [comment]
Vandaag heb ik ook https://conduction.atlassian.net/browse/GW-1191 afgerond

(de volgende voorbeelden werken voor nu alleen met Accept header application/json+ld of application/json+hal)

Het is nu mogelijk om bij een get collectie api-call de query parameter dateRead=true mee te geven, hiermee krijg je bij alle objecten te zien wanneer de ingelogde user voor het laatst het object gelezen heeft.
![Image](https://user-images.githubusercontent.com/3785488/181461612-2e3d0add-3bf9-4aff-bb5e-eda279795034.png)

Door een get item api-call te doen word een object gemarkeerd als gelezen (en word dus dateRead geupdate naar de laatst gelezen datum)
Als je iets alleen als gelezen wilt markeren en verder geen velden van het object nodig hebt kun je de query parameter fields[]= meesturen, hierdoor krijg je minder data terug. (zie verschil met get collectie afbeelding)
![Image](https://user-images.githubusercontent.com/3785488/181463169-e197b3f1-6d00-4fdb-8de0-df8a002889a8.png)

Door een put api-call te doen met "@dateRead":false in de body kan je een object weer als ongelezen markeren (@dateRead zal dan null zijn). Ook hierbij zou je gebruik kunnen maken van fields[]= om minder data terug te krijgen in de response.
![Image](https://user-images.githubusercontent.com/3785488/181464519-1c4daf67-cf8c-44c4-b6b4-05611a32b579.png)

**Comment by mstokericatt** [comment]
overlegd met @rubenvdlinde , er wordt nu niet meer rechtstreeks geproxied, daardoor worden request params niet meer begrepene ne is de repsonse anders. @ruben gaat dit fixen: doel is dat request en response weer gelijk worden aan het /api/openpub/kiss_openpub_pub endpoint

**Comment by lencodes** [comment]
@sytskevanhasselt om dit te testen kan je zoeken naar een klant per e-mailadres: `icatttest+roza@gmail.com`.

Je kan uiteraard ook op andere klanten zoeken, maar let op:

1. Als een klant geen BSN bevat, dan tonen er ook geen zaken (we kunnen immers niet zoeken op BSN) en
2. Als een klant wél een BSN bevat én zaken bevat maar **geen** gekoppelde medewerker aan de zaak, dan wordt het label "Onbekend" bij behandelaar.

**Comment by hannekevanderhorst** [comment]
Je spreekt hier over klantbeeld maar deze story gaat over het afvinken van gelezen berichten. En die is volgens mij niet klaar?

**Comment by lencodes** [comment]
> Je spreekt hier over klantbeeld maar deze story gaat over het afvinken van gelezen berichten. En die is volgens mij niet klaar?

Mijn fout, ik heb in het verkeerde issue een comment geplaatst.

**Comment by WilcoLouwerse** [comment]
Vandaag synchronisatie geregeld als vervanging van proxy.
Nieuwe endpoint voor nieuws is nu /api/kiss_openpub_pub
![image](https://user-images.githubusercontent.com/3785488/185596994-d6f4be14-2ed4-4678-b167-8ab161f21ba2.png)

Side note:
![image](https://user-images.githubusercontent.com/3785488/185597069-d1fb0406-8b4d-4596-871d-1a9bd485f636.png)
^ w.i.p.

**Comment by lencodes** [comment]
Alle onderstaande changes zijn beschikbaar op `feature/A-05_berichten_gelezen_markeren`.

De UI voor dit issue is geschreven. De koppeling voor de data met de gateway is gedeeltelijk opgepakt, zie onderstaand een stappenplan van wat er moet gebeuren:

**1. Data ophalen incl. `@dateRead` property:**

- [x] `json+ld` meesturen in de accept headers;
- [x] query param `_dateRead=true` meesturen;

_Let op: er gaat door bovenstaand iets kapot in de UI, maar de data komt wél juist mee._

**2. Een bericht markeren als gelezen of ongelezen**

- [ ] `GET` op een specifiek bericht doen; hij wordt hierdoor automatisch op gelezen gezet.
- [ ] `PUT` op een specifiek bericht doen; deze verwacht het volledige bericht én `@dateRead: false`. Dit betekent effectief: `PUT { ...bericht, @dateRead: false }`; het kan hier dus zo zijn dat we eerst een `GET` moeten doen om het volledige bericht op te halen.

**Notes**:

- Wanneer we de data **niet** nodig hebben van een bericht (bij het markeren als gelezen én bij de `PUT` van het markeren als ongelezen) kunnen we de query paramater `?fields[]` meegeven, hierdoor komt alle onnodige data niet mee terug en wordt de call sneller;
- Een gelezen bericht is een bericht waar `@dateRead` een `DateTime string` bevat;
- Een ongelezen bericht is een bericht waar `@dateRead` `null` bevat.

**Comment by WilcoLouwerse** [comment]
Als vervolg op de cronjob bug voor het syncen een issue aangemaakt op het Conduction jira bord:
https://conduction.atlassian.net/browse/KISS-132

**Comment by WilcoLouwerse** [comment]
Kleine update over hoe dateRead werkt op de back-end:
![Image](https://user-images.githubusercontent.com/3785488/187422729-51dd8505-4ac7-415d-a5f4-f610142394da.png)

Voor Accept=application/json (of =*/*)
![Image](https://user-images.githubusercontent.com/3785488/187422770-1aa0da70-aa25-46d2-83eb-01cf48b633e8.png)

**Comment by sytskevanhasselt** [comment]
Vandaag het testen verder afgemaakt. De werking zoals beschreven in het testscenario zie ik hier terug. 
Bevindingendocument staat in teams: Testen + testdata > Bevindingen Sprint-04, Sprint-05, Sprint-06: Bevindingen_A06_GelezenOngelezenMarkeren.docx. In diezelfde map staat ook een map A-06
Alleen er lijkt nog wat mis te gaan, hieronder wat ik zie

https://user-images.githubusercontent.com/53014699/190653836-da55eb0a-1d7f-46b6-ac41-cc867eade288.mp4

**Comment by felixcicatt** [comment]
De bovenstaande bug is gefixt, maar:
Vanwege het caching mechanisme dat we hebben, krijg je bij het verwijderen van je zoekopdracht en weer opnieuw zoeken, eerst een gecachede versie van de berichten terug (die nog ongelezen zijn). Vlak daarna, zodra het 'verse' antwoord van de Gateway binnen is, worden ze geupdate (en dus gelezen/ingeklapt). Als dit ook niet acceptabel is, zijn er nog dingen die we kunnen doen om dit scenario nog verder uit te sluiten. Maar ik wacht graag af wat Sytske en/of de gebruikersgroep ervan vinden.

**Comment by sytskevanhasselt** [comment]
Ik heb dit idd gezien, en het lijkt mij afdoende. Voor nu sluit ik deze, en beschouw deze als Done. 
@hannekevanderhorst  : mochten hier uit gebruikerstest nog dingen uitkomen, dan overleggen we even wat dan.
