### ISSUE TITLE
Lijst nieuws / werkinstructies ordenen op datum laatst gewijzigd

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#92]
**Story**
Als klantcontactmedewerker wil ik dat een bericht na aanpassing bovenaan wordt geplaatst in de nieuwsfeed en de lijst met werkinstructies, zodat ik actuele informatie altijd in beeld heb

### Toelichting

DAtum laatst gewijzigd zit wel in de API, maar er wordt niet op gesorteerd.

### Acceptatiecriteria
- [x] berichten in het startscherm worden op volgorde getoond (obv datum gewijzigd, datum aangemaakt).
- [x] De lijsten met berichten worden automatisch (binnen enkele seconden) ververst, zodat gewijzigde berichten en nieuwe berichten automatisch bovenaan komen te staan
- [x] De tijd die bij een bericht te zien is, is de gewijizgd-datum van berichten
- [x] De tijd die bij een bericht te zien is, is in de Nederlandse tijdzone (dus niet server tijd, 2 uur eerder)

### Functionele teststappen
- [x] Zoek een nieuwsbericht op op de laatste pagina. Ga naar PUB, doe een wijziging. Constateer dat het bericht bovenaan op de startpagina komt te staan
- [x] Doe hetzelfde voor een werkinstructie.

### Taken Conduction
- [x] Laatst gewijzigd in de PUB api  opslaan
- [x] Er wordt geordend op datum laatst gewijzigd
- [x] 2 properties laatst gewijzigd pub en gateway gelijk trekken
- [x] vastleggen en communiceren met ICATT welke velden in de api hiervoor gebruikt worden en wanneer deze beschikbaar zijn. 
- [x] Sortering op datum laatste gwijzigd

### Taken ICATT
- [ ] testen NA DONDERDAG of er niet al een update datum meegestuurd owrdt vanuit pub. dan hoeft conduction misschien niets meer te doen.
blocked voor ICATT: wachten op inrichting conduction
- [ ] berichten worden al automatisch ververst, nu ook rekening houden met de aanmaak/wijzig datum
- [ ] besproken: alleen de laatste datum wordt getoond (dus initieel de datum van plaatsing en daarna alleen de datum van de laatste wijziging )
- [ ] Servrtijd rechttrekken

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik dat een bericht na aanpassing bovenaan wordt geplaatst in de nieuwsfeed en de lijst met werkinstructies.

**Comment by rubenvdlinde** [comment]
Defacto komt dat er dan nu denk ik gewoon weer bij

**Comment by sytskevanhasselt** [comment]
@mstokericatt , @rjzondervan , ik heb nog even gekeken naar Laatst GEwijizgd datum, en ik heb mij vergist. Er is namelijk bij gepubliceerde publications géén 'Date Modified'. Alleen maar een Published. 

Bij het bewerken van een artikel in WordPress kún je de publicatiedatum resetten, en dan wordt de publicatiedatum gezet op 'nu'. Maar dat is niet per sé hetzelfde. 

Ik zie dat in het object (als ik het goed zeg) van een item wél een 'modified' staan, en wordt ook bijgewerkt, als ik een artikel wijzig, zie onderstaand screenshot. 

LETOP: de tijd die in het bericht staat en die dus ook in de front end staat, loopt 2 uur achter. kunnen we het fixen daarvan in deze story meemenen?



![Image](https://user-images.githubusercontent.com/53014699/178025009-dc05a38d-3f41-4cfd-8d47-3dd49ff1bfa1.png)

**Comment by bbrands02** [comment]
@sytskevanhasselt Ik heb net getest met query parameter `?orderby=modified` en dit lijkt wel te werken. Had je dezelfde parameter toegevoegd bij het testen? Zo niet kan je `?orderby=modified` toevoegen achter de url en zou het moeten werken.

**Comment by felixcicatt** [comment]
@bbrands02 dat lukt vanaf de frontend ook. We kunnen de sortering dus vanaf de frontend regelen.

**Comment by sytskevanhasselt** [comment]
Status = done
