### ISSUE TITLE
Rollen voor het Startscherm van KISS

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#93]
**Story**
Als organisatie willen we rollen aan gebruikers kunnen toewijzen, waarbij een gebruiker ook meerdere of alle rollen kan hebben, voor het werken met de nieuwsfeed en de werkinstructies. (C-01)

### Toelichting
Als organisatie willen we rollen aan gebruikers kunnen toewijzen, waarbij een gebruiker ook meerdere of alle rollen kan hebben, voor het werken met de nieuwsfeed en de werkinstructies, namelijk: 
1.	Klantcontactmedewerker. 
2.	Medewerker die op dagelijkse basis nieuwsberichten schrijft (bijvoorbeeld een vakinhoudelijk medewerker). Deze voert de regie over de berichten, zoals het maken, aanpassen of verwijderen ervan. 
3.	Medewerker die de inrichting van categorieën of skills beheert, zoals de keuze voor labels als “Parkeren”, “Burgerzaken” of “Afval”. 
Deze rolverdeling willen we, zodat fouten worden voorkomen en gebruikers in hun eigen rol een zo overzichtelijk mogelijke gebruikersinterface kan worden geboden. 

 ##Beslissing nodig
@hannekevanderhorst : doen we dit via SSO in openPub, of via een geintegereerde beheerinterface?
Anwoord: Niet, nice to have voor later. Voor nu aparte eigen inlog in openPub.
**
Er zijn op dit moment geen rollen nodig omdat alle rol-speccifieke functies in afzonderlijke systemen zitten ( In de gateway admin-ui worden categorien beheerd. In pub worden de berichten beheerd), waar de medewerkers aparte individuele accounts voor krijgen. deze story vervalt dus voorlopig. het nadeel (geen sso, maar meerdere accounts) accepteren we voorlopig.**

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...
- [ ] ...

### Taken ICATT
- [ ] ...
- [ ] ...

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Tijdinschatting 
- *Conduction* 
- *ICATT* 

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Hebben we het hier alleen over rollen die betrekking hebben op werkzaamheden of ook rechten structuur.

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als organisatie willen we rollen aan gebruikers kunnen toewijzen, waarbij een gebruiker ook
meerdere of alle rollen kan hebben, voor het werken met de nieuwsfeed en de werkinstructies,
namelijk:
1. Klantcontactmedewerker.
2. Medewerker die op dagelijkse basis nieuwsberichten schrijft (bijvoorbeeld een vakinhoudelijk
medewerker). Deze voert de regie over de berichten, zoals het maken, aanpassen of verwijderen
ervan.
3. Medewerker die de inrichting van categorieën of skills beheert, zoals de keuze voor labels als
“Parkeren”, “Burgerzaken” of “Afval”.
Deze rolverdeling willen we, zodat fouten worden voorkomen en gebruikers in hun eigen rol een
zo overzichtelijk mogelijke gebruikersinterface kan worden geboden

**Comment by sytskevanhasselt** [comment]
Ik begrijp het meer als een Rechtenstructuur. Ofwel: 

1. Een gebruiker met de ROL redacteur, heeft het RECHT om nieuwsberichten toe te voegen, te wijzigen, etc. 
2. Een gebruiker met de ROL 'Categoriebeheerder', heeft het RECHT om het lijstje SKILLs / categorieën te beheren. 
3. Een gebruiker met de rol Klantcontactmedewerker, kan alleen maar nieuws en werkinstructies lezen, zoeken en filteren in die berichten.

**Comment by hannekevanderhorst** [comment]
Medewerkers API gaan we niet gebruiken voor smoelenboek, rechten voor redactuer kunnen we instellen in PUB en voor de Categoriebeheerder in de GAteway UI - medewerkers api is niet nodig

**Comment by PascalIcatt** [comment]
Inloggen komt in eeen aparte story

**Comment by sytskevanhasselt** [comment]
@hannekevanderhorst er is een vraag voor jou in deze story  geplaatst

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C; is gerealiseerd in juni 2023
