### ISSUE TITLE
Als KCM wil ik een zoekopdracht tegelijkertijd kunnen uitvoeren in meerdere bronnen

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#94]
### Toelichting
Als klantcontactmedewerker wil ik een zoekopdracht tegelijkertijd kunnen uitvoeren in meerdere bronnen, zodat ik snel een zoekresultaat beschikbaar heb om mijn klant mee te helpen. 

Randvoorwaarde: meerdere bronnen gekoppeld.

### Acceptatiecriteria
- [x] Als je één zoekwoord intikt vind je resultaten uit meerder bronnen. 
- [x] Als je meer zoekwoorden intikt, vindt je alléén resultaten waar beide woorden in voorkomen
- [x] De meest relevante resultaten staan bovenaan, deze kunnen uit verschillende bronnen komen *)
- [x] de zoekmachine zoekt op hele woorden. Dus als ik 'eik' intik, vind ik zoekresultaten waar het woord 'eik' in voorkomt, en niet waar 'eik' onderdeel is van een woord (zoals in bereiken). 
- NB: de resultaten van verschillende bronnen lijken niet onderling geprioriteerd te worden. alle resultaten van de ene bron lijken  altijd boven de resultaten van de andere bron te staan. uitzoeken of dit klopt of toeval is en zo nodig aanpassen: de volgorde moet niet afhankelijk zijn van de bron, maar van de relevantie van het zoekresultaat

*) hiervoor moeten we vermoedelijk wel beslissen wát er voor zorgt dat een gevonden resultaat relevanter is dan een ander. Dit zou elastic zelf moeten regelen, maar dat gaat nu niet goed. uitzoeken en verbeteren.

### Functionele teststappen
- [ ] ...
- [ ] ...

### Taken ICATT
- [x] elastic inrichting verbeteren

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Als we zoeken via elastick search doen is dit issue al opgelost door @PascalIcatt en @rjzondervan

**Comment by PascalIcatt** [comment]
Volgens mij is er een taak nodig om pub aan elastic te hangen, inclusief acceptatiecrietria.
 Bij de eerste story waar dit geimplementeerd wordt zal deze taak opgepakt moeten worden.
Is daarmee je vraag beantwoord @rubenvdlinde ?

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik een zoekopdracht tegelijkertijd kunnen uitvoeren in meerdere
bronnen, zodat ik snel een zoekresultaat beschikbaar heb om mijn klant mee te helpen.

**Comment by sytskevanhasselt** [comment]
In #19 gaat het om _alleen_ zoeken in nieuws/werkinstructies. Daarvoor is een eigen zoekbalk op het startscherm. 

Deze gaat over het zoeken in alle bronnen, in de grote zoekbalk bovenin. En de vraag is inderdaad of je via deze grote zoekbalk óók kan zoeken in nieuw/werkinstructies. Of dat zoeken in nieuw/werkinstructies alleen kan door de kleine zoekbalk boven de feed.

**Comment by mstokericatt** [comment]
Dan moeten er toch eerst meer bronnen ontsloten worden?! oa smoelenboek, intranet, eigen website, externe websites.

nieuws en werkinstructies horen daar in principe juist niet bij. die hebben hun eigen zoekfunctie.

**Comment by PascalIcatt** [comment]
@hannekevanderhorst Deze story is al opgeleverd, correct?
