### ISSUE TITLE
Zoeken op basis van Skill / Als KCM wil ik makkelijk kunnen schakelen tussen (vooringestelde) profielen

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#95]
### Toelichting
Als klantcontactmedewerker wil ik makkelijk kunnen schakelen tussen (vooringestelde) profielen (bijvoorbeeld: skill toe kunnen voegen of verwijderen), zodat alleen de bronnen aangeroepen worden die belangrijk zijn voor dat profiel, die skill(s) of mijn specialismegebied. 

HH 20-9: Deze is in de ontwerpgroep van 13-9 out op scope gezet

Deze is randvoorwaardelijk voor #99  .

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Dit zou betekenen dat we nog een taxonomie object zouden moeten definiëren voor #134

**Comment by sytskevanhasselt** [comment]
Dit heeft m.i. twee aspecten: 

1. in KISS profielen obv Skill kunnen aanmaken/beheren, en als KCM kunnen selecteren
2. Zoekbronnen (of _content binnen die bronnen??_) gekoppeld aan  Skills

**Comment by PascalIcatt** [comment]
@hannekevanderhorst 
De huidige bron api's ondersteunen volgens ons geen categorie/skill metadata. Hoe moeten we dit opvragen?

**Comment by sytskevanhasselt** [comment]
Gesloten ivm fase 1C
