### ISSUE TITLE
Als KCM wil ik zoeken naar informatie over collega’s

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#96]
### Toelichting
Als klantcontactmedewerker wil ik zoeken naar informatie over collega’s, zoals bereikbaarheids- en contactinformatie, zodat ik mezelf of mijn klant in contact kan brengen met de juiste persoon.

*RvL: Dit vraag om het inleesbaar maken van een smoelenboek.
We lezen het smoelenboek in in het medewerkersregister  en indexeren dat in elastic search (doorzoekbaar en gestructureerde  data)*

**Besproken en besloten (18-7-2022)**
- tweede telefoonnummer ondersteunen we niet.
- "skills" vervangen door een vrij tekst veld, dat gaat over 'Wat doe ik en wat kan ik'
- vervanging wordt gestructureerd: 1 link naar een andere medewerker
- beschikbaarheid wordt gestructureerd in de vorm van een lijst dagdelen (dus geen ICAL)

**Gebruikersgroep 19-5-2022**
*verplaatst naar [comment](https://github.com/Klantinteractie-Servicesysteem/KISS-frontend/issues/96#issuecomment-1155221766)*

### Acceptatiecriteria
- [x] Als ik zoek op een bepaalde term, vind ik ook medewerkers waarbij die zoekterm voorkomt in één van de velden van het Medewerkers-object
- [x] Bij deze resultaten staat als bron: 'Smoelenboek'. 
- [x] Als ik zo'n collega aanklik, kom ik in een detailscherm, waarin alle gegevens van die medewerker uit de medewerkersregistratie te zien zijn. 

### Functionele teststappen
- [x] Zoek op eHerkenning
- [x] Vind een aantal resultaten uit de website over eHerkenning, én twee collega's die iets doen met eHerkenning
- [ ] Klik de eerste aan, [NaamVolgt]: hier zien we de naam, afdeling, functie, contactgegevens, omschrijving en 'wat-kun-je-wat-doe-je'

### Taken Conduction
- [x] Mederwerkers api beschikbaar maken op gateway
- [x] lijst met api opties 'leesbaar' aanleveren aan gebruikersgroep (hanneke), om keuze te kunnen maken uit te gebruiken velden.
- [ ] aantal mock medewerkers in de gateway. via de medewerkers api inlezen in elastic. 

### Taken ICATT
- [x] Pascal en barry stemmen samen testdata 
- [x] medewerkers zoeken >zoekresulaten, doorklik detailresultaten tonen
- [x] elastic index structuur uitbreiden
- [ ] bespreken met gebruikers: welke info is het meest relevant? zoek je vooral een specifieke persoon, of een afdeling, een skill, etc?
- [ ] styling detailinfo

### Taken DIMPACT
- [ ] ...
- [ ] ...

### Discussie
- [ ] ...

**Comment by rubenvdlinde** [comment]
Hier moeten we een keuze maken, time allowing zou ik natuurlijk liever voor optie 2 gaan.

**Comment by felixcicatt** [comment]
Denk ook een een goede oplossing voor de vertaling van de verschillende engines in elasticsearch naar een 'Bron' in de UI (bv Website, Kennisbank, etc)

**Comment by rubenvdlinde** [comment]
Medewerkers API  is opgenomen onder #134

**Comment by sytskevanhasselt** [comment]
Ik begrijp dat de medewerkers-api beschikbaar is gesteld op de Gateway. Van Barry kreeg ik deze redocly-link van de oorspronkelijke medewerkers-api: 
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/ConductionNL/medewerkercatalogus/master/api/public/schema/openapi.yaml&nocors#tag/Employee/operation/postEmployeeCollection

Deze api lijkt erg gericht op HR-zaken, en minder op 'zoek-een-collega'-functionaliteit. 
Gebruikersgroep (bij monde van Moniek) geeft aan: 
- we willen standaard contactgegevens zie zoals ze bv in AD staan (naam, functie, contact, afdeling, werkplek (adres, kamernummer?)
- En daarnaast: 
  - Beschikbaarheid (wat zijn je werkdagen)
  - Wie is je vervanger
  - Wat zijn jouw speerpunten ('bij mij kan je terecht met vragen over de sloopmelding' bijv.).

**Comment by sytskevanhasselt** [comment]
Ik heb de story bijgewerkt met input van de Gebruikersgroep van donderdag 7/7

**Comment by rubenvdlinde** [comment]
Trekken we het medewerkers register weer in scope, in architectuur overleg is destijds besloten hem out of scope te houden

**Comment by rubenvdlinde** [comment]
OKe in lijn met het eerdere architectuur overleg omgeslagen van volledig register naar ORC object. Definitie daarvan is hier  te vinden https://conduction.stoplight.io/docs/huwelijksplanner/branches/main/08e5fbaf6bf4a-medewerker

**Comment by hannekevanderhorst** [comment]
Mooi - klopt in ieder geval met de gegevens die we willen zien.
Ik begrijp dat calendar daarbij de invulling voor werkdagen is.

**Comment by rubenvdlinde** [comment]
Calander is een component dat een aantal dingen bevat, maar basically is het gewoon ICAL naar rest API. Dus daar zitten zowel beschikbaarheid als taken in (dat laatste is dan weer nodig voor het bijhouden van wel/niet verzeten acties).

Maar, lang verhaal kort, ja ! :)

API specs voor het calander stukje volgen morgen

**Comment by bbrands02** [comment]
Medewerker object is beschikbaar op `/api/medewerkers` op de dev omgeving.

**Comment by bbrands02** [comment]
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Huwelijksplanner/AgendaService/main/OAS.yaml&nocors

AgendaService staat op de dev omgeving. Met de calendar en availability objecten is beschikbaarheid in te regelen.

**Comment by sytskevanhasselt** [comment]
### terugkoppeling over de Medewerker-api, van de PO
    
Het Medewerker-object bevat alle gevraagde informatie op twee dingen na:
	
1. Een tweede telefoonnummer: want dat zit niet in de Klanten-api	
2. Het element Skills zoals dat nu is opgenomen is Helemaal Niet de bedoeling

Ad 1. - Tweede telefoonnummer
NB; dit is voor MEDEWERKER minder relevant. Voorlopig oke dat we maar 1 telefoonnummer hebben. 

Ad 2 – Skills
Skills als gestructureerde data, zoals die nu in het object zit **voldoet NIET** om het onderwerp ‘speerpunten’ in te vatten. Zeker de Skills in Pub niet, want die Skills zijn specifiek voor KCMs. En met Medewerker halen we véél meer mensen op dan alleen de KCMs.
	
Het lijkt de PO ook niet haalbaar / zinvol om hier een andersoortige gestructureerde vorm voor te vinden. Want het is een heel gemeleerde ‘lijst’ (als het er al één is). Het gaat over taakgebieden in jouw werk (bv. laadpalen, zonnepanelen). Maar óók over bv. Projecten of (landelijke of gemeente specifieke) programma’s. Dit is binnen een gemeente al lastig te structureren, laat staan over meerdere gegevens heen.

Het voorstel van de PO is om het Skills-attribuut te vervangen door één ongestructureerd veld. Dit kan vanuit de  gemeente gevuld worden met de info in één of meerdere velden uit hun medewerkersregistratie. In Deventer is het bv één veld. In de Utrechtse Wie-is-Wie is Wat doe je en Wat kun je in twee verschillende velden gegoten. Dit veld geeft antwoord op de vraag 'Wat kun je en wat doe je'

Voor het overige:
1. Is PO akkoord met de aanpak rondom ‘vervanging’ als gestructureerd
2. Is beschikbaarheid als gestructureerd gegeven ook akkoord. Ik ben er bij Beschikbaarheid wel vanuit gegaan dat het bv. een lijstje is met dagdelen waarop  je werkt.

Wat er precies in het veld Description kan dus per gemeente verschillen. Is het mogelijk om iets van Opmaak toe te staan in dat veld?

**Comment by sytskevanhasselt** [comment]
@PascalIcatt , @WilcoLouwerse ik heb iets meer ingevuld bij Acceptatiecriteria, om wat richting te geven aan de elastic inregeling

**Comment by bbrands02** [comment]
Skills is nu ongestructueerd op het medewerkers object op de dev omgeving

**Comment by sytskevanhasselt** [comment]
Status = done
