### ISSUE TITLE
Als KCM wil ik kunnen aangeven uit welke bronnen ik resultaten wil zien

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#97]
### Toelichting
Als klantcontactmedewerker wil ik kunnen aangeven uit welke bronnen ik resultaten wil zien, zodat ik op een handige manier relevante informatie voor mijn klant kan vinden. 

Het gaat hier om het vooraf beperken van de bronnen waarin je gaat zoeken. Er moet een interface element zijn waarin je bepaalde bronnen kunt uitvinken. Ofjuist aanvinken (en niks aangevinkt is zoeken in alles). Daarmee kan ik bv. mijn zoekopdracht uitvoeren op alléén de PDC en het zaaksysteem.

ontwerp: https://www.figma.com/file/FLoLgiBhA3V6TMgA2s8uhV/KISS-schermen?node-id=0%3A1
er is gekozen voor het ontwerp warbij de opties als rij checkboxes boven de zoekbalk staan

### Acceptatiecriteria
- [x] filter opties voor alle bronnen zijn beschikbaar (op dit mometn eigenwebsite en pdc)
- [x] er worden alleen resultaten uit de geselecteerde bronnen getoond

### Functionele teststappen
- [ ] ...
- [ ] ...

### Taken Conduction
- [ ] ...

### Taken ICATT
- [x] betekenisvolle namen voor de elastic search engines. 
- [x] dynamisch tonen bovenstaande engine lijst uit elastic. nb nog niet duidelijk dat of dit wel uit elastic gehaald kan worden. als dat niet eenvoudig kan, dan moet het lijstje in de gateway apart geconfigureerd worden en door de front-end opgevraagd kunnen worden.
- [x] selectie meenemen in zoekopdracht
- [ ] documentatie implementatie

nb. aanname dat dit kan in elastic zonder aanpassingen.

### Taken DIMPACT
- [ ] ...

### Discussie
- [ ] type hekje om te linken

**Comment by rubenvdlinde** [comment]
Is dit geen standaard functionaliteit via de gekozen elastic search route?

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik kunnen aangeven uit welke bronnen ik resultaten wil zien, zodat ik op een handige manier relevante informatie voor mijn klant kan vinden.

**Comment by sytskevanhasselt** [comment]
Nu de het voorlopig nog onduidelijk is welke zoek-engine we gaan gebruiken (elastic of iets anders), kunnen we wel verder met het interface gedeelte van deze Story? 
@mstokericatt , @hannekevanderhorst

**Comment by sytskevanhasselt** [comment]
Status = done
