### ISSUE TITLE
Als KCM wil ik naast de meest gestelde vragen, ook een top-5 van de meest gestelde vragen op de skill waarop ik op dat moment ben ingeroosterd

### ISSUE THREAD

**Issue by hannekevanderhorst** [Klantinteractie-Servicesysteem/KISS-frontend#99]
### Toelichting
Als klantcontactmedewerker wil ik naast de meest gestelde vragen, ook een top-5 van de meest gestelde vragen op de skill waarop ik op dat moment ben ingeroosterd, zodat ik deze vragen snel bij de hand heb.

Randvoorwaarde: #95 is geimplementeerd.
Randvoorwaarde: vragen in #169 zijn beantwoord

### Acceptatiecriteria
- [ ] ...

### Functionele teststappen
- [ ] ...

**Comment by hannekevanderhorst** [comment]
Uit userstories KISS gebruikersgroep 22-3-22
Als klantcontactmedewerker wil ik naast de meest gestelde vragen, ook een top-5 van de meest
gestelde vragen op de skill waarop ik op dat moment ben ingeroosterd, zodat ik deze vragen snel
bij de hand heb.Als klantcontactmedewerker wil ik naast de meest gestelde vragen, ook een top-5 van de meest
gestelde vragen op de skill waarop ik op dat moment ben ingeroosterd, zodat ik deze vragen snel
bij de hand heb.

**Comment by sytskevanhasselt** [comment]
Deze is de oorspronkelijke, dus #170 de duplicate

**Comment by sytskevanhasselt** [comment]
gelabled en gesloten
